// Friendly names for the ideas mistakes are grouped under ("You've made 3 mistakes with ...").
export const CONCEPTS = {
  // Excel
  'cell-refs': 'relative vs absolute references ($)',
  'basic-agg': 'SUM, AVERAGE, COUNT and friends',
  'count-types': 'COUNT vs COUNTA vs COUNTBLANK',
  'if-logic': 'IF, AND, OR logic',
  'countif-sumif': 'COUNTIF and SUMIF',
  'text-funcs': 'text functions (LEFT, MID, TRIM...)',
  'dates': 'working with dates',
  'text-numbers': 'numbers and dates stored as text',
  'cleaning': 'cleaning messy data',
  'xlookup': 'XLOOKUP',
  'exact-match': 'exact vs approximate match',
  'index-match': 'INDEX + MATCH',
  'sumifs': 'SUMIFS / COUNTIFS with several conditions',
  'date-criteria': 'date ranges inside SUMIFS/COUNTIFS',
  'iferror': 'handling errors with IFERROR',
  'dynamic-arrays': 'FILTER, SORT and UNIQUE',
  'pivot': 'PivotTables',
  'weighted-avg': 'weighted vs simple averages',
  'lookup-strategy': 'choosing a lookup approach',
  'anomaly': 'spotting anomalies and outliers',
  'scenario': 'scenario and what-if analysis',
  'dashboard': 'dashboard design',
  'tables': 'Excel Tables',
  'sort-filter': 'sorting and filtering',
  'structured-refs': 'structured references',
  'pivot-charts': 'PivotCharts and slicers',
  'what-if': 'Goal Seek and data tables',
  'data-validation': 'data validation rules',
  'conditional-format': 'conditional formatting',
  // SQL
  'select-basics': 'SELECT, ORDER BY and LIMIT',
  'where-logic': 'filtering with WHERE (AND/OR)',
  'null': 'NULL values',
  'like-in-between': 'LIKE, IN and BETWEEN',
  'aggregates': 'COUNT, SUM, AVG',
  'count-distinct': 'COUNT vs COUNT(DISTINCT)',
  'group-by': 'GROUP BY',
  'having': 'HAVING vs WHERE',
  'case': 'CASE expressions',
  'inner-join': 'INNER JOIN',
  'left-join': 'LEFT JOIN vs INNER JOIN',
  'join-filter': 'filters that break a LEFT JOIN',
  'fan-out': 'joins that duplicate rows (fan-out)',
  'anti-join': 'finding rows with no match',
  'subquery': 'subqueries',
  'cte': 'CTEs (WITH ...)',
  'not-in-null': 'NOT IN with NULLs',
  'union': 'UNION vs UNION ALL',
  'conditional-agg': 'conditional aggregation',
  'sql-dates': 'dates in SQL',
  'integer-division': 'integer division',
  'dedup': 'deduplication',
  'window-rank': 'ROW_NUMBER / RANK / DENSE_RANK',
  'top-n-group': 'top N per group',
  'lag-lead': 'LAG and LEAD',
  'running-total': 'running totals and moving averages',
  'window-filter': 'filtering after a window function',
  'cohort': 'cohorts and retention',
  'segmentation': 'segmentation',
  'funnel': 'funnel analysis',
  'optimization': 'writing efficient queries',
  'string-funcs': 'string functions in SQL',
  'window-frame': 'window frames (ROWS BETWEEN)',
  // Power Query
  'pq-basics': 'what Power Query does',
  'pq-types': 'data types in Power Query',
  'pq-clean': 'cleaning steps in Power Query',
  'pq-split': 'splitting and merging columns',
  'pq-append': 'Append and folder imports',
  'pq-merge': 'Merge (lookups) in Power Query',
  'pq-unpivot': 'Unpivot and Pivot',
  'pq-group': 'Group By',
  'pq-custom': 'conditional and custom columns',
  'pq-robust': 'refresh-proof queries',
  'm-code': 'M code',
  'locale': 'dates and numbers in other formats (locale)',
  'pq-params': 'parameters',
  'pq-folder': 'importing a whole folder',
  'pq-functions': 'custom functions',
  'pq-dynamic': 'dynamic transformations',
  // Power BI
  'pbi-basics': 'how Power BI works',
  'pbi-model': 'relationships and cardinality',
  'star-schema': 'fact and dimension tables',
  'date-table': 'date tables',
  'pbi-visuals': 'visuals, filters and slicers',
  'measure-vs-column': 'measures vs calculated columns',
  'dax-basics': 'basic DAX (SUM, COUNTROWS, DIVIDE)',
  'calculate': 'CALCULATE and filter context',
  'time-intel': 'time intelligence (YTD, YoY)',
  'pbi-query': 'Power Query inside Power BI',
  'filter-context': 'how filters flow through a model',
  'row-context': 'row context and iterators (SUMX, RELATED)',
  'dax-ranking': 'ranking and Top N',
  'report-design': 'report pages and KPI cards',
  'pbi-analysis': 'targets, variance and like-for-like',
  'pbi-sharing': 'publishing, refresh and sharing',
  // Thinking
  'data-trust': 'checking whether a number can be trusted',
  'denominator': 'denominators and definitions',
  'mean-median': 'mean vs median',
  'pct-points': 'percent vs percentage points',
  'simpson': 'mix effects (Simpson\'s paradox)',
  'causation': 'correlation vs causation',
  'survivorship': 'survivorship bias',
  'chart-choice': 'choosing the right chart',
  'chart-honesty': 'honest, uncluttered charts',
  'tool-choice': 'choosing the right tool',
  'scoping': 'turning a vague question into a plan',
  'communication': 'explaining results to managers',
  'kpi': 'designing useful KPIs',
  'data-quality': 'data quality checks',
  'missing-data': 'missing data',
  'duplicates': 'duplicate records',
  'outliers': 'outliers and impossible values',
  'definitions': 'inconsistent definitions',
  'reconciliation': 'reconciling conflicting numbers',
  'metric-choice': 'choosing the right metric',
  'business-questions': 'asking for missing business information',
  'sample-size': 'small samples and noise',
  'seasonality': 'seasonality and like-for-like comparisons',
  'validation': 'validating your own analysis',
  'interpretation': 'interpreting results carefully',
};

/** Which skill each concept belongs to. Analyst-thinking concepts may be used by any skill. */
const GROUPS = {
  excel: ['cell-refs', 'basic-agg', 'count-types', 'if-logic', 'countif-sumif', 'text-funcs', 'dates', 'text-numbers', 'cleaning', 'xlookup', 'exact-match', 'index-match', 'sumifs', 'date-criteria', 'iferror', 'dynamic-arrays', 'pivot', 'weighted-avg', 'lookup-strategy', 'scenario', 'dashboard', 'tables', 'sort-filter', 'structured-refs', 'pivot-charts', 'what-if', 'data-validation', 'conditional-format'],
  sql: ['select-basics', 'where-logic', 'null', 'like-in-between', 'aggregates', 'count-distinct', 'group-by', 'having', 'case', 'inner-join', 'left-join', 'join-filter', 'fan-out', 'anti-join', 'subquery', 'cte', 'not-in-null', 'union', 'conditional-agg', 'sql-dates', 'integer-division', 'dedup', 'window-rank', 'top-n-group', 'lag-lead', 'running-total', 'window-filter', 'cohort', 'segmentation', 'funnel', 'optimization', 'string-funcs', 'window-frame'],
  pq: ['pq-basics', 'pq-types', 'pq-clean', 'pq-split', 'pq-append', 'pq-merge', 'pq-unpivot', 'pq-group', 'pq-custom', 'pq-robust', 'm-code', 'locale', 'pq-params', 'pq-folder', 'pq-functions', 'pq-dynamic'],
  pbi: ['pbi-basics', 'pbi-model', 'star-schema', 'date-table', 'pbi-visuals', 'measure-vs-column', 'dax-basics', 'calculate', 'time-intel', 'pbi-query', 'filter-context', 'row-context', 'dax-ranking', 'report-design', 'pbi-analysis', 'pbi-sharing'],
};
export const CONCEPT_SKILL = Object.fromEntries(
  Object.keys(CONCEPTS).map((c) => [c, Object.entries(GROUPS).find(([, ids]) => ids.includes(c))?.[0] || 'think']),
);
