// First-run placement check: 20 quick questions. Passing a tier (2 of 3, or 1 of 1)
// credits that tier's topics so the learning path starts at the right place.
// area = the skill the answer credits; "pq" covers data cleaning.

export const PLACEMENT = [
  // Excel
  { id: 'pl-xl-b1', area: 'excel', tier: 'Beginner', type: 'mc', concept: 'cell-refs', prompt: 'D2 contains `=B2*$F$1`. You copy D2 to E5. What is in E5?', options: ['=B5*$F$1', '=C5*$F$1', '=C5*$G$4', '=B2*$F$1'], answer: 1 },
  { id: 'pl-xl-b2', area: 'excel', tier: 'Beginner', type: 'mc', concept: 'countif-sumif', prompt: 'What does `=SUMIF(B2:B100,"West",C2:C100)` return?', options: ['The number of West rows', 'The total of column C for rows where column B is "West"', 'The average of West', 'An error: SUMIF needs three conditions'], answer: 1 },
  { id: 'pl-xl-b3', area: 'excel', tier: 'Beginner', type: 'mc', concept: 'if-logic', prompt: 'What does `=IF(A2>100,"High")` show when A2 is 50?', options: ['Low', 'An empty cell', 'FALSE', '#N/A'], answer: 2 },
  { id: 'pl-xl-i1', area: 'excel', tier: 'Intermediate', type: 'mc', concept: 'exact-match', prompt: '`=VLOOKUP(A2, Prices!A:C, 3)` returns believable but wrong prices, and never an error. Why?', options: ['The prices sheet is protected', 'The 4th argument is missing, so it does an approximate match', 'VLOOKUP can only return column 2', 'The data must be a Table'], answer: 1 },
  { id: 'pl-xl-i2', area: 'excel', tier: 'Intermediate', type: 'mc', concept: 'date-criteria', prompt: 'Which SUMIFS condition means "on or after 1 March 2026"?', options: ['">=DATE(2026,3,1)"', '">="&DATE(2026,3,1)', '>=DATE(2026,3,1)', '"&>=DATE(2026,3,1)"'], answer: 1 },
  { id: 'pl-xl-i3', area: 'excel', tier: 'Intermediate', type: 'mc', concept: 'dynamic-arrays', prompt: '`=FILTER(A2:A50, B2:B50="West")` shows #SPILL!. The most likely cause?', options: ['No West rows', 'The cells below the formula are not empty', 'FILTER needs sorted data', 'The workbook is too big'], answer: 1 },
  { id: 'pl-xl-a1', area: 'excel', tier: 'Advanced', type: 'mc', concept: 'weighted-avg', prompt: 'A PivotTable shows "Average of UnitPrice" by category. The manager wants the average selling price per unit. What should you use instead?', options: ['Max of UnitPrice', 'Sum of Revenue ÷ Sum of Units (a weighted average)', 'Count of UnitPrice', 'The same average: it is correct'], answer: 1 },
  // SQL
  { id: 'pl-sql-b1', area: 'sql', tier: 'Beginner', type: 'mc', concept: 'null', prompt: '300 orders have no promo code. `SELECT COUNT(*) FROM orders WHERE promo_code = NULL;` returns…', options: ['300', '0', 'An error', 'The rows with a promo code'], answer: 1 },
  { id: 'pl-sql-b2', area: 'sql', tier: 'Beginner', type: 'mc', concept: 'having', prompt: 'You want only the regions with more than 100 customers. Which clause filters on the count?', options: ['WHERE', 'HAVING', 'ORDER BY', 'LIMIT'], answer: 1 },
  { id: 'pl-sql-b3', area: 'sql', tier: 'Beginner', type: 'mc', concept: 'count-distinct', prompt: 'Column x: 5, 5, NULL, 7, NULL. COUNT(*), COUNT(x), COUNT(DISTINCT x)?', options: ['5, 5, 3', '3, 3, 2', '5, 3, 2', '5, 3, 3'], answer: 2 },
  { id: 'pl-sql-i1', area: 'sql', tier: 'Intermediate', type: 'mc', concept: 'join-filter', prompt: "`FROM customers c LEFT JOIN orders o ON o.customer_id = c.customer_id WHERE o.order_date >= '2026-01-01'`. Customers with no 2026 orders…", options: ['appear with NULLs', 'disappear: the WHERE turns it into an inner join', 'appear with their old orders', 'cause an error'], answer: 1 },
  { id: 'pl-sql-i2', area: 'sql', tier: 'Intermediate', type: 'mc', concept: 'fan-out', prompt: '`SELECT SUM(o.shipping_fee) FROM orders o JOIN order_items oi ON oi.order_id = o.order_id;` The result is…', options: ['correct', 'too high: fees are counted once per item', 'too low', 'an error'], answer: 1 },
  { id: 'pl-sql-a1', area: 'sql', tier: 'Advanced', type: 'mc', concept: 'window-rank', prompt: 'Scores 100, 90, 90, 80 ranked descending with RANK()?', options: ['1, 2, 3, 4', '1, 2, 2, 3', '1, 2, 2, 4', '1, 1, 2, 3'], answer: 2 },
  // Data cleaning / Power Query
  { id: 'pl-pq-b1', area: 'pq', tier: 'Beginner', type: 'mc', concept: 'pq-append', prompt: 'You have 12 monthly files with the same columns and want all rows in one table. In Power Query you use…', options: ['Merge', 'Append', 'Pivot', 'Group By'], answer: 1 },
  { id: 'pl-pq-b2', area: 'pq', tier: 'Beginner', type: 'mc', concept: 'text-numbers', prompt: 'SUM over a quantity column gives less than you count by hand. Some cells show green triangles. Why?', options: ['SUM rounds the values it adds', 'Some quantities are stored as text and SUM skips them', 'Some rows are hidden by a filter', 'There are too many rows to add'], answer: 1 },
  { id: 'pl-pq-b3', area: 'pq', tier: 'Beginner', type: 'mc', concept: 'pq-robust', prompt: 'A query refreshed fine last month; now it fails with "column Qty not found". The usual culprit?', options: ['The version of Excel has been updated recently', 'A step (like Changed Type) that hard-codes a column name the source has renamed', 'There is too much data for it to load', 'The source file is open in Excel'], answer: 1 },
  // Analytical thinking
  { id: 'pl-th-1', area: 'think', tier: 'Beginner', type: 'mc', concept: 'pct-points', prompt: 'Conversion rose from 2.0% to 2.5%. Which is correct?', options: ['+0.5% relative', '+0.5 percentage points (+25% relative)', '+25 percentage points', '+2.5%'], answer: 1 },
  { id: 'pl-th-2', area: 'think', tier: 'Beginner', type: 'mc', concept: 'mean-median', prompt: 'Order values: 42, 38, 55, 47, 51, 39, 44, 2,450. The best "typical" value to report?', options: ['The mean (345.75)', 'The median (45.50), flagging the 2,450 order', '2,450', 'The total'], answer: 1 },
  { id: 'pl-th-3', area: 'think', tier: 'Beginner', type: 'mc', concept: 'data-trust', prompt: '"Sales increased 20% this month." Is that automatically good?', options: ['Yes, because growth is always a good thing to see', 'Not necessarily: check the season (vs last year), margin, one-off orders and the target', 'No: a 20% rise is too little to matter', 'Only if costs fell in the same month'], answer: 1 },
  { id: 'pl-th-4', area: 'think', tier: 'Beginner', type: 'mc', concept: 'chart-choice', prompt: 'Best default chart for monthly revenue over 24 months?', options: ['Pie', 'Line', 'Scatter', 'Radar'], answer: 1 },
];
