// Power BI quiz bank, part C: filter context, row context and CALCULATE.
export const PBI_QUIZ_C = [
  // ================================================================ pbi-context
  { id: 'pb2-ctx-01', topic: 'pbi-context', type: 'mc', kind: 'concept', difficulty: 2, concept: 'filter-context',
    prompt: 'A matrix shows Revenue by Category (rows) and Year (columns), with a Store slicer set to Northgate. Which filters does the cell "Tents, 2025" use?',
    options: ['Tents, 2025 and Northgate', 'Tents and 2025 only', 'Northgate only', 'No filters: it is a total'], answer: 0,
    explain: 'Each cell combines its row, its column and every slicer or filter on the page.' },
  { id: 'pb2-ctx-02', topic: 'pbi-context', type: 'tf', kind: 'concept', difficulty: 2, concept: 'filter-context',
    prompt: 'True or false: the total row of a matrix is calculated by adding up the rows above it.',
    answer: false, explain: 'The total runs the measure again with fewer filters. For SUM it matches the rows; for distinct counts and ratios it usually does not.' },
  { id: 'pb2-ctx-03', topic: 'pbi-context', type: 'number', kind: 'calculation', difficulty: 3, concept: 'filter-context',
    prompt: 'In a month, 800 customers bought online, 650 bought in store, and 250 of them did both. What does DISTINCTCOUNT of customers show in the total row?',
    answer: 1200, verify: () => 800 + 650 - 250,
    explain: '800 + 650 − 250 = 1,200. The customers who used both channels are counted once in the total.' },
  { id: 'pb2-ctx-04', topic: 'pbi-context', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'filter-context',
    prompt: 'Margin % by region shows 40%, 50% and 60%, and the total says 44%. Is the total wrong?',
    options: ['No: it is total margin over total revenue', 'Yes: it should be 50%', 'Yes: it should be 150%', 'No: totals are always the average'], answer: 0,
    explain: 'The total is the overall ratio. It sits closer to the region with the most revenue, not at the simple average of the rows.' },
  { id: 'pb2-ctx-05', topic: 'pbi-context', type: 'mc', kind: 'concept', difficulty: 2, concept: 'filter-context',
    prompt: 'Why can a Category column from the Product table filter the Sales table?',
    options: ['A relationship carries the filter to Sales', 'Both tables have a column called category', 'Power BI filters all tables at once', 'Sales has a copy of each product row'], answer: 0,
    explain: 'Filters travel along relationships, from the one side (Product) to the many side (Sales).' },
  { id: 'pb2-ctx-06', topic: 'pbi-context', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'row-context',
    prompt: 'Which function works through a table one row at a time and then adds up the results?',
    options: ['SUMX', 'SUM', 'CALCULATE', 'FILTER'], answer: 0,
    explain: 'SUMX is an iterator: it evaluates an expression for each row, then sums.' },
  { id: 'pb2-ctx-07', topic: 'pbi-context', type: 'fill', kind: 'tool-selection', difficulty: 2, concept: 'row-context',
    prompt: 'Inside SUMX over Sales, the function that fetches a Product column for the current row is ____.',
    answer: ['RELATED'], explain: 'RELATED(Product[list_price]) follows the relationship from the current Sales row to its product.' },
  { id: 'pb2-ctx-08', topic: 'pbi-context', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'row-context',
    prompt: '`SUMX(Product, Product[list_price] * RELATED(Sales[quantity]))` gives an error. Why?',
    options: ['RELATED only looks from the many side to the one side', 'SUMX cannot multiply two different columns', 'list_price must be a measure', 'Product has too few rows'], answer: 0,
    explain: 'From Product there are many sales rows, so RELATED cannot return a single value. Iterate Sales and use RELATED(Product[list_price]).' },
  { id: 'pb2-ctx-09', topic: 'pbi-context', type: 'tf', kind: 'concept', difficulty: 2, concept: 'row-context',
    prompt: 'True or false: a calculated column is computed in a row context, one row at a time.',
    answer: true, explain: 'Each row of a calculated column is computed using that row\'s values.' },
  { id: 'pb2-ctx-10', topic: 'pbi-context', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'filter-context',
    prompt: 'A table by customer region has a "(Blank)" row holding $32,000. What does it most likely contain?',
    options: ['Sales with no customer or no region', 'Sales in a region called Blank', 'Rows that failed to load', 'Returned items only'], answer: 0,
    explain: 'Walk-in sales (no customer) and customers without a region both land in (Blank). Explain it rather than hide it.' },
  { id: 'pb2-ctx-11', topic: 'pbi-context', type: 'number', kind: 'calculation', difficulty: 3, concept: 'filter-context',
    prompt: 'Store A had revenue $60,000 from 400 orders; store B had $20,000 from 200 orders. What average order value does the total row show?',
    answer: 133.33, tolerance: 0.01, verify: () => Math.round(((60000 + 20000) / (400 + 200)) * 100) / 100,
    explain: 'Total revenue ÷ total orders = 80,000 ÷ 600 = $133.33. The simple average of the two stores ($150 and $100 = $125) would be wrong.' },
  { id: 'pb2-ctx-12', topic: 'pbi-context', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'filter-context',
    prompt: 'A manager adds up the "Customers" column of a table by month and says the company has 14,000 customers. The yearly card says 6,500. What do you tell her?',
    options: ['Customers repeat across months, so months overlap', 'The card is filtered to one store', 'The monthly table is wrong', 'Both numbers need a refresh'], answer: 0,
    explain: 'Someone who buys in three months is counted in each month but once for the year. Distinct counts are not additive across periods.' },
  { id: 'pb2-ctx-13', topic: 'pbi-context', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'filter-context',
    prompt: 'A chart by Supplier shows the same purchase total for every supplier. The Supplier table is related to Ingredients, not to Purchases. What is the fix?',
    options: ['Relate Supplier to Purchases on supplier id', 'Make the Ingredients relationship both ways', 'Use AVERAGE instead of SUM', 'Add a page filter for suppliers'], answer: 0,
    explain: 'The filter needs a path from Supplier to Purchases. A direct relationship on the supplier id is the clean fix.' },
  { id: 'pb2-ctx-14', topic: 'pbi-context', type: 'tf', kind: 'concept', difficulty: 3, concept: 'filter-context',
    prompt: 'True or false: a measure used inside a calculated column can behave differently from the same measure in a visual.',
    answer: true, explain: 'In a calculated column a measure is evaluated with the current row turned into a filter (context transition), which often surprises beginners.' },
  { id: 'pb2-ctx-15', topic: 'pbi-context', type: 'mc', kind: 'concept', difficulty: 2, concept: 'row-context',
    prompt: 'What does AVERAGEX(Orders, [Order value]) average?',
    options: ['The value of each order, one per order row', 'Every sales line separately', 'The total divided by 12', 'The largest order only'], answer: 0,
    explain: 'AVERAGEX evaluates [Order value] for each row of Orders and averages those results.' },
  { id: 'pb2-ctx-16', topic: 'pbi-context', type: 'number', kind: 'calculation', difficulty: 3, concept: 'row-context',
    prompt: 'Three sales lines: 2 × list price $30, 1 × $50 and 4 × $10. What does `SUMX(Sales, Sales[qty] * RELATED(Product[list_price]))` return?',
    answer: 150, verify: () => 2 * 30 + 1 * 50 + 4 * 10,
    explain: '2×30 + 1×50 + 4×10 = 60 + 50 + 40 = 150. RELATED fetches each line\'s product price before the multiplication.' },
  { id: 'pb2-ctx-17', topic: 'pbi-context', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'filter-context',
    prompt: 'A slicer on Sales[channel] should limit which products appear in a product list visual (showing only products sold online). The list does not change. Why?',
    options: ['Filters do not flow from Sales back to Product', 'The slicer only works on numbers', 'Products have no channel', 'The slicer is on another page'], answer: 0,
    explain: 'With a single-direction relationship the filter stops at Sales. Adding a measure (such as sales lines) to the visual limits it to products with values.' },
  { id: 'pb2-ctx-18', topic: 'pbi-context', type: 'fill', kind: 'concept', difficulty: 2, concept: 'filter-context',
    prompt: 'The set of filters a measure sees in one cell of a visual is called the filter ____.',
    answer: ['context'], explain: 'Filter context: rows, columns, slicers, filters and any changes made by CALCULATE.' },
  { id: 'pb2-ctx-19', topic: 'pbi-context', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'filter-context',
    prompt: 'A card shows total revenue, but you expected it to follow the Year slicer. Edit interactions is set to Filter. What else could stop it?',
    options: ['The Year slicer uses the fact table\'s year, unrelated to the card\'s table', 'The card uses a SUM measure instead of COUNT', 'The card is formatted with a dark theme', 'The slicer is displayed as a dropdown list'], answer: 0,
    explain: 'If the slicer column cannot reach the card\'s data through relationships, the card ignores it.' },
  { id: 'pb2-ctx-20', topic: 'pbi-context', type: 'tf', kind: 'concept', difficulty: 2, concept: 'row-context',
    prompt: 'True or false: SUM(Sales[amount]) and SUMX(Sales, Sales[amount]) return the same result.',
    answer: true, explain: 'SUM of a single column is shorthand for SUMX over that column. The difference matters when the expression uses several columns.' },
  { id: 'pb2-ctx-21', topic: 'pbi-context', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'filter-context',
    prompt: 'Online customers 1,366 and In-store customers 1,228 add up to 2,594, but the total shows 2,053. About how many customers used both channels?',
    options: ['541', '2,053', '138', '1,366'], answer: 0,
    verify: () => String(1366 + 1228 - 2053),
    explain: '2,594 − 2,053 = 541 people appear in both channel rows but once in the total.' },
  { id: 'pb2-ctx-22', topic: 'pbi-context', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'filter-context',
    prompt: 'An NGO table shows donations by campaign, and the "Donors" column adds up to more than the number of donors. What should the report say?',
    options: ['Some donors gave to several campaigns', 'The data has errors', 'Donors must be summed instead', 'Hide the total row'], answer: 0,
    explain: 'That is the overlap between campaigns. Explaining it is more useful than hiding the total.' },
  { id: 'pb2-ctx-23', topic: 'pbi-context', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'row-context',
    prompt: 'You need, for each product, the number of sales lines, as a column in the Product table. Which calculated column works?',
    options: ['COUNTROWS(RELATEDTABLE(Sales))', 'RELATED(Sales[quantity])', 'COUNT(Product[product_id])', 'SUM(Sales[quantity])'], answer: 0,
    explain: 'RELATEDTABLE returns the Sales rows related to the current product; COUNTROWS counts them.' },
  { id: 'pb2-ctx-24', topic: 'pbi-context', type: 'order', kind: 'sequence', difficulty: 3, concept: 'row-context',
    prompt: 'Order what SUMX(Sales, Sales[qty] * Sales[price]) does.',
    options: ['Take the Sales rows allowed by the filters', 'For each row, multiply qty by price', 'Keep each row\'s result', 'Add up all the results'], answer: [0, 1, 2, 3],
    explain: 'An iterator starts from the filtered table, evaluates the expression per row, then aggregates.' },
  { id: 'pb2-ctx-25', topic: 'pbi-context', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'filter-context',
    prompt: 'Revenue by Product shows a "(Blank)" product with $4,000. The product table was built from last year\'s catalogue. Most likely?',
    options: ['This year\'s new products are missing from it', 'Four thousand products have no name', 'The revenue measure is wrong', 'The date table is missing'], answer: 0,
    explain: 'Sales rows whose product id is not in the dimension fall under (Blank). Update the product table so every sold product exists.' },

  // ================================================================ pbi-calculate
  { id: 'pb2-calc-01', topic: 'pbi-calculate', type: 'fill', kind: 'concept', difficulty: 2, concept: 'calculate',
    prompt: 'The DAX function that evaluates an expression with modified filters is ____.',
    answer: ['CALCULATE'], explain: 'CALCULATE(expression, filter1, filter2...) is the most important DAX function.' },
  { id: 'pb2-calc-02', topic: 'pbi-calculate', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'calculate',
    prompt: 'Which measure returns revenue for the Online channel only, in any visual?',
    options: ['CALCULATE([Revenue], Sales[channel] = "Online")', 'FILTER([Revenue], Sales[channel] = "Online")', 'SUM(Sales[channel] = "Online")', 'IF(Sales[channel] = "Online", [Revenue])'], answer: 0,
    explain: 'CALCULATE adds the channel filter to whatever the visual already filters. FILTER returns a table, not a number.' },
  { id: 'pb2-calc-03', topic: 'pbi-calculate', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'calculate',
    prompt: 'In a table by channel, `Online revenue = CALCULATE([Revenue], Sales[channel] = "Online")` shows the online value on the In-Store row too. Why?',
    options: ['CALCULATE replaces the row\'s channel filter with Online', 'The relationship is broken', 'The In-Store rows are duplicated', 'DIVIDE was not used'], answer: 0,
    explain: 'A CALCULATE filter on a column overwrites any existing filter on that same column, so every row shows online revenue.' },
  { id: 'pb2-calc-04', topic: 'pbi-calculate', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'calculate',
    prompt: 'Which denominator makes "category share of total" work in a table by category?',
    options: ['CALCULATE([Revenue], ALL(Product[category]))', 'CALCULATE([Revenue], Product[category])', 'SUM(Product[category])', 'CALCULATE([Revenue], VALUES(Product[category]))'], answer: 0,
    explain: 'ALL removes the category filter so the denominator is the revenue of all categories under the other filters.' },
  { id: 'pb2-calc-05', topic: 'pbi-calculate', type: 'number', kind: 'calculation', difficulty: 2, concept: 'calculate',
    prompt: 'Tents revenue is $91,000 and revenue for all categories is $455,000. What does the share measure return, as a percentage?',
    answer: 20, verify: () => (91000 / 455000) * 100,
    explain: '91,000 ÷ 455,000 = 0.20 = 20%. The denominator is the revenue of all categories under the same other filters (year, store...).' },
  { id: 'pb2-calc-06', topic: 'pbi-calculate', type: 'tf', kind: 'concept', difficulty: 3, concept: 'calculate',
    prompt: 'True or false: ALL(Product[category]) removes the category filter but keeps a year filter from a slicer.',
    answer: true, explain: 'ALL on one column removes filters on that column only. Other filters stay in place.' },
  { id: 'pb2-calc-07', topic: 'pbi-calculate', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'calculate',
    prompt: 'A "% of total" measure uses `CALCULATE([Revenue], ALL(Sales))`. With the page filtered to 2025, the shares add up to far less than 100%. Why?',
    options: ['ALL(Sales) also removed the year filter from the denominator', 'Categories are missing from Sales', 'DIVIDE rounds the values down to zero', 'The measure needs SUMX'], answer: 0,
    explain: 'ALL(Sales) removes every filter on the Sales table, so the denominator became revenue for all years. Remove only the filter you mean.' },
  { id: 'pb2-calc-08', topic: 'pbi-calculate', type: 'mc', kind: 'concept', difficulty: 3, concept: 'calculate',
    prompt: 'What does `CALCULATE([Revenue], Store[region] = "West", Product[category] = "Tents")` return?',
    options: ['Revenue for Tents in West stores', 'Revenue for West or for Tents', 'Revenue for everything except Tents', 'An error: only one filter allowed'], answer: 0,
    explain: 'Several filter arguments combine with AND.' },
  { id: 'pb2-calc-09', topic: 'pbi-calculate', type: 'fill', kind: 'tool-selection', difficulty: 3, concept: 'calculate',
    prompt: 'A function that removes filters and is often used as a clearer synonym of ALL inside CALCULATE is REMOVE____.',
    answer: ['FILTERS'], explain: 'REMOVEFILTERS(Product[category]) inside CALCULATE does the same as ALL for this purpose and reads clearly.' },
  { id: 'pb2-calc-10', topic: 'pbi-calculate', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'calculate',
    prompt: 'A restaurant group wants "Revenue from main courses" that works in every chart. Main courses are menu category "Mains". Which measure?',
    options: ['CALCULATE([Net sales], Menu[category] = "Mains")', 'SUM(Menu[category] = "Mains")', 'COUNTROWS(FILTER(Menu, "Mains"))', 'AVERAGE(Menu[category])'], answer: 0,
    explain: 'CALCULATE with a filter on the menu dimension; the relationship carries it to the sales rows.' },
  { id: 'pb2-calc-11', topic: 'pbi-calculate', type: 'number', kind: 'calculation', difficulty: 3, concept: 'calculate',
    prompt: 'Online revenue is $433,600 and total revenue $861,600. What is the online share, to one decimal place?',
    answer: 50.3, tolerance: 0.05, verify: () => Math.round((433600 / 861600) * 1000) / 10,
    explain: '433,600 ÷ 861,600 = 50.3%. About half of revenue is online, so a channel filter changes almost every number in the report.' },
  { id: 'pb2-calc-12', topic: 'pbi-calculate', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'calculate',
    prompt: 'You want revenue from products priced over $100 (list price). Which filter argument is valid inside CALCULATE?',
    options: ['Product[list_price] > 100', '[Revenue] > 100', 'SUM(Product[list_price]) > 100', 'Product > 100'], answer: 0,
    explain: 'Simple filter arguments compare a column with a value. Filtering on a measure needs FILTER over a table.' },
  { id: 'pb2-calc-13', topic: 'pbi-calculate', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'calculate',
    prompt: 'You need revenue from customers whose total spend is above $1,000. Which approach fits?',
    options: ['CALCULATE([Revenue], FILTER(VALUES(Customer[id]), [Revenue] > 1000))', 'CALCULATE([Revenue], [Revenue] > 1000)', 'CALCULATE([Revenue], Customer[id] > 1000)', 'SUMX(Customer, [Revenue] > 1000)'], answer: 0,
    explain: 'Filtering on a measure requires FILTER over a table of customers, keeping those whose revenue exceeds 1,000.' },
  { id: 'pb2-calc-14', topic: 'pbi-calculate', type: 'tf', kind: 'concept', difficulty: 2, concept: 'calculate',
    prompt: 'True or false: CALCULATE can reference other measures as its first argument.',
    answer: true, explain: 'CALCULATE([Revenue], ...) is the usual pattern: build base measures, then filter them.' },
  { id: 'pb2-calc-15', topic: 'pbi-calculate', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'calculate',
    prompt: 'A "Share of region" measure shows 100% on every region row and 100% in the total. What is the likely mistake?',
    options: ['The denominator did not remove the region filter', 'The numerator removed every filter', 'The regions are not related', 'The measure uses DIVIDE'], answer: 0,
    explain: 'If the denominator keeps the region filter, each region is divided by itself.' },
  { id: 'pb2-calc-16', topic: 'pbi-calculate', type: 'number', kind: 'calculation', difficulty: 3, concept: 'calculate',
    prompt: 'In-store revenue is $298,000 and Footwear in-store revenue is $60,700. What is Footwear\'s share of in-store revenue, to one decimal place?',
    answer: 20.4, tolerance: 0.05, verify: () => Math.round((60700 / 298000) * 1000) / 10,
    explain: '60,700 ÷ 298,000 = 20.4%. The denominator keeps the channel filter (In-Store) and removes only the category filter.' },
  { id: 'pb2-calc-17', topic: 'pbi-calculate', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'calculate',
    prompt: 'HR wants "Absence rate for Drivers" next to the overall absence rate in a table by month. What is the neat way?',
    options: ['CALCULATE([Absence rate], Employee[role] = "Driver")', 'A separate report for drivers', 'A page filter on role', 'A calculated column for drivers'], answer: 0,
    explain: 'A CALCULATE measure keeps the month filter and fixes the role, so both rates sit side by side.' },
  { id: 'pb2-calc-18', topic: 'pbi-calculate', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'calculate',
    prompt: '`West revenue = CALCULATE([Revenue], Store[region] = "West")` shows West revenue even when the slicer is set to North. The director wants it blank then. What respects the slicer?',
    options: ['CALCULATE([Revenue], KEEPFILTERS(Store[region] = "West"))', 'CALCULATE([Revenue], ALL(Store[region]))', 'CALCULATE([Revenue], REMOVEFILTERS(Store))', 'SUM(Store[region] = "West")'], answer: 0,
    explain: 'KEEPFILTERS intersects the new filter with the existing one: West ∩ North is empty, so the result is blank.' },
  { id: 'pb2-calc-19', topic: 'pbi-calculate', type: 'fill', kind: 'concept', difficulty: 3, concept: 'calculate',
    prompt: 'The CALCULATE modifier that keeps existing filters on a column instead of replacing them is ____.',
    answer: ['KEEPFILTERS'], explain: 'KEEPFILTERS(filter) makes the new filter combine with the old one (AND) rather than overwrite it.' },
  { id: 'pb2-calc-20', topic: 'pbi-calculate', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'calculate',
    prompt: 'In a table of stores, which measure shows every store\'s revenue as a share of the stores shown after a slicer selection?',
    options: ['DIVIDE([Revenue], CALCULATE([Revenue], ALLSELECTED(Store)))', 'DIVIDE([Revenue], CALCULATE([Revenue], ALL(Store)))', 'DIVIDE([Revenue], [Revenue])', 'DIVIDE([Revenue], SUM(Store[store_id]))'], answer: 0,
    explain: 'ALLSELECTED keeps the slicer selection but removes the row\'s own store filter, so shares add up to 100% of what is selected.' },
  { id: 'pb2-calc-21', topic: 'pbi-calculate', type: 'tf', kind: 'concept', difficulty: 3, concept: 'calculate',
    prompt: 'True or false: FILTER returns a table, so on its own it cannot be put in a card.',
    answer: true, explain: 'FILTER is used inside CALCULATE or iterators. A card needs a single value.' },
  { id: 'pb2-calc-22', topic: 'pbi-calculate', type: 'number', kind: 'calculation', difficulty: 3, concept: 'calculate',
    prompt: 'Selected stores have revenue $120,000 in total. Store C has $30,000. What does the ALLSELECTED share measure show for Store C, as a percentage?',
    answer: 25, verify: () => (30000 / 120000) * 100,
    explain: '30,000 ÷ 120,000 = 25% of the selected stores.' },
  { id: 'pb2-calc-23', topic: 'pbi-calculate', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'calculate',
    prompt: 'An e-commerce manager wants conversion rate = orders ÷ sessions, but only for mobile traffic. Sessions and Orders are separate tables that share a Device dimension. Which measure?',
    options: ['CALCULATE(DIVIDE([Orders], [Sessions]), Device[type] = "Mobile")', 'DIVIDE([Orders], [Sessions]) * 0.5', 'COUNTROWS(FILTER(Device, "Mobile"))', 'DIVIDE(SUM(Device[type]), [Sessions])'], answer: 0,
    explain: 'The Device filter flows to both fact tables, so both parts of the ratio are limited to mobile.' },
  { id: 'pb2-calc-24', topic: 'pbi-calculate', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'calculate',
    prompt: '`CALCULATE([Revenue], Sales[discount] > 0)` returns blank in every cell. Sales[discount] is text ("0.15"). What is wrong?',
    options: ['A text column cannot be compared with a number', 'CALCULATE cannot filter the fact table', 'Discounts need a date table', 'The measure needs ALL'], answer: 0,
    explain: 'The comparison fails because the column is text. Fix the type in Power Query.' },
  { id: 'pb2-calc-25', topic: 'pbi-calculate', type: 'mc', kind: 'concept', difficulty: 2, concept: 'calculate',
    prompt: 'What happens to the filters from a visual\'s rows when a measure uses CALCULATE with a filter on a different column?',
    options: ['They stay and are combined with the new filter', 'They are all removed', 'They are replaced by the new filter', 'They only apply to the total row'], answer: 0,
    explain: 'CALCULATE only changes filters on the columns it names. The rest of the context stays.' },
  { id: 'pb2-calc-26', topic: 'pbi-calculate', type: 'order', kind: 'sequence', difficulty: 3, concept: 'calculate',
    prompt: 'Order the steps to build a "category share of total" measure.',
    options: ['Create [Revenue] = SUM(...)', 'Create the denominator with ALL on category', 'Divide [Revenue] by the denominator with DIVIDE', 'Format the result as a percentage'], answer: [0, 1, 2, 3],
    explain: 'Base measure first, then the denominator, then the ratio, then formatting.' },
  { id: 'pb2-calc-27', topic: 'pbi-calculate', type: 'tf', kind: 'concept', difficulty: 3, concept: 'calculate',
    prompt: 'True or false: `CALCULATE([Revenue], Product[is_active] = 1)` filters Sales even though is_active lives in the Product table.',
    answer: true, explain: 'The filter on Product travels to Sales through the relationship.' },
  { id: 'pb2-calc-28', topic: 'pbi-calculate', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'calculate',
    prompt: 'A card "Revenue (all regions)" = CALCULATE([Revenue], ALL(Store[region])) shows $900k. After selecting 2024 in a Year slicer it shows $310k. Is that right?',
    options: ['Yes: only the region filter is removed', 'No: ALL should ignore the year too', 'No: it should show $900k always', 'Yes, but only by coincidence'], answer: 0,
    explain: 'ALL(Store[region]) keeps the year filter. The card shows 2024 revenue for all regions.' },
  { id: 'pb2-calc-29', topic: 'pbi-calculate', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'calculate',
    prompt: 'Finance wants revenue excluding cancelled orders, and the fact table has a status column. What is the most maintainable approach?',
    options: ['One base measure with CALCULATE on status "completed"', 'A page filter on every page', 'Delete cancelled rows in each visual', 'A second copy of the table'], answer: 0,
    explain: 'A single measure encodes the business rule once, so every visual uses the same definition. (Removing cancelled rows in Power Query is also fine if they are never needed.)' },
  { id: 'pb2-calc-30', topic: 'pbi-calculate', type: 'number', kind: 'calculation', difficulty: 3, concept: 'calculate',
    prompt: 'West stores made $55,300 in the summer; all stores in-store made $196,600. What share is West, to one decimal place?',
    answer: 28.1, tolerance: 0.05, verify: () => Math.round((55300 / 196600) * 1000) / 10,
    explain: '55,300 ÷ 196,600 = 28.1%. The denominator is in-store revenue only, so the online shop does not dilute the West share.' },
  { id: 'pb2-calc-31', topic: 'pbi-calculate', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'calculate',
    prompt: 'A "Last year" measure written as `CALCULATE([Revenue], \'Date\'[Year] = 2024)` always shows 2024, even when 2026 is selected. What is the better approach?',
    options: ['Use SAMEPERIODLASTYEAR on the date column', 'Add KEEPFILTERS to the year filter', 'Hard-code 2025 as well', 'Use a calculated column'], answer: 0,
    explain: 'Hard-coded years do not move. Time-intelligence functions shift whatever period is selected.' },
  { id: 'pb2-calc-32', topic: 'pbi-calculate', type: 'fill', kind: 'tool-selection', difficulty: 3, concept: 'calculate',
    prompt: 'Complete: `% of selected = DIVIDE([Revenue], CALCULATE([Revenue], ____(Store)))` so shares follow the slicer selection.',
    answer: ['ALLSELECTED'], explain: 'ALLSELECTED keeps outer selections while removing the row-level store filter.' },
  { id: 'pb2-calc-33', topic: 'pbi-calculate', type: 'mc', kind: 'concept', difficulty: 2, concept: 'calculate',
    prompt: 'Why is it good to build "Online revenue" on top of [Revenue] rather than repeating SUM(...)?',
    options: ['A change to the revenue rule updates every measure', 'It makes the report file much smaller', 'CALCULATE cannot use SUM', 'It removes all filters'], answer: 0,
    explain: 'One definition of revenue, reused everywhere, keeps numbers consistent.' },
  { id: 'pb2-calc-34', topic: 'pbi-calculate', type: 'tf', kind: 'concept', difficulty: 3, concept: 'calculate',
    prompt: 'True or false: two filter arguments on the same column in one CALCULATE (for example region = "West" and region = "North") return revenue for both regions.',
    answer: false, explain: 'Filters combine with AND, and no row is both West and North, so the result is blank. Use IN {"West","North"} instead.' },
  { id: 'pb2-calc-35', topic: 'pbi-calculate', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'calculate',
    prompt: 'Which filter returns revenue for West and North together?',
    options: ['Store[region] IN {"West", "North"}', 'Store[region] = "West" && "North"', 'Store[region] = "West", "North"', 'Store[region] BETWEEN "North" AND "West"'], answer: 0,
    explain: 'IN with a list checks membership. It is the DAX equivalent of SQL\'s IN.' },
  { id: 'pb2-calc-36', topic: 'pbi-calculate', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'calculate',
    prompt: 'Revenue from inactive products is 3.6% of this year\'s revenue. What does that mean for the buying team?',
    options: ['A small amount of revenue needs replacing', 'Inactive products are the main business', 'The measure is wrong', 'Nothing: 3.6% cannot matter'], answer: 0,
    explain: 'The products are being phased out, so that revenue has to come from somewhere else. Small, but real.' },
  { id: 'pb2-calc-37', topic: 'pbi-calculate', type: 'mc', kind: 'scenario', difficulty: 4, concept: 'calculate',
    prompt: 'A report shows Canyon store at 47% of West revenue. The director asks whether that makes Canyon "the West\'s best store". What do you add?',
    options: ['Context: West has only two stores, so 47% is second place', 'Nothing: 47% is clearly the top', 'A pie chart of the two stores instead', 'A bigger font for the number'], answer: 0,
    explain: 'With two stores, 47% means Canyon is slightly behind the other store. A share needs its denominator described.' },
];
