// Power BI quiz bank, part B: date tables, visuals and filters, report pages, first DAX measures.
export const PBI_QUIZ_B = [
  // ================================================================ pbi-datetable
  { id: 'pb2-date-01', topic: 'pbi-datetable', type: 'mc', kind: 'tool-selection', difficulty: 1, concept: 'date-table',
    prompt: 'Which DAX function creates a table with one row for every day between two dates?',
    options: ['CALENDAR', 'DATESBETWEEN', 'DATEDIFF', 'EOMONTH'], answer: 0,
    explain: 'CALENDAR(start, end) returns a single Date column with every day in the range. DATESBETWEEN filters an existing date column; it does not build a table.' },
  { id: 'pb2-date-02', topic: 'pbi-datetable', type: 'number', kind: 'calculation', difficulty: 2, concept: 'date-table',
    prompt: 'A date table runs from 1 January 2023 to 31 December 2024. How many rows does it have?',
    answer: 731, verify: () => 365 + 366,
    explain: '2023 has 365 days and 2024 is a leap year with 366: 731 rows. A quick row check catches tables that stop early.' },
  { id: 'pb2-date-03', topic: 'pbi-datetable', type: 'tf', kind: 'concept', difficulty: 1, concept: 'date-table',
    prompt: 'True or false: after marking a table as a date table, you still need a relationship from it to the fact table\'s date column.',
    answer: true, explain: 'Marking tells Power BI which column is the calendar. The relationship is what lets its filters reach the facts.' },
  { id: 'pb2-date-04', topic: 'pbi-datetable', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'date-table',
    prompt: 'A chart by Month shows April, August, December, February... How do you fix the order?',
    options: ['Sort the Month column by Month number', 'Rename the months with numbers first', 'Sort the chart by revenue instead', 'Use the fact table\'s date column'], answer: 0,
    explain: 'Column tools → Sort by column → Month number. Month names are text and sort alphabetically unless told otherwise.' },
  { id: 'pb2-date-05', topic: 'pbi-datetable', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'date-table',
    prompt: 'A Year slicer from the date table changes nothing on a sales chart. What is the most likely cause?',
    options: ['The date table is not related to the sales date', 'The slicer is set to a list style', 'The sales table has too many rows', 'The Year column is a whole number'], answer: 0,
    explain: 'Without a relationship the date filter has no path to the sales rows, so the chart stays the same.' },
  { id: 'pb2-date-06', topic: 'pbi-datetable', type: 'fill', kind: 'concept', difficulty: 2, concept: 'date-table',
    prompt: 'To stop Power BI creating hidden date tables for every date column, switch off Auto ____ in Options.',
    answer: ['date/time', 'date time', 'datetime'], explain: 'File → Options → Current file → Data load → Auto date/time. One marked date table replaces them.' },
  { id: 'pb2-date-07', topic: 'pbi-datetable', type: 'mc', kind: 'concept', difficulty: 2, concept: 'date-table',
    prompt: 'What does `WEEKDAY([Date], 2)` return for a Monday?',
    options: ['1', '2', '0', '7'], answer: 0,
    verify: () => '1',
    explain: 'Return type 2 numbers Monday as 1 through Sunday as 7. The default (type 1) starts at Sunday = 1.' },
  { id: 'pb2-date-08', topic: 'pbi-datetable', type: 'number', kind: 'calculation', difficulty: 2, concept: 'date-table',
    prompt: 'A company\'s fiscal year starts on 1 April and is named after the year it ends. Using `YEAR([Date]) + IF(MONTH([Date]) >= 4, 1, 0)`, which fiscal year does 15 May 2025 fall in?',
    answer: 2026, verify: () => 2025 + (5 >= 4 ? 1 : 0),
    explain: 'May is on or after April, so 1 is added: fiscal year 2026 (April 2025 to March 2026).' },
  { id: 'pb2-date-09', topic: 'pbi-datetable', type: 'tf', kind: 'concept', difficulty: 2, concept: 'date-table',
    prompt: 'True or false: a date table should start on the first day of the earliest year in your data, even if the first sale was in March.',
    answer: true, explain: 'Whole years keep year-to-date and same-period-last-year calculations correct from the start.' },
  { id: 'pb2-date-10', topic: 'pbi-datetable', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'date-table',
    prompt: 'A restaurant wants to compare lunchtime Fridays with Saturdays. Which date table column makes this easy?',
    options: ['Weekday name, sorted by weekday number', 'A column with the full date as text', 'A column with the year only', 'A column with the day of the month'], answer: 0,
    explain: 'A weekday column lets any visual group sales by day of the week; sorting by weekday number keeps Monday to Sunday in order.' },
  { id: 'pb2-date-11', topic: 'pbi-datetable', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'date-table',
    prompt: 'The Year slicer lists 1899, 2024 and 2025. Where does 1899 most likely come from?',
    options: ['Blank or zero dates in the data', 'A leap year in the date table', 'A fiscal year column', 'A report theme setting'], answer: 0,
    explain: 'Zero or broken dates often show up as 30/12/1899. Find those rows in Power Query instead of widening the calendar.' },
  { id: 'pb2-date-12', topic: 'pbi-datetable', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'date-table',
    prompt: 'You want the date table to cover exactly the years present in the model, automatically. Which function helps?',
    options: ['CALENDARAUTO', 'CALENDAR with fixed dates', 'TODAY', 'DATEADD'], answer: 0,
    explain: 'CALENDARAUTO scans the model\'s date columns and builds whole years around them. Check the result: a stray 1899 date widens it.' },
  { id: 'pb2-date-13', topic: 'pbi-datetable', type: 'order', kind: 'sequence', difficulty: 2, concept: 'date-table',
    prompt: 'Order the columns from the biggest period to the smallest.',
    options: ['Year', 'Quarter', 'Month', 'Date'], answer: [0, 1, 2, 3],
    explain: 'Year → Quarter → Month → Date is the natural drill-down hierarchy for a calendar.' },
  { id: 'pb2-date-14', topic: 'pbi-datetable', type: 'fill', kind: 'concept', difficulty: 1, concept: 'date-table',
    prompt: 'Complete: `"Quarter", "Q" & ____([Date])` adds a column like Q1, Q2...',
    answer: ['QUARTER'], explain: 'QUARTER returns 1-4; joining it to "Q" gives a readable label.' },
  { id: 'pb2-date-15', topic: 'pbi-datetable', type: 'tf', kind: 'concept', difficulty: 2, concept: 'date-table',
    prompt: 'True or false: using the fact table\'s order_date on a chart axis is as good as using the date table\'s Date.',
    answer: false, explain: 'The fact table has no rows for days without sales and no extra columns. Use the date table so every visual shares one calendar.' },
  { id: 'pb2-date-16', topic: 'pbi-datetable', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'date-table',
    prompt: 'Orders have both an order date and a ship date. You want sales by order month and shipments by ship month. What is a common design?',
    options: ['One date table with an inactive ship-date relationship', 'Two separate sales tables, one per date', 'Merge both dates into one column', 'Remove the ship date'], answer: 0,
    explain: 'Relate both dates; one relationship is active and the other is used with USERELATIONSHIP in the shipments measure (or use a second date table).' },
  { id: 'pb2-date-17', topic: 'pbi-datetable', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'date-table',
    prompt: 'Power BI will not let you mark a table as a date table. What is the likely problem?',
    options: ['The date column has gaps or repeated dates', 'The table has more than 12 columns', 'The table has a Month name column', 'The dates are in 2026'], answer: 0,
    explain: 'The marked column must contain unique dates with no gaps (and no time parts or blanks).' },
  { id: 'pb2-date-18', topic: 'pbi-datetable', type: 'number', kind: 'calculation', difficulty: 2, concept: 'denominator', crossConcept: true,
    prompt: 'A new café opened on 1 November and took $18,300 up to 31 December. What was its average revenue per day open?',
    answer: 300, verify: () => 18300 / (30 + 31),
    explain: 'November has 30 days and December 31: 61 days, so $18,300 ÷ 61 = $300 a day. Dividing by 365 would say $50, which is wrong for a café that did not exist for ten months.' },
  { id: 'pb2-date-19', topic: 'pbi-datetable', type: 'mc', kind: 'concept', difficulty: 2, concept: 'date-table',
    prompt: 'Why add a "Month number" column when you already have "Month"?',
    options: ['To sort the month names in calendar order', 'To make the table smaller', 'Because visuals cannot show text', 'To remove leap years'], answer: 0,
    explain: 'Month names sort alphabetically. Sort by column uses Month number to put January first.' },
  { id: 'pb2-date-20', topic: 'pbi-datetable', type: 'tf', kind: 'concept', difficulty: 3, concept: 'date-table',
    prompt: 'True or false: a date column that includes a time (like 2025-06-01 14:32) can still match a pure date table without any change.',
    answer: false, explain: 'A date with a time part does not equal the date at midnight. Convert it to a date only (or split date and time) before relating.' },
  { id: 'pb2-date-21', topic: 'pbi-datetable', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'date-table',
    prompt: 'A matrix by Year and Quarter shows Q1 to Q4 for 2025 but only Q1 to Q3 for 2026, and today is 20 September 2026. Is something broken?',
    options: ['No: Q4 2026 has not happened yet', 'Yes: the date table is missing Q4', 'Yes: the relationship is inactive', 'Yes: 2026 was loaded as text'], answer: 0,
    explain: 'Quarters without sales show no row in a matrix by default. Q3 is also incomplete, which matters when comparing it with a full Q3 last year.' },
  { id: 'pb2-date-22', topic: 'pbi-datetable', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'date-table',
    prompt: 'Where can a date table be created besides DAX?',
    options: ['In Power Query, from a list of dates', 'Only in an external database', 'In the Format pane', 'In the Filters pane'], answer: 0,
    explain: 'Power Query can generate a date list (for example with List.Dates) and add columns. Either way, mark it and relate it.' },
  { id: 'pb2-date-23', topic: 'pbi-datetable', type: 'number', kind: 'calculation', difficulty: 3, concept: 'date-table',
    prompt: 'Weekend revenue was $52,000 out of $182,000 for the year. What percentage is that (to one decimal place)?',
    answer: 28.6, tolerance: 0.05, verify: () => Math.round((52000 / 182000) * 1000) / 10,
    explain: '52,000 ÷ 182,000 = 28.6%. Weekends are 2 of 7 days (28.6%), so this business sells about the same per day at weekends as on weekdays.' },
  { id: 'pb2-date-24', topic: 'pbi-datetable', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'seasonality', crossConcept: true,
    prompt: 'A ski-hire shop compares December with November and celebrates a 180% jump. What is the better comparison?',
    options: ['December with December last year', 'December with the yearly average', 'December with the best month ever', 'December with next January'], answer: 0,
    explain: 'Seasonal businesses should be compared like for like. The date table makes same-period-last-year comparisons easy.' },
  { id: 'pb2-date-25', topic: 'pbi-datetable', type: 'fill', kind: 'concept', difficulty: 2, concept: 'date-table',
    prompt: 'The function that returns the last day of a month, useful for month-end stock dates, is ____.',
    answer: ['EOMONTH'], explain: 'EOMONTH(date, 0) returns the last day of that date\'s month.' },

  // ================================================================ pbi-visuals
  { id: 'pb2-vis-01', topic: 'pbi-visuals', type: 'mc', kind: 'tool-selection', difficulty: 1, concept: 'chart-choice', crossConcept: true,
    prompt: 'Which visual best compares revenue across 12 product categories?',
    options: ['A sorted bar chart', 'A pie chart', 'A line chart', 'A single card'], answer: 0,
    explain: 'Bars sorted by value make ranking and gaps obvious. Twelve pie slices are hard to compare.' },
  { id: 'pb2-vis-02', topic: 'pbi-visuals', type: 'mc', kind: 'concept', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'What does a page-level filter affect?',
    options: ['Every visual on that page', 'Only the selected visual', 'Every page in the report', 'Only slicers'], answer: 0,
    explain: 'Visual filters affect one visual, page filters one page, report filters every page.' },
  { id: 'pb2-vis-03', topic: 'pbi-visuals', type: 'tf', kind: 'concept', difficulty: 1, concept: 'pbi-visuals',
    prompt: 'True or false: a slicer is a filter that report readers can change themselves.',
    answer: true, explain: 'Slicers are visible, clickable filters. Filters in the Filters pane can be hidden or locked.' },
  { id: 'pb2-vis-04', topic: 'pbi-visuals', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'A card still shows all regions although you picked "North" in a slicer. What should you check?',
    options: ['Edit interactions: the slicer may be set not to filter the card', 'Whether the card font is too small to update', 'Whether North has its own theme colour', 'Whether the page background is transparent'], answer: 0,
    explain: 'Format → Edit interactions shows, for each visual, whether the selected slicer filters it.' },
  { id: 'pb2-vis-05', topic: 'pbi-visuals', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'Which visual shows revenue by Region and Year in a grid with subtotals?',
    options: ['Matrix', 'Card', 'Donut chart', 'Slicer'], answer: 0,
    explain: 'A matrix is Power BI\'s pivot table: rows, columns and subtotals.' },
  { id: 'pb2-vis-06', topic: 'pbi-visuals', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'A column chart\'s axis starts at 90,000, and a 4% difference looks like a doubling. What is the issue?',
    options: ['A truncated axis exaggerates differences', 'The chart uses too many colours', 'The data is filtered by year', 'The chart is sorted by value'], answer: 0,
    explain: 'Bars should start at zero, because readers compare bar lengths. Set the axis start to 0.' },
  { id: 'pb2-vis-07', topic: 'pbi-visuals', type: 'fill', kind: 'tool-selection', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'To stop clicks in one chart from filtering another, use Format → Edit ____.',
    answer: ['interactions'], explain: 'Edit interactions lets you set filter, highlight or none for each pair of visuals.' },
  { id: 'pb2-vis-08', topic: 'pbi-visuals', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'A hotel manager wants to see occupancy for a chosen month and hotel without the report author\'s help. What do you add?',
    options: ['Month and hotel slicers', 'A text box with instructions', 'A second copy of the page', 'A report-level filter'], answer: 0,
    explain: 'Slicers let the manager pick the month and hotel. A fixed report-level filter would need the author to change it.' },
  { id: 'pb2-vis-09', topic: 'pbi-visuals', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'True or false: dragging a number column into a visual creates an automatic "Sum of" aggregation.',
    answer: true, explain: 'That is an implicit measure. Explicit DAX measures are better for anything you reuse.' },
  { id: 'pb2-vis-10', topic: 'pbi-visuals', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-visuals',
    prompt: 'A table visual shows "Sum of Price" for each order, but you wanted the average price. Where do you fix it quickly?',
    options: ['Change the field\'s summary to Average in the well', 'Change the Price column type to text', 'Add a page-level filter on the Price column', 'Switch the table visual to a card visual'], answer: 0,
    explain: 'The field dropdown in the well changes the implicit aggregation. For reports that matter, write an explicit AVERAGE measure.' },
  { id: 'pb2-vis-11', topic: 'pbi-visuals', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'You want to show only the top 10 products in a bar chart. What do you use?',
    options: ['A Top N filter on the visual', 'A pie chart with 10 slices', 'A report-level filter on price', 'A text box listing them'], answer: 0,
    explain: 'The visual-level Top N filter keeps the 10 products with the highest value of a chosen measure and follows other filters.' },
  { id: 'pb2-vis-12', topic: 'pbi-visuals', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'A line chart by month dips to zero in June for one store. What should you do before reporting a collapse?',
    options: ['Check whether June data exists for that store', 'Report the collapse straight away', 'Change the line colour', 'Smooth the line'], answer: 0,
    explain: 'A zero can be a missing file or a closed store. Confirm the data before explaining it.' },
  { id: 'pb2-vis-13', topic: 'pbi-visuals', type: 'fill', kind: 'concept', difficulty: 1, concept: 'pbi-visuals',
    prompt: 'The three filter levels in Power BI are visual, page and ____.',
    answer: ['report'], explain: 'Visual, page and report level filters, from narrowest to widest.' },
  { id: 'pb2-vis-14', topic: 'pbi-visuals', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'chart-honesty', crossConcept: true,
    prompt: 'Two charts on a page use different colours for the same region. What is the risk?',
    options: ['Readers misread which bar is which region', 'The report will not refresh', 'The totals will change', 'Slicers stop working'], answer: 0,
    explain: 'Consistent colours for the same category across a page (and report) prevent misreading. A theme or data colours fix it.' },
  { id: 'pb2-vis-15', topic: 'pbi-visuals', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'True or false: a slicer only filters the page it is on, unless you sync it to other pages.',
    answer: true, explain: 'Slicers are page-scoped by default. View → Sync slicers applies them across pages.' },
  { id: 'pb2-vis-16', topic: 'pbi-visuals', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'Which visual lets readers see the exact numbers per order line?',
    options: ['Table', 'Gauge', 'Pie chart', 'Card'], answer: 0,
    explain: 'Detail belongs in a table (or matrix). Keep it below the summary visuals.' },
  { id: 'pb2-vis-17', topic: 'pbi-visuals', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-visuals',
    prompt: 'A slicer from the fact table lists only the regions that sold something this month. Why is that a problem?',
    options: ['Regions with no sales cannot be selected or shown', 'The slicer becomes too long', 'The regions change colour', 'Totals are doubled'], answer: 0,
    explain: 'Use the dimension column for slicers so every region is listed, including those with zero sales worth noticing.' },
  { id: 'pb2-vis-18', topic: 'pbi-visuals', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pbi-visuals',
    prompt: 'A card shows $240,000 for all stores. After selecting two stores in a slicer it shows $60,000 and $36,000 for each store in a table. What does the card show now?',
    answer: 96000, verify: () => 60000 + 36000,
    explain: 'With two stores selected, the card sums what the slicer allows: $60,000 + $36,000 = $96,000.' },

  // ================================================================ pbi-reports
  { id: 'pb2-rep-01', topic: 'pbi-reports', type: 'mc', kind: 'concept', difficulty: 1, concept: 'report-design',
    prompt: 'Where do most readers look first on a report page?',
    options: ['Top left', 'Bottom right', 'The centre', 'The page tabs'], answer: 0,
    explain: 'Western readers scan from the top left. Put the headline numbers there.' },
  { id: 'pb2-rep-02', topic: 'pbi-reports', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'report-design',
    prompt: 'Which card is most useful to a manager?',
    options: ['Revenue $114k, +21% vs last August', 'Revenue $114k', 'Sum of net_revenue', 'Revenue (all time)'], answer: 0,
    explain: 'A number with a comparison tells the reader whether it is good or bad.' },
  { id: 'pb2-rep-03', topic: 'pbi-reports', type: 'tf', kind: 'concept', difficulty: 1, concept: 'report-design',
    prompt: 'True or false: a report page should try to answer one main question.',
    answer: true, explain: 'Pages with a clear purpose are faster to read. Other questions get their own pages.' },
  { id: 'pb2-rep-04', topic: 'pbi-reports', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'report-design',
    prompt: 'A regional manager wants to right-click a store and open a page with that store\'s details. What feature is that?',
    options: ['Drill-through', 'Bookmarks', 'Sync slicers', 'Themes'], answer: 0,
    explain: 'A drill-through page opens filtered to the item that was right-clicked.' },
  { id: 'pb2-rep-05', topic: 'pbi-reports', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'report-design',
    prompt: 'Which visual shows a value, a target and whether the target is met in one place?',
    options: ['KPI', 'Slicer', 'Table', 'Scatter chart'], answer: 0,
    explain: 'The KPI visual takes a value, a target and a trend axis, and colours the result.' },
  { id: 'pb2-rep-06', topic: 'pbi-reports', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'report-design',
    prompt: 'A page has 18 visuals, six colours and no titles. What is the main problem?',
    options: ['Readers cannot tell what to look at', 'It will not publish', 'The numbers will be wrong', 'Slicers will not work'], answer: 0,
    explain: 'Clutter hides the message. Fewer visuals, one highlight colour and informative titles fix it.' },
  { id: 'pb2-rep-07', topic: 'pbi-reports', type: 'fill', kind: 'tool-selection', difficulty: 2, concept: 'report-design',
    prompt: 'To make a Year slicer apply to several pages, use View → ____ slicers.',
    answer: ['Sync'], explain: 'Sync slicers links the same slicer across the pages you choose.' },
  { id: 'pb2-rep-08', topic: 'pbi-reports', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'report-design',
    prompt: 'Which chart title is best for the board?',
    options: ['Online sales passed store sales in July', 'Sales by channel by month', 'Chart 3', 'Online vs In-Store (sum)'], answer: 0,
    explain: 'An informative title states the finding, so the board knows what to see before reading the chart.' },
  { id: 'pb2-rep-09', topic: 'pbi-reports', type: 'tf', kind: 'concept', difficulty: 2, concept: 'report-design',
    prompt: 'True or false: using one strong colour to highlight the key bar and grey for the rest usually helps readers.',
    answer: true, explain: 'Contrast directs attention. When everything is coloured, nothing stands out.' },
  { id: 'pb2-rep-10', topic: 'pbi-reports', type: 'mc', kind: 'concept', difficulty: 2, concept: 'report-design',
    prompt: 'What is a report page tooltip?',
    options: ['A small page shown when hovering over a data point', 'A text note typed directly on the canvas', 'A filter that hides tooltips on a page', 'A theme colour used for highlighted values'], answer: 0,
    explain: 'A tooltip page shows extra detail for whatever the reader hovers over.' },
  { id: 'pb2-rep-11', topic: 'pbi-reports', type: 'order', kind: 'sequence', difficulty: 2, concept: 'report-design',
    prompt: 'Order the parts of an overview page from top to bottom, as a reader would use them.',
    options: ['KPI cards with comparisons', 'Trend over time', 'Breakdown by category or store', 'Detail table'], answer: [0, 1, 2, 3],
    explain: 'Headline → trend → where it comes from → details for those who need them.' },
  { id: 'pb2-rep-12', topic: 'pbi-reports', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'report-design',
    prompt: 'A KPI card says "+35% vs last month" on 10 September. The manager is delighted. What is wrong?',
    options: ['It compares 10 days with a full month', 'KPI cards cannot show percentages', 'Last month had no data', 'The card needs a darker colour'], answer: 0,
    explain: 'A partial month should be compared with the same days of the previous period, or the card should use the last complete month.' },
  { id: 'pb2-rep-13', topic: 'pbi-reports', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'report-design',
    prompt: 'An NGO report is read by trustees who are not analysts. What helps most?',
    options: ['Few visuals with plain titles and units', 'Every available chart type', 'Raw tables of all donations', 'Technical field names'], answer: 0,
    explain: 'Plain language, clear units and few visuals help non-specialists read a report correctly.' },
  { id: 'pb2-rep-14', topic: 'pbi-reports', type: 'tf', kind: 'concept', difficulty: 2, concept: 'report-design',
    prompt: 'True or false: alt text on visuals helps readers who use screen readers.',
    answer: true, explain: 'Alt text (Format → General) describes a visual for screen readers. Make it say what the chart shows.' },
  { id: 'pb2-rep-15', topic: 'pbi-reports', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'report-design',
    prompt: 'You want the chart title to read "Revenue for North" when North is chosen in the slicer. How?',
    options: ['Use a measure for the title (fx on the Title)', 'Type a new title for each region', 'Add a text box behind the chart', 'Rename the region column'], answer: 0,
    explain: 'Conditional formatting (fx) on the title can use a measure such as "Revenue for " & SELECTEDVALUE(Store[region]).' },
  { id: 'pb2-rep-16', topic: 'pbi-reports', type: 'fill', kind: 'concept', difficulty: 3, concept: 'report-design',
    prompt: 'The DAX function that returns the single value chosen in a slicer (or a default) is ____.',
    answer: ['SELECTEDVALUE'], explain: 'SELECTEDVALUE(column, "All") returns the one selected value, or the alternative text.' },
  { id: 'pb2-rep-17', topic: 'pbi-reports', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'report-design',
    prompt: 'A KPI visual shows revenue in red with a target of $50k and a value of $48k. What does red mean here?',
    options: ['The value is below target', 'The data failed to refresh', 'Revenue fell to zero', 'The target is missing'], answer: 0,
    explain: 'KPI visuals colour the value by whether it meets the target (and whether higher is better).' },
  { id: 'pb2-rep-18', topic: 'pbi-reports', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'report-design',
    prompt: 'Store managers read the report on their phones. What should you prepare?',
    options: ['A mobile layout for the key pages', 'Smaller fonts on the desktop layout', 'A PDF with every page', 'More visuals per page'], answer: 0,
    explain: 'View → Mobile layout arranges the most important visuals for a phone screen.' },
  { id: 'pb2-rep-19', topic: 'pbi-reports', type: 'tf', kind: 'concept', difficulty: 2, concept: 'chart-honesty', crossConcept: true,
    prompt: 'True or false: labelling units (such as "$ thousands") is optional when everyone knows the business.',
    answer: false, explain: 'Reports travel. Unlabelled units are one of the most common causes of misread numbers.' },
  { id: 'pb2-rep-20', topic: 'pbi-reports', type: 'mc', kind: 'concept', difficulty: 2, concept: 'report-design',
    prompt: 'What are bookmarks used for?',
    options: ['Saving a page state, such as filters and visible visuals', 'Marking important rows in a table visual', 'Scheduling a refresh at set times', 'Creating measures from saved filters'], answer: 0,
    explain: 'Bookmarks capture a view of a page (filters, selections, visibility), which buttons can then switch between.' },

  // ================================================================ pbi-dax (first measures)
  { id: 'pb2-dax-01', topic: 'pbi-dax', type: 'fill', kind: 'concept', difficulty: 1, concept: 'dax-basics',
    prompt: 'Complete: `Revenue = ____ ( Sales[Amount] )` to add up the Amount column.',
    answer: ['SUM'], explain: 'SUM adds up a numeric column in the current filter context.' },
  { id: 'pb2-dax-02', topic: 'pbi-dax', type: 'mc', kind: 'tool-selection', difficulty: 1, concept: 'dax-basics',
    prompt: 'Which function counts the rows of a table?',
    options: ['COUNTROWS', 'COUNT', 'SUM', 'DISTINCT'], answer: 0,
    explain: 'COUNTROWS(table) counts rows. COUNT counts non-blank values in one column.' },
  { id: 'pb2-dax-03', topic: 'pbi-dax', type: 'number', kind: 'calculation', difficulty: 2, concept: 'dax-basics',
    prompt: 'Revenue is $84,000 from 600 orders. What does `DIVIDE([Revenue], [Orders])` return?',
    answer: 140, verify: () => 84000 / 600,
    explain: '84,000 ÷ 600 = 140: an average order value of $140.' },
  { id: 'pb2-dax-04', topic: 'pbi-dax', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'dax-basics',
    prompt: 'What does `DIVIDE([Revenue], [Orders])` show for a month with no orders?',
    options: ['Blank', 'Zero', 'An error', 'Infinity'], answer: 0,
    explain: 'DIVIDE returns blank (or the optional third argument) when the denominator is zero or blank, so visuals stay clean.' },
  { id: 'pb2-dax-05', topic: 'pbi-dax', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'dax-basics',
    prompt: 'A customer count is exactly one higher than the CRM says. The sales table has walk-in sales with no customer. Why?',
    options: ['DISTINCTCOUNT counts the blank as a value', 'DISTINCTCOUNT rounds up', 'The CRM is always wrong', 'COUNTROWS was used by mistake'], answer: 0,
    explain: 'DISTINCTCOUNT includes blank as one distinct value. DISTINCTCOUNTNOBLANK leaves it out.' },
  { id: 'pb2-dax-06', topic: 'pbi-dax', type: 'tf', kind: 'concept', difficulty: 2, concept: 'measure-vs-column',
    prompt: 'True or false: a measure is stored row by row in the table, like a column.',
    answer: false, explain: 'Measures store nothing; they are calculated for each cell of a visual. Calculated columns are stored per row.' },
  { id: 'pb2-dax-07', topic: 'pbi-dax', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'dax-basics',
    prompt: 'You need revenue as quantity × price per line, but there is no revenue column. Which measure is right?',
    options: ['SUMX(Sales, Sales[Qty] * Sales[Price])', 'SUM(Sales[Qty]) * SUM(Sales[Price])', 'SUM(Sales[Qty] * Sales[Price])', 'COUNTROWS(Sales) * AVERAGE(Sales[Price])'], answer: 0,
    explain: 'SUMX multiplies on each row, then adds. Multiplying two totals mixes up lines; SUM only accepts a single column.' },
  { id: 'pb2-dax-08', topic: 'pbi-dax', type: 'number', kind: 'calculation', difficulty: 3, concept: 'dax-basics',
    prompt: 'Two sales lines: 2 units at $10 and 5 units at $4. What does `SUM(Qty) * SUM(Price)` give, compared with the true revenue of $40?',
    answer: 98, verify: () => (2 + 5) * (10 + 4),
    explain: '(2 + 5) × (10 + 4) = 98, while the real revenue is 2×10 + 5×4 = 40. That is why row-by-row maths needs SUMX.' },
  { id: 'pb2-dax-09', topic: 'pbi-dax', type: 'mc', kind: 'concept', difficulty: 2, concept: 'dax-basics',
    prompt: 'How do you refer to a measure named Revenue inside another measure?',
    options: ['[Revenue]', 'Sales[Revenue]', '"Revenue"', 'Revenue()'], answer: 0,
    explain: 'Measures are referenced by name in square brackets. Table[Column] is for columns.' },
  { id: 'pb2-dax-10', topic: 'pbi-dax', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'kpi', crossConcept: true,
    prompt: 'A restaurant wants "average spend per cover" (covers = guests). Which measure fits?',
    options: ['DIVIDE([Net sales], SUM(Visits[Covers]))', 'AVERAGE(Sales[Net sales])', 'SUM(Visits[Covers]) / 12', 'DISTINCTCOUNT(Sales[Net sales])'], answer: 0,
    explain: 'Spend per cover is total sales divided by total guests. AVERAGE of the sales column would average line values instead.' },
  { id: 'pb2-dax-11', topic: 'pbi-dax', type: 'tf', kind: 'concept', difficulty: 1, concept: 'dax-basics',
    prompt: 'True or false: measure names should describe the business meaning, such as "Revenue" rather than "Measure 3".',
    answer: true, explain: 'Measure names appear in visuals and tooltips. Clear names make reports self-explanatory.' },
  { id: 'pb2-dax-12', topic: 'pbi-dax', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'dax-basics',
    prompt: '`Margin % = AVERAGE(Sales[margin_pct])` shows 38%, but total margin ÷ total revenue is 47%. Which is right for the company?',
    options: ['47%: a ratio of the totals', '38%: the average is safer', 'Both, depending on the colour', 'Neither can be trusted'], answer: 0,
    explain: 'Averaging line percentages treats a $5 item like a $500 item. Company margin % is total margin divided by total revenue.' },
  { id: 'pb2-dax-13', topic: 'pbi-dax', type: 'fill', kind: 'concept', difficulty: 2, concept: 'dax-basics',
    prompt: 'The DAX function that counts distinct values while ignoring blanks is DISTINCTCOUNT____.',
    answer: ['NOBLANK'], explain: 'DISTINCTCOUNTNOBLANK(column) counts different non-blank values.' },
  { id: 'pb2-dax-14', topic: 'pbi-dax', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'measure-vs-column',
    prompt: 'You want to colour products by a "Price band" (Budget, Mid, Premium) on a chart axis. What do you create?',
    options: ['A calculated column (or a Power Query column)', 'A measure that returns the band', 'A report-level filter on price', 'A bookmark for each price band'], answer: 0,
    explain: 'An axis needs a column with a value per product. Measures cannot be put on an axis.' },
  { id: 'pb2-dax-15', topic: 'pbi-dax', type: 'number', kind: 'calculation', difficulty: 2, concept: 'dax-basics',
    prompt: 'Cost is $52,000 and revenue is $80,000. What is Margin % = DIVIDE([Revenue] − [Cost], [Revenue]), as a percentage?',
    answer: 35, verify: () => ((80000 - 52000) / 80000) * 100,
    explain: '(80,000 − 52,000) ÷ 80,000 = 0.35 = 35%.' },
  { id: 'pb2-dax-16', topic: 'pbi-dax', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'dax-basics',
    prompt: 'A Revenue measure shows $1.2M in the total row and $300k, $500k, $400k in the region rows. What does this tell you about SUM?',
    options: ['For sums, the total equals the rows added up', 'Totals are always independent of rows', 'The regions are missing data', 'The measure is a column'], answer: 0,
    explain: 'For additive measures like SUM, the total matches the sum of rows. Ratios and distinct counts behave differently.' },
  { id: 'pb2-dax-17', topic: 'pbi-dax', type: 'tf', kind: 'concept', difficulty: 2, concept: 'dax-basics',
    prompt: 'True or false: COUNT(Sales[customer_id]) counts each customer only once.',
    answer: false, explain: 'COUNT counts every non-blank value, so repeat customers are counted each time. Use DISTINCTCOUNT for unique customers.' },
  { id: 'pb2-dax-18', topic: 'pbi-dax', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'dax-basics',
    prompt: 'An HR report needs "Headcount" = number of employees currently employed. Which is closest?',
    options: ['CALCULATE(COUNTROWS(Employees), ISBLANK(Employees[leave_date]))', 'CALCULATE(COUNTROWS(Employees), NOT ISBLANK(Employees[leave_date]))', 'COUNTROWS(Employees)', 'COUNT(Employees[leave_date])'], answer: 0,
    explain: 'Count the employee rows with no leave date. Summing ids or counting leave dates answers a different question.' },
  { id: 'pb2-dax-19', topic: 'pbi-dax', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'dax-basics',
    prompt: 'A new measure `Revenue = SUM(net_revenue)` shows an error. What is missing?',
    options: ['The table name: SUM(Sales[net_revenue])', 'A closing semicolon', 'The word CALCULATE', 'Quotation marks around the name'], answer: 0,
    explain: 'Columns are referenced as Table[Column]. Writing the table name avoids ambiguity.' },
  { id: 'pb2-dax-20', topic: 'pbi-dax', type: 'number', kind: 'calculation', difficulty: 2, concept: 'dax-basics',
    prompt: 'An NGO had 1,250 donations from 400 donors. Donations per donor = DIVIDE(COUNTROWS(Donations), DISTINCTCOUNT(Donations[donor_id])). What is it?',
    answer: 3.125, tolerance: 0.001, verify: () => 1250 / 400,
    explain: '1,250 ÷ 400 = 3.125 donations per donor on average.' },
  { id: 'pb2-dax-21', topic: 'pbi-dax', type: 'mc', kind: 'concept', difficulty: 2, concept: 'dax-basics',
    prompt: 'What is an implicit measure?',
    options: ['An automatic Sum or Count from dragging a column', 'A measure hidden from report users', 'A measure written in M instead of DAX', 'A measure saved without a display name'], answer: 0,
    explain: 'Implicit measures are convenient for exploring, but explicit measures are reusable, named and formatted.' },
  { id: 'pb2-dax-22', topic: 'pbi-dax', type: 'tf', kind: 'concept', difficulty: 2, concept: 'dax-basics',
    prompt: 'True or false: DIVIDE accepts a third argument that is returned instead of blank when dividing by zero.',
    answer: true, explain: 'DIVIDE(numerator, denominator, alternate). For example DIVIDE([A], [B], 0).' },
  { id: 'pb2-dax-23', topic: 'pbi-dax', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'dax-basics',
    prompt: 'Which measure gives the average line value rather than the average order value?',
    options: ['AVERAGE(Sales[net_revenue])', 'DIVIDE([Revenue], [Orders])', 'DIVIDE([Revenue], [Customers])', 'SUM(Sales[net_revenue])'], answer: 0,
    explain: 'AVERAGE over the line column averages lines. Orders often have several lines, so the two figures differ.' },
  { id: 'pb2-dax-24', topic: 'pbi-dax', type: 'order', kind: 'sequence', difficulty: 2, concept: 'dax-basics',
    prompt: 'Order the measures so each one can be built from the ones before it.',
    options: ['Revenue', 'Cost', 'Margin', 'Margin %'], answer: [0, 1, 2, 3],
    explain: 'Revenue and Cost first, then Margin = [Revenue] − [Cost], then Margin % = DIVIDE([Margin], [Revenue]).' },
  { id: 'pb2-dax-25', topic: 'pbi-dax', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'measure-vs-column',
    prompt: 'A colleague added a calculated column `Revenue share = Sales[net_revenue] / SUM(Sales[net_revenue])`. What will happen when a user filters by region?',
    options: ['The shares stay fixed from refresh time', 'The shares recalculate per region', 'The column turns into a measure', 'The report stops loading'], answer: 0,
    explain: 'Calculated columns are computed at refresh and never react to slicers. A share of total must be a measure.' },
  { id: 'pb2-dax-26', topic: 'pbi-dax', type: 'number', kind: 'calculation', difficulty: 3, concept: 'dax-basics',
    prompt: 'Gross sales (before discount) were $50,000 and net revenue $46,500. What percentage of gross was given as discount?',
    answer: 7, verify: () => ((50000 - 46500) / 50000) * 100,
    explain: '(50,000 − 46,500) ÷ 50,000 = 7%. Discounts are measured against gross sales, the value before any discount, not against net revenue.' },
  { id: 'pb2-dax-27', topic: 'pbi-dax', type: 'fill', kind: 'tool-selection', difficulty: 2, concept: 'dax-basics',
    prompt: 'Measures are created in Power BI Desktop with Home → New ____.',
    answer: ['measure'], explain: 'New measure opens the formula bar for a measure on the selected table.' },
];
