// Power BI quiz bank, part A: what Power BI is, importing, Power Query in Power BI,
// relationships and the star schema. Written for someone starting from zero.
export const PBI_QUIZ_A = [
  // ================================================================ pbi-intro (what Power BI is)
  { id: 'pb2-intro-01', topic: 'pbi-intro', type: 'mc', kind: 'concept', difficulty: 1, concept: 'pbi-basics',
    prompt: 'What is a Power BI **measure**?',
    options: ['A formula calculated when a visual needs it', 'A column typed in by hand', 'A saved copy of a chart', 'A filter applied to one page'], answer: 0,
    explain: 'A measure is a DAX formula (such as total revenue) that Power BI calculates on demand, for whatever the visual is showing.' },
  { id: 'pb2-intro-02', topic: 'pbi-intro', type: 'tf', kind: 'concept', difficulty: 1, concept: 'pbi-basics',
    prompt: 'True or false: when you refresh a Power BI report, the original source files are changed.',
    answer: false, explain: 'Power BI only reads the sources. Refresh re-reads them and re-runs your steps; the files themselves are never edited.' },
  { id: 'pb2-intro-03', topic: 'pbi-intro', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'tool-choice',
    prompt: 'A restaurant manager wants to see yesterday\'s sales by site every morning without anyone rebuilding a spreadsheet. Which is the better fit?',
    options: ['A Power BI report with scheduled refresh', 'A new Excel copy emailed each day', 'A handwritten summary', 'A PDF export of last month'], answer: 0,
    explain: 'A report that refreshes on a schedule removes the daily manual step and gives everyone the same numbers.' },
  { id: 'pb2-intro-04', topic: 'pbi-intro', type: 'order', kind: 'sequence', difficulty: 1, concept: 'pbi-basics',
    prompt: 'Order the views you would typically use when starting a new report: load data, check the rows, connect tables, then build visuals.',
    options: ['Get data', 'Table view', 'Model view', 'Report view'], answer: [0, 1, 2, 3],
    explain: 'Load, look at what arrived, relate the tables, then build pages. Skipping the checks is how wrong numbers reach a report.' },
  { id: 'pb2-intro-05', topic: 'pbi-intro', type: 'mc', kind: 'concept', difficulty: 1, concept: 'pbi-basics',
    prompt: 'What does the **Report view** in Power BI Desktop show?',
    options: ['The canvas where you build visuals', 'The raw rows of each table', 'The relationships between tables', 'The Power Query steps'], answer: 0,
    explain: 'Report view is the canvas. Table view shows rows, Model view shows relationships, and Power Query steps live in the Transform data editor.' },
  { id: 'pb2-intro-06', topic: 'pbi-intro', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'tool-choice',
    prompt: 'An NGO has 300 donations a month in one sheet and needs a one-off total for a grant form. What is sensible?',
    options: ['A SUM in the Excel sheet', 'A new Power BI data model', 'A SQL database for the sheet', 'A Power BI app for the team'], answer: 0,
    explain: 'For a small, one-off calculation Excel is quicker. Power BI earns its setup time when data is large, repeated or shared.' },
  { id: 'pb2-intro-07', topic: 'pbi-intro', type: 'fill', kind: 'concept', difficulty: 1, concept: 'pbi-basics',
    prompt: 'Power BI\'s formula language for measures is called ____.',
    answer: ['DAX', 'Data Analysis Expressions'], explain: 'DAX (Data Analysis Expressions) is used for measures, calculated columns and calculated tables.' },
  { id: 'pb2-intro-08', topic: 'pbi-intro', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-basics',
    prompt: 'True or false: a .pbix file can contain the data model, the Power Query steps and the report pages together.',
    answer: true, explain: 'A .pbix file bundles the queries, the loaded model and the report. That is why it can be large when the data is large.' },
  { id: 'pb2-intro-09', topic: 'pbi-intro', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pbi-basics',
    prompt: 'You click a bar for "Riverside" in one chart and the card next to it changes from 1.2M to 310K. What happened?',
    options: ['The card was filtered to Riverside by cross-filtering', 'The data was refreshed in the background', 'The card switched to a different measure', 'Riverside rows were removed from the model'], answer: 0,
    explain: 'Clicking a data point filters the other visuals on the page. The card now shows Riverside only; click the bar again to clear it.' },
  { id: 'pb2-intro-10', topic: 'pbi-intro', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pbi-basics',
    prompt: 'Your manager asks for "the Power BI file" so she can view the report on her phone. What is the usual way to share it?',
    options: ['Publish it to the Power BI Service', 'Email the .pbix file', 'Print every page to PDF', 'Share a screenshot folder'], answer: 0,
    explain: 'Published reports can be opened in a browser or the mobile app with permissions, and stay up to date. Emailed .pbix copies drift apart.' },
  { id: 'pb2-intro-11', topic: 'pbi-intro', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pbi-basics',
    prompt: 'A card shows "Count of Price" instead of total revenue. What went wrong?',
    options: ['Price was loaded as text, so Power BI counted it', 'The card is too small', 'Revenue needs a date table', 'The report is not published'], answer: 0,
    explain: 'Text columns can only be counted. Change Price to a number type in Power Query, then the default summary becomes Sum.' },
  { id: 'pb2-intro-12', topic: 'pbi-intro', type: 'tf', kind: 'concept', difficulty: 1, concept: 'pbi-basics',
    prompt: 'True or false: Power BI can combine data from Excel, CSV files and a database in one report.',
    answer: true, explain: 'Get data connects to many sources, and the model can relate tables that came from different places.' },

  // ================================================================ pbi-import
  { id: 'pb2-imp-01', topic: 'pbi-import', type: 'mc', kind: 'tool-selection', difficulty: 1, concept: 'pbi-basics',
    prompt: 'Which Get data option loads every CSV file in one folder as a single table?',
    options: ['Folder', 'Text/CSV', 'Excel workbook', 'Blank query'], answer: 0,
    explain: 'The Folder connector combines files with the same layout, so next month\'s file is picked up on refresh.' },
  { id: 'pb2-imp-02', topic: 'pbi-import', type: 'mc', kind: 'concept', difficulty: 1, concept: 'pbi-basics',
    prompt: 'In the Navigator window, what is the difference between **Load** and **Transform Data**?',
    options: ['Load imports as-is; Transform Data opens Power Query first', 'Load is for Excel; Transform Data is for CSV', 'They do the same thing', 'Transform Data publishes the report'], answer: 0,
    explain: 'Transform Data lets you check and fix types, columns and rows before anything reaches the model.' },
  { id: 'pb2-imp-03', topic: 'pbi-import', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pq-types', crossConcept: true,
    prompt: 'After import, the order_date column sorts as 01/02/2025, 01/03/2025, 02/01/2025... in text order. Why?',
    options: ['It was loaded as text, not as a date', 'The dates are in the wrong year', 'The table has no relationship', 'Sorting only works on numbers'], answer: 0,
    explain: 'Text sorts character by character. Change the type to Date (with the right locale if needed) and it sorts by calendar.' },
  { id: 'pb2-imp-04', topic: 'pbi-import', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-basics',
    prompt: 'True or false: in Import mode, a copy of the data is stored inside the Power BI file.',
    answer: true, explain: 'Import loads the data into the model, which makes reports fast. DirectQuery instead queries the source each time.' },
  { id: 'pb2-imp-05', topic: 'pbi-import', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pbi-basics',
    prompt: 'A purchases export has 40 columns, but your report needs 9 of them. What should you do on import?',
    options: ['Remove the unused columns in Power Query', 'Load all 40 and hide 31', 'Split the file in two', 'Import it twice'], answer: 0,
    explain: 'Removing columns early makes the model smaller and faster, and the field list easier to use. Hiding still stores them.' },
  { id: 'pb2-imp-06', topic: 'pbi-import', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pbi-basics',
    prompt: 'A refresh fails with "could not find file C:\\Users\\Ana\\Desktop\\sales.xlsx" on your laptop. Most likely?',
    options: ['The query points at a colleague\'s local file path', 'The file has too many rows', 'The report has too many pages', 'DAX measures are missing'], answer: 0,
    explain: 'Sources are stored as paths. A file on someone else\'s desktop is unreachable. Use a shared location (SharePoint, a network folder) or a parameter.' },
  { id: 'pb2-imp-07', topic: 'pbi-import', type: 'fill', kind: 'concept', difficulty: 1, concept: 'pbi-basics',
    prompt: 'The Power BI mode that stores a copy of the data in the file is called ____ mode.',
    answer: ['Import'], explain: 'Import mode. The alternative, DirectQuery, leaves the data in the source.' },
  { id: 'pb2-imp-08', topic: 'pbi-import', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'data-quality', crossConcept: true,
    prompt: 'The preview of a CSV shows a column named "Column1" with values like "StoreCode" in the first row. What does that tell you?',
    options: ['The header row was not promoted', 'The file is empty', 'StoreCode is a number', 'The file is an Excel file'], answer: 0,
    explain: 'Use First Row as Headers (Power Query usually does this automatically, but not always).' },
  { id: 'pb2-imp-09', topic: 'pbi-import', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-basics',
    prompt: 'True or false: renaming a column in the source file after building the report can break the refresh.',
    answer: true, explain: 'Power Query steps refer to columns by name. A renamed source column makes steps like "Changed Type" fail.' },
  { id: 'pb2-imp-10', topic: 'pbi-import', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pbi-basics',
    prompt: 'Sales from three restaurants arrive as three monthly CSV files with identical columns. What is the most maintainable import?',
    options: ['One Folder query that combines them', 'Three separate tables with three relationships', 'Copy-paste them into one file each month', 'Import only the largest site'], answer: 0,
    explain: 'A Folder query combines the files once. New files dropped into the folder are included on the next refresh.' },
  { id: 'pb2-imp-11', topic: 'pbi-import', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-basics',
    prompt: 'Revenue is 10 times too high after importing a German export where "1.234,50" means one thousand two hundred and thirty-four. What was missed?',
    options: ['Setting the locale when changing the type', 'Removing duplicate rows', 'Marking a date table', 'Publishing the report'], answer: 0,
    explain: 'Decimal and thousands separators depend on locale. Change Type → Using Locale → German reads "1.234,50" correctly.' },
  { id: 'pb2-imp-12', topic: 'pbi-import', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pbi-basics',
    prompt: 'You need live, second-by-second figures from a very large database that must not be copied. Which connection mode fits?',
    options: ['DirectQuery', 'Import', 'Folder', 'Enter data'], answer: 0,
    explain: 'DirectQuery leaves the data in the database and sends queries when visuals need them. It is slower and more limited, but nothing is copied.' },
  { id: 'pb2-imp-13', topic: 'pbi-import', type: 'number', kind: 'calculation', difficulty: 2, concept: 'data-quality', crossConcept: true,
    prompt: 'A file has 12,480 rows. Power Query shows 12,480 rows after "Remove Blank Rows" and 12,391 after "Remove Duplicates". How many duplicate rows were removed?',
    answer: 89, verify: () => 12480 - 12391,
    explain: '12,480 − 12,391 = 89. Keeping a note of the row count after each step is how you notice when a step removes far more than expected.' },
  { id: 'pb2-imp-14', topic: 'pbi-import', type: 'tf', kind: 'concept', difficulty: 1, concept: 'pbi-basics',
    prompt: 'True or false: Enter data lets you type a small table (like a list of target values) directly into Power BI.',
    answer: true, explain: 'Home → Enter data creates a small table by hand. Fine for a handful of values; real data should come from a source.' },

  // ================================================================ pbi-pq (Power Query inside Power BI)
  { id: 'pb2-pq-01', topic: 'pbi-pq', type: 'mc', kind: 'concept', difficulty: 1, concept: 'pbi-query',
    prompt: 'Where is the list of every transformation you applied to a query?',
    options: ['Applied Steps', 'The Filters pane', 'The Data pane', 'The Model view'], answer: 0,
    explain: 'Applied Steps records each step in order. Selecting a step shows the data at that point.' },
  { id: 'pb2-pq-02', topic: 'pbi-pq', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pbi-query',
    prompt: 'Which belongs in Power Query rather than in DAX?',
    options: ['Trimming spaces from product codes', 'Year-over-year growth', 'Share of total revenue', 'A ranking of stores'], answer: 0,
    explain: 'Cleaning values row by row is Power Query work. Growth, shares and ranks must react to filters, so they are DAX measures.' },
  { id: 'pb2-pq-03', topic: 'pbi-pq', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-query',
    prompt: 'True or false: a query with "Enable load" switched off still runs when another query uses it.',
    answer: true, explain: 'It still runs as an input; it just is not loaded as a table in the model.' },
  { id: 'pb2-pq-04', topic: 'pbi-pq', type: 'mc', kind: 'concept', difficulty: 2, concept: 'pbi-query',
    prompt: 'You **Reference** the Sales query to build a monthly summary, then add a filter to Sales. What happens to the summary?',
    options: ['It follows, because it starts from Sales\' result', 'Nothing, it has its own copy of the steps', 'It is deleted', 'It shows an error'], answer: 0,
    explain: 'A reference starts from the output of the original query, so changes upstream flow into it. A duplicate would not follow.' },
  { id: 'pb2-pq-05', topic: 'pbi-pq', type: 'order', kind: 'sequence', difficulty: 2, concept: 'pbi-query',
    prompt: 'Put a sensible first pass on a messy sales table in order.',
    options: ['Promote headers', 'Set column types', 'Remove unneeded columns and blank rows', 'Close & Apply'], answer: [0, 1, 2, 3],
    explain: 'Headers first (so columns have names), then types, then trimming the table down, then load it.' },
  { id: 'pb2-pq-06', topic: 'pbi-pq', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pbi-query',
    prompt: 'After a new file arrived, refresh fails at the step "Changed Type" with "column Unit Cost not found". Most likely?',
    options: ['The column was renamed in the new file', 'The file has more rows', 'A measure is broken', 'The date table is missing'], answer: 0,
    explain: 'Type steps name each column. If the source renames "Unit Cost" to "UnitCost", that step breaks. Fix the step or ask for a stable layout.' },
  { id: 'pb2-pq-07', topic: 'pbi-pq', type: 'fill', kind: 'concept', difficulty: 1, concept: 'pbi-query',
    prompt: 'To load your Power Query changes into the model you click Close & ____.',
    answer: ['Apply'], explain: 'Close & Apply runs the queries and loads the results.' },
  { id: 'pb2-pq-08', topic: 'pbi-pq', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pbi-query',
    prompt: 'A supplier file has a "Product" column like "Tomatoes - 5kg box". You need the product and the pack size separately. What do you do?',
    options: ['Split Column by delimiter " - "', 'Create a DAX measure', 'Change the type to number', 'Remove the column'], answer: 0,
    explain: 'Split Column by the " - " delimiter gives "Tomatoes" and "5kg box" as separate columns.' },
  { id: 'pb2-pq-09', topic: 'pbi-pq', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-query',
    prompt: 'A merged column shows "null" for every row after merging Sales with Products on product code. Most likely?',
    options: ['The codes differ in case or spaces between the tables', 'Merge only works on number columns', 'Products has too few rows to match', 'The relationship between the tables is inactive'], answer: 0,
    explain: 'Merges match exact values. "TNT-100 " and "tnt-100" do not match. Trim and use the same case on both keys first.' },
  { id: 'pb2-pq-10', topic: 'pbi-pq', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-query',
    prompt: 'True or false: adding a "Profit %" column in Power Query is the best way to show profit % that changes with slicers.',
    answer: false, explain: 'A column is fixed per row. A ratio that must be recalculated for any selection is a DAX measure.' },
  { id: 'pb2-pq-11', topic: 'pbi-pq', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pbi-query',
    prompt: 'Which Power Query action turns 12 month columns (Jan...Dec) into two columns, Month and Value?',
    options: ['Unpivot Columns', 'Pivot Column', 'Group By', 'Merge Queries'], answer: 0,
    explain: 'Unpivot turns wide month columns into rows, which is the shape Power BI models need.' },
  { id: 'pb2-pq-12', topic: 'pbi-pq', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'data-quality', crossConcept: true,
    prompt: 'Column quality shows "Valid 97%, Error 3%" on a quantity column. What should you do first?',
    options: ['Look at the error rows to see what they contain', 'Remove the column', 'Replace errors with 0 straight away', 'Ignore it: 3% is small'], answer: 0,
    explain: 'Errors usually come from text such as "n/a" in a number column. Find out what they are before deciding to fix, replace or remove them.' },
  { id: 'pb2-pq-13', topic: 'pbi-pq', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pbi-query',
    prompt: 'You need a Supplier name on every purchase row, and suppliers are in a separate small table. In Power BI, what is usually better?',
    options: ['Relate the tables in the model and use the supplier column in visuals', 'Merge the name into the purchases table in Power Query', 'Type the names in by hand', 'Create one query per supplier'], answer: 0,
    explain: 'In Power BI a relationship keeps the supplier table as a dimension you can slice by. Merging copies the name into every row, which is what you would do in Excel.' },
  { id: 'pb2-pq-14', topic: 'pbi-pq', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pbi-query',
    prompt: 'The language Power Query writes behind every step is called ____.',
    answer: ['M', 'M code', 'Power Query M'], explain: 'Each step is an M expression. You can see it in the formula bar or the Advanced Editor.' },
  { id: 'pb2-pq-15', topic: 'pbi-pq', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pbi-query',
    prompt: 'You filtered a table to 2026 in Power Query "just to test" and forgot. What will the report show?',
    options: ['Only 2026 data, whatever the slicers say', 'All years, because slicers override it', 'An error on refresh', 'Nothing until you publish'], answer: 0,
    explain: 'Rows removed in Power Query never reach the model. Slicers can only filter what was loaded.' },
  { id: 'pb2-pq-16', topic: 'pbi-pq', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-query',
    prompt: 'True or false: the order of Applied Steps matters.',
    answer: true, explain: 'Each step works on the result of the one before. Removing duplicates before trimming spaces gives a different result from the other way round.' },
  { id: 'pb2-pq-17', topic: 'pbi-pq', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pbi-query',
    prompt: 'Monthly purchase files keep arriving with a blank line and a report title above the headers. Which step handles it?',
    options: ['Remove Top Rows, then Use First Row as Headers', 'Remove Duplicates, then Change Type', 'Fill Down, then Remove Blank Rows', 'Promote headers, then Remove Errors'], answer: 0,
    explain: 'Remove the fixed rows above the real header, then promote the header. Because it is a recorded step, next month\'s file is handled too.' },
  { id: 'pb2-pq-18', topic: 'pbi-pq', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pbi-query',
    prompt: 'Waste logs from three kitchens use "Kg", "kg" and "KG" as the unit. What is the cleanest fix?',
    options: ['Format → lowercase on the Unit column', 'A DAX measure for each spelling', 'Filter out two of them', 'Leave it: visuals merge them'], answer: 0,
    explain: 'One transformation makes the values identical. Otherwise a visual shows three separate "units" and totals split three ways.' },
  { id: 'pb2-pq-19', topic: 'pbi-pq', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pbi-query',
    prompt: 'A query starts with 5,200 rows. "Remove Blank Rows" leaves 5,180, and a filter to one restaurant leaves 1,730. How many rows did the restaurant filter remove?',
    answer: 3450, verify: () => 5180 - 1730,
    explain: '5,180 − 1,730 = 3,450. Always compare with the row count of the step before, not the original.' },
  { id: 'pb2-pq-20', topic: 'pbi-pq', type: 'mc', kind: 'concept', difficulty: 2, concept: 'pbi-query',
    prompt: 'Why is it good practice to give queries clear names such as "Sales" and "Product"?',
    options: ['Query names become table names in the model and in DAX', 'Power Query runs faster with short names', 'Names are required to publish', 'It hides the query from users'], answer: 0,
    explain: 'The query name is the table name you will type in every measure (Sales[Amount]) and see in every field list.' },
  { id: 'pb2-pq-21', topic: 'pbi-pq', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-query',
    prompt: 'A Year column added in Power Query shows 1905 for every row. What is the likely cause?',
    options: ['The date column was a number (like 45657) and was read as a year', 'The source system really stores dates from 1905', 'The locale is set to German instead of English', 'Blank dates are shown as the year 1905'], answer: 0,
    explain: 'Excel serial numbers (days since 1900) must be converted to dates first. Taking the Year of the wrong type gives nonsense.' },
  { id: 'pb2-pq-22', topic: 'pbi-pq', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-query',
    prompt: 'True or false: you can undo a Power Query transformation by deleting its step in Applied Steps.',
    answer: true, explain: 'Deleting a step removes it (later steps that depend on it may then need fixing).' },
  { id: 'pb2-pq-23', topic: 'pbi-pq', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pbi-query',
    prompt: 'An HR export lists employees with their department only on the first row of each department block. How do you give every row its department?',
    options: ['Fill Down on the department column', 'Remove Blank Rows', 'Pivot the department column', 'A calculated column in DAX'], answer: 0,
    explain: 'Fill Down copies the value above into the empty cells below it, which is exactly this report-style layout.' },
  { id: 'pb2-pq-24', topic: 'pbi-pq', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pbi-query',
    prompt: 'The column profile says "Distinct 5, Unique 0" for a Region column with 9,000 rows. What does that mean?',
    options: ['5 different regions, each appearing more than once', '5 rows in the table, all of them regions', '5 rows contain an error value', 'Only 5 rows have a valid region'], answer: 0,
    explain: 'Distinct counts different values; Unique counts values that appear exactly once. Five regions repeated across 9,000 rows is expected.' },
  { id: 'pb2-pq-25', topic: 'pbi-pq', type: 'fill', kind: 'tool-selection', difficulty: 2, concept: 'pbi-query',
    prompt: 'The Power Query command that combines two tables with the same columns (stacking one under the other) is called Append ____.',
    answer: ['Queries', 'Queries as New'], explain: 'Append Queries stacks tables. Merge Queries adds columns by matching keys.' },

  // ================================================================ pbi-model (relationships)
  { id: 'pb2-mod-01', topic: 'pbi-model', type: 'mc', kind: 'concept', difficulty: 1, concept: 'pbi-model',
    prompt: 'What must be true of the key column on the "one" side of a one-to-many relationship?',
    options: ['Each value appears only once', 'It must be a number', 'It must contain blanks', 'It must be a date'], answer: 0,
    explain: 'One product row per product_id. Duplicate keys on the "one" side force a many-to-many relationship.' },
  { id: 'pb2-mod-02', topic: 'pbi-model', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pbi-model',
    prompt: 'A table of revenue by supplier shows the same total on every supplier row. What is the most likely cause?',
    options: ['Supplier is not related to the purchases table', 'The measure uses DIVIDE', 'There are too many suppliers', 'The date table is marked'], answer: 0,
    explain: 'When the filter from Supplier has no path to the fact table, every row shows the overall total.' },
  { id: 'pb2-mod-03', topic: 'pbi-model', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-model',
    prompt: 'True or false: Power BI can have only one active relationship between the same two tables.',
    answer: true, explain: 'Extra relationships (for example ship date as well as order date) are inactive and must be activated in a measure with USERELATIONSHIP.' },
  { id: 'pb2-mod-04', topic: 'pbi-model', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'pbi-model',
    prompt: 'Orders have an order date and a delivery date, both related to the Date table. The delivery relationship is dotted. How do you count deliveries by month?',
    options: ['CALCULATE(COUNTROWS(Orders), USERELATIONSHIP(Orders[delivery_date], \'Date\'[Date]))', 'CALCULATE(COUNTROWS(Orders), ALL(Orders[order_date]), \'Date\'[Date] = Orders[delivery_date])', 'CALCULATE(COUNTROWS(Orders), CROSSFILTER(Orders[delivery_date], \'Date\'[Date], None))', 'COUNTROWS(RELATEDTABLE(Orders)) with both relationships set to active'], answer: 0,
    explain: 'USERELATIONSHIP switches on the inactive relationship for that one measure. A second Date table (role-playing) is the other common approach.' },
  { id: 'pb2-mod-05', topic: 'pbi-model', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pbi-model',
    prompt: 'In the Model view, a line has a "1" next to Product and a "*" next to Sales. What does it mean?',
    options: ['One product can appear on many sales rows', 'One sale can have many products', 'Each product has exactly one sale', 'The relationship is inactive'], answer: 0,
    explain: '1 = the one side (unique products), * = the many side (sales lines).' },
  { id: 'pb2-mod-06', topic: 'pbi-model', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-model',
    prompt: 'A table visual by product category has a "(Blank)" row with revenue in it. What should you check first?',
    options: ['Sales rows whose product_id has no match in the product table', 'Whether the category column is formatted as text', 'Whether the report theme hides some colours', 'Whether the visual has a Top N filter'], answer: 0,
    explain: 'Unmatched keys (new products missing from the dimension, typos, blanks) appear as (Blank). Find those rows before hiding the blank.' },
  { id: 'pb2-mod-07', topic: 'pbi-model', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-model',
    prompt: 'True or false: Power BI can create relationships automatically when column names match, and you should always check them.',
    answer: true, explain: 'Autodetect can join the wrong columns (for example two different "id" columns). Review every relationship in the Model view.' },
  { id: 'pb2-mod-08', topic: 'pbi-model', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pbi-model',
    prompt: 'A restaurant model has Sales (one row per dish sold) and Menu (one row per dish). How should they be related?',
    options: ['Menu 1 → * Sales on the dish id', 'Sales 1 → * Menu', 'Many-to-many on dish name', 'No relationship; merge them'], answer: 0,
    explain: 'Menu is the dimension (one row per dish) and Sales the fact (many rows per dish).' },
  { id: 'pb2-mod-09', topic: 'pbi-model', type: 'mc', kind: 'concept', difficulty: 3, concept: 'filter-context', crossConcept: true,
    prompt: 'With a single-direction relationship from Product to Sales, what happens when you filter by a Sales column (for example channel) in a product table visual?',
    options: ['Products are not filtered by the Sales column', 'Products are filtered the same way', 'The relationship is deleted', 'An error appears'], answer: 0,
    explain: 'Filters flow from the one side to the many side. A filter on Sales does not travel back to Product unless the direction is Both (or a measure handles it).' },
  { id: 'pb2-mod-10', topic: 'pbi-model', type: 'fill', kind: 'tool-selection', difficulty: 3, concept: 'pbi-model',
    prompt: 'The DAX function that activates an inactive relationship inside CALCULATE is ____.',
    answer: ['USERELATIONSHIP'], explain: 'CALCULATE([Measure], USERELATIONSHIP(Fact[OtherDate], \'Date\'[Date])).' },
  { id: 'pb2-mod-11', topic: 'pbi-model', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-model',
    prompt: 'Power BI refuses to create a one-to-many relationship from Customers to Sales and says both sides have duplicates. What do you check?',
    options: ['Duplicate customer_id values (or blanks) in Customers', 'Whether Sales has too many rows', 'The column colour', 'The report filters'], answer: 0,
    explain: 'A customer registered twice with the same id breaks uniqueness. Fix the dimension in Power Query (remove duplicates on the key) before relating.' },
  { id: 'pb2-mod-12', topic: 'pbi-model', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pbi-model',
    prompt: 'Where do you create or edit relationships?',
    options: ['Model view (or Manage relationships)', 'The Filters pane', 'The Format pane', 'The Power Query editor'], answer: 0,
    explain: 'Drag between columns in Model view, or use Modeling → Manage relationships to edit direction, cardinality and active state.' },
  { id: 'pb2-mod-13', topic: 'pbi-model', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pbi-model',
    prompt: 'True or false: many-to-many relationships are wrong by definition and Power BI cannot use them.',
    answer: false, explain: 'Power BI supports them, but they are easy to misread. Usually they point to a missing dimension or duplicate keys, so check before accepting one.' },
  { id: 'pb2-mod-14', topic: 'pbi-model', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pbi-model',
    prompt: 'HR has an Employees table and an Absences table (one row per absence). Absences also has a department column copied from Employees. Which relationship design is cleaner?',
    options: ['Relate on employee id; slice by Employees[department]', 'Relate the two tables on the department column', 'Keep them unrelated and use two separate slicers', 'Merge all the absence rows into Employees'], answer: 0,
    explain: 'Employee id is the true key. Department should come from the employee dimension, so an employee who changes department is handled in one place.' },
  { id: 'pb2-mod-15', topic: 'pbi-model', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pbi-model',
    prompt: 'A relationship line in Model view is dotted. What does that tell you?',
    options: ['It is inactive', 'It is many-to-many', 'It filters both ways', 'It is broken'], answer: 0,
    explain: 'Dotted lines are inactive relationships. Solid lines are active.' },
  { id: 'pb2-mod-16', topic: 'pbi-model', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-model',
    prompt: 'Two tables are related on "id", but the numbers by category are nonsense. The Product table\'s id is the product id; the Sales table\'s id is the sales line id. What is wrong?',
    options: ['The relationship joins two unrelated keys', 'The measure needs DIVIDE', 'The date table is missing', 'Sales has blank rows'], answer: 0,
    explain: 'Same column name, different meaning. Relate Sales[product_id] to Product[id] instead.' },
  { id: 'pb2-mod-17', topic: 'pbi-model', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-model',
    prompt: 'True or false: relating tables in the model means you no longer need to copy lookup columns into the fact table.',
    answer: true, explain: 'That is the point of the model: descriptive columns stay in their own table and filter the facts through the relationship.' },
  { id: 'pb2-mod-18', topic: 'pbi-model', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pbi-model',
    prompt: 'The cardinality of a normal dimension-to-fact relationship is one-to-____.',
    answer: ['many', 'many (1:*)'], explain: 'One-to-many (1:*): one dimension row, many fact rows.' },

  // ================================================================ pbi-star (star schema)
  { id: 'pb2-star-01', topic: 'pbi-star', type: 'mc', kind: 'concept', difficulty: 1, concept: 'star-schema',
    prompt: 'Which of these is a **dimension** table in a restaurant model?',
    options: ['Menu items (one row per dish)', 'Daily sales lines', 'Supplier invoice lines', 'Waste log entries'], answer: 0,
    explain: 'Dimensions describe things you slice by. The other three record events with numbers, so they are fact tables.' },
  { id: 'pb2-star-02', topic: 'pbi-star', type: 'mc', kind: 'concept', difficulty: 2, concept: 'star-schema',
    prompt: 'What is the **grain** of a fact table?',
    options: ['What one row represents', 'How many columns it has', 'How often it refreshes', 'Its file size'], answer: 0,
    explain: 'Grain: "one row per sales line", "one row per store per month"... Knowing it tells you what can be summed and compared.' },
  { id: 'pb2-star-03', topic: 'pbi-star', type: 'tf', kind: 'concept', difficulty: 2, concept: 'star-schema',
    prompt: 'True or false: in a star schema, dimension tables relate to the fact table, not to each other.',
    answer: true, explain: 'Each dimension connects to the fact table in the centre, which is what makes the "star" shape.' },
  { id: 'pb2-star-04', topic: 'pbi-star', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'star-schema',
    prompt: 'A flat export has 30 columns including customer name, city and signup date repeated on every order line. What is the star-schema approach?',
    options: ['Move customer attributes into a Customer table keyed by customer id', 'Keep the flat table and hide the customer columns', 'Create one table per city', 'Delete the customer columns'], answer: 0,
    explain: 'Customer attributes belong in one dimension row per customer. The fact keeps only customer_id plus the numbers.' },
  { id: 'pb2-star-05', topic: 'pbi-star', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'star-schema',
    prompt: 'Where should a "Region" slicer usually get its values from?',
    options: ['The Store (or Region) dimension', 'The sales fact table', 'A measure', 'A text box'], answer: 0,
    explain: 'Slice by dimension columns. A region slicer from the fact table only lists regions that happened to sell, and does not filter other facts.' },
  { id: 'pb2-star-06', topic: 'pbi-star', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'star-schema',
    prompt: 'A report has Sales and Budget fact tables. A Category slicer filters Sales but Budget stays the same. Most likely?',
    options: ['Budget is not related to the Category (Product) dimension', 'Budget has no values for those categories', 'The slicer only works on one visual', 'The date table has not been marked'], answer: 0,
    explain: 'Every fact that should respond to a slicer needs a relationship to that slicer\'s dimension (or be at a grain where it makes sense).' },
  { id: 'pb2-star-07', topic: 'pbi-star', type: 'fill', kind: 'concept', difficulty: 2, concept: 'star-schema',
    prompt: 'A dimension used by several fact tables (for example Date used by Sales and Targets) is called a ____ dimension.',
    answer: ['conformed', 'shared', 'common'], explain: 'A conformed (shared) dimension lets one slicer filter several facts consistently.' },
  { id: 'pb2-star-08', topic: 'pbi-star', type: 'tf', kind: 'concept', difficulty: 2, concept: 'star-schema',
    prompt: 'True or false: a fact table should hold numeric columns you aggregate plus the keys to its dimensions.',
    answer: true, explain: 'Amounts and quantities to sum, and keys (date, product, store...) to relate. Descriptions live in the dimensions.' },
  { id: 'pb2-star-09', topic: 'pbi-star', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'star-schema',
    prompt: 'Purchases (daily, per ingredient) and a monthly Stock count (per ingredient) must appear together by month. What do both need?',
    options: ['Relationships to the same Ingredient and Date dimensions', 'A direct relationship to each other', 'To be merged into one table', 'Separate reports'], answer: 0,
    explain: 'Shared dimensions let you compare facts with different grains. The stock table relates to the date table at its month-end date.' },
  { id: 'pb2-star-10', topic: 'pbi-star', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'star-schema',
    prompt: 'A model has Sales related to Store, and Store related to Region, and Region related to Sales. Totals now look wrong. What is the design problem?',
    options: ['A loop of relationships creates ambiguous filter paths', 'There are too many dimension tables', 'Region needs one row per store', 'Sales should be turned into a dimension'], answer: 0,
    explain: 'Filter paths must be unambiguous. Put Region as a column on Store (or snowflake it one way) and remove the extra relationship.' },
  { id: 'pb2-star-11', topic: 'pbi-star', type: 'mc', kind: 'concept', difficulty: 2, concept: 'star-schema',
    prompt: 'What is a **snowflake** in model design?',
    options: ['A dimension split into further related tables (Product → Category)', 'A fact table that has no dimension keys', 'A model that uses only calculated tables', 'A chart type for hierarchical data'], answer: 0,
    explain: 'Snowflaking normalises dimensions. It works, but a flat Product table with a Category column is usually simpler in Power BI.' },
  { id: 'pb2-star-12', topic: 'pbi-star', type: 'tf', kind: 'concept', difficulty: 3, concept: 'star-schema',
    prompt: 'True or false: a small "bridge" of two fact tables related directly to each other is the recommended way to compare them.',
    answer: false, explain: 'Compare facts through shared dimensions, not by relating the facts to each other.' },
  { id: 'pb2-star-13', topic: 'pbi-star', type: 'number', kind: 'calculation', difficulty: 2, concept: 'star-schema',
    prompt: 'A flat table has 50,000 order lines. Each line repeats 6 customer columns. Customers are 2,000 people. How many customer rows would the Customer dimension hold?',
    answer: 2000, verify: () => 2000,
    explain: 'One row per customer: 2,000 rows instead of repeating the same 6 columns on 50,000 lines.' },
  { id: 'pb2-star-14', topic: 'pbi-star', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'star-schema',
    prompt: 'An NGO tracks donations and wants to slice them by donor type, campaign and month. Which set of dimensions fits?',
    options: ['Donor, Campaign, Date', 'Donation amount, Gift Aid, Fee', 'One dimension per donation', 'A single Settings table'], answer: 0,
    explain: 'Donor, Campaign and Date describe the donation; the amounts stay in the Donations fact table.' },
  { id: 'pb2-star-15', topic: 'pbi-star', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'star-schema',
    prompt: 'Sales are per day and per product. Targets are per month and per category. A chart of target by product shows the same target on every product in a category. Why?',
    options: ['Targets are per category, so each product repeats it', 'The target relationship is set to inactive', 'Those products have no sales in that month', 'The target measure is a calculated column'], answer: 0,
    explain: 'You cannot show a figure below the grain it was recorded at. Show targets by category (or allocate them deliberately), never by product.' },
  { id: 'pb2-star-16', topic: 'pbi-star', type: 'fill', kind: 'concept', difficulty: 1, concept: 'star-schema',
    prompt: 'Tables that record events with numbers (sales, purchases, absences) are called ____ tables.',
    answer: ['fact', 'facts'], explain: 'Fact tables record events; dimension tables describe them.' },
];
