// Power BI quiz bank, part D: time intelligence, ranking and Top N, targets and analysis.
export const PBI_QUIZ_D = [
  // ================================================================ pbi-time
  { id: 'pb2-time-01', topic: 'pbi-time', type: 'fill', kind: 'tool-selection', difficulty: 2, concept: 'time-intel',
    prompt: 'Complete: `Revenue YTD = ____([Revenue], \'Date\'[Date])` for year-to-date revenue.',
    answer: ['TOTALYTD'], explain: 'TOTALYTD accumulates from 1 January (or a fiscal year start) to the current date in the filter.' },
  { id: 'pb2-time-02', topic: 'pbi-time', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'time-intel',
    prompt: 'Which function shifts the current dates back by exactly one year inside CALCULATE?',
    options: ['SAMEPERIODLASTYEAR', 'DATESYTD', 'PREVIOUSDAY', 'ENDOFYEAR'], answer: 0,
    explain: 'SAMEPERIODLASTYEAR returns the same dates one year earlier; CALCULATE applies them as the filter.' },
  { id: 'pb2-time-03', topic: 'pbi-time', type: 'number', kind: 'calculation', difficulty: 2, concept: 'time-intel',
    prompt: 'Revenue this year to date is $770,700 and last year to date $594,200. What is YoY growth, to one decimal place?',
    answer: 29.7, tolerance: 0.05, verify: () => Math.round(((770700 - 594200) / 594200) * 1000) / 10,
    explain: '(770,700 − 594,200) ÷ 594,200 = 29.7%. Growth is always divided by the earlier value.' },
  { id: 'pb2-time-04', topic: 'pbi-time', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'time-intel',
    prompt: 'Revenue LY shows blank for every month of 2024. What is the most likely cause?',
    options: ['The date table does not include 2023', 'SAMEPERIODLASTYEAR only works for 2025', 'The Revenue measure uses SUM', 'The report has too many pages'], answer: 0,
    explain: 'If the calendar starts in 2024, there are no 2023 dates to shift to, so last year is blank.' },
  { id: 'pb2-time-05', topic: 'pbi-time', type: 'tf', kind: 'concept', difficulty: 2, concept: 'time-intel',
    prompt: 'True or false: YTD for March shows revenue from 1 January to the end of March.',
    answer: true, explain: 'Year-to-date accumulates from the start of the year to the last date in the current filter.' },
  { id: 'pb2-time-06', topic: 'pbi-time', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'time-intel',
    prompt: 'Finance\'s year runs from 1 July. How do you make TOTALYTD follow it?',
    options: ['Add the year-end date: TOTALYTD([Revenue], \'Date\'[Date], "30/6")', 'Filter the date table to July onwards', 'Use TOTALMTD instead', 'Add 6 months to every sale'], answer: 0,
    explain: 'The optional year-end argument moves the start of the year. Check the date format matches your locale.' },
  { id: 'pb2-time-07', topic: 'pbi-time', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'time-intel',
    prompt: 'On 15 August, "MTD vs last August" shows −48%. What is the most likely explanation?',
    options: ['Half a month is compared with a full month', 'August sales halved', 'The date table is wrong', 'MTD only counts weekdays'], answer: 0,
    explain: 'Compare month-to-date with the same days last year (1 to 15 August), not with the whole of last August.' },
  { id: 'pb2-time-08', topic: 'pbi-time', type: 'number', kind: 'calculation', difficulty: 3, concept: 'time-intel',
    prompt: 'Revenue for 1 to 15 August was $52,750 this year and $48,870 on the same days last year. What is the growth, to one decimal place?',
    answer: 7.9, tolerance: 0.05, verify: () => Math.round(((52750 - 48870) / 48870) * 1000) / 10,
    explain: '(52,750 − 48,870) ÷ 48,870 = 7.9%. Same days, same length: a fair comparison.' },
  { id: 'pb2-time-09', topic: 'pbi-time', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'time-intel',
    prompt: 'Which filter gives a rolling three-month total ending in the selected month?',
    options: ['DATESINPERIOD(\'Date\'[Date], MAX(\'Date\'[Date]), -3, MONTH)', 'SAMEPERIODLASTYEAR(\'Date\'[Date])', 'DATESYTD(\'Date\'[Date])', 'PARALLELPERIOD(\'Date\'[Date], 3, MONTH)'], answer: 0,
    explain: 'DATESINPERIOD returns the dates from the last selected date back three months.' },
  { id: 'pb2-time-10', topic: 'pbi-time', type: 'tf', kind: 'concept', difficulty: 2, concept: 'time-intel',
    prompt: 'True or false: YoY % should be DIVIDE([Revenue] − [Revenue LY], [Revenue LY]).',
    answer: true, explain: 'The change divided by last year\'s value. DIVIDE keeps months without last-year data blank rather than showing an error.' },
  { id: 'pb2-time-11', topic: 'pbi-time', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'seasonality', crossConcept: true,
    prompt: 'An ice-cream brand compares July with June and sees +40%. The CEO asks if the new campaign worked. What comparison helps most?',
    options: ['July with July last year', 'July with the yearly average', 'July with January', 'June with May'], answer: 0,
    explain: 'July is always stronger than June for ice cream. Same period last year removes the season.' },
  { id: 'pb2-time-12', topic: 'pbi-time', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'time-intel',
    prompt: 'A YTD measure is placed in a chart with the fact table\'s order_date on the axis and gives odd results. What should the axis use?',
    options: ['The date table\'s Date or Month columns', 'The order id', 'A text version of order_date', 'The year only'], answer: 0,
    explain: 'Time intelligence relies on the marked date table. Put its columns on axes and slicers.' },
  { id: 'pb2-time-13', topic: 'pbi-time', type: 'fill', kind: 'concept', difficulty: 2, concept: 'time-intel',
    prompt: 'Month-to-date revenue can be written as `TOTAL____([Revenue], \'Date\'[Date])`.',
    answer: ['MTD'], explain: 'TOTALMTD accumulates from the first day of the month.' },
  { id: 'pb2-time-14', topic: 'pbi-time', type: 'number', kind: 'calculation', difficulty: 3, concept: 'time-intel',
    prompt: 'Monthly revenue: June $120,000, July $140,000, August $122,000. What is the rolling three-month total at August?',
    answer: 382000, verify: () => 120000 + 140000 + 122000,
    explain: '120,000 + 140,000 + 122,000 = 382,000. Rolling totals smooth out a single unusual month.' },
  { id: 'pb2-time-15', topic: 'pbi-time', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'time-intel',
    prompt: 'A matrix shows YTD growing month by month and then dropping to a small number in January. Is that a problem?',
    options: ['No: YTD restarts every year', 'Yes: January data is missing', 'Yes: the measure lost its filter', 'No: January is always small'], answer: 0,
    explain: 'Year-to-date resets at the start of each (fiscal) year by design.' },
  { id: 'pb2-time-16', topic: 'pbi-time', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'A new store opened last October. Its YoY % for this March is blank. What should the report say?',
    options: ['No comparison: the store did not trade last March', 'Growth is 0%', 'Growth is 100%', 'The store lost all its sales'], answer: 0,
    explain: 'DIVIDE returns blank when last year is blank. Say so clearly rather than showing 0% or infinity.' },
  { id: 'pb2-time-17', topic: 'pbi-time', type: 'tf', kind: 'concept', difficulty: 3, concept: 'time-intel',
    prompt: 'True or false: time-intelligence functions need the date column to be continuous, with no missing days.',
    answer: true, explain: 'Functions like SAMEPERIODLASTYEAR and DATESYTD assume a complete calendar. That is one reason for a proper date table.' },
  { id: 'pb2-time-18', topic: 'pbi-time', type: 'order', kind: 'sequence', difficulty: 3, concept: 'time-intel',
    prompt: 'Order the steps to build a YoY % measure.',
    options: ['Mark and relate a date table', 'Create [Revenue]', 'Create [Revenue LY] with SAMEPERIODLASTYEAR', 'Create YoY % with DIVIDE'], answer: [0, 1, 2, 3],
    explain: 'Calendar first, then the base measure, then last year, then the ratio.' },
  { id: 'pb2-time-19', topic: 'pbi-time', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'time-intel',
    prompt: 'You want to compare each month with the month three months earlier (for example May with February). Which function shifts the dates?',
    options: ['DATEADD(\'Date\'[Date], -3, MONTH)', 'SAMEPERIODLASTYEAR(\'Date\'[Date])', 'TOTALYTD([Revenue], \'Date\'[Date])', 'CALENDARAUTO()'], answer: 0,
    explain: 'DATEADD shifts dates by any number of days, months, quarters or years.' },
  { id: 'pb2-time-20', topic: 'pbi-time', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'In-store revenue is up 32% year to date, but excluding a store that opened in September it is up 14%. Which figure describes the existing stores?',
    options: ['14%', '32%', 'The average, 23%', 'Neither'], answer: 0,
    explain: 'Like-for-like growth (stores open in both periods) describes the existing business. The 32% includes a new store with no prior-year sales.' },
  { id: 'pb2-time-21', topic: 'pbi-time', type: 'number', kind: 'calculation', difficulty: 3, concept: 'time-intel',
    prompt: 'Last year to date: $400,000. This year to date: $372,000. What is the YoY %?',
    answer: -7, verify: () => ((372000 - 400000) / 400000) * 100,
    explain: '(372,000 − 400,000) ÷ 400,000 = −7%. A negative YoY is a decline; format it so the minus sign is visible.' },
  { id: 'pb2-time-22', topic: 'pbi-time', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'time-intel',
    prompt: 'A "Revenue LY" card shows the same number as "Revenue". The page has no date filter at all. Why?',
    options: ['Shifting all dates by a year still covers most sales', 'SAMEPERIODLASTYEAR does not work in cards', 'The card is missing a target value', 'Revenue was built as a calculated column'], answer: 0,
    explain: 'With every date selected, shifting by a year still overlaps most of the data. Time comparisons need a period in the filter context.' },

  // ================================================================ pbi-ranking
  { id: 'pb2-rank-01', topic: 'pbi-ranking', type: 'fill', kind: 'tool-selection', difficulty: 2, concept: 'dax-ranking',
    prompt: 'The DAX function that ranks items by a measure is ____.',
    answer: ['RANKX'], explain: 'RANKX(table, expression) ranks each item of the table by the expression.' },
  { id: 'pb2-rank-02', topic: 'pbi-ranking', type: 'mc', kind: 'concept', difficulty: 2, concept: 'dax-ranking',
    prompt: 'Why is ALL(Product[name]) used as RANKX\'s first argument?',
    options: ['So each product is compared with all products', 'So only one product is ranked', 'So the rank ignores the year slicer', 'So products are sorted by name'], answer: 0,
    explain: 'Without removing the product filter, each row would only see itself and rank 1.' },
  { id: 'pb2-rank-03', topic: 'pbi-ranking', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'dax-ranking',
    prompt: 'Every product shows rank 1. What is the likely mistake?',
    options: ['RANKX was given the filtered product, not ALL(...)', 'The revenue measure is a simple SUM', 'Products have no category assigned', 'The visual is a table, not a chart'], answer: 0,
    explain: 'RANKX over the filtered product (just itself) always returns 1. Use ALL or ALLSELECTED on the product column.' },
  { id: 'pb2-rank-04', topic: 'pbi-ranking', type: 'number', kind: 'calculation', difficulty: 2, concept: 'dax-ranking',
    prompt: 'Revenue: A $900, B $700, C $700, D $400. With default (skip) ties, what rank does D get?',
    answer: 4, verify: () => { const v = [900, 700, 700, 400]; return 1 + v.filter((x) => x > 400).length; },
    explain: 'A=1, B and C tie at 2, and the next rank skips to 4.' },
  { id: 'pb2-rank-05', topic: 'pbi-ranking', type: 'number', kind: 'calculation', difficulty: 2, concept: 'dax-ranking',
    prompt: 'Same revenues (A $900, B $700, C $700, D $400) with Dense ranking. What rank does D get?',
    answer: 3, verify: () => { const v = [900, 700, 700, 400]; return 1 + new Set(v.filter((x) => x > 400)).size; },
    explain: 'Dense ranking does not skip: A=1, B=C=2, D=3.' },
  { id: 'pb2-rank-06', topic: 'pbi-ranking', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'dax-ranking',
    prompt: 'What is the quickest way to show only the top 5 stores by revenue in a bar chart?',
    options: ['A Top N filter on the visual', 'A RANKX measure in a card', 'A page filter on store name', 'A sorted slicer'], answer: 0,
    explain: 'Filters pane → store → Top N → 5 by Revenue. No DAX needed.' },
  { id: 'pb2-rank-07', topic: 'pbi-ranking', type: 'tf', kind: 'concept', difficulty: 2, concept: 'dax-ranking',
    prompt: 'True or false: a Top N visual filter follows the other slicers on the page.',
    answer: true, explain: 'Pick 2025 in a slicer and the Top N shows 2025\'s top items.' },
  { id: 'pb2-rank-08', topic: 'pbi-ranking', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'dax-ranking',
    prompt: 'Which measure returns the revenue of the top 5 products as one number?',
    options: ['CALCULATE([Revenue], TOPN(5, ALL(Product[name]), [Revenue]))', 'TOPN(5, [Revenue])', 'RANKX(ALL(Product[name]), [Revenue]) <= 5', 'MAXX(Product, [Revenue]) * 5'], answer: 0,
    explain: 'TOPN returns the five products with the highest revenue; CALCULATE sums revenue over them.' },
  { id: 'pb2-rank-09', topic: 'pbi-ranking', type: 'number', kind: 'calculation', difficulty: 3, concept: 'dax-ranking',
    prompt: 'The top 5 products made $172,700 of $851,000 total revenue. What share is that, to one decimal place?',
    answer: 20.3, tolerance: 0.05, verify: () => Math.round((172700 / 851000) * 1000) / 10,
    explain: '172,700 ÷ 851,000 = 20.3%. A fifth of revenue from five products.' },
  { id: 'pb2-rank-10', topic: 'pbi-ranking', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'dax-ranking',
    prompt: 'It takes 16 of 58 products to reach 50% of revenue. What does that suggest?',
    options: ['Sales are spread fairly widely across the range', 'Two products carry the business', 'Most products never sell', 'The ranking is wrong'], answer: 0,
    explain: 'A quarter of the range makes half the revenue: a middle-heavy spread, not extreme concentration.' },
  { id: 'pb2-rank-11', topic: 'pbi-ranking', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'dax-ranking',
    prompt: 'You want ranks that restart within each category shown in the visual. Which table suits RANKX?',
    options: ['ALLSELECTED(Product[name]) with category on the rows', 'ALL(Product) with category on the rows', 'VALUES(Sales[product_id]) with category', 'ALL(Product[category]) with product rows'], answer: 0,
    explain: 'ALLSELECTED keeps the category from the row while ranking all products within it.' },
  { id: 'pb2-rank-12', topic: 'pbi-ranking', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'dax-ranking',
    prompt: 'Products that never sold appear at the bottom with a rank. The manager wants them left out. What do you change?',
    options: ['Return blank when [Revenue] is blank before ranking', 'Delete those products from the model', 'Rank by product name instead', 'Use a pie chart'], answer: 0,
    explain: 'IF(ISBLANK([Revenue]), BLANK(), RANKX(...)) keeps unsold products out of the ranking without removing them from the data.' },
  { id: 'pb2-rank-13', topic: 'pbi-ranking', type: 'tf', kind: 'concept', difficulty: 3, concept: 'dax-ranking',
    prompt: 'True or false: RANKX should rank by a measure rather than by a raw column.',
    answer: true, explain: 'A measure reacts to the filter context (year, store...). Ranking by a column ignores it.' },
  { id: 'pb2-rank-14', topic: 'pbi-ranking', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'dax-ranking',
    prompt: 'A league table of stores ranks the newest store last. The regional manager is upset. What should the report add?',
    options: ['Trading days or open date next to each store', 'A smaller font for the new store', 'Remove the new store', 'A different colour for last place'], answer: 0,
    explain: 'Ranks without context mislead. Showing months open (or a like-for-like ranking) makes the comparison fair.' },
  { id: 'pb2-rank-15', topic: 'pbi-ranking', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'dax-ranking',
    prompt: 'Stores ranked 1 and 2 have revenue $57,600 and $57,100. What should you say about the ranking?',
    options: ['They are practically level', 'Store 1 is clearly better', 'Store 2 is failing', 'The ranking is invalid'], answer: 0,
    explain: 'A 1% gap is within normal variation. Show values with ranks so readers see how close they are.' },
  { id: 'pb2-rank-16', topic: 'pbi-ranking', type: 'order', kind: 'sequence', difficulty: 3, concept: 'dax-ranking',
    prompt: 'Order the steps to find how many products make 50% of revenue.',
    options: ['Sort products by revenue, highest first', 'Calculate each product\'s share of total', 'Add a running total of the shares', 'Count products until the running total reaches 50%'], answer: [0, 1, 2, 3],
    explain: 'That is a Pareto analysis: sort, share, accumulate, count.' },
  { id: 'pb2-rank-17', topic: 'pbi-ranking', type: 'fill', kind: 'concept', difficulty: 3, concept: 'dax-ranking',
    prompt: 'To rank 1, 2, 2, 3 instead of 1, 2, 2, 4, use the ____ ties option in RANKX.',
    answer: ['Dense', 'DENSE'], explain: 'RANKX(table, expr, , DESC, Dense) gives consecutive ranks.' },
  { id: 'pb2-rank-18', topic: 'pbi-ranking', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'dax-ranking',
    prompt: 'A restaurant wants the three dishes with the lowest margin each month, to review pricing. What do you build?',
    options: ['A Bottom 3 filter by margin, per month', 'A pie chart of all dishes', 'A card with total margin', 'A list sorted by dish name'], answer: 0,
    explain: 'Top N can show bottom items too; by margin and filtered to a month, it gives the pricing shortlist.' },
  { id: 'pb2-rank-19', topic: 'pbi-ranking', type: 'number', kind: 'calculation', difficulty: 2, concept: 'dax-ranking',
    prompt: 'Product revenues: $50, $30, $10, $10. What share of the total do the top two products make, as a percentage?',
    answer: 80, verify: () => ((50 + 30) / (50 + 30 + 10 + 10)) * 100,
    explain: '(50 + 30) ÷ 100 = 80%. Two of four products make most of the revenue.' },
  { id: 'pb2-rank-20', topic: 'pbi-ranking', type: 'mc', kind: 'concept', difficulty: 3, concept: 'dax-ranking',
    prompt: 'What does TOPN(3, ALL(Store[name]), [Revenue]) return?',
    options: ['A table of the three stores with the highest revenue', 'The third highest revenue value', 'A rank number from 1 to 3', 'The top three revenue lines'], answer: 0,
    explain: 'TOPN returns a table, which is used inside CALCULATE or an iterator.' },
  { id: 'pb2-rank-21', topic: 'pbi-ranking', type: 'tf', kind: 'concept', difficulty: 2, concept: 'dax-ranking',
    prompt: 'True or false: a rank on its own shows how far apart two items are.',
    answer: false, explain: 'Ranks hide the distance between positions. Show the values as well.' },
  { id: 'pb2-rank-22', topic: 'pbi-ranking', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'dax-ranking',
    prompt: 'The rank changes when a user picks two stores in a slicer, but the manager wanted the rank among all stores. Which table fixes it?',
    options: ['ALL(Store[name]) instead of ALLSELECTED(Store[name])', 'VALUES(Store[name])', 'FILTER(Store, [Revenue] > 0)', 'ALLSELECTED(Sales)'], answer: 0,
    explain: 'ALLSELECTED ranks among the selected stores; ALL ranks among every store regardless of the slicer.' },
  { id: 'pb2-rank-23', topic: 'pbi-ranking', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'metric-choice', crossConcept: true,
    prompt: 'HR wants to rank departments by "absence". Department sizes range from 8 to 400 people. What should the rank be based on?',
    options: ['Absence days per employee (a rate)', 'Total absence days', 'Number of employees', 'Alphabetical order'], answer: 0,
    explain: 'Totals rank the biggest departments worst. A rate makes departments of different sizes comparable.' },
  { id: 'pb2-rank-24', topic: 'pbi-ranking', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'dax-ranking',
    prompt: 'A product moved from rank 14 to rank 6 in a year, but its revenue fell. How is that possible?',
    options: ['Products above it fell even more', 'The ranking is broken', 'Revenue cannot fall while rank rises', 'Its price must have gone up'], answer: 0,
    explain: 'Ranks are relative. If others fell further, a shrinking product can still climb.' },
  { id: 'pb2-rank-25', topic: 'pbi-ranking', type: 'fill', kind: 'tool-selection', difficulty: 3, concept: 'dax-ranking',
    prompt: 'The function that returns a table of the N highest items by an expression is ____.',
    answer: ['TOPN'], explain: 'TOPN(n, table, expression) returns a table of the n items with the highest value, ready to use inside CALCULATE.' },

  // ================================================================ pbi-analysis
  { id: 'pb2-an-01', topic: 'pbi-analysis', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pbi-analysis',
    prompt: 'Store targets arrive as one column per month. What do you do in Power Query first?',
    options: ['Unpivot the month columns', 'Pivot the store column', 'Merge with Sales', 'Remove the month columns'], answer: 0,
    explain: 'Unpivot turns months into rows (Store, Month, Target), the shape the model needs.' },
  { id: 'pb2-an-02', topic: 'pbi-analysis', type: 'mc', kind: 'concept', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Targets are per store per month. Which relationships are right?',
    options: ['Targets to Store and to the Date table by month', 'Targets directly to Sales', 'Targets to Product', 'No relationships: use slicers'], answer: 0,
    explain: 'Relate the target table to the shared dimensions at its own grain (store and month).' },
  { id: 'pb2-an-03', topic: 'pbi-analysis', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pbi-analysis',
    prompt: 'A store made $43,100 against a target of $44,000. What is attainment, to one decimal place?',
    answer: 98, tolerance: 0.05, verify: () => Math.round((43100 / 44000) * 1000) / 10,
    explain: '43,100 ÷ 44,000 = 98.0%. The store missed by $900, about 2%.' },
  { id: 'pb2-an-04', topic: 'pbi-analysis', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pbi-analysis',
    prompt: 'Growth measured only on stores open in both periods is called ____-for-____ growth. (Write the phrase.)',
    answer: ['like-for-like', 'like for like', 'lfl'], explain: 'Like-for-like excludes openings and closures, so the comparison is fair.' },
  { id: 'pb2-an-05', topic: 'pbi-analysis', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Five stores reached 97% of target overall; four were between 95% and 106%, one was at 77%. What is the main message?',
    options: ['The shortfall is concentrated in one store', 'All stores missed their targets', 'Targets were far too high everywhere', 'The overall miss is spread evenly'], answer: 0,
    explain: 'A total can hide where the problem is. The breakdown shows one store causes most of the gap.' },
  { id: 'pb2-an-06', topic: 'pbi-analysis', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'A store opened eight months ago is 23% below its target. What should you check before blaming the store?',
    options: ['How its target was set without trading history', 'The colour of its bar', 'Whether its manager is new', 'Whether the report is published'], answer: 0,
    explain: 'A new store\'s target is a guess. Questioning the target is as important as questioning the store.' },
  { id: 'pb2-an-07', topic: 'pbi-analysis', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-analysis',
    prompt: 'True or false: a month with no target should show blank attainment rather than 0%.',
    answer: true, explain: 'No target means no comparison. 0% would look like a total failure.' },
  { id: 'pb2-an-08', topic: 'pbi-analysis', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Revenue grew by $176,500. Footwear grew by $42,700 and Tents by $39,900. What share of the growth came from those two categories, to one decimal place?',
    answer: 46.8, tolerance: 0.05, verify: () => Math.round(((42700 + 39900) / 176500) * 1000) / 10,
    explain: '(42,700 + 39,900) ÷ 176,500 = 46.8%. Two categories explain almost half of the growth.' },
  { id: 'pb2-an-09', topic: 'pbi-analysis', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Which visual lets a manager click down from total growth into region, then store, then category?',
    options: ['Decomposition tree', 'Card', 'Gauge', 'Slicer'], answer: 0,
    explain: 'The decomposition tree splits a measure step by step along the fields the reader chooses.' },
  { id: 'pb2-an-10', topic: 'pbi-analysis', type: 'mc', kind: 'concept', difficulty: 2, concept: 'pbi-sharing',
    prompt: 'What does publishing a report do?',
    options: ['Sends it to the Power BI Service for sharing', 'Saves it as a PDF', 'Emails it to everyone', 'Locks the data forever'], answer: 0,
    explain: 'Publish uploads the report and its data to a workspace in the Service.' },
  { id: 'pb2-an-11', topic: 'pbi-analysis', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-sharing',
    prompt: 'A published report refreshes fine in Desktop but fails in the Service. The source is an Excel file on your laptop. Why?',
    options: ['The Service cannot reach a local file without a gateway', 'The file has too many sheets', 'Measures are not allowed in the Service', 'The report has no date table'], answer: 0,
    explain: 'Local files need an on-premises data gateway, or a cloud location such as SharePoint or OneDrive.' },
  { id: 'pb2-an-12', topic: 'pbi-analysis', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pbi-sharing',
    prompt: 'True or false: sharing one published app is better than emailing copies of the .pbix file.',
    answer: true, explain: 'An app keeps one version, controlled permissions and scheduled refresh. Copies drift apart.' },
  { id: 'pb2-an-13', topic: 'pbi-analysis', type: 'mc', kind: 'concept', difficulty: 3, concept: 'pbi-sharing',
    prompt: 'What is row-level security (RLS) used for?',
    options: ['Showing each user only the rows they may see', 'Encrypting the .pbix file', 'Hiding measures from authors', 'Speeding up refresh'], answer: 0,
    explain: 'RLS applies filters per user role, for example each manager sees only their own stores.' },
  { id: 'pb2-an-14', topic: 'pbi-analysis', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Revenue is up 30%, and the company opened 3 new stores this year. What should the headline include?',
    options: ['Total growth and like-for-like growth', 'Only the 30%', 'Only the new stores\' revenue', 'Growth per new store'], answer: 0,
    explain: 'Both numbers answer different questions: how big the business is, and how the existing stores are doing.' },
  { id: 'pb2-an-15', topic: 'pbi-analysis', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'The West region target was $64,500 and actual revenue $55,300. What is the variance (actual − target)?',
    answer: -9200, verify: () => 55300 - 64500,
    explain: '55,300 − 64,500 = −9,200. A negative variance means below target.' },
  { id: 'pb2-an-16', topic: 'pbi-analysis', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Every category grew this year. The category manager of the slowest-growing one is told she "declined". What is wrong?',
    options: ['Lowest growth is not a decline', 'Nothing: lowest means declining', 'Growth cannot be compared', 'Her category is not in the data'], answer: 0,
    explain: 'Words matter. "Grew least" and "declined" lead to very different conversations.' },
  { id: 'pb2-an-17', topic: 'pbi-analysis', type: 'order', kind: 'sequence', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Order the steps to add a target comparison to a sales report.',
    options: ['Unpivot and clean the target file', 'Relate targets to Store and Date', 'Create Target, Variance and Attainment measures', 'Show attainment by store with a clear title'], answer: [0, 1, 2, 3],
    explain: 'Shape the file, relate it at its own grain, write the measures, then present them so the reader sees who is behind.' },
  { id: 'pb2-an-18', topic: 'pbi-analysis', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'A director asks why revenue grew. You have revenue by category, channel and store. What is the best first step?',
    options: ['Compare this period with last period by each field', 'Show only the total growth figure', 'Build a new model from scratch', 'Ask for more data before looking'], answer: 0,
    explain: 'Break the change down by each dimension; the fields with the biggest differences are where the story is.' },
  { id: 'pb2-an-19', topic: 'pbi-analysis', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pbi-sharing',
    prompt: 'True or false: scheduled refresh in the Service re-runs the Power Query steps against the sources.',
    answer: true, explain: 'Refresh repeats the load, so the report stays current without anyone opening Desktop.' },
  { id: 'pb2-an-20', topic: 'pbi-analysis', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Attainment shows 250% for one store in June. The store\'s target for June is $4,000 while others are around $15,000. What do you check?',
    options: ['Whether the target was entered wrongly', 'Whether the store is excellent', 'The chart colours', 'The relationship direction'], answer: 0,
    explain: 'An outlier in a ratio is often a data entry issue in the denominator. Check the target before celebrating.' },
  { id: 'pb2-an-21', topic: 'pbi-analysis', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pbi-sharing',
    prompt: 'To refresh a published report that reads files on a company server, you need an on-premises data ____.',
    answer: ['gateway'], explain: 'A gateway lets the Service reach sources inside the company network.' },
  { id: 'pb2-an-22', topic: 'pbi-analysis', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'communication', crossConcept: true,
    prompt: 'Your analysis shows a store missed target, but the data cannot say why. What belongs in your summary?',
    options: ['The facts, possible causes, and what to check next', 'A definite cause to sound confident', 'Only the chart without comment', 'A recommendation to close the store'], answer: 0,
    explain: 'Separate what the data shows from what you suspect, and say how you would find out.' },
  { id: 'pb2-an-23', topic: 'pbi-analysis', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Like-for-like stores made $520,000 last year and $590,000 this year. What is like-for-like growth, to one decimal place?',
    answer: 13.5, tolerance: 0.05, verify: () => Math.round(((590000 - 520000) / 520000) * 1000) / 10,
    explain: '(590,000 − 520,000) ÷ 520,000 = 13.5%. Only stores open in both years are counted, so new openings do not inflate it.' },
  { id: 'pb2-an-24', topic: 'pbi-analysis', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Actual is 97% of target overall and the director asks "so we are fine?". What is the most honest reply?',
    options: ['Close overall, but one store is well below', 'Yes, 97% is fine', 'No, anything under 100% is a failure', 'It depends on the colours'], answer: 0,
    explain: 'Give the headline and the part that needs attention.' },
  { id: 'pb2-an-25', topic: 'pbi-analysis', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'pbi-analysis',
    prompt: 'Which measure keeps like-for-like revenue for stores opened before 2025?',
    options: ['CALCULATE([Revenue], Store[opened_on] < DATE(2025,1,1))', 'CALCULATE([Revenue], Store[opened_on] > TODAY())', 'SUM(Store[opened_on])', 'FILTER(Store, 2025)'], answer: 0,
    explain: 'A filter on the store open date keeps only stores that traded in both periods.' },
];
