// Power Query quiz bank, part C: M code, parameters and folder imports.
export const PQ_QUIZ_C = [
  // ================================================================ pq-m
  { id: 'pq2-m-01', topic: 'pq-m', type: 'mc', kind: 'concept', difficulty: 3, concept: 'm-code',
    prompt: 'Why does a step appear as #"Changed Type" in the Advanced Editor?',
    options: ['Names with spaces need the #"…" form', 'It marks a step that has an error', 'It is a comment added by Power Query', 'It means the step runs first'], answer: 0,
    explain: 'A step name with spaces or symbols is written #"…". Renaming steps without spaces (ChangedType) keeps the code easier to read.' },
  { id: 'pq2-m-02', topic: 'pq-m', type: 'fill', kind: 'concept', difficulty: 3, concept: 'm-code',
    prompt: 'In M, a missing value is written ____.',
    answer: ['null'], explain: 'null means "no value". Test it with [Qty] = null; it is not the same as 0 or "".' },
  { id: 'pq2-m-03', topic: 'pq-m', type: 'tf', kind: 'concept', difficulty: 4, concept: 'm-code',
    prompt: 'True or false: inside let, steps refer to each other by name, so M works out the order in which to evaluate them.',
    answer: true, explain: 'M evaluates what the result needs, following the names. Keep the steps in reading order anyway: people read top to bottom.' },
  { id: 'pq2-m-04', topic: 'pq-m', type: 'number', kind: 'calculation', difficulty: 3, concept: 'm-code',
    prompt: 'What does List.Sum({12, 8, null, 5}) return?',
    answer: 25, verify: () => 12 + 8 + 5,
    explain: 'List.Sum adds the values that are not null: 12 + 8 + 5 = 25. Decide whether a null should really count as nothing.' },
  { id: 'pq2-m-05', topic: 'pq-m', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'm-code',
    prompt: 'Which rows does Table.SelectRows(Source, each [Qty] > 0 and [Status] <> "Cancelled") keep?',
    options: ['Rows with a positive Qty that are not cancelled', 'Rows with a positive Qty or a cancelled status', 'Only the cancelled rows with a positive Qty', 'Every row, with cancelled ones set to 0'], answer: 0,
    explain: 'Both conditions must be true for a row to stay: and means both, or means either.' },
  { id: 'pq2-m-06', topic: 'pq-m', type: 'fill', kind: 'concept', difficulty: 4, concept: 'pq-robust',
    prompt: 'Complete so a missing Notes column comes back filled with null: Table.SelectColumns(Source, {"Date", "Units", "Notes"}, MissingField.____)',
    answer: ['usenull'], explain: 'MissingField.UseNull adds the missing column with nulls; MissingField.Ignore leaves it out.' },
  { id: 'pq2-m-07', topic: 'pq-m', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'm-code',
    prompt: 'A Custom Column "Store " & [StoreID] fails with "We cannot apply operator & to types Text and Number". What is the fix?',
    options: ['Wrap the number: Text.From([StoreID])', 'Use + instead of &', 'Change the column to Whole Number', 'Put [StoreID] in quotes'], answer: 0,
    explain: '& joins text only. Text.From turns the number into text first.' },
  { id: 'pq2-m-08', topic: 'pq-m', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'pq-robust',
    prompt: 'Which expression checks whether a table has a Notes column?',
    options: ['Table.HasColumns(Source, "Notes")', 'Source[Notes] <> null', 'List.Contains(Source, "Notes")', 'Table.RowCount(Source[Notes])'], answer: 0,
    explain: 'Table.HasColumns returns true or false, so an if … then … else can handle both layouts.' },
  { id: 'pq2-m-09', topic: 'pq-m', type: 'number', kind: 'calculation', difficulty: 3, concept: 'm-code',
    prompt: 'What does Text.Length(Text.Trim("  W02 ")) return?',
    answer: 3, verify: () => '  W02 '.trim().length,
    explain: 'Trim removes the spaces at both ends, leaving "W02": 3 characters.' },
  { id: 'pq2-m-10', topic: 'pq-m', type: 'order', kind: 'sequence', difficulty: 3, concept: 'm-code',
    prompt: 'Order the parts of a query as they appear in the Advanced Editor.',
    options: ['let', 'Source = … (the connection)', 'The transformation steps', 'in, followed by the final step'], answer: [0, 1, 2, 3],
    explain: 'let opens the list of steps, the source comes first, each step builds on an earlier one, and in names the result.' },
  { id: 'pq2-m-11', topic: 'pq-m', type: 'mc', kind: 'concept', difficulty: 3, concept: 'm-code',
    prompt: 'What is a record in M?',
    options: ['A set of named fields, like one row', 'A list of values without names', 'A saved copy of a query', 'A table with a single column'], answer: 0,
    explain: '[Store = "W02", Units = 3] is a record. Each row of a table is a record, which is why [Units] reads a field.' },
  { id: 'pq2-m-12', topic: 'pq-m', type: 'tf', kind: 'concept', difficulty: 3, concept: 'm-code',
    prompt: 'True or false: {1, 2, 3} is a list and [a = 1] is a record.',
    answer: true, explain: 'Curly braces make lists, square brackets make records (and pick fields in a row).' },
  { id: 'pq2-m-13', topic: 'pq-m', type: 'mc', kind: 'scenario', difficulty: 4, concept: 'locale',
    prompt: 'An Amount text column holds "1,234.50", "n/a" and "-". You want numbers, with bad values as null and no errors. Which Custom Column?',
    options: ['try Number.From([Amount], "en-US") otherwise null', 'Number.From([Amount])', 'Text.Remove([Amount], {"n", "/"})', 'if [Amount] = null then 0 else [Amount]'], answer: 0,
    explain: 'The culture says how to read the comma and point; try … otherwise turns anything unreadable into null.' },
  { id: 'pq2-m-14', topic: 'pq-m', type: 'fill', kind: 'concept', difficulty: 3, concept: 'm-code',
    prompt: 'The function that returns the current date and time on the computer is DateTime.____().',
    answer: ['localnow'], explain: 'DateTime.LocalNow() changes on every refresh, so reports built on it change too.' },
  { id: 'pq2-m-15', topic: 'pq-m', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'pq-robust',
    prompt: 'Table.Skip(Source, 2) worked for June, but July has three title lines. What is the robust version?',
    options: ['Table.Skip(Source, each [Column1] <> "Date")', 'Table.Skip(Source, 3)', 'Table.FirstN(Source, 3)', 'Table.Skip(Source, 2) twice'], answer: 0,
    explain: 'With a condition, Table.Skip drops rows until it reaches the header, however many title lines there are.' },
  { id: 'pq2-m-16', topic: 'pq-m', type: 'number', kind: 'calculation', difficulty: 3, concept: 'm-code',
    prompt: 'Date.AddDays(#date(2026, 7, 30), 5) returns a date in August. Which day of the month?',
    answer: 4, verify: () => new Date(Date.UTC(2026, 6, 30 + 5)).getUTCDate(),
    explain: 'July has 31 days: 30 July + 5 days = 4 August. #date(year, month, day) builds a date in M.' },
  { id: 'pq2-m-17', topic: 'pq-m', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pq-robust',
    prompt: 'True or false: an error in one cell stops the whole query from loading into Excel.',
    answer: false, explain: 'The rows load with an error cell, and the query shows an errors link. That is why error counts must be checked after a refresh.' },
  { id: 'pq2-m-18', topic: 'pq-m', type: 'mc', kind: 'interpretation', difficulty: 4, concept: 'm-code',
    prompt: 'What does try [Revenue] / [Orders] return for a row where the division fails, if there is no otherwise?',
    options: ['A record with HasError and Error fields', 'The number zero', 'A null value', 'The text "Error"'], answer: 0,
    explain: 'try without otherwise returns a record. Expand it, or read [HasError], to see what went wrong on each row.' },
  { id: 'pq2-m-19', topic: 'pq-m', type: 'mc', kind: 'concept', difficulty: 4, concept: 'pq-robust',
    prompt: 'What does "query folding" mean?',
    options: ['Power Query sends the steps to the database as one query', 'Power Query hides steps you no longer need', 'Two queries are merged into one', 'The query is saved in a smaller file'], answer: 0,
    explain: 'When steps fold, the database does the filtering and grouping, and only the result travels to Power Query.' },
  { id: 'pq2-m-20', topic: 'pq-m', type: 'tf', kind: 'concept', difficulty: 4, concept: 'pq-robust',
    prompt: 'True or false: on a large database, filtering early helps because a folded filter means fewer rows are sent to Power Query.',
    answer: true, explain: 'Filter and remove columns early, before steps that stop folding (such as some custom columns).' },
  { id: 'pq2-m-21', topic: 'pq-m', type: 'fill', kind: 'concept', difficulty: 4, concept: 'm-code',
    prompt: 'Complete so capital letters are ignored: Text.Contains([Name], "chen", Comparer.____)',
    answer: ['ordinalignorecase'], explain: 'Comparer.OrdinalIgnoreCase makes the comparison case-insensitive; without it, "Chen" does not contain "chen".' },

  // ================================================================ pq-params
  { id: 'pq2-par-01', topic: 'pq-params', type: 'mc', kind: 'concept', difficulty: 2, concept: 'pq-params',
    prompt: 'What is a parameter in Power Query?',
    options: ['A named value that steps can use', 'A step that removes errors', 'A column added to every table', 'A copy of a query'], answer: 0,
    explain: 'A parameter holds one value (a path, a date, a region) that queries use by name.' },
  { id: 'pq2-par-02', topic: 'pq-params', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pq-params',
    prompt: 'Where do you create a parameter in the Power Query editor?',
    options: ['Home → Manage Parameters → New Parameter', 'View → Advanced Editor → Parameter', 'Add Column → Parameter Column', 'Transform → Replace Values'], answer: 0,
    explain: 'Manage Parameters lists every parameter with its type and current value.' },
  { id: 'pq2-par-03', topic: 'pq-params', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-params',
    prompt: 'True or false: a parameter can hold a date, a number or text.',
    answer: true, explain: 'Choose the type when you create it; the steps that use it expect that type.' },
  { id: 'pq2-par-04', topic: 'pq-params', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pq-params',
    prompt: 'A query reads from C:\\Users\\ana\\Reports, and Ana leaves the company. What should have been done?',
    options: ['Keep the path in a parameter and the files in a shared place', 'Copy Ana\'s folder to every laptop', 'Rename the folder to Reports2', 'Delete the query and start again'], answer: 0,
    explain: 'Personal paths break for everyone else. A shared location plus a FolderPath parameter makes the change a one-minute job.' },
  { id: 'pq2-par-05', topic: 'pq-params', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pq-folder',
    prompt: 'In the file list of a folder import, the column that holds each file itself is called ____.',
    answer: ['content'], explain: 'Content holds each file as binary; Combine Files and custom functions read it.' },
  { id: 'pq2-par-06', topic: 'pq-params', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pq-folder',
    prompt: 'Someone saved "Sales_June (1).csv" next to "Sales_June.csv" in the folder, and June doubled. What is the lasting fix?',
    options: ['Filter the file list to the expected name pattern', 'Remove duplicate rows at the end', 'Divide June by two', 'Ask people never to save copies'], answer: 0,
    explain: 'A filter on the file name (or a check per file) stops stray copies being combined. Deduplicating rows would hide real repeat orders too.' },
  { id: 'pq2-par-07', topic: 'pq-params', type: 'order', kind: 'sequence', difficulty: 3, concept: 'pq-params',
    prompt: 'Order the steps to use a date parameter in a filter.',
    options: ['Create the StartDate parameter', 'Filter the date column with any fixed date', 'Replace the fixed date with StartDate in the formula bar', 'Change the parameter and refresh to test it'], answer: [0, 1, 2, 3],
    explain: 'The filter dialog writes a fixed date; you swap it for the parameter, then prove it works with another value.' },
  { id: 'pq2-par-08', topic: 'pq-params', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pq-folder',
    prompt: 'A folder holds 12 monthly CSV files, a README.txt and an "archive" subfolder with 12 older CSV files. If you only filter on Extension = ".csv", how many files are combined?',
    answer: 24, verify: () => 12 + 12,
    explain: 'The file list includes subfolders, so the 12 archived files come along. Filter on Folder Path too.' },
  { id: 'pq2-par-09', topic: 'pq-params', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pq-folder',
    prompt: 'A check of rows per file shows 388, 400, 395 and 788. What does the last figure suggest?',
    options: ['That file may hold two months or repeated rows', 'That month was twice as busy as usual', 'The check counted the header twice', 'Nothing unusual: files vary in size'], answer: 0,
    explain: 'A file about double the usual size deserves a look before its month is reported as a record.' },
  { id: 'pq2-par-10', topic: 'pq-params', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-folder',
    prompt: 'True or false: Text Between Delimiters "_" and "_" on "Swiftline_ML_2026-Q3.csv" returns ML.',
    answer: true, explain: 'The first two underscores surround ML, the depot code, which you can then merge with a depot list.' },
  { id: 'pq2-par-11', topic: 'pq-params', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'pq-folder',
    prompt: 'Files are named like "POS_Summary_2026-07.csv". How do you get the month into a column?',
    options: ['Extract the text after the last "_" and before ".csv"', 'Use each file\'s Date modified value', 'Split the name into single characters', 'Type the month into every file'], answer: 0,
    explain: 'The name is set by the export; the modified date changes whenever someone opens and saves the file.' },
  { id: 'pq2-par-12', topic: 'pq-params', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-folder',
    prompt: 'True or false: a file\'s Date modified always tells you which month its data covers.',
    answer: false, explain: 'Re-saving or copying a file changes its modified date. Use the name or a date inside the file.' },
  { id: 'pq2-par-13', topic: 'pq-params', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pq-params',
    prompt: 'Two teams need the same report, one from the North folder and one from the South folder. What is the best set-up?',
    options: ['One query with a FolderPath parameter', 'Two copies of the query to maintain', 'One query reading both folders mixed', 'A manual copy of each folder\'s data'], answer: 0,
    explain: 'One set of steps, one parameter to switch: a fix to the cleaning reaches both teams.' },
  { id: 'pq2-par-14', topic: 'pq-params', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pq-params',
    prompt: 'StartDate is 1 August 2026 and the data ends on 30 September 2026. How many calendar days does the filtered report cover?',
    answer: 61, verify: () => (Date.UTC(2026, 8, 30) - Date.UTC(2026, 7, 1)) / 86400000 + 1,
    explain: 'August has 31 days and September 30: 61 days, counting both the first and the last day.' },
  { id: 'pq2-par-15', topic: 'pq-params', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pq-params',
    prompt: 'You changed the StartDate parameter, but the report in the sheet still shows the old numbers. Why?',
    options: ['The query has not been refreshed yet', 'Parameters only work in Power BI', 'The parameter must be a text value', 'Filters cannot use parameters'], answer: 0,
    explain: 'Changing a parameter changes the recipe; Refresh runs it again and updates the loaded table.' },
  { id: 'pq2-par-16', topic: 'pq-params', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pq-params',
    prompt: 'True or false: in Power BI, a dataset\'s parameters can be changed in the online service without opening Power BI Desktop.',
    answer: true, explain: 'Semantic model settings list the parameters, which is handy for switching a source path or a date.' },
  { id: 'pq2-par-17', topic: 'pq-params', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pq-append',
    prompt: 'After combining depot files, Easton\'s rows are null in DistanceKm, and a DistanceMi column appears. Why?',
    options: ['Easton\'s column has another name, and append matches names', 'Easton did not record any distances', 'The DistanceKm column type is wrong', 'Folder imports rename columns at random'], answer: 0,
    explain: 'Rows stack by column name. Easton writes miles under another name, so its values land in their own column.' },
  { id: 'pq2-par-18', topic: 'pq-params', type: 'fill', kind: 'concept', difficulty: 3, concept: 'pq-params',
    prompt: 'Under Suggested Values, a parameter can offer a list of ____ for users to choose from.',
    answer: ['values', 'allowed values'], explain: 'A list of allowed values (for example the four depot codes) prevents typing mistakes.' },
  { id: 'pq2-par-19', topic: 'pq-params', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pq-folder',
    prompt: 'The depot list (codes and names) is saved in the same folder as the depot exports. What happens on refresh?',
    options: ['It is combined as if it were a depot export', 'Power Query uses it as a lookup automatically', 'It is ignored because it is small', 'The refresh asks which file to skip'], answer: 0,
    explain: 'Everything in the folder is data to a folder import. Keep lookups elsewhere, or filter them out by name.' },
  { id: 'pq2-par-20', topic: 'pq-params', type: 'number', kind: 'calculation', difficulty: 2, concept: 'reconciliation',
    prompt: 'Four files hold 480, 310, 390 and 240 data rows. The combined table has 1,423 rows. How many rows too many?',
    answer: 3, verify: () => 1423 - (480 + 310 + 390 + 240),
    explain: '480 + 310 + 390 + 240 = 1,420, so 3 extra rows came from somewhere: empty lines, a TOTAL row or a stray file.' },
  { id: 'pq2-par-21', topic: 'pq-params', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pq-clean',
    prompt: 'The 3 extra rows are empty in every column except Source.Name. What are they?',
    options: ['Empty lines in one file that were not removed', 'Rows from a hidden sheet', 'Duplicate headers from each file', 'Rows added by the parameter'], answer: 0,
    explain: 'Source.Name is filled for every row, so blank lines look almost empty. Remove blank rows in the sample transformation.' },
  { id: 'pq2-par-22', topic: 'pq-params', type: 'tf', kind: 'debugging', difficulty: 3, concept: 'pq-folder',
    prompt: 'True or false: if one file in the folder uses semicolons instead of commas, the sample transformation still splits it correctly.',
    answer: false, explain: 'The sample file\'s delimiter is applied to every file. A different delimiter puts the whole line in one column.' },
  { id: 'pq2-par-23', topic: 'pq-params', type: 'mc', kind: 'concept', difficulty: 3, concept: 'pq-folder',
    prompt: 'Besides the combined query, what does Combine Files create?',
    options: ['A sample file, a sample transformation and a function', 'A backup copy of every file', 'One query per file in the folder', 'A PivotTable of the combined data'], answer: 0,
    explain: 'Transform Sample File is where you edit; the function applies those steps to every file.' },
  { id: 'pq2-par-24', topic: 'pq-params', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-folder',
    prompt: 'True or false: a folder import can combine Excel workbooks as well as CSV files.',
    answer: true, explain: 'For workbooks, you pick the sheet or table to use in the sample file; every workbook needs the same one.' },
  { id: 'pq2-par-25', topic: 'pq-params', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pq-folder',
    prompt: 'A fifth depot starts sending files in the same layout as Harbor City. What must you change in the folder query?',
    options: ['Only the depot list: add the new depot, then refresh', 'Build a new query for the fifth depot', 'Edit every step to name the new depot', 'Rename its file to match another depot'], answer: 0,
    explain: 'The folder query picks up the new file by itself; the lookup just needs the new code so the name and region appear.' },
];
