// Power Query quiz bank, part D: custom functions and dynamic transformations (Advanced).
export const PQ_QUIZ_D = [
  // ================================================================ pq-functions
  { id: 'pq2-fn-01', topic: 'pq-functions', type: 'mc', kind: 'concept', difficulty: 3, concept: 'pq-functions',
    prompt: 'What is a custom function in Power Query?',
    options: ['A query that takes inputs and returns a result', 'A step recorded by clicking a button', 'A parameter with a list of values', 'A column that holds formulas'], answer: 0,
    explain: 'A function has inputs and a body. You write it once and call it for every file, row or value.' },
  { id: 'pq2-fn-02', topic: 'pq-functions', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'pq-functions',
    prompt: 'How do you run a function called fnMargin on every row of a table without writing code?',
    options: ['Add Column → Invoke Custom Function', 'Home → Manage Parameters', 'Transform → Replace Values', 'View → Advanced Editor'], answer: 0,
    explain: 'Invoke Custom Function asks which column feeds each input and adds the result as a new column.' },
  { id: 'pq2-fn-03', topic: 'pq-functions', type: 'fill', kind: 'concept', difficulty: 3, concept: 'pq-functions',
    prompt: 'In M, a function\'s inputs in brackets are followed by the symbol ____ and then the body.',
    answer: ['=>', 'arrow'], explain: '(price, cost) => (price - cost) / price: the arrow separates the inputs from what the function returns.' },
  { id: 'pq2-fn-04', topic: 'pq-functions', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pq-functions',
    prompt: 'fnMargin = (price, cost) => (price - cost) / price. What does fnMargin(40, 30) return?',
    answer: 0.25, tolerance: 0.0001, verify: () => (40 - 30) / 40,
    explain: '(40 − 30) ÷ 40 = 0.25, a 25% margin. Format it as a percentage after loading.' },
  { id: 'pq2-fn-05', topic: 'pq-functions', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pq-functions',
    prompt: 'True or false: a function saved as a query does not load a table of its own; other queries call it.',
    answer: true, explain: 'Set functions (and helper queries) to "Connection only" so they do not create sheets.' },
  { id: 'pq2-fn-06', topic: 'pq-functions', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pq-functions',
    prompt: 'In Table.TransformColumns(t, {{"Product", each Text.Upper(_)}}), what is _?',
    options: ['The value in each Product cell', 'The whole table t', 'The name of the column', 'The previous step'], answer: 0,
    explain: 'each defines a one-input function; in TransformColumns that input is one cell value at a time.' },
  { id: 'pq2-fn-07', topic: 'pq-functions', type: 'order', kind: 'sequence', difficulty: 3, concept: 'pq-functions',
    prompt: 'Order the steps to turn a one-file query into a function for a whole folder.',
    options: ['Build and test a query on one file', 'Wrap it in (file as binary) as table => …', 'Invoke it on the Content column of the folder list', 'Expand the tables it returns'], answer: [0, 1, 2, 3],
    explain: 'Test on one file first, then generalise, then apply to every file, then expand the results into rows.' },
  { id: 'pq2-fn-08', topic: 'pq-functions', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'pq-functions',
    prompt: 'Invoking fnClean on the folder list fails: "We cannot convert the value "Swiftline_HC_2026-Q3.csv" to type Binary." Why?',
    options: ['The Name column was passed instead of Content', 'The CSV file is damaged', 'fnClean needs a text input', 'Folder lists cannot be used with functions'], answer: 0,
    explain: 'The function expects the file itself (Content), not its name. Pick the Content column in the Invoke dialog.' },
  { id: 'pq2-fn-09', topic: 'pq-functions', type: 'tf', kind: 'debugging', difficulty: 3, concept: 'pq-functions',
    prompt: 'True or false: if a function is declared as (file as binary), passing it a table gives a clear type error.',
    answer: true, explain: 'Typed inputs fail early and say why, instead of producing strange results further down.' },
  { id: 'pq2-fn-10', topic: 'pq-functions', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pq-functions',
    prompt: 'fnBand = (x as number) => if x >= 4 then "Scale" else if x >= 2 then "Keep" else "Cut". How many of the values 4.5, 3.9, 2.0 and 1.99 return "Keep"?',
    answer: 2, verify: () => [4.5, 3.9, 2.0, 1.99].filter((x) => x < 4 && x >= 2).length,
    explain: '3.9 and 2.0 are Keep; 4.5 is Scale; 1.99 is Cut. Boundary values are where rules usually go wrong: test them.' },
  { id: 'pq2-fn-11', topic: 'pq-functions', type: 'mc', kind: 'scenario', difficulty: 4, concept: 'pq-functions',
    prompt: 'Three suppliers send invoices in three different layouts. What is a good design?',
    options: ['One function per layout, all returning the same columns', 'One huge query full of supplier conditions', 'Copy each file into one layout by hand', 'Three separate reports that never meet'], answer: 0,
    explain: 'Each function hides one supplier\'s quirks and returns a standard table, so the results append cleanly.' },
  { id: 'pq2-fn-12', topic: 'pq-functions', type: 'fill', kind: 'concept', difficulty: 4, concept: 'pq-functions',
    prompt: 'An input written as "optional cost as number" may be left out, and inside the function it is then ____.',
    answer: ['null'], explain: 'Test for it: if cost = null then … else …, so the function works with and without the input.' },
  { id: 'pq2-fn-13', topic: 'pq-functions', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'pq-params',
    prompt: 'Every report should start from the same start date. Parameter or function?',
    options: ['A parameter: it is a single value', 'A function: it is used by several queries', 'A function: dates need code', 'Neither: type the date in each query'], answer: 0,
    explain: 'One value that steps use is a parameter. Functions are for logic you call with different inputs.' },
  { id: 'pq2-fn-14', topic: 'pq-functions', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pq-folder',
    prompt: 'The Combine Files wizard created a query called "Transform File". What is it?',
    options: ['A function that applies the sample steps to one file', 'A copy of the first file in the folder', 'The list of files in the folder', 'A backup of the combined table'], answer: 0,
    explain: 'The combined query calls Transform File for every file. You change it by editing Transform Sample File.' },
  { id: 'pq2-fn-15', topic: 'pq-functions', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pq-folder',
    prompt: 'True or false: editing the Transform Sample File query changes what the Transform File function does.',
    answer: true, explain: 'The function is built from the sample query, so every file gets your new steps on the next refresh.' },
  { id: 'pq2-fn-16', topic: 'pq-functions', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'pq-robust',
    prompt: 'A function works on the sample file but fails on another with "The column Qty was not found", because that file calls it Quantity. What is the best fix inside the function?',
    options: ['Rename "Quantity" to "Qty" with MissingField.Ignore', 'Delete that file from the folder', 'Remove the Qty column everywhere', 'Invoke the function twice'], answer: 0,
    explain: 'The rename runs where Quantity exists and is skipped where the file already says Qty, so both layouts end up the same.' },
  { id: 'pq2-fn-17', topic: 'pq-functions', type: 'number', kind: 'calculation', difficulty: 3, concept: 'reconciliation',
    prompt: 'Four invoice files hold 120, 135, 136 and 136 lines. One file includes a TOTAL row and another one duplicated line. How many lines remain after the function and Remove Duplicates?',
    answer: 525, verify: () => 120 + 135 + 136 + 136 - 1 - 1,
    explain: '527 lines, minus the TOTAL row and the duplicate = 525. Count before and after so you know what was removed.' },
  { id: 'pq2-fn-18', topic: 'pq-functions', type: 'mc', kind: 'scenario', difficulty: 5, concept: 'pq-functions',
    prompt: 'A function looks up a price by reading a 50,000-row table, and it is invoked on 10,000 rows. The refresh takes forever. What helps most?',
    options: ['Merge the price table once instead', 'Invoke the function twice as fast', 'Add more columns to the price table', 'Change the prices to text'], answer: 0,
    explain: 'Reading a big table inside a per-row function repeats the work thousands of times. One merge does the lookup in a single pass.' },
  { id: 'pq2-fn-19', topic: 'pq-functions', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pq-functions',
    prompt: 'True or false: a custom function can call another custom function.',
    answer: true, explain: 'fnCleanInvoice can use fnTidyText, for example. Small functions are easier to test.' },
  { id: 'pq2-fn-20', topic: 'pq-functions', type: 'mc', kind: 'concept', difficulty: 3, concept: 'pq-functions',
    prompt: 'Why give a function\'s inputs a type, such as "price as number"?',
    options: ['Wrong inputs then fail clearly', 'Typed functions load more rows', 'Power Query refuses untyped functions', 'It makes the function private'], answer: 0,
    explain: 'A clear type error at the call is easier to fix than a wrong result three steps later.' },

  // ================================================================ pq-dynamic
  { id: 'pq2-dyn-01', topic: 'pq-dynamic', type: 'mc', kind: 'concept', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'What does Table.ColumnNames(Source) return?',
    options: ['A list of the table\'s column names', 'The number of columns', 'The first row of the table', 'The types of the columns'], answer: 0,
    explain: 'A list you can filter and transform, so steps can work on whatever columns the file has.' },
  { id: 'pq2-dyn-02', topic: 'pq-dynamic', type: 'mc', kind: 'tool-selection', difficulty: 4, concept: 'pq-dynamic',
    prompt: 'Which expression returns the names of all columns that start with "2026"?',
    options: ['List.Select(Table.ColumnNames(t), each Text.StartsWith(_, "2026"))', 'Table.SelectColumns(t, "2026")', 'Text.StartsWith(Table.ColumnNames(t), "2026")', 'List.First(Table.ColumnNames(t))'], answer: 0,
    explain: 'List.Select keeps the names that pass the test. Use the result wherever a step expects a list of columns.' },
  { id: 'pq2-dyn-03', topic: 'pq-dynamic', type: 'fill', kind: 'concept', difficulty: 4, concept: 'pq-dynamic',
    prompt: 'Complete: Table.RenameColumns(t, List.____({Map[OldName], Map[NewName]}), MissingField.Ignore)',
    answer: ['zip'], explain: 'List.Zip pairs the old and new names into {old, new} pairs, the shape RenameColumns needs.' },
  { id: 'pq2-dyn-04', topic: 'pq-dynamic', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'Table.ColumnNames returns {"Region", "2026-01", "2026-02", "2026-03", "Notes"}. How many names does List.Select(…, each Text.StartsWith(_, "2026")) keep?',
    answer: 3, verify: () => ['Region', '2026-01', '2026-02', '2026-03', 'Notes'].filter((c) => c.startsWith('2026')).length,
    explain: 'Only the three month columns start with "2026".' },
  { id: 'pq2-dyn-05', topic: 'pq-dynamic', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'True or false: Unpivot Other Columns is already dynamic, because new month columns are unpivoted automatically.',
    answer: true, explain: 'It names the columns to keep, not the ones to unpivot, so new months are included.' },
  { id: 'pq2-dyn-06', topic: 'pq-dynamic', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'pq-dynamic',
    prompt: 'A mapping table renames "Qty Sold" to "Units", but one file still shows "Qty sold". Why?',
    options: ['Column names are case-sensitive, so it does not match', 'The mapping table is too short', 'Rename steps only work on the sample file', 'MissingField.Ignore blocks the rename'], answer: 0,
    explain: '"Qty sold" and "Qty Sold" are different names. Add the variant to the mapping, or standardise header case first.' },
  { id: 'pq2-dyn-07', topic: 'pq-dynamic', type: 'order', kind: 'sequence', difficulty: 4, concept: 'pq-dynamic',
    prompt: 'Order the steps to type every month column, whatever the months are.',
    options: ['Get the column names with Table.ColumnNames', 'Keep the month names with List.Select', 'Build {name, type} pairs with List.Transform', 'Pass the pairs to Table.TransformColumnTypes'], answer: [0, 1, 2, 3],
    explain: 'Names, then the ones you want, then the pairs, then the typing step.' },
  { id: 'pq2-dyn-08', topic: 'pq-dynamic', type: 'mc', kind: 'scenario', difficulty: 4, concept: 'pq-params',
    prompt: 'A report must show the last 12 months, and a manager must be able to reproduce last month\'s figures exactly. What do you use?',
    options: ['An end-date parameter that defaults to today', 'DateTime.LocalNow() with no way to change it', 'A fixed date typed into the filter', 'A new copy of the query every month'], answer: 0,
    explain: 'The rolling window counts back from the end date. Setting the parameter to a past date recreates an old report.' },
  { id: 'pq2-dyn-09', topic: 'pq-dynamic', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'A filter keeps dates on or after Date.AddMonths(#date(2026, 9, 17), -12). How many days before 17 September 2026 is that date?',
    answer: 365, verify: () => (Date.UTC(2026, 8, 17) - Date.UTC(2025, 8, 17)) / 86400000,
    explain: '12 months back is 17 September 2025; there is no 29 February in between, so it is 365 days.' },
  { id: 'pq2-dyn-10', topic: 'pq-dynamic', type: 'tf', kind: 'debugging', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'True or false: a filter based on DateTime.LocalNow() gives the same result every day.',
    answer: false, explain: 'The window moves with the clock, so figures change daily. Say so on the report, or use a parameter.' },
  { id: 'pq2-dyn-11', topic: 'pq-dynamic', type: 'mc', kind: 'interpretation', difficulty: 4, concept: 'pq-dynamic',
    prompt: 'What does if Table.HasColumns(t, "DistanceMi") then … else … achieve inside a file function?',
    options: ['Each file is handled according to its columns', 'Files without miles are removed', 'Every file is converted to miles', 'The query stops at the first file in miles'], answer: 0,
    explain: 'One function can then convert miles for the depots that report them and keep kilometres for the rest.' },
  { id: 'pq2-dyn-12', topic: 'pq-dynamic', type: 'fill', kind: 'concept', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'The function that returns true when a table has all the named columns is Table.____.',
    answer: ['hascolumns'], explain: 'Table.HasColumns(t, {"A", "B"}) checks several at once.' },
  { id: 'pq2-dyn-13', topic: 'pq-dynamic', type: 'mc', kind: 'concept', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'Why keep column renames in a mapping table instead of in the query code?',
    options: ['New variants can be added without editing M', 'Mapping tables refresh faster than code', 'M cannot rename more than one column', 'Rename steps break every refresh'], answer: 0,
    explain: 'A business user can add "Qty sold → Units" to the table; the query picks it up on the next refresh.' },
  { id: 'pq2-dyn-14', topic: 'pq-dynamic', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'A depot reports 18,500 miles for the quarter. How many kilometres is that, to the nearest km? (1 mile = 1.609344 km)',
    answer: 29773, tolerance: 0.5, verify: () => Math.round(18500 * 1.609344),
    explain: '18,500 × 1.609344 = 29,772.9, so 29,773 km. Convert before adding miles to kilometres.' },
  { id: 'pq2-dyn-15', topic: 'pq-dynamic', type: 'mc', kind: 'tool-selection', difficulty: 4, concept: 'pq-dynamic',
    prompt: 'You need to replace "n/a" with null in every column, whatever columns exist. Which approach?',
    options: ['Table.ReplaceValue(t, "n/a", null, Replacer.ReplaceValue, Table.ColumnNames(t))', 'A Replace Values step recorded on today\'s columns', 'A Conditional Column for each column', 'A filter on every column for "n/a"'], answer: 0,
    explain: 'The last argument is the list of columns to search; Table.ColumnNames supplies whatever columns the table has.' },
  { id: 'pq2-dyn-16', topic: 'pq-dynamic', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'True or false: dynamic code is always better than recorded steps.',
    answer: false, explain: 'It is harder to read. Use it where the source really changes, and keep simple steps elsewhere.' },
  { id: 'pq2-dyn-17', topic: 'pq-dynamic', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'pq-dynamic',
    prompt: 'A rule types every column starting with "2026" as a number. A new column "2026 comments" now shows errors. Why?',
    options: ['The rule also matched the comments column', 'Comments cannot be loaded from CSV', 'The mapping table is out of date', 'Numbers cannot start with 2026'], answer: 0,
    explain: 'A loose rule catches columns you did not mean. Tighten it, for example to names shaped like "2026-01".' },
  { id: 'pq2-dyn-18', topic: 'pq-dynamic', type: 'mc', kind: 'scenario', difficulty: 4, concept: 'pq-robust',
    prompt: 'Regional files share the standard columns, but some add extra ones you do not need, and a few lack Notes. How do you keep exactly the standard columns?',
    options: ['Table.SelectColumns with the standard list and MissingField.UseNull', 'Remove the extra columns by name in each file', 'Keep every column and hide the extras', 'Ask every region to change its export'], answer: 0,
    explain: 'SelectColumns keeps the list you give it; UseNull adds any missing standard column filled with null.' },
  { id: 'pq2-dyn-19', topic: 'pq-dynamic', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pq-dynamic',
    prompt: 'A mapping table has 6 rows. A file has 9 columns, and 4 of them appear as OldName in the mapping. With MissingField.Ignore, how many columns are renamed?',
    answer: 4, verify: () => Math.min(6, 4),
    explain: 'Only names that exist in the file are renamed; the other mapping rows are ignored for this file.' },
  { id: 'pq2-dyn-20', topic: 'pq-dynamic', type: 'mc', kind: 'interpretation', difficulty: 4, concept: 'pq-dynamic',
    prompt: 'What does List.Transform({"Jan", "Feb"}, each {_, type number}) return?',
    options: ['{{"Jan", type number}, {"Feb", type number}}', '{"Jan", "Feb", type number}', 'A table with two number columns', 'The numbers 1 and 2'], answer: 0,
    explain: 'Each name becomes a {name, type} pair: exactly the list Table.TransformColumnTypes expects.' },
];
