// Power Query quiz bank, part A: the Beginner topics (intro, types, cleaning, splitting).
export const PQ_QUIZ_A = [
  // ================================================================ pq-intro
  { id: 'pq2-intro-01', topic: 'pq-intro', type: 'tf', kind: 'concept', difficulty: 1, concept: 'pq-basics',
    prompt: 'True or false: Refresh runs every Applied Step again on the current contents of the source.',
    answer: true, explain: 'That is the whole point: the steps are a recipe, and Refresh cooks it again with whatever the source holds now.' },
  { id: 'pq2-intro-02', topic: 'pq-intro', type: 'fill', kind: 'concept', difficulty: 1, concept: 'pq-basics',
    prompt: 'The pane on the right of the editor that lists every transformation in order is called ____ Steps.',
    answer: ['applied'], explain: 'Applied Steps: click a step to see the data at that point, rename it, or delete it to undo it.' },
  { id: 'pq2-intro-03', topic: 'pq-intro', type: 'mc', kind: 'scenario', difficulty: 1, concept: 'pq-basics',
    prompt: 'Finance sends this month\'s version of a file your query already uses, with the same name. How do you update the report?',
    options: ['Save it over the old file in the same place, then Refresh', 'Build a new query for the new file', 'Copy the new rows into the loaded table', 'Delete the query and import the file again'], answer: 0,
    explain: 'The query remembers the file path. Replace the file in the same place and Refresh: every step runs on the new data.' },
  { id: 'pq2-intro-04', topic: 'pq-intro', type: 'tf', kind: 'concept', difficulty: 1, concept: 'pq-basics',
    prompt: 'True or false: you can rename a step in Applied Steps so it says what it does.',
    answer: true, explain: 'Right-click → Rename. "Removed title rows" is far easier to follow next month than "Removed Top Rows1".' },
  { id: 'pq2-intro-05', topic: 'pq-intro', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pq-basics',
    prompt: 'Cleaning a weekly file by hand takes 50 minutes. Building a query takes 200 minutes once, after which each week takes 5 minutes. From which week onwards has the query saved time overall?',
    answer: 5, verify: () => Math.ceil(200 / (50 - 5)),
    explain: 'Each week saves 45 minutes. 200 ÷ 45 ≈ 4.4, so by the end of week 5 the saving (225 minutes) is bigger than the build time.' },
  { id: 'pq2-intro-06', topic: 'pq-intro', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pq-basics',
    prompt: 'The editor says "Column profiling based on top 1000 rows". What does that mean for the column quality percentages?',
    options: ['They describe only the first 1,000 rows', 'They describe the whole file', 'The file has exactly 1,000 rows', 'Only 1,000 rows will be loaded'], answer: 0,
    explain: 'Profiling looks at a sample by default. Click the message and choose "entire data set" before trusting the percentages.' },

  // ================================================================ pq-types
  { id: 'pq2-types-01', topic: 'pq-types', type: 'order', kind: 'sequence', difficulty: 2, concept: 'pq-types',
    prompt: 'Put these first steps for a messy CSV import in a sensible order.',
    options: ['Look at the raw preview', 'Remove the title rows', 'Promote the header row', 'Set the data type of each column'], answer: [0, 1, 2, 3],
    explain: 'You can only name and type columns once the real header row is at the top, and you only know what to remove after looking.' },
  { id: 'pq2-types-02', topic: 'pq-types', type: 'mc', kind: 'concept', difficulty: 1, concept: 'pq-types',
    prompt: 'A column header shows the icon "ABC/123". What does it mean?',
    options: ['Its type is Any: not decided yet', 'It holds text and numbers in separate rows', 'It is a text column of product codes', 'It is a whole number column'], answer: 0,
    explain: 'Any means Power Query has not set a type. Sums, date filters and merges may behave unexpectedly until you choose one.' },
  { id: 'pq2-types-03', topic: 'pq-types', type: 'number', kind: 'calculation', difficulty: 1, concept: 'pq-types',
    prompt: 'A column has 1,000 rows. Column quality shows 97% valid, 2% error and 1% empty. How many rows are errors?',
    answer: 20, verify: () => 1000 * 0.02,
    explain: '2% of 1,000 = 20 rows. Click an error cell to see why the conversion failed before removing anything.' },
  { id: 'pq2-types-04', topic: 'pq-types', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'locale',
    prompt: 'A monthly chart shows sales only on days 1 to 12 of each month and nothing from the 13th. What most likely happened?',
    options: ['Day-first dates were read month-first', 'The shop closes after the 12th', 'The chart only shows 12 points', 'The file was cut off at row 12'], answer: 0,
    explain: 'Read month-first, 13/07 is not a valid date, so those rows became errors and were dropped, while days 1 to 12 landed in the wrong months.' },
  { id: 'pq2-types-05', topic: 'pq-types', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-types',
    prompt: 'True or false: changing a column with the value 2.7 to Whole Number gives 3.',
    answer: true, explain: 'Whole Number rounds without warning. Use Decimal Number for prices and quantities that can have decimals.' },
  { id: 'pq2-types-06', topic: 'pq-types', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'locale',
    prompt: 'Your query gives correct dates on your PC, but a colleague abroad gets wrong dates from the same file. Why?',
    options: ['The type step used each PC\'s regional settings', 'Their copy of the file is corrupted', 'Power Query versions cannot share queries', 'Dates can only be read on one computer'], answer: 0,
    explain: 'A plain Change Type follows the computer\'s settings. Using Locale fixes the source format, so the query reads the file the same way everywhere.' },
  { id: 'pq2-types-07', topic: 'pq-types', type: 'fill', kind: 'concept', difficulty: 1, concept: 'locale',
    prompt: 'Change Type → Using ____ lets you say which country\'s date and number format the source file uses.',
    answer: ['locale'], explain: 'Using Locale: for example Date with English (United Kingdom) for day-first dates.' },

  // ================================================================ pq-clean
  { id: 'pq2-clean-01', topic: 'pq-clean', type: 'order', kind: 'sequence', difficulty: 2, concept: 'pq-clean',
    prompt: 'Order these steps for cleaning a contact export.',
    options: ['Remove blank rows', 'Trim and fix the case of text columns', 'Replace placeholders such as N/A with null', 'Remove duplicates on the customer key'], answer: [0, 1, 2, 3],
    explain: 'Trim before replacing, so " N/A " matches "N/A"; remove duplicates last, once equal records look equal.' },
  { id: 'pq2-clean-02', topic: 'pq-clean', type: 'number', kind: 'calculation', difficulty: 1, concept: 'duplicates',
    prompt: 'A file has 239 rows. 3 are completely blank and 6 are exact copies of other rows. How many rows are left after removing both?',
    answer: 230, verify: () => 239 - 3 - 6,
    explain: '239 − 3 − 6 = 230. Write down the count after each step: it proves nothing else disappeared.' },
  { id: 'pq2-clean-03', topic: 'pq-clean', type: 'fill', kind: 'concept', difficulty: 1, concept: 'pq-clean',
    prompt: 'Transform → Fill → ____ copies the value above into the empty cells below it.',
    answer: ['down'], explain: 'Fill Down repairs report exports that show a group name only on the first row of each block.' },
  { id: 'pq2-clean-04', topic: 'pq-clean', type: 'tf', kind: 'concept', difficulty: 1, concept: 'pq-clean',
    prompt: 'True or false: Remove Blank Rows only removes rows where every column is empty.',
    answer: true, explain: 'A row with one value somewhere stays. Filter a key column for null if you also want to drop partly empty rows.' },
  { id: 'pq2-clean-05', topic: 'pq-clean', type: 'tf', kind: 'concept', difficulty: 1, concept: 'pq-clean',
    prompt: 'True or false: Replace Values only changes the columns you selected.',
    answer: true, explain: 'Select the right columns first: replacing "0" everywhere could damage prices, phone numbers and codes.' },
  { id: 'pq2-clean-06', topic: 'pq-clean', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pq-clean',
    prompt: 'After replacing "N/A" with null, some "n/a" values are still there. Why?',
    options: ['Replace Values is case-sensitive', 'Nulls cannot be used in text columns', 'Replace only works on the first match', 'The column must be sorted first'], answer: 0,
    explain: 'Replace Values matches exact text, capitals included. Lowercase the column first, or add a second replacement.' },
  { id: 'pq2-clean-07', topic: 'pq-clean', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'missing-data',
    prompt: 'Column quality for Email shows Valid 88%, Error 0%, Empty 12%. What does "Empty" count?',
    options: ['Null and blank cells', 'Cells with an invalid email', 'Rows that failed to load', 'Emails longer than the column'], answer: 0,
    explain: 'Empty covers null and empty text. Invalid addresses such as "N/A" count as valid text until you replace them.' },
  { id: 'pq2-clean-08', topic: 'pq-clean', type: 'number', kind: 'calculation', difficulty: 1, concept: 'missing-data',
    prompt: 'A column has 480 rows and column quality shows 12.5% empty. How many rows have no value?',
    answer: 60, verify: () => 480 * 0.125,
    explain: '12.5% of 480 = 60 rows. Decide what they mean (unknown, zero, not applicable) before filling or removing them.' },
  { id: 'pq2-clean-09', topic: 'pq-clean', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pq-clean',
    prompt: 'Finance confirms that a missing discount means no discount. The Discount column has nulls. What do you do?',
    options: ['Replace null with 0 in Discount only', 'Remove every row with a null discount', 'Replace null with 0 in all columns', 'Leave the nulls and ignore them'], answer: 0,
    explain: 'The business rule says null means zero here, so replace it in that column. Removing rows would drop real sales.' },
  { id: 'pq2-clean-10', topic: 'pq-clean', type: 'fill', kind: 'concept', difficulty: 1, concept: 'pq-clean',
    prompt: 'The Format option that removes spaces at the start and end of a text value is called ____.',
    answer: ['trim'], explain: 'Trim removes leading and trailing spaces (not double spaces in the middle).' },
  { id: 'pq2-clean-11', topic: 'pq-clean', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pq-clean',
    prompt: 'Some text values contain hidden line breaks from the export. Which step removes them?',
    options: ['Format → Clean', 'Format → Trim', 'Format → Uppercase', 'Remove Rows → Remove Errors'], answer: 0,
    explain: 'Clean removes non-printing characters such as line breaks; Trim only handles spaces at the ends.' },
  { id: 'pq2-clean-12', topic: 'pq-clean', type: 'tf', kind: 'concept', difficulty: 2, concept: 'duplicates',
    prompt: 'True or false: Keep Rows → Keep Duplicates shows which rows are duplicated before you remove them.',
    answer: true, explain: 'Look before deleting: the duplicates may be real repeat orders rather than export mistakes.' },

  // ================================================================ pq-split
  { id: 'pq2-split-01', topic: 'pq-split', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'pq-split',
    prompt: 'You split "Chen, Anna" by "," only. The First Name column now starts with a space. What is the fix?',
    options: ['Split by ", " instead, or Trim the new column', 'Split by number of characters', 'Change the column to Whole Number', 'Merge the columns back together'], answer: 0,
    explain: 'The space after the comma stays with the second part. Include it in the delimiter, or trim afterwards.' },
  { id: 'pq2-split-02', topic: 'pq-split', type: 'order', kind: 'sequence', difficulty: 2, concept: 'pq-split',
    prompt: 'Order the steps to build a key such as "S01-2026-07" from a store code and a date.',
    options: ['Trim the store code and put it in capitals', 'Add a Month column as text (yyyy-MM)', 'Select the store code, then the Month column', 'Merge Columns with "-" as separator'], answer: [0, 1, 2, 3],
    explain: 'Clean the parts first, then select them in the order you want them joined, then merge.' },
  { id: 'pq2-split-03', topic: 'pq-split', type: 'number', kind: 'calculation', difficulty: 1, concept: 'pq-split',
    prompt: 'A column holds "2026|Q3|Marlow|HC|R2". You split it by "|" at each occurrence. How many columns come out?',
    answer: 5, verify: () => '2026|Q3|Marlow|HC|R2'.split('|').length,
    explain: 'Four delimiters make five pieces, so five columns. Rename them straight away.' },
  { id: 'pq2-split-04', topic: 'pq-split', type: 'fill', kind: 'concept', difficulty: 1, concept: 'pq-split',
    prompt: 'Add Column → Extract → Text ____ Delimiter returns the part in front of the delimiter.',
    answer: ['before'], explain: 'Text Before Delimiter; its partners are Text After Delimiter and Text Between Delimiters.' },
  { id: 'pq2-split-05', topic: 'pq-split', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-split',
    prompt: 'True or false: Split Column → By Delimiter can split into rows instead of columns.',
    answer: true, explain: 'Under Advanced options, choose Rows: "red;blue" becomes two rows. Useful for tags or lists in one cell.' },
  { id: 'pq2-split-06', topic: 'pq-split', type: 'mc', kind: 'tool-selection', difficulty: 1, concept: 'pq-split',
    prompt: 'Emails look like "irene.sato@mail.example". You want the domain. Which step?',
    options: ['Extract → Text After Delimiter "@"', 'Extract → First Characters (10)', 'Split Column → By Positions', 'Replace Values "@" with nothing'], answer: 0,
    explain: 'The domain is everything after "@", whatever the length of the name in front.' },
  { id: 'pq2-split-07', topic: 'pq-split', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pq-split',
    prompt: 'A Quantity column holds values such as "12 kg", "3 each" and "0.5 l". You need a number and a unit. What do you do?',
    options: ['Split at the left-most space and type the first part as a number', 'Change the whole column to Decimal Number', 'Split by number of characters (2)', 'Replace every letter with nothing'], answer: 0,
    explain: 'The space separates the number from the unit. Changing the type directly would turn every value into an error.' },
  { id: 'pq2-split-08', topic: 'pq-split', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-split',
    prompt: 'True or false: Transform → Merge Columns replaces the original columns, while Add Column → Merge Columns keeps them.',
    answer: true, explain: 'The same choice exists for Extract. Keep the originals while you are still checking the result.' },
  { id: 'pq2-split-09', topic: 'pq-split', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pq-types',
    prompt: 'After a split, Power Query added a Changed Type step that turned the code "0042" into 42. Why does it matter?',
    options: ['Codes lose leading zeros and stop matching other tables', 'The column becomes too wide to display', 'Numbers load more slowly than text', 'It does not matter at all'], answer: 0,
    explain: 'Codes are labels. Delete that automatic step, or set the column back to Text, before merging with another table.' },
  { id: 'pq2-split-10', topic: 'pq-split', type: 'tf', kind: 'debugging', difficulty: 1, concept: 'pq-split',
    prompt: 'True or false: Split Column → By Number of Characters works well for names such as "Chen, Anna" and "Wright, Jamal".',
    answer: false, explain: 'Last names have different lengths, so a fixed position cuts names in the wrong place. Split by the delimiter.' },
];
