// Power Query quiz bank, part B: the Intermediate topics (append, merge, reshape, custom columns).
export const PQ_QUIZ_B = [
  // ================================================================ pq-append
  { id: 'pq2-app-01', topic: 'pq-append', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pq-append',
    prompt: 'Three monthly files hold 388, 400 and 395 data rows. How many rows should the combined table have?',
    answer: 1183, verify: () => 388 + 400 + 395,
    explain: '388 + 400 + 395 = 1,183. Write the expected count down before combining, then check the result against it.' },
  { id: 'pq2-app-02', topic: 'pq-append', type: 'order', kind: 'sequence', difficulty: 2, concept: 'pq-folder',
    prompt: 'Order the steps of a folder import.',
    options: ['Get Data → From Folder', 'Filter the file list to the export files', 'Combine Files', 'Clean the data in Transform Sample File'], answer: [0, 1, 2, 3],
    explain: 'Choose the folder, keep only the right files, combine, then put the cleaning in the sample transformation so every file gets it.' },
  { id: 'pq2-app-03', topic: 'pq-append', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-append',
    prompt: 'True or false: Append Queries can stack three or more tables in one step.',
    answer: true, explain: 'Choose "Three or more tables" in the Append dialog and add them all to the list.' },
  { id: 'pq2-app-04', topic: 'pq-append', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pq-folder',
    prompt: 'After Combine Files, the column that holds each row\'s file name is called Source.____.',
    answer: ['name'], explain: 'Source.Name tells you which file a row came from, and it often carries a month or depot code you can extract.' },
  { id: 'pq2-app-05', topic: 'pq-append', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pq-folder',
    prompt: 'A check grouped by Source.Name shows one monthly file with 0 rows after combining. What does it tell you?',
    options: ['A step removed all of that file\'s rows', 'That month had no sales at all', 'The file was combined twice', 'Folder imports skip one file'], answer: 0,
    explain: 'A different layout (title lines, a renamed column) can make a filter or header step throw that file\'s rows away. Look at it before reporting a zero month.' },
  { id: 'pq2-app-06', topic: 'pq-append', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pq-append',
    prompt: 'Two regions send the same monthly layout, but one writes amounts in thousands of dollars. What must happen before appending?',
    options: ['Convert one region\'s amounts to the same unit', 'Nothing: Append fixes the units', 'Sort both files by amount', 'Rename the amount column in one file'], answer: 0,
    explain: 'Append stacks values as they are. Mixed units give totals that look plausible and are wrong.' },
  { id: 'pq2-app-07', topic: 'pq-append', type: 'tf', kind: 'concept', difficulty: 3, concept: 'pq-folder',
    prompt: 'True or false: a From Folder query also reads files in subfolders unless you filter them out.',
    answer: true, explain: 'The file list includes subfolders. An "archive" subfolder would be combined too, doubling old months.' },
  { id: 'pq2-app-08', topic: 'pq-append', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pq-clean',
    prompt: 'August\'s data rows add up to NetSales 59,971.55, and the file ends with a TOTAL row showing the same amount. If the TOTAL row is not removed, what will August\'s total be?',
    answer: 119943.1, tolerance: 0.01, verify: () => Math.round(59971.55 * 2 * 100) / 100,
    explain: 'The total counts itself: 59,971.55 × 2 = 119,943.10. Filter summary rows out in the sample transformation.' },
  { id: 'pq2-app-09', topic: 'pq-append', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pq-folder',
    prompt: 'After a folder combine, one file\'s rows show the text "Date", "StoreCode", "Units" as values. Why?',
    options: ['That file has title lines, so the wrong row was promoted', 'Its headers are written in capitals', 'That file uses a different delimiter', 'Headers are always repeated once per file'], answer: 0,
    explain: 'The sample file promoted its first row. In a file with title lines, the real header ends up as data. Skip rows until the header instead.' },

  // ================================================================ pq-merge
  { id: 'pq2-mrg-01', topic: 'pq-merge', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pq-merge',
    prompt: 'Orders has 5,000 rows. In the Customers table, 12 customer IDs appear twice, and those 12 customers have 300 orders. How many rows are there after a Left Outer merge and expand?',
    answer: 5300, verify: () => 5000 + 300,
    explain: 'Each of the 300 orders matches two customer rows, so it appears twice: 5,000 + 300 = 5,300. Remove duplicate keys in the lookup first.' },
  { id: 'pq2-mrg-02', topic: 'pq-merge', type: 'order', kind: 'sequence', difficulty: 2, concept: 'pq-merge',
    prompt: 'Order the steps of a careful merge.',
    options: ['Clean the key columns in both tables', 'Merge Queries and pick the key in each table', 'Read the match count in the dialog', 'Expand only the columns you need'], answer: [0, 1, 2, 3],
    explain: 'Clean keys match; the match count tells you how many do; expanding only what you need keeps the table readable.' },
  { id: 'pq2-mrg-03', topic: 'pq-merge', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pq-merge',
    prompt: 'With fuzzy matching on, "Riverside Cafe" was matched with "Riverside Cafe Airport". What should you change?',
    options: ['Raise the similarity threshold', 'Switch to a Left Anti merge', 'Change the key to Whole Number', 'Remove the Riverside rows'], answer: 0,
    explain: 'A low threshold accepts weak matches. Raise it, or add a transformation table that maps the known variants.' },
  { id: 'pq2-mrg-04', topic: 'pq-merge', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'pq-merge',
    prompt: 'The merge dialog says "The selection matches 1,150 of 1,183 rows from the first table." What do you do next?',
    options: ['Find the unmatched rows and see why', 'Carry on: 97% is close enough', 'Switch to an Inner merge', 'Delete the lookup and try again'], answer: 0,
    explain: 'The missing 33 are often a case, space or type problem. A Left Anti merge lists them.' },
  { id: 'pq2-mrg-05', topic: 'pq-merge', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pq-merge',
    prompt: 'The dialog says 1,150 of 1,183 rows match. After a Left Outer merge, how many rows have null in the expanded columns?',
    answer: 33, verify: () => 1183 - 1150,
    explain: '1,183 − 1,150 = 33 rows keep their place but get no looked-up values.' },
  { id: 'pq2-mrg-06', topic: 'pq-merge', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-merge',
    prompt: 'True or false: a Right Anti merge returns the rows of the second table that have no match in the first.',
    answer: true, explain: 'Right Anti answers "what is in the lookup that nobody used?", for example products never ordered.' },
  { id: 'pq2-mrg-07', topic: 'pq-merge', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pq-merge',
    prompt: 'The join kind that keeps only the rows with a match in both tables is called ____.',
    answer: ['inner', 'inner join'], explain: 'Inner keeps matches only, so unmatched rows disappear. Check the row count when you use it.' },
  { id: 'pq2-mrg-08', topic: 'pq-merge', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'pq-merge',
    prompt: 'You compare this month\'s and last month\'s price lists and want every product that appears in either. Which join kind?',
    options: ['Full Outer', 'Inner', 'Left Anti', 'Left Outer'], answer: 0,
    explain: 'Full Outer keeps both sides, so new, dropped and unchanged products all appear, with nulls where a month is missing.' },
  { id: 'pq2-mrg-09', topic: 'pq-merge', type: 'tf', kind: 'debugging', difficulty: 2, concept: 'pq-merge',
    prompt: 'True or false: a merge on a text key ignores spaces at the end of the values.',
    answer: false, explain: '"W02 " and "W02" are different values. Trim both keys before merging.' },
  { id: 'pq2-mrg-10', topic: 'pq-merge', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'duplicates',
    prompt: 'Another team maintains a lookup table that sometimes contains duplicate keys. How do you protect your merge?',
    options: ['Remove duplicates on the key before merging', 'Use fuzzy matching instead', 'Sort the lookup by key', 'Merge twice and compare'], answer: 0,
    explain: 'Duplicate keys multiply your rows. Deduplicate the lookup (and report the duplicates to the owner).' },
  { id: 'pq2-mrg-11', topic: 'pq-merge', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-merge',
    prompt: 'True or false: Merge Queries as New leaves both original queries unchanged.',
    answer: true, explain: 'It creates a third query. Plain Merge Queries adds the step to the query you started from.' },

  // ================================================================ pq-reshape
  { id: 'pq2-rsh-01', topic: 'pq-reshape', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pq-unpivot',
    prompt: 'A targets table has 15 stores and 3 month columns, and 2 of the target cells are empty. How many rows does Unpivot Other Columns produce?',
    answer: 43, verify: () => 15 * 3 - 2,
    explain: '15 × 3 = 45 cells, minus the 2 empty ones that Unpivot skips = 43 rows.' },
  { id: 'pq2-rsh-02', topic: 'pq-reshape', type: 'order', kind: 'sequence', difficulty: 2, concept: 'pq-unpivot',
    prompt: 'Order the steps to turn a wide budget sheet into a long table.',
    options: ['Remove title rows and promote headers', 'Select the identifier columns', 'Unpivot Other Columns', 'Rename Attribute and Value'], answer: [0, 1, 2, 3],
    explain: 'Get a clean header, choose what identifies a row, unpivot the rest, then give the new columns meaningful names.' },
  { id: 'pq2-rsh-03', topic: 'pq-reshape', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pq-group',
    prompt: 'After Group By Region with "Count Rows", the North row shows 1,240. What is that number?',
    options: ['North\'s rows in the table before grouping', 'The number of North customers', 'North\'s total sales', 'The number of regions'], answer: 0,
    explain: 'Count Rows counts rows. If a row is an order line, it is a count of lines, not of orders or customers.' },
  { id: 'pq2-rsh-04', topic: 'pq-reshape', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pq-group',
    prompt: 'Group By Store gives Sum of Sales 48,000 and Count Rows 1,600 for one store. What is its average sale per row?',
    answer: 30, verify: () => 48000 / 1600,
    explain: '48,000 ÷ 1,600 = 30. Adding both aggregations in one Group By lets you build averages from totals.' },
  { id: 'pq2-rsh-05', topic: 'pq-reshape', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-unpivot',
    prompt: 'True or false: Unpivot leaves out cells that are empty (null).',
    answer: true, explain: 'Handy for sparse sheets, but a missing survey or target then leaves no row at all. Count before and after.' },
  { id: 'pq2-rsh-06', topic: 'pq-reshape', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pq-unpivot',
    prompt: 'The operation that turns the values of a Month column into separate columns is called ____ Column.',
    answer: ['pivot'], explain: 'Pivot Column goes from long to wide, the opposite of Unpivot.' },
  { id: 'pq2-rsh-07', topic: 'pq-reshape', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'pq-unpivot',
    prompt: 'You pivot a Status column whose values are text, and you just want them spread across columns. Which aggregation option?',
    options: ['Don\'t Aggregate', 'Sum', 'Count (All)', 'Average'], answer: 0,
    explain: 'Under Advanced options, Don\'t Aggregate places each value as it is. It fails if a row and column pair has more than one value.' },
  { id: 'pq2-rsh-08', topic: 'pq-reshape', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pq-unpivot',
    prompt: 'Targets are wide (one column per month) and sales are long. You need attainment by store and month. What is the plan?',
    options: ['Unpivot the targets, then merge on store and month', 'Pivot the sales, then append the targets', 'Append the targets under the sales rows', 'Group the targets by month only'], answer: 0,
    explain: 'Put both in the same long shape, then merge on the two-column key and divide.' },
  { id: 'pq2-rsh-09', topic: 'pq-reshape', type: 'tf', kind: 'debugging', difficulty: 3, concept: 'pq-group',
    prompt: 'True or false: Group By Region with Average of a margin % column gives each region\'s true overall margin.',
    answer: false, explain: 'An average of rates weights every row equally. Sum profit and revenue in the Group By, then divide.' },
  { id: 'pq2-rsh-10', topic: 'pq-reshape', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pq-unpivot',
    prompt: 'After unpivoting, the Month column holds "Jan", "Feb" and so on, and a chart sorts them alphabetically. What is the fix?',
    options: ['Turn the month into a real date and sort by it', 'Rename the months with capital letters', 'Pivot the months back into columns', 'Sort the rows in Power Query only'], answer: 0,
    explain: 'Text months sort as text. A real date (or a month number to sort by) keeps the calendar order everywhere.' },
  { id: 'pq2-rsh-11', topic: 'pq-reshape', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pq-group',
    prompt: 'In Group By, the Advanced option lets you group by several columns and add more than one ____.',
    answer: ['aggregation', 'aggregations'], explain: 'For example Sum of Sales, Count Rows and Max of Date in one step.' },

  // ================================================================ pq-custom
  { id: 'pq2-cus-01', topic: 'pq-custom', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pq-custom',
    prompt: 'A Custom Column is [Units] * [UnitPrice] * (1 - [Discount]). What does it return for Units 3, UnitPrice 40 and Discount 0.15?',
    answer: 102, tolerance: 0.001, verify: () => 3 * 40 * (1 - 0.15),
    explain: '3 × 40 = 120, and 120 × 0.85 = 102. The discount is stored as a fraction, so 1 − 0.15 keeps 85%.' },
  { id: 'pq2-cus-02', topic: 'pq-custom', type: 'fill', kind: 'concept', difficulty: 3, concept: 'm-code',
    prompt: 'Complete the weekend test so Saturday and Sunday give true: Date.DayOfWeek([Date], Day.____) >= 5',
    answer: ['monday'], explain: 'With Monday as day 0, Saturday is 5 and Sunday is 6, whatever the computer\'s regional settings.' },
  { id: 'pq2-cus-03', topic: 'pq-custom', type: 'order', kind: 'sequence', difficulty: 3, concept: 'pq-custom',
    prompt: 'Order the steps to add a margin % column safely.',
    options: ['Make sure Revenue and Cost are numbers', 'Add a Custom Column for Revenue minus Cost', 'Divide it by Revenue, with try … otherwise null', 'Set the new column\'s type to Percentage'], answer: [0, 1, 2, 3],
    explain: 'Types first, then the calculation, a guard for zero revenue, and a type on the result so it loads correctly.' },
  { id: 'pq2-cus-04', topic: 'pq-custom', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pq-custom',
    prompt: 'A Conditional Column has two rules (NetSales > 1000 → Big, NetSales ≤ 1000 → Small) and an empty Else. Some rows show null. Why?',
    options: ['Their NetSales is null, so they reach the empty Else', 'Conditional Columns skip every tenth row', 'The rules are in the wrong order', 'The column type is Percentage'], answer: 0,
    explain: 'A comparison with null is never true, so those rows fall through. Give Else a value such as "Unknown", or deal with nulls first.' },
  { id: 'pq2-cus-05', topic: 'pq-custom', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pq-params',
    prompt: 'True or false: a parameter can be used inside a Custom Column formula.',
    answer: true, explain: 'For example [Discount] > DiscountLimit * [Gross]. Change the parameter, and the column follows.' },
  { id: 'pq2-cus-06', topic: 'pq-custom', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'm-code',
    prompt: 'You need labels "Q1" to "Q4" from a date column. Which is the cleanest way?',
    options: ['"Q" & Text.From(Date.QuarterOfYear([Date]))', 'A Conditional Column with twelve month rules', 'Split the date by "/" and divide by 3', 'Group By the date column'], answer: 0,
    explain: 'Date.QuarterOfYear returns 1 to 4; Text.From turns it into text so & can join it to "Q".' },
  { id: 'pq2-cus-07', topic: 'pq-custom', type: 'tf', kind: 'debugging', difficulty: 3, concept: 'm-code',
    prompt: 'True or false: in a Custom Column, "Q" + Text.From(3) joins the two pieces of text.',
    answer: false, explain: 'M joins text with &. The + operator is for numbers and gives an error with text.' },
  { id: 'pq2-cus-08', topic: 'pq-custom', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pq-custom',
    prompt: 'A Custom Column is Number.Round([Revenue] / [Orders], 2). What does it return for Revenue 4,571 and Orders 24?',
    answer: 190.46, tolerance: 0.001, verify: () => Math.round((4571 / 24) * 100) / 100,
    explain: '4,571 ÷ 24 = 190.458…, rounded to two decimals = 190.46.' },
  { id: 'pq2-cus-09', topic: 'pq-custom', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pq-params',
    prompt: 'The "deep discount" threshold changes every quarter (10% now, 12% next). How do you keep the query easy to update?',
    options: ['Store the threshold in a parameter', 'Duplicate the query each quarter', 'Type the new value into every row', 'Ask users to filter the report by hand'], answer: 0,
    explain: 'A parameter keeps the rule in one visible place, and the Custom Column refers to it by name.' },
];
