// SQL quiz bank, part D: dates, window functions, cohorts and business queries.
const NET = 'oi.quantity * oi.unit_price * (1 - oi.discount_pct)';

export const SQL_QUIZ_D = [
  // ================================================================ sql-dates
  { id: 'sq2-dt-01', topic: 'sql-dates', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'sql-dates',
    prompt: 'For **completed** orders dated in **2026**, count orders per **weekday number** (strftime(\'%w\'), where 0 = Sunday). Return the weekday number and the count.',
    answer: "SELECT strftime('%w', order_date) AS weekday, COUNT(*) FROM orders WHERE status = 'completed' AND order_date >= '2026-01-01' GROUP BY weekday;",
    explain: 'strftime(\'%w\') turns a date into 0 to 6. Tuesday (2) is the busiest day and Monday (1) the quietest, but the spread is small.' },
  { id: 'sq2-dt-02', topic: 'sql-dates', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'sql-dates', ordered: true,
    prompt: 'Restaurant database: net sales (2 decimals) per **month** (YYYY-MM) for the **Airport** (restaurant_id 3) in **2026**, oldest month first.',
    answer: "SELECT strftime('%Y-%m', sale_date) AS month, ROUND(SUM(net_sales), 2) FROM daily_sales WHERE restaurant_id = 3 AND sale_date >= '2026-01-01' GROUP BY month ORDER BY month;",
    traps: [{ sql: "SELECT strftime('%m', sale_date) AS month, ROUND(SUM(net_sales), 2) FROM daily_sales WHERE restaurant_id = 3 GROUP BY month ORDER BY month;", feedback: 'Grouping by month number alone mixes 2025 and 2026. Filter 2026 and group by year and month.' }],
    explain: 'The Airport grew steadily through 2026, peaking in July at about 130,809.' },
  { id: 'sq2-dt-03', topic: 'sql-dates', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'sql-dates',
    prompt: 'HR database: the **average tenure in years** of current employees on **2026-08-31**, to 1 decimal. Tenure = (julianday(\'2026-08-31\') − julianday(hire_date)) ÷ 365.25.',
    answer: "SELECT ROUND(AVG((julianday('2026-08-31') - julianday(hire_date)) / 365.25), 1) FROM employees WHERE termination_date IS NULL;",
    explain: 'julianday turns dates into day numbers you can subtract. Current staff have been with the company for about 5 years on average.' },
  { id: 'sq2-dt-04', topic: 'sql-dates', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'sql-dates',
    prompt: 'How many returns happened **within 7 days** of the order date (return_date − order_date ≤ 7 days)? Return one number.',
    answer: 'SELECT COUNT(*) FROM returns r JOIN order_items oi ON oi.order_item_id = r.order_item_id JOIN orders o ON o.order_id = oi.order_id WHERE julianday(r.return_date) - julianday(o.order_date) <= 7;',
    traps: [{ sql: 'SELECT COUNT(*) FROM returns r JOIN order_items oi ON oi.order_item_id = r.order_item_id JOIN orders o ON o.order_id = oi.order_id WHERE julianday(r.return_date) - julianday(o.order_date) < 7;', feedback: 'The question includes exactly 7 days: use <= 7.' }],
    explain: '230 returns came back within a week, the window in which "changed mind" returns usually happen.' },
  { id: 'sq2-dt-05', topic: 'sql-dates', type: 'number', kind: 'calculation', difficulty: 2, concept: 'sql-dates',
    prompt: 'What does `julianday(\'2026-03-10\') - julianday(\'2026-02-26\')` return? (2026 is not a leap year.)',
    answer: 12, verify: () => (Date.UTC(2026, 2, 10) - Date.UTC(2026, 1, 26)) / 86400000,
    explain: 'Two days are left in February after the 26th, plus 10 in March: 12 days.' },
  { id: 'sq2-dt-06', topic: 'sql-dates', type: 'number', kind: 'calculation', difficulty: 3, concept: 'sql-dates',
    prompt: 'SQLite\'s `date(\'2026-01-31\', \'+1 month\')` rolls over the short February. Which day of **March** does it return?',
    answer: 3, verify: () => new Date(Date.UTC(2026, 1, 31)).getUTCDate(),
    explain: 'It makes "31 February", which rolls on to 3 March. For month ends, use date(d, \'start of month\', \'+2 months\', \'-1 day\') instead.' },
  { id: 'sq2-dt-07', topic: 'sql-dates', type: 'tf', kind: 'debugging', difficulty: 2, concept: 'sql-dates',
    prompt: 'True or false: strftime(\'%Y\', order_date) returns text, so compare it with \'2026\', not with the number 2026.',
    answer: true, explain: 'In SQLite, \'2026\' = 2026 can be false, because text and numbers are different types. Quote the year, or use a date range.' },
  { id: 'sq2-dt-08', topic: 'sql-dates', type: 'order', kind: 'sequence', difficulty: 2, concept: 'sql-dates',
    prompt: 'Order the steps of a monthly trend query in SQLite.',
    options: ['Filter the date range with >= and <', 'Build the month key with strftime(\'%Y-%m\', …)', 'GROUP BY the month key', 'ORDER BY the month key'], answer: [0, 1, 2, 3],
    explain: 'A range filter can use an index; a year-month key keeps different years apart and sorts correctly as text.' },
  { id: 'sq2-dt-09', topic: 'sql-dates', type: 'fill', kind: 'concept', difficulty: 2, concept: 'sql-dates',
    prompt: 'In SQLite, the function that turns a date into a day number, so two dates can be subtracted, is ____.',
    answer: ['julianday', 'JULIANDAY'], explain: 'julianday(end) − julianday(start) gives the days between two dates (with decimals if times are included).' },

  // ================================================================ sql-window-rank
  { id: 'sq2-wr-01', topic: 'sql-window-rank', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 4, concept: 'top-n-group',
    prompt: `For **completed 2025** orders, return the **top-selling product in each category** by net revenue (${NET}): category, product_name and revenue (2 decimals).`,
    answer: `WITH rev AS (SELECT p.category, p.product_name, SUM(${NET}) AS revenue FROM order_items oi JOIN orders o ON o.order_id = oi.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' AND o.order_date BETWEEN '2025-01-01' AND '2025-12-31' GROUP BY p.category, p.product_name), ranked AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) AS rn FROM rev) SELECT category, product_name, ROUND(revenue, 2) FROM ranked WHERE rn = 1;`,
    traps: [{ sql: `SELECT p.category, p.product_name, ROUND(SUM(${NET}), 2) AS revenue FROM order_items oi JOIN orders o ON o.order_id = oi.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' AND o.order_date BETWEEN '2025-01-01' AND '2025-12-31' GROUP BY p.category, p.product_name ORDER BY revenue DESC LIMIT 7;`, feedback: 'LIMIT takes the top 7 overall, so a strong category can take several places. Number the products within each category instead.' }],
    explain: 'Aggregate, number within each category, then keep number 1. In Footwear and Sleeping Gear the leader is only just ahead: check the runner-up before calling it a winner.' },
  { id: 'sq2-wr-02', topic: 'sql-window-rank', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'window-rank',
    prompt: 'HR database: for **current employees**, return department_id, the **headcount** and its **DENSE_RANK** by headcount (largest = 1).',
    answer: 'SELECT department_id, COUNT(*) AS headcount, DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk FROM employees WHERE termination_date IS NULL GROUP BY department_id;',
    explain: 'A window function can rank an aggregate in the same query: department 1 ranks first with 179 people.' },
  { id: 'sq2-wr-03', topic: 'sql-window-rank', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 4, concept: 'top-n-group',
    prompt: 'Restaurant database: for **July 2026**, return the **dish with the highest net sales at each restaurant**: restaurant_id, dish name and net sales (2 decimals).',
    answer: "WITH s AS (SELECT restaurant_id, menu_item_id, SUM(net_sales) AS sales FROM daily_sales WHERE sale_date BETWEEN '2026-07-01' AND '2026-07-31' GROUP BY restaurant_id, menu_item_id), r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY restaurant_id ORDER BY sales DESC) AS rn FROM s) SELECT r.restaurant_id, m.name, ROUND(r.sales, 2) FROM r JOIN menu_items m ON m.menu_item_id = r.menu_item_id WHERE r.rn = 1;",
    traps: [{ sql: "WITH s AS (SELECT restaurant_id, menu_item_id, SUM(qty_sold) AS sales FROM daily_sales WHERE sale_date BETWEEN '2026-07-01' AND '2026-07-31' GROUP BY restaurant_id, menu_item_id), r AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY restaurant_id ORDER BY sales DESC) AS rn FROM s) SELECT r.restaurant_id, m.name, r.sales FROM r JOIN menu_items m ON m.menu_item_id = r.menu_item_id WHERE r.rn = 1;", feedback: 'That ranks by portions sold, where cheap coffees win. The question asks for net sales.' }],
    explain: 'The Ember Burger leads at Downtown and the Airport, the Grilled Salmon at Riverside. By portions, Cappuccino would win everywhere: the measure changes the answer.' },
  { id: 'sq2-wr-04', topic: 'sql-window-rank', type: 'number', kind: 'calculation', difficulty: 3, concept: 'window-rank',
    prompt: 'Revenues are 500, 400, 400, 400 and 300. What RANK() (largest first) does the product with 300 get?',
    answer: 5, verify: () => 1 + [500, 400, 400, 400].length,
    explain: 'RANK skips places after a tie: 1, 2, 2, 2, then 5. DENSE_RANK would give 3.' },
  { id: 'sq2-wr-05', topic: 'sql-window-rank', type: 'order', kind: 'sequence', difficulty: 3, concept: 'top-n-group',
    prompt: 'Order the steps for "top 3 products per category".',
    options: ['Aggregate revenue per product', 'Number the products within each category with ROW_NUMBER', 'Wrap that result in a CTE or subquery', 'Keep the rows numbered 3 or less'], answer: [0, 1, 2, 3],
    explain: 'The window runs on the aggregated rows, and its result can only be filtered from an outer query.' },
  { id: 'sq2-wr-06', topic: 'sql-window-rank', type: 'fill', kind: 'concept', difficulty: 3, concept: 'window-rank',
    prompt: 'The window clause that restarts the numbering for each group is PARTITION ____.',
    answer: ['BY', 'by'], explain: 'ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) starts again at 1 in every category.' },

  // ================================================================ sql-window-lag
  { id: 'sq2-wl-01', topic: 'sql-window-lag', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 4, concept: 'lag-lead', ordered: true,
    prompt: 'Restaurant database: for **Downtown** (restaurant_id 1) in **2026**, return **month** (YYYY-MM), **net sales**, the **previous month\'s** net sales and the **change** (all 2 decimals), oldest first.',
    answer: "WITH m AS (SELECT strftime('%Y-%m', sale_date) AS month, SUM(net_sales) AS sales FROM daily_sales WHERE restaurant_id = 1 AND sale_date >= '2026-01-01' GROUP BY month) SELECT month, ROUND(sales, 2), ROUND(LAG(sales) OVER (ORDER BY month), 2), ROUND(sales - LAG(sales) OVER (ORDER BY month), 2) FROM m ORDER BY month;",
    explain: 'January has no previous month in the filtered data, so LAG gives NULL there. Downtown peaked in May and has fallen since.' },
  { id: 'sq2-wl-02', topic: 'sql-window-lag', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'running-total', ordered: true,
    prompt: 'HR database: hires per **hire year** (first four characters of hire_date) with a **running total** of hires, oldest year first. Return year, hires and running total.',
    answer: 'WITH h AS (SELECT substr(hire_date, 1, 4) AS year, COUNT(*) AS hires FROM employees GROUP BY year) SELECT year, hires, SUM(hires) OVER (ORDER BY year) FROM h ORDER BY year;',
    explain: 'SUM over an ordered window adds up everything so far. The final running total equals everyone ever hired.' },
  { id: 'sq2-wl-03', topic: 'sql-window-lag', type: 'number', kind: 'calculation', difficulty: 3, concept: 'window-frame',
    prompt: 'Monthly revenue is 100, 120 and 90. What is the 2-month moving average (this month and the one before) in the third month?',
    answer: 105, verify: () => (120 + 90) / 2,
    explain: 'The window covers the second and third months: (120 + 90) ÷ 2 = 105.' },
  { id: 'sq2-wl-04', topic: 'sql-window-lag', type: 'order', kind: 'sequence', difficulty: 3, concept: 'lag-lead',
    prompt: 'Order the steps for month-on-month growth.',
    options: ['Aggregate revenue per month', 'Add LAG(revenue) over the months', 'Divide by the previous month and subtract 1', 'Leave the first month blank, not zero'], answer: [0, 1, 2, 3],
    explain: 'LAG needs one row per month; growth needs a previous value; the first month has none and should say so.' },
  { id: 'sq2-wl-05', topic: 'sql-window-lag', type: 'tf', kind: 'concept', difficulty: 3, concept: 'lag-lead',
    prompt: 'True or false: LEAD returns a value from the following row in the window order.',
    answer: true, explain: 'LAG looks back, LEAD looks forward; both take an optional offset and a default value.' },

  // ================================================================ sql-cohorts
  { id: 'sq2-co-01', topic: 'sql-cohorts', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'cohort', ordered: true,
    prompt: 'Group customers by the month of their **first order** (any status, customers only). For first orders in **2026**, return the cohort month (YYYY-MM) and the number of customers, oldest first.',
    answer: "WITH f AS (SELECT customer_id, MIN(order_date) AS first_order FROM orders WHERE customer_id IS NOT NULL GROUP BY customer_id) SELECT strftime('%Y-%m', first_order) AS cohort, COUNT(*) FROM f WHERE first_order >= '2026-01-01' GROUP BY cohort ORDER BY cohort;",
    traps: [{ sql: "SELECT strftime('%Y-%m', order_date) AS cohort, COUNT(DISTINCT customer_id) FROM orders WHERE order_date >= '2026-01-01' GROUP BY cohort ORDER BY cohort;", feedback: 'That counts everyone who ordered in each month, including repeat customers. A cohort uses each customer\'s first order only.' }],
    explain: 'New customers per month rose from under 100 in January to 187 in August: the acquisition side is healthy.' },
  { id: 'sq2-co-02', topic: 'sql-cohorts', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'cohort',
    prompt: 'HR database: for people hired from **2020 to 2025**, return the **hire year**, the **number hired** and how many are **still employed** (termination_date IS NULL).',
    answer: "SELECT substr(hire_date, 1, 4) AS hire_year, COUNT(*), SUM(CASE WHEN termination_date IS NULL THEN 1 ELSE 0 END) FROM employees WHERE hire_date >= '2020-01-01' AND hire_date < '2026-01-01' GROUP BY hire_year;",
    explain: 'Only 12 of the 105 people hired in 2020 are still there. Older cohorts have had more time to leave, so compare them at the same age.' },
  { id: 'sq2-co-03', topic: 'sql-cohorts', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 4, concept: 'funnel',
    prompt: 'For customers who **signed up in 2025**, return one row: the number who signed up, who placed **any order**, who have **at least one completed** order, and who have **two or more completed** orders.',
    answer: "WITH c AS (SELECT customer_id FROM customers WHERE signup_date BETWEEN '2025-01-01' AND '2025-12-31'), s AS (SELECT c.customer_id, COUNT(o.order_id) AS orders_any, SUM(CASE WHEN o.status = 'completed' THEN 1 ELSE 0 END) AS completed FROM c LEFT JOIN orders o ON o.customer_id = c.customer_id GROUP BY c.customer_id) SELECT COUNT(*), SUM(CASE WHEN orders_any > 0 THEN 1 ELSE 0 END), SUM(CASE WHEN completed >= 1 THEN 1 ELSE 0 END), SUM(CASE WHEN completed >= 2 THEN 1 ELSE 0 END) FROM s;",
    explain: 'Of 1,523 sign-ups, 1,329 ordered, 1,321 completed an order and 852 came back for a second. The biggest drop is from first to second purchase.' },
  { id: 'sq2-co-04', topic: 'sql-cohorts', type: 'number', kind: 'calculation', difficulty: 3, concept: 'cohort',
    prompt: 'A cohort starts with 400 customers, and 120 of them are still buying in month 3. What is the month-3 retention in %?',
    answer: 30, verify: () => (120 / 400) * 100,
    explain: 'Retention is measured against the cohort\'s starting size: 120 ÷ 400 = 30%.' },
  { id: 'sq2-co-05', topic: 'sql-cohorts', type: 'number', kind: 'calculation', difficulty: 3, concept: 'funnel',
    prompt: 'A funnel goes 1,000 → 400 → 380 → 50. What is the conversion from the third step to the fourth, in % (two decimals)?',
    answer: 13.16, tolerance: 0.01, verify: () => Math.round((50 / 380) * 10000) / 100,
    explain: '50 ÷ 380 = 13.16%: the last step loses almost everyone, so that is where to look first.' },
  { id: 'sq2-co-06', topic: 'sql-cohorts', type: 'order', kind: 'sequence', difficulty: 3, concept: 'cohort',
    prompt: 'Order the steps of a monthly cohort retention query.',
    options: ['Find each customer\'s first order month', 'Tag every order with that customer\'s cohort', 'Work out the months since the cohort month', 'Count distinct customers per cohort and month number'], answer: [0, 1, 2, 3],
    explain: 'The cohort is fixed by the first order; every later order is placed on the cohort\'s timeline before counting.' },

  // ================================================================ sql-business
  { id: 'sq2-bz-01', topic: 'sql-business', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 4, concept: 'kpi',
    prompt: 'Restaurant database: **labour cost as a % of net sales** for **July 2026**, per restaurant name (2 decimals). Return name and the percentage.',
    answer: "WITH l AS (SELECT restaurant_id, SUM(labor_cost) AS labour FROM labor_daily WHERE work_date BETWEEN '2026-07-01' AND '2026-07-31' GROUP BY restaurant_id), s AS (SELECT restaurant_id, SUM(net_sales) AS sales FROM daily_sales WHERE sale_date BETWEEN '2026-07-01' AND '2026-07-31' GROUP BY restaurant_id) SELECT r.name, ROUND(100.0 * l.labour / s.sales, 2) FROM restaurants r JOIN l ON l.restaurant_id = r.restaurant_id JOIN s ON s.restaurant_id = r.restaurant_id;",
    traps: [{ sql: "SELECT r.name, ROUND(100.0 * SUM(l.labor_cost) / SUM(d.net_sales), 2) FROM restaurants r JOIN labor_daily l ON l.restaurant_id = r.restaurant_id AND l.work_date BETWEEN '2026-07-01' AND '2026-07-31' JOIN daily_sales d ON d.restaurant_id = r.restaurant_id AND d.sale_date BETWEEN '2026-07-01' AND '2026-07-31' GROUP BY r.name;", feedback: 'Joining two daily tables directly multiplies the rows, so both sums are inflated. Total each table separately, then join the totals.' }],
    explain: 'Aggregate each fact table on its own, then join the totals. The Airport spends about 28% of sales on labour, Riverside under 24%.' },
  { id: 'sq2-bz-02', topic: 'sql-business', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 4, concept: 'kpi',
    prompt: `For **completed orders in 2026**, return the **average order value** per **channel** (net revenue per order, ${NET}, 2 decimals) and the number of orders.`,
    answer: `WITH t AS (SELECT o.order_id, o.channel, SUM(${NET}) AS value FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' AND o.order_date >= '2026-01-01' GROUP BY o.order_id, o.channel) SELECT channel, ROUND(AVG(value), 2), COUNT(*) FROM t GROUP BY channel;`,
    traps: [{ sql: `SELECT o.channel, ROUND(AVG(${NET}), 2), COUNT(*) FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' AND o.order_date >= '2026-01-01' GROUP BY o.channel;`, feedback: 'That averages order lines, not orders, and counts lines too. Total each order first.' }],
    explain: 'In-store and online orders are worth almost the same (about 199 and 195): the channel mix barely changes the average basket.' },
  { id: 'sq2-bz-03', topic: 'sql-business', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 4, concept: 'kpi', ordered: true,
    prompt: 'HR database: the **absence rate** for **2025** per department_id = total days_absent ÷ total scheduled_days × 100 (2 decimals), highest first.',
    answer: "SELECT e.department_id, ROUND(100.0 * SUM(a.days_absent) / SUM(a.scheduled_days), 2) AS absence_rate FROM attendance_monthly a JOIN employees e ON e.employee_id = a.employee_id WHERE a.month LIKE '2025%' GROUP BY e.department_id ORDER BY absence_rate DESC;",
    traps: [{ sql: "SELECT e.department_id, ROUND(AVG(100.0 * a.days_absent / a.scheduled_days), 2) AS absence_rate FROM attendance_monthly a JOIN employees e ON e.employee_id = a.employee_id WHERE a.month LIKE '2025%' GROUP BY e.department_id ORDER BY absence_rate DESC;", feedback: 'Averaging monthly rates gives every person-month the same weight. Build the rate from the totals.' }],
    explain: 'Department 2 (Transport) is absent 7.5% of scheduled days, far above the others at about 4%: the place to look first.' },
  { id: 'sq2-bz-04', topic: 'sql-business', type: 'number', kind: 'calculation', difficulty: 3, concept: 'kpi',
    prompt: 'A site spent 38,000 on labour with net sales of 130,000. What is labour as a % of sales (two decimals)?',
    answer: 29.23, tolerance: 0.01, verify: () => Math.round((38000 / 130000) * 10000) / 100,
    explain: '38,000 ÷ 130,000 = 29.23%. Put the definition next to the number: net sales, labour including or excluding management.' },
  { id: 'sq2-bz-05', topic: 'sql-business', type: 'number', kind: 'calculation', difficulty: 3, concept: 'kpi',
    prompt: 'A query reports average revenue per customer of 312 across 2,055 active customers. What total revenue does that imply?',
    answer: 641160, verify: () => 312 * 2055,
    explain: '312 × 2,055 = 641,160. Rebuilding the total is a quick sanity check against the finance figure.' },
  { id: 'sq2-bz-06', topic: 'sql-business', type: 'order', kind: 'sequence', difficulty: 3, concept: 'validation',
    prompt: 'Order the steps before sharing the result of a business query.',
    options: ['Check row counts and a total against a known figure', 'Test the edge cases: NULLs, cancelled orders, date limits', 'Write the definitions and filters at the top of the query', 'Share the result together with its caveats'], answer: [0, 1, 2, 3],
    explain: 'Prove the numbers, stress-test them, document the logic, then communicate honestly.' },
];
