// SQL quiz bank, part E: CTEs, text functions, segmentation (topics added by the expansion).
const NET = 'oi.quantity * oi.unit_price * (1 - oi.discount_pct)';

export const SQL_QUIZ_E = [
  // ================================================================ sql-cte
  { id: 'sq2-cte-01', topic: 'sql-cte', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'cte',
    prompt: `Using a CTE of order totals (${NET}), how many **completed orders dated in 2026** were worth **more than 500**? Return one number.`,
    answer: `WITH t AS (SELECT o.order_id, SUM(${NET}) AS value FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' AND o.order_date >= '2026-01-01' GROUP BY o.order_id) SELECT COUNT(*) FROM t WHERE value > 500;`,
    traps: [{ sql: `SELECT COUNT(*) FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' AND o.order_date >= '2026-01-01' AND ${NET} > 500;`, feedback: 'That counts order lines above 500. An order made of several smaller lines can also pass 500: total the order first.' }],
    explain: '286 orders passed 500 in 2026. The threshold only makes sense at the order level, which the CTE creates.' },
  { id: 'sq2-cte-02', topic: 'sql-cte', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 3, concept: 'cte',
    prompt: 'Restaurant database: with a CTE of **monthly net sales per restaurant** for 2026, return each restaurant_id and its **best month\'s** net sales (2 decimals).',
    answer: "WITH m AS (SELECT restaurant_id, strftime('%Y-%m', sale_date) AS month, SUM(net_sales) AS sales FROM daily_sales WHERE sale_date >= '2026-01-01' GROUP BY restaurant_id, month) SELECT restaurant_id, ROUND(MAX(sales), 2) FROM m GROUP BY restaurant_id;",
    traps: [{ sql: "SELECT restaurant_id, ROUND(MAX(net_sales), 2) FROM daily_sales WHERE sale_date >= '2026-01-01' GROUP BY restaurant_id;", feedback: 'That is the largest single sales row, not the best month. Total by month first.' }],
    explain: 'Aggregate to months, then take the maximum of those totals. Riverside\'s best month (July) is the highest of the three.' },
  { id: 'sq2-cte-03', topic: 'sql-cte', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'cte',
    prompt: 'HR database: **headcount on 2024-12-31** per location. Someone counts if hire_date <= that date and (termination_date IS NULL or termination_date > that date). Return location and headcount.',
    answer: "SELECT location, SUM(CASE WHEN hire_date <= '2024-12-31' AND (termination_date IS NULL OR termination_date > '2024-12-31') THEN 1 ELSE 0 END) FROM employees GROUP BY location;",
    traps: [{ sql: 'SELECT location, COUNT(*) FROM employees WHERE termination_date IS NULL GROUP BY location;', feedback: 'That is today\'s headcount. People who left in 2025 or 2026 were still employed at the end of 2024.' }],
    explain: 'The date test turns an employee list into a headcount on any day: North Hub had 235 people at the end of 2024.' },
  { id: 'sq2-cte-04', topic: 'sql-cte', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'cte',
    prompt: 'How many customers have placed **exactly one order** (any status)? Ignore orders without a customer. Return one number.',
    answer: 'WITH c AS (SELECT customer_id, COUNT(*) AS orders FROM orders WHERE customer_id IS NOT NULL GROUP BY customer_id) SELECT COUNT(*) FROM c WHERE orders = 1;',
    explain: '1,457 customers ordered once and never again: a large group for a second-purchase campaign.' },
  { id: 'sq2-cte-05', topic: 'sql-cte', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 4, concept: 'cte',
    prompt: 'Restaurant database: in **July 2026**, on how many days did **Downtown** (restaurant_id 1) log **no waste at all**? Generate the 31 dates with a recursive CTE. Return one number.',
    answer: "WITH RECURSIVE days(d) AS (SELECT '2026-07-01' UNION ALL SELECT date(d, '+1 day') FROM days WHERE d < '2026-07-31') SELECT COUNT(*) FROM days WHERE NOT EXISTS (SELECT 1 FROM waste_log w WHERE w.waste_date = days.d AND w.restaurant_id = 1);",
    traps: [{ sql: "SELECT COUNT(DISTINCT waste_date) FROM waste_log WHERE restaurant_id = 1 AND waste_date BETWEEN '2026-07-01' AND '2026-07-31';", feedback: 'That counts the days with waste. The question asks for days without any, which only a list of all dates can show.' }],
    explain: 'Waste is logged weekly, so 27 of the 31 days have no entry. Days with nothing only appear once you generate them.' },
  { id: 'sq2-cte-06', topic: 'sql-cte', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'cte',
    prompt: 'HR database: which departments pay **current** staff a higher average salary than the **company-wide** current average? Return department_id and its average (0 decimals).',
    answer: 'WITH d AS (SELECT department_id, AVG(current_salary) AS avg_salary FROM employees WHERE termination_date IS NULL GROUP BY department_id) SELECT department_id, ROUND(avg_salary, 0) FROM d WHERE avg_salary > (SELECT AVG(current_salary) FROM employees WHERE termination_date IS NULL);',
    traps: [{ sql: 'WITH d AS (SELECT department_id, AVG(current_salary) AS avg_salary FROM employees WHERE termination_date IS NULL GROUP BY department_id) SELECT department_id, ROUND(avg_salary, 0) FROM d WHERE avg_salary > (SELECT AVG(avg_salary) FROM d);', feedback: 'The average of department averages treats a 10-person department like a 179-person one. Compare with the average over all employees.' }],
    explain: 'Five departments sit above the company average, which is pulled down by the large Operations team.' },
  { id: 'sq2-cte-07', topic: 'sql-cte', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 4, concept: 'cte', ordered: true,
    prompt: `Like-for-like growth: per product **category**, compare completed net revenue (${NET}) for **Jan–Aug 2025** with **Jan–Aug 2026**. Return category and growth % (1 decimal), highest first.`,
    answer: `WITH r AS (SELECT p.category, SUM(CASE WHEN o.order_date BETWEEN '2025-01-01' AND '2025-08-31' THEN ${NET} END) AS y25, SUM(CASE WHEN o.order_date BETWEEN '2026-01-01' AND '2026-08-31' THEN ${NET} END) AS y26 FROM order_items oi JOIN orders o ON o.order_id = oi.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY p.category) SELECT category, ROUND(100.0 * (y26 - y25) / y25, 1) AS growth FROM r ORDER BY growth DESC;`,
    traps: [{ sql: `WITH r AS (SELECT p.category, SUM(CASE WHEN o.order_date BETWEEN '2025-01-01' AND '2025-12-31' THEN ${NET} END) AS y25, SUM(CASE WHEN o.order_date BETWEEN '2026-01-01' AND '2026-08-31' THEN ${NET} END) AS y26 FROM order_items oi JOIN orders o ON o.order_id = oi.order_id JOIN products p ON p.product_id = oi.product_id WHERE o.status = 'completed' GROUP BY p.category) SELECT category, ROUND(100.0 * (y26 - y25) / y25, 1) AS growth FROM r ORDER BY growth DESC;`, feedback: 'Comparing eight months of 2026 with all twelve months of 2025 makes every category look like it is shrinking. Compare the same months.' }],
    explain: 'Every category grew; Sleeping Gear grew fastest (about 41%). Comparing equal periods is what makes the numbers fair.' },
  { id: 'sq2-cte-08', topic: 'sql-cte', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 3, concept: 'cte', ordered: true,
    prompt: 'Restaurant database: for **August 2026** deliveries, return the **3 ingredients with the highest average price per unit** (sum of line_total ÷ sum of qty): ingredient name and price (2 decimals), dearest first.',
    answer: "WITH c AS (SELECT ingredient_id, SUM(line_total) / SUM(qty) AS unit_price FROM purchases WHERE delivery_date BETWEEN '2026-08-01' AND '2026-08-31' GROUP BY ingredient_id) SELECT i.name, ROUND(c.unit_price, 2) FROM c JOIN ingredients i ON i.ingredient_id = c.ingredient_id ORDER BY c.unit_price DESC LIMIT 3;",
    traps: [{ sql: "WITH c AS (SELECT ingredient_id, AVG(unit_cost) AS unit_price FROM purchases WHERE delivery_date BETWEEN '2026-08-01' AND '2026-08-31' GROUP BY ingredient_id) SELECT i.name, ROUND(c.unit_price, 2) FROM c JOIN ingredients i ON i.ingredient_id = c.ingredient_id ORDER BY c.unit_price DESC LIMIT 3;", feedback: 'AVG(unit_cost) weights a small delivery like a big one. Divide the totals.' }],
    explain: 'Truffle paste (about 120.71 a kg) is by far the dearest, then ribeye and salmon: small quantities, big effect on dish costs.' },
  { id: 'sq2-cte-09', topic: 'sql-cte', type: 'number', kind: 'calculation', difficulty: 2, concept: 'cte',
    prompt: 'A recursive CTE starts at 2026-08-01 and adds one day while d < \'2026-08-31\'. How many rows does it produce?',
    answer: 31, verify: () => (Date.UTC(2026, 7, 31) - Date.UTC(2026, 7, 1)) / 86400000 + 1,
    explain: 'The step still runs when d is 2026-08-30 and adds the 31st, then stops: 31 rows, one per day.' },
  { id: 'sq2-cte-10', topic: 'sql-cte', type: 'number', kind: 'calculation', difficulty: 2, concept: 'cte',
    prompt: 'A CTE holds four order totals: 120, 80, 200 and 100. How many orders are above the CTE\'s average total?',
    answer: 1, verify: () => [120, 80, 200, 100].filter((v) => v > 125).length,
    explain: 'The average is 125, so only the 200 order is above it. A skewed list often has fewer rows above the mean than below.' },
  { id: 'sq2-cte-11', topic: 'sql-cte', type: 'number', kind: 'calculation', difficulty: 3, concept: 'cte',
    prompt: 'A department had 90 people on 1 January and 90 on 31 December, and 37 left voluntarily during the year. What is the voluntary turnover rate in % (one decimal)?',
    answer: 41.1, tolerance: 0.05, verify: () => Math.round((37 / ((90 + 90) / 2)) * 1000) / 10,
    explain: '37 ÷ 90 = 41.1%. The average headcount is the denominator, so a team can lose many people and still look the same size.' },
  { id: 'sq2-cte-12', topic: 'sql-cte', type: 'tf', kind: 'concept', difficulty: 2, concept: 'cte',
    prompt: 'True or false: a CTE is saved in the database after the query has run.',
    answer: false, explain: 'A CTE exists only while its query runs. To keep a result, create a view or a table.' },
  { id: 'sq2-cte-13', topic: 'sql-cte', type: 'tf', kind: 'concept', difficulty: 2, concept: 'cte',
    prompt: 'True or false: a later CTE in the same WITH block can read from an earlier one.',
    answer: true, explain: 'That is how multi-step pipelines are built: WITH a AS (…), b AS (SELECT … FROM a) SELECT … FROM b.' },
  { id: 'sq2-cte-14', topic: 'sql-cte', type: 'tf', kind: 'concept', difficulty: 3, concept: 'cte',
    prompt: 'True or false: the final SELECT after a WITH block can only read the last CTE.',
    answer: false, explain: 'It can read any of them, and join them together.' },
  { id: 'sq2-cte-15', topic: 'sql-cte', type: 'fill', kind: 'concept', difficulty: 2, concept: 'cte',
    prompt: 'A common table expression starts with the keyword ____.',
    answer: ['WITH', 'with'], explain: 'WITH name AS (SELECT …) SELECT … FROM name.' },
  { id: 'sq2-cte-16', topic: 'sql-cte', type: 'fill', kind: 'concept', difficulty: 3, concept: 'cte',
    prompt: 'In a recursive CTE, the starting row and the step that adds the next row are joined with UNION ____.',
    answer: ['ALL', 'all'], explain: 'UNION ALL keeps every generated row without checking for duplicates, which is what a generator needs.' },
  { id: 'sq2-cte-17', topic: 'sql-cte', type: 'order', kind: 'sequence', difficulty: 3, concept: 'cte',
    prompt: 'Order the parts of a recursive calendar CTE.',
    options: ['WITH RECURSIVE and the CTE name', 'The starting row', 'UNION ALL', 'The step that adds a day, with a stop condition'], answer: [0, 1, 2, 3],
    explain: 'Name, anchor, UNION ALL, then the recursive step with its WHERE, which stops the loop.' },
  { id: 'sq2-cte-18', topic: 'sql-cte', type: 'order', kind: 'sequence', difficulty: 3, concept: 'cte',
    prompt: 'Order the steps of a turnover calculation built from CTEs.',
    options: ['Headcount at the start of the year', 'Headcount at the end of the year', 'Voluntary leavers during the year', 'Leavers ÷ average headcount × 100'], answer: [0, 1, 2, 3],
    explain: 'Two headcounts give the average; the leavers and the average give the rate.' },
  { id: 'sq2-cte-19', topic: 'sql-cte', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'cte',
    prompt: 'A recursive calendar query never finishes. What is the most likely cause?',
    options: ['The step has no stop condition', 'UNION ALL should be UNION', 'The starting date is text', 'The CTE has no alias'], answer: 0,
    explain: 'Without WHERE d < end_date, the step keeps adding days forever. Always write the stop condition first.' },
  { id: 'sq2-cte-20', topic: 'sql-cte', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'cte',
    prompt: 'Why would you run `WITH t AS (…) SELECT * FROM t LIMIT 10` before finishing a query?',
    options: ['To check that step\'s output before building on it', 'To make the final query faster', 'To save the CTE in the database', 'To sort the final result'], answer: 0,
    explain: 'Checking each step catches wrong grain or filters early, when the fix is easy.' },
  { id: 'sq2-cte-21', topic: 'sql-cte', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'cte',
    prompt: 'Your query needs per-customer totals twice: once for an average and once for a list. What is the cleanest design?',
    options: ['Compute them once in a CTE and use it twice', 'Paste the same subquery in both places', 'Create two separate queries by hand', 'Store the totals in a spreadsheet'], answer: 0,
    explain: 'One definition, used twice, means a fix to the totals reaches both uses.' },
  { id: 'sq2-cte-22', topic: 'sql-cte', type: 'mc', kind: 'concept', difficulty: 2, concept: 'cte',
    prompt: 'Why does a daily report often need a generated calendar?',
    options: ['So days with no activity still appear, with zero', 'So the query runs faster', 'Because dates cannot be grouped otherwise', 'To convert text dates to numbers'], answer: 0,
    explain: 'Grouping the activity table only returns days that have rows; a calendar LEFT JOIN shows the gaps.' },
  { id: 'sq2-cte-23', topic: 'sql-cte', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'cte',
    prompt: 'An "average order value" CTE returns a number far below what finance expects. The CTE selects straight from order_items. What is wrong?',
    options: ['Its grain is order lines, not orders', 'CTEs cannot calculate averages', 'The CTE needs ORDER BY', 'Finance uses a different currency'], answer: 0,
    explain: 'Group by order_id inside the CTE so each row is one order; then the average is per order.' },
  { id: 'sq2-cte-24', topic: 'sql-cte', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'sql-dates',
    prompt: 'Which condition counts someone as employed on 2025-12-31?',
    options: ['hire_date <= \'2025-12-31\' AND (termination_date IS NULL OR termination_date > \'2025-12-31\')', 'hire_date <= \'2025-12-31\' AND termination_date IS NULL', 'hire_date <= \'2025-12-31\' AND termination_date > \'2025-12-31\'', 'hire_date <= \'2025-12-31\' OR termination_date > \'2025-12-31\''], answer: 0,
    explain: 'Hired by that date and not yet gone. Asking only for termination_date IS NULL misses people who left later; asking only for termination_date after the date drops everyone still employed, whose termination_date is NULL; and OR lets people hired in 2026 count as well.' },
  { id: 'sq2-cte-25', topic: 'sql-cte', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'cte',
    prompt: 'A 200-line query with six CTEs returns a wrong total. What is the fastest way to find the problem?',
    options: ['Select from each CTE in turn and check its row count', 'Rewrite the whole query from scratch', 'Add DISTINCT to the final SELECT', 'Ask the database to optimise it'], answer: 0,
    explain: 'Walk the pipeline step by step; the first step with a surprising count is where the error starts.' },

  // ================================================================ sql-strings
  { id: 'sq2-str-01', topic: 'sql-strings', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'string-funcs',
    prompt: 'For each **SKU prefix** (the first 3 characters of sku), return the prefix, the **number of products** and the **number of different categories**.',
    answer: 'SELECT SUBSTR(sku, 1, 3) AS prefix, COUNT(*), COUNT(DISTINCT category) FROM products GROUP BY prefix;',
    explain: 'Every prefix maps to exactly one category (TNT to Tents, FTW to Footwear and so on), so the prefix is a reliable check on the category field.' },
  { id: 'sq2-str-02', topic: 'sql-strings', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 2, concept: 'string-funcs', ordered: true,
    prompt: 'HR database: for **current Head Office** employees, return a display name **"Last, First"**, sorted by last name, then first name, then employee_id. Show the first 5.',
    answer: "SELECT last_name || ', ' || first_name FROM employees WHERE location = 'Head Office' AND termination_date IS NULL ORDER BY last_name, first_name, employee_id LIMIT 5;",
    traps: [{ sql: "SELECT first_name || ' ' || last_name FROM employees WHERE location = 'Head Office' AND termination_date IS NULL ORDER BY last_name, first_name, employee_id LIMIT 5;", feedback: 'The display name must be "Last, First" with a comma and a space.' }],
    explain: '|| joins the pieces. Sorting by the separate columns (not the joined text) keeps the order reliable.' },
  { id: 'sq2-str-03', topic: 'sql-strings', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'string-funcs',
    prompt: 'Restaurant database: how many ingredient **names consist of two or more words** (they contain a space)? Return one number.',
    answer: "SELECT COUNT(*) FROM ingredients WHERE INSTR(name, ' ') > 0;",
    explain: '14 names contain a space. LIKE \'% %\' gives the same answer; both work because the names have no leading spaces.' },
  { id: 'sq2-str-04', topic: 'sql-strings', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 2, concept: 'string-funcs',
    prompt: 'HR database: how many **current** employees have a job title containing the word **Senior**? Return one number.',
    answer: "SELECT COUNT(*) FROM employees WHERE job_title LIKE '%Senior%' AND termination_date IS NULL;",
    traps: [{ sql: "SELECT COUNT(*) FROM employees WHERE job_title LIKE 'Senior' AND termination_date IS NULL;", feedback: 'Without the % wildcards, LIKE needs the whole title to be exactly "Senior".' }],
    explain: '61 current employees hold senior titles. The % on each side allows any text before and after.' },
  { id: 'sq2-str-05', topic: 'sql-strings', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'string-funcs', ordered: true,
    prompt: 'Return the **3 longest product names** with their length in characters, longest first; for equal lengths, A to Z.',
    answer: 'SELECT product_name, LENGTH(product_name) AS len FROM products ORDER BY len DESC, product_name LIMIT 3;',
    explain: 'Three names tie at 27 characters, which is why the second sort column matters: a label field of 25 characters would cut all of them.' },
  { id: 'sq2-str-06', topic: 'sql-strings', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 2, concept: 'string-funcs',
    prompt: 'HR database: how many **different last names** do current employees have? Return one number.',
    answer: 'SELECT COUNT(DISTINCT last_name) FROM employees WHERE termination_date IS NULL;',
    explain: 'Only 36 surnames across 489 people: surname is useless as a key, and even first plus last name clashes often.' },
  { id: 'sq2-str-07', topic: 'sql-strings', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'string-funcs',
    prompt: 'How many customer emails contain **capital letters** but **no** stray spaces at either end? Return one number.',
    answer: 'SELECT COUNT(*) FROM customers WHERE email <> LOWER(email) AND email = TRIM(email);',
    explain: 'Combining two tests shows how the problems overlap: the 35 capitalised emails and the 36 spaced ones are different records.' },
  { id: 'sq2-str-08', topic: 'sql-strings', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 3, concept: 'string-funcs',
    prompt: 'Restaurant database: invoice numbers end with the restaurant code (e.g. "…-DT"). How many purchase lines have an invoice_no ending in the **right restaurant\'s code**? Use SUBSTR(invoice_no, -2).',
    answer: 'SELECT COUNT(*) FROM purchases p JOIN restaurants r ON r.restaurant_id = p.restaurant_id WHERE SUBSTR(p.invoice_no, -2) = r.code;',
    explain: 'Almost every line matches; the few that do not use a different invoice pattern and are worth a look before relying on the code.' },
  { id: 'sq2-str-09', topic: 'sql-strings', type: 'number', kind: 'calculation', difficulty: 2, concept: 'string-funcs',
    prompt: 'What does `SUBSTR(\'PM-20260702-DT\', 4, 8)` return? (type the digits)',
    answer: 20260702, verify: () => Number('PM-20260702-DT'.substr(3, 8)),
    explain: 'Start at position 4 (the first digit) and take 8 characters: the delivery date written as 20260702.' },
  { id: 'sq2-str-10', topic: 'sql-strings', type: 'number', kind: 'calculation', difficulty: 2, concept: 'string-funcs',
    prompt: 'What does `INSTR(\'ana.silva@post.example\', \'@\')` return?',
    answer: 10, verify: () => 'ana.silva@post.example'.indexOf('@') + 1,
    explain: 'The @ is the 10th character. SUBSTR(email, 1, 9) is the name part and SUBSTR(email, 11) the domain.' },
  { id: 'sq2-str-11', topic: 'sql-strings', type: 'number', kind: 'calculation', difficulty: 2, concept: 'string-funcs',
    prompt: 'What does `LENGTH(TRIM(\'  Tent  \'))` return?',
    answer: 4, verify: () => '  Tent  '.trim().length,
    explain: 'TRIM removes the two spaces on each side, leaving "Tent": 4 characters.' },
  { id: 'sq2-str-12', topic: 'sql-strings', type: 'tf', kind: 'concept', difficulty: 2, concept: 'string-funcs',
    prompt: 'True or false: in SQLite, `\'Tent\' = \'tent\'` is true.',
    answer: false, explain: '= compares text exactly, capitals included. Compare LOWER() on both sides to ignore case.' },
  { id: 'sq2-str-13', topic: 'sql-strings', type: 'tf', kind: 'concept', difficulty: 2, concept: 'string-funcs',
    prompt: 'True or false: SUBSTR positions start at 1 in SQLite.',
    answer: true, explain: 'SUBSTR(\'Tent\', 1, 1) is "T". A negative start counts from the end: SUBSTR(x, -2) is the last two characters.' },
  { id: 'sq2-str-14', topic: 'sql-strings', type: 'tf', kind: 'concept', difficulty: 2, concept: 'string-funcs',
    prompt: 'True or false: REPLACE changes only the first occurrence of the text.',
    answer: false, explain: 'REPLACE swaps every occurrence: REPLACE(\'0428 299 4190\', \' \', \'\') removes both spaces.' },
  { id: 'sq2-str-15', topic: 'sql-strings', type: 'fill', kind: 'concept', difficulty: 2, concept: 'string-funcs',
    prompt: 'In SQLite, the operator that joins two pieces of text is ____.',
    answer: ['||', 'double pipe', 'pipes'], explain: 'first_name || \' \' || last_name. Some databases use CONCAT() or + instead.' },
  { id: 'sq2-str-16', topic: 'sql-strings', type: 'fill', kind: 'concept', difficulty: 2, concept: 'string-funcs',
    prompt: 'INSTR returns ____ when the text it looks for is not found.',
    answer: ['0', 'zero'], explain: 'A 0 lets you test for presence: WHERE INSTR(email, \'@\') = 0 finds emails without an @.' },
  { id: 'sq2-str-17', topic: 'sql-strings', type: 'order', kind: 'sequence', difficulty: 2, concept: 'string-funcs',
    prompt: 'Order the steps to fix a join that fails because keys are written differently.',
    options: ['Look at examples of keys that fail to match', 'Apply TRIM and a consistent case', 'Clean both sides of the join the same way', 'Check how many rows now match'], answer: [0, 1, 2, 3],
    explain: 'Understand the difference, clean it, clean it everywhere, and measure the improvement.' },
  { id: 'sq2-str-18', topic: 'sql-strings', type: 'order', kind: 'sequence', difficulty: 3, concept: 'string-funcs',
    prompt: 'Order the steps to split "Chen, Anna" into a last and a first name.',
    options: ['Find the comma with INSTR', 'Take the text before it for the last name', 'Take the text two characters after it for the first name', 'Trim both parts'], answer: [0, 1, 2, 3],
    explain: 'The comma\'s position drives both SUBSTR calls; trimming protects against stray spaces around the comma.' },
  { id: 'sq2-str-19', topic: 'sql-strings', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'string-funcs',
    prompt: 'A join on sku matches 58 of 61 products. The three missing SKUs are written in lower case in one table. What is the fix?',
    options: ['Compare UPPER(sku) on both sides, or fix the data', 'Use a LEFT JOIN instead', 'Add DISTINCT to the query', 'Sort both tables by sku first'], answer: 0,
    explain: 'The join compares exactly. Normalising the case on both sides makes the keys equal; fixing the source stops it recurring.' },
  { id: 'sq2-str-20', topic: 'sql-strings', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'string-funcs',
    prompt: 'What does `SUBSTR(email, INSTR(email, \'@\') + 1)` return?',
    options: ['The domain after the @', 'The name before the @', 'The position of the @', 'The email without the @'], answer: 0,
    explain: 'It starts one character after the @ and, with no length given, runs to the end.' },
  { id: 'sq2-str-21', topic: 'sql-strings', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'string-funcs',
    prompt: 'Prices stored as text sort as "100", "25", "9". How do you sort them as numbers?',
    options: ['ORDER BY CAST(price AS REAL)', 'ORDER BY TRIM(price)', 'ORDER BY LENGTH(price) DESC', 'ORDER BY UPPER(price)'], answer: 0,
    explain: 'CAST turns the text into a number for sorting; better still, store numbers in a numeric column.' },
  { id: 'sq2-str-22', topic: 'sql-strings', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'duplicates',
    prompt: 'Two customer records have the same email apart from capitals and a trailing space. How should the customer count be reported?',
    options: ['Count people by cleaned email and say how many records were merged', 'Count both records: they are different emails', 'Delete one record before counting', 'Leave customers out of the report'], answer: 0,
    explain: 'Report the cleaned count and the size of the fix, so readers know the data was adjusted and by how much.' },
  { id: 'sq2-str-23', topic: 'sql-strings', type: 'mc', kind: 'concept', difficulty: 3, concept: 'string-funcs',
    prompt: 'Why is it risky to rely on LIKE ignoring capitals?',
    options: ['Other databases treat LIKE as case-sensitive', 'LIKE never works on text', 'LIKE changes the stored data', 'LIKE only matches numbers'], answer: 0,
    explain: 'SQLite\'s LIKE ignores the case of plain letters; PostgreSQL\'s does not. Cleaning the text makes the query portable.' },
  { id: 'sq2-str-24', topic: 'sql-strings', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'string-funcs',
    prompt: 'A query formats rates with printf(\'%.1f%%\', rate), and a colleague who adds up that column gets nonsense. Why?',
    options: ['The formatted column is text, not a number', 'printf rounds every value to zero', 'The % sign doubles the value', 'SUM cannot read decimals'], answer: 0,
    explain: 'Formatting turns numbers into text. Keep the numeric column for calculations and format only for display.' },
  { id: 'sq2-str-25', topic: 'sql-strings', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'string-funcs',
    prompt: 'Which expression builds a key such as "S01-2026-07" from a store and an order date?',
    options: ['store_id || \'-\' || strftime(\'%Y-%m\', order_date)', 'store_id + \'-\' + order_date', 'SUBSTR(store_id, order_date)', 'REPLACE(order_date, \'-\', store_id)'], answer: 0,
    explain: '|| joins the pieces and strftime gives the year and month. The + operator adds numbers in SQLite, it does not join text.' },

  // ================================================================ sql-segments
  { id: 'sq2-seg-01', topic: 'sql-segments', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'segmentation',
    prompt: 'Recency check: among customers with at least one **completed** order, how many made their **last completed order more than 180 days before 2026-08-31**? Return one number.',
    answer: "WITH l AS (SELECT customer_id, MAX(order_date) AS last_order FROM orders WHERE status = 'completed' AND customer_id IS NOT NULL GROUP BY customer_id) SELECT COUNT(*) FROM l WHERE julianday('2026-08-31') - julianday(last_order) > 180;",
    traps: [{ sql: "SELECT COUNT(DISTINCT customer_id) FROM orders WHERE status = 'completed' AND julianday('2026-08-31') - julianday(order_date) > 180;", feedback: 'That counts anyone with any old order, including active customers. Use each customer\'s latest order.' }],
    explain: 'Half of all buyers (1,852 of 3,699) have not bought in six months: recency is the first thing an RFM model looks at.' },
  { id: 'sq2-seg-02', topic: 'sql-segments', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 4, concept: 'segmentation',
    prompt: 'Restaurant database: in **July 2026** (all restaurants), what **share of net sales** came from the **5 best-selling dishes** by net sales? Return the % (2 decimals).',
    answer: "WITH d AS (SELECT menu_item_id, SUM(net_sales) AS sales FROM daily_sales WHERE sale_date BETWEEN '2026-07-01' AND '2026-07-31' GROUP BY menu_item_id), r AS (SELECT *, ROW_NUMBER() OVER (ORDER BY sales DESC) AS rn FROM d) SELECT ROUND(100.0 * SUM(CASE WHEN rn <= 5 THEN sales END) / SUM(sales), 2) FROM r;",
    explain: 'Five of 25 dishes (20%) bring in about a third of sales: concentrated, but far from an 80/20 menu.' },
  { id: 'sq2-seg-03', topic: 'sql-segments', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'segmentation',
    prompt: 'HR database: split **current** employees into **4 salary groups** with NTILE(4) (highest salaries = group 1). Return the group, the number of people, and the lowest and highest salary in each.',
    answer: 'WITH q AS (SELECT current_salary, NTILE(4) OVER (ORDER BY current_salary DESC) AS grp FROM employees WHERE termination_date IS NULL) SELECT grp, COUNT(*), MIN(current_salary), MAX(current_salary) FROM q GROUP BY grp;',
    explain: 'The group edges overlap (41,800 and 37,000 appear in two groups): NTILE splits people with the same salary to keep group sizes even.' },
  { id: 'sq2-seg-04', topic: 'sql-segments', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 4, concept: 'segmentation',
    prompt: `For customers with **completed 2025** orders, return their **acquisition_channel** ("Unknown" when missing), the **number of customers** and their **average 2025 spend** (${NET}, 2 decimals).`,
    answer: `WITH s AS (SELECT o.customer_id, SUM(${NET}) AS spend FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' AND o.customer_id IS NOT NULL AND o.order_date BETWEEN '2025-01-01' AND '2025-12-31' GROUP BY o.customer_id) SELECT COALESCE(c.acquisition_channel, 'Unknown') AS channel, COUNT(*), ROUND(AVG(s.spend), 2) FROM s JOIN customers c ON c.customer_id = s.customer_id GROUP BY channel;`,
    traps: [{ sql: `SELECT c.acquisition_channel, COUNT(DISTINCT o.customer_id), ROUND(AVG(${NET}), 2) FROM orders o JOIN order_items oi ON oi.order_id = o.order_id JOIN customers c ON c.customer_id = o.customer_id WHERE o.status = 'completed' AND o.order_date BETWEEN '2025-01-01' AND '2025-12-31' GROUP BY c.acquisition_channel;`, feedback: 'That averages order lines, not customers, and leaves the missing channel as NULL. Total per customer first.' }],
    explain: 'Referral customers spend the most on average (about 501), Email customers the least: a hint for where acquisition money works best.' },
  { id: 'sq2-seg-05', topic: 'sql-segments', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 5, concept: 'anomaly',
    prompt: 'Daily order counts (all orders): how many days have a **z-score above 3**? Use z = (count − mean) ÷ standard deviation, with sd = sqrt(AVG(n*n) − AVG(n)*AVG(n)). Return one number.',
    answer: 'WITH d AS (SELECT order_date, COUNT(*) AS n FROM orders GROUP BY order_date), s AS (SELECT AVG(n) AS mean, sqrt(AVG(n * n) - AVG(n) * AVG(n)) AS sd FROM d) SELECT COUNT(*) FROM d, s WHERE (d.n - s.mean) / s.sd > 3;',
    explain: 'Four days stand out, all in the summer peak: compared with the yearly average, busy season looks unusual. A seasonal comparison would flag fewer.' },
  { id: 'sq2-seg-06', topic: 'sql-segments', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 5, concept: 'anomaly',
    prompt: 'Restaurant database: count the restaurant-days whose **net sales were below 60%** of that restaurant\'s **average for the same weekday** (over all dates). Return one number.',
    answer: "WITH d AS (SELECT restaurant_id, sale_date, SUM(net_sales) AS sales FROM daily_sales GROUP BY restaurant_id, sale_date), w AS (SELECT *, AVG(sales) OVER (PARTITION BY restaurant_id, strftime('%w', sale_date)) AS typical FROM d) SELECT COUNT(*) FROM w WHERE sales < 0.6 * typical;",
    traps: [{ sql: "WITH d AS (SELECT restaurant_id, sale_date, SUM(net_sales) AS sales FROM daily_sales GROUP BY restaurant_id, sale_date), w AS (SELECT *, AVG(sales) OVER (PARTITION BY restaurant_id) AS typical FROM d) SELECT COUNT(*) FROM w WHERE sales < 0.6 * typical;", feedback: 'Without the weekday in the partition, quiet weekdays are compared with busy weekends.' }],
    explain: 'Five days are flagged, all at Riverside in the winter of 2025. They are the seasonal low of a summer restaurant, not incidents: check the calendar before calling them anomalies.' },
  { id: 'sq2-seg-07', topic: 'sql-segments', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 4, concept: 'window-rank', ordered: true,
    prompt: `Return the **3 biggest customers** by completed 2025 spend (${NET}) with their spend and their **share of all 2025 customer spend** (%, 2 decimals), biggest first.`,
    answer: `WITH s AS (SELECT o.customer_id, SUM(${NET}) AS spend FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' AND o.customer_id IS NOT NULL AND o.order_date BETWEEN '2025-01-01' AND '2025-12-31' GROUP BY o.customer_id), t AS (SELECT customer_id, spend, 100.0 * spend / SUM(spend) OVER () AS share FROM s) SELECT customer_id, ROUND(spend, 2), ROUND(share, 2) FROM t ORDER BY spend DESC LIMIT 3;`,
    traps: [{ sql: `WITH s AS (SELECT o.customer_id, SUM(${NET}) AS spend FROM orders o JOIN order_items oi ON oi.order_id = o.order_id WHERE o.status = 'completed' AND o.customer_id IS NOT NULL AND o.order_date BETWEEN '2025-01-01' AND '2025-12-31' GROUP BY o.customer_id ORDER BY spend DESC LIMIT 3) SELECT customer_id, ROUND(spend, 2), ROUND(100.0 * spend / SUM(spend) OVER (), 2) FROM s ORDER BY spend DESC;`, feedback: 'Limiting to three before the window makes the shares add up to 100% among the three. Compute the share over all customers first.' }],
    explain: 'The biggest customer is under half a percent of spend: no single account is critical. The window SUM() OVER () must run before LIMIT.' },
  { id: 'sq2-seg-08', topic: 'sql-segments', type: 'number', kind: 'calculation', difficulty: 3, concept: 'segmentation',
    prompt: 'The top 10% of customers bring 34.6% of revenue. If customer revenue was 829,000, how much came from the top 10%?',
    answer: 286834, tolerance: 1, verify: () => Math.round(0.346 * 829000),
    explain: '0.346 × 829,000 = 286,834. The other 90% of customers bring the remaining 542,166.' },
  { id: 'sq2-seg-09', topic: 'sql-segments', type: 'number', kind: 'calculation', difficulty: 3, concept: 'window-rank',
    prompt: 'NTILE(4) is applied to 10 rows. How many rows go into group 1?',
    answer: 3, verify: () => Math.ceil(10 / 4),
    explain: '10 rows into 4 groups gives 3, 3, 2, 2: the extra rows go to the first groups.' },
  { id: 'sq2-seg-10', topic: 'sql-segments', type: 'number', kind: 'calculation', difficulty: 3, concept: 'anomaly',
    prompt: 'A day has 35 orders. The mean is 20 and the standard deviation is 4. What is the z-score?',
    answer: 3.75, tolerance: 0.001, verify: () => (35 - 20) / 4,
    explain: '(35 − 20) ÷ 4 = 3.75: well above the usual ±3 alert line.' },
  { id: 'sq2-seg-11', topic: 'sql-segments', type: 'number', kind: 'calculation', difficulty: 3, concept: 'segmentation',
    prompt: 'A customer\'s last order was on 2026-06-02 and the report date is 2026-08-31. What is their recency in days?',
    answer: 90, verify: () => (Date.UTC(2026, 7, 31) - Date.UTC(2026, 5, 2)) / 86400000,
    explain: '28 days left in June, 31 in July and 31 in August: 90 days.' },
  { id: 'sq2-seg-12', topic: 'sql-segments', type: 'tf', kind: 'concept', difficulty: 3, concept: 'window-rank',
    prompt: 'True or false: NTILE(10) always creates ten groups of exactly the same size.',
    answer: false, explain: 'When the rows do not divide evenly, the first groups get one extra row, and equal values can be split between groups.' },
  { id: 'sq2-seg-13', topic: 'sql-segments', type: 'tf', kind: 'concept', difficulty: 3, concept: 'segmentation',
    prompt: 'True or false: with a CASE-based segmentation, each customer ends up in exactly one segment.',
    answer: true, explain: 'CASE returns the first matching label, so segments never overlap, which keeps the counts additive.' },
  { id: 'sq2-seg-14', topic: 'sql-segments', type: 'tf', kind: 'concept', difficulty: 3, concept: 'anomaly',
    prompt: 'True or false: SQLite has a built-in STDEV function.',
    answer: false, explain: 'Use sqrt(AVG(x*x) − AVG(x)*AVG(x)) for the population standard deviation (with math functions enabled).' },
  { id: 'sq2-seg-15', topic: 'sql-segments', type: 'fill', kind: 'concept', difficulty: 3, concept: 'window-rank',
    prompt: 'The window function that splits ordered rows into a given number of groups is ____.',
    answer: ['NTILE', 'ntile'], explain: 'NTILE(n) OVER (ORDER BY …) numbers the groups 1 to n.' },
  { id: 'sq2-seg-16', topic: 'sql-segments', type: 'fill', kind: 'concept', difficulty: 3, concept: 'segmentation',
    prompt: 'The idea that a small share of customers brings a large share of revenue is often called the ____ principle.',
    answer: ['Pareto', 'pareto', '80/20', '80-20'], explain: 'The Pareto (80/20) principle is a rule of thumb; measure the real split, as it is rarely exactly 80/20.' },
  { id: 'sq2-seg-17', topic: 'sql-segments', type: 'order', kind: 'sequence', difficulty: 4, concept: 'segmentation',
    prompt: 'Order the steps of an RFM segmentation.',
    options: ['One row per customer with last order, order count and spend', 'Score each measure from 1 to 5 with NTILE', 'Combine the scores into a segment label', 'Count and describe each segment'], answer: [0, 1, 2, 3],
    explain: 'Measures first, then scores, then labels a marketer can act on, then the sizes that tell you which labels matter.' },
  { id: 'sq2-seg-18', topic: 'sql-segments', type: 'order', kind: 'sequence', difficulty: 4, concept: 'anomaly',
    prompt: 'Order the steps of an outlier check in SQL.',
    options: ['Compute the typical value for comparable days', 'Flag values far from it', 'Check the calendar and data quality for flagged days', 'Report which flags are real events and which are errors'], answer: [0, 1, 2, 3],
    explain: 'Comparable context first, then flags, then investigation, then an honest report.' },
  { id: 'sq2-seg-19', topic: 'sql-segments', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'segmentation',
    prompt: 'A "Champions" segment holds 5% of customers and 30% of revenue. What does it tell you?',
    options: ['A small group drives a large share of sales', 'Revenue is spread evenly across customers', 'The segment is too small to matter', 'The segmentation has an error'], answer: 0,
    explain: 'Losing a few of these customers would hurt: they deserve their own retention plan.' },
  { id: 'sq2-seg-20', topic: 'sql-segments', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'segmentation',
    prompt: 'Marketing wants to win back "lapsed regulars". Which rule fits best?',
    options: ['3+ orders last year and none in the last few months', 'Any customer who has ever ordered', 'Customers who signed up this year', 'Customers with the most returns'], answer: 0,
    explain: 'Regular past behaviour plus recent silence is exactly the group a win-back offer is for.' },
  { id: 'sq2-seg-21', topic: 'sql-segments', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'seasonality',
    prompt: 'An outlier rule flags almost every summer day for a seasonal shop. What went wrong?',
    options: ['Days are compared with the yearly average, not the season', 'The z-score threshold is too high', 'Summer data is always wrong', 'The query needs DISTINCT'], answer: 0,
    explain: 'Compare with the same month, week or weekday so normal seasonal peaks are not mistaken for problems.' },
  { id: 'sq2-seg-22', topic: 'sql-segments', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'window-rank',
    prompt: 'Which expression shows, on every row, each customer\'s share of total spend?',
    options: ['spend * 100.0 / SUM(spend) OVER ()', 'spend * 100.0 / SUM(spend)', 'spend / COUNT(*) OVER ()', 'RANK() OVER (ORDER BY spend)'], answer: 0,
    explain: 'SUM(…) OVER () is the grand total on every row without grouping. A plain SUM would collapse the rows into one.' },
  { id: 'sq2-seg-23', topic: 'sql-segments', type: 'mc', kind: 'concept', difficulty: 3, concept: 'segmentation',
    prompt: 'Why should a segmentation report state the date it was calculated?',
    options: ['Customers move between segments over time', 'Segments never change once built', 'Dates make the report look official', 'The database requires it'], answer: 0,
    explain: 'A "Champion" today may be lapsed next quarter. The label is only true for its calculation date.' },
  { id: 'sq2-seg-24', topic: 'sql-segments', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'segmentation',
    prompt: 'Spend deciles look wrong: customers with many small orders land in several deciles at once. What happened?',
    options: ['NTILE ran on order lines instead of one row per customer', 'NTILE cannot handle small orders', 'The deciles need ORDER BY ASC', 'Customers should be grouped by name'], answer: 0,
    explain: 'Aggregate to one row per customer first; otherwise each line is ranked on its own.' },
  { id: 'sq2-seg-25', topic: 'sql-segments', type: 'mc', kind: 'scenario', difficulty: 4, concept: 'outliers',
    prompt: 'One customer spends 40 times the average. What should you do before building segments?',
    options: ['Check whether it is a business account or a data error', 'Delete the customer from the data', 'Put the customer in every segment', 'Ignore it: averages handle outliers'], answer: 0,
    explain: 'A wholesale buyer or a data error can distort every segment. Decide how to treat it, and say so in the report.' },
];
