// SQL quiz bank, part B: GROUP BY / HAVING and CASE (Beginner).
export const SQL_QUIZ_B = [
  // ================================================================ sql-groupby
  { id: 'sq2-grp-01', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'group-by',
    prompt: 'Restaurant database: total **net_sales per restaurant_id** for **July 2026**, rounded to 2 decimals. Return restaurant_id and the total.',
    answer: "SELECT restaurant_id, ROUND(SUM(net_sales), 2) FROM daily_sales WHERE sale_date BETWEEN '2026-07-01' AND '2026-07-31' GROUP BY restaurant_id;",
    traps: [{ sql: 'SELECT restaurant_id, ROUND(SUM(net_sales), 2) FROM daily_sales GROUP BY restaurant_id;', feedback: 'That totals every month since January 2025. Filter sale_date to July 2026 first.' }],
    explain: 'WHERE picks July, GROUP BY makes one row per restaurant. Riverside (2) leads in July, its busiest season.' },
  { id: 'sq2-grp-02', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 1, concept: 'group-by',
    prompt: 'HR database: count **current employees** (termination_date IS NULL) per **location**. Return location and the count.',
    answer: 'SELECT location, COUNT(*) FROM employees WHERE termination_date IS NULL GROUP BY location;',
    traps: [{ sql: 'SELECT location, COUNT(*) FROM employees GROUP BY location;', feedback: 'That counts everyone who ever worked there. Keep only current employees.' }],
    explain: 'North Hub has 231 current staff, South Hub 178 and Head Office 80.' },
  { id: 'sq2-grp-03', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'group-by', ordered: true,
    prompt: 'For each return **reason**, return the reason, the **number of returns** and the **total refund** (2 decimals). Largest total refund first.',
    answer: 'SELECT reason, COUNT(*), ROUND(SUM(refund_amount), 2) AS refunded FROM returns GROUP BY reason ORDER BY refunded DESC;',
    traps: [{ sql: 'SELECT reason, COUNT(*), ROUND(SUM(refund_amount), 2) FROM returns GROUP BY reason ORDER BY reason;', feedback: 'That sorts alphabetically. The task asks for the largest refund total first.' }],
    explain: 'Wrong size leads (528 returns, about 53,423 refunded), ahead of Changed mind and Defective.' },
  { id: 'sq2-grp-04', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'having',
    prompt: 'Restaurant database: which waste **reasons** have **more than 500 entries** from **2026** onwards? Return the reason and the number of entries.',
    answer: "SELECT reason, COUNT(*) FROM waste_log WHERE waste_date >= '2026-01-01' GROUP BY reason HAVING COUNT(*) > 500;",
    traps: [{ sql: "SELECT reason, COUNT(*) FROM waste_log WHERE waste_date >= '2026-01-01' GROUP BY reason;", feedback: 'That returns all five reasons. HAVING keeps only the groups above 500.' }],
    explain: 'WHERE filters rows before grouping; HAVING filters the groups after counting. Expired, Spoiled and Over-prepared pass.' },
  { id: 'sq2-grp-05', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 2, concept: 'group-by', ordered: true,
    prompt: 'HR database: among exit interviews where the person **would return** (would_return = \'Yes\'), count them per **primary_reason**, most common first (reasons with the same count in A to Z order).',
    answer: "SELECT primary_reason, COUNT(*) AS n FROM exit_interviews WHERE would_return = 'Yes' GROUP BY primary_reason ORDER BY n DESC, primary_reason;",
    explain: 'Pay is the top reason among people who would come back (46), a sign that some leavers could be won back with a better offer.' },
  { id: 'sq2-grp-06', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'group-by',
    prompt: 'For orders dated in **2026**, count orders per **channel and status**. Return channel, status and the count.',
    answer: "SELECT channel, status, COUNT(*) FROM orders WHERE order_date >= '2026-01-01' GROUP BY channel, status;",
    traps: [{ sql: "SELECT channel, COUNT(*) FROM orders WHERE order_date >= '2026-01-01' GROUP BY channel;", feedback: 'Group by both columns to get one row per channel and status.' }],
    explain: 'Two grouping columns give one row per combination that exists: five here, because in-store orders are never pending.' },
  { id: 'sq2-grp-07', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'group-by',
    prompt: 'Restaurant database: total operating costs per **cost_type** for months in **2026** (month is text like "2026-03"). Return cost_type and the total (2 decimals).',
    answer: "SELECT cost_type, ROUND(SUM(amount), 2) FROM operating_costs WHERE month LIKE '2026%' GROUP BY cost_type;",
    traps: [{ sql: 'SELECT cost_type, ROUND(SUM(amount), 2) FROM operating_costs GROUP BY cost_type;', feedback: 'That includes 2025. Keep only months starting with 2026.' }],
    explain: 'Rent dominates at about 360,000 for eight months across three sites; marketing is the smallest line after maintenance.' },
  { id: 'sq2-grp-08', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 2, concept: 'group-by', ordered: true,
    prompt: 'HR database: the **average rating** (2 decimals) and the **number of reviews** per **review_year**, oldest year first.',
    answer: 'SELECT review_year, ROUND(AVG(rating), 2), COUNT(*) FROM performance_reviews GROUP BY review_year ORDER BY review_year;',
    explain: 'The average slipped from 3.34 in 2024 to 3.26 in 2025, on almost the same number of reviews.' },
  { id: 'sq2-grp-09', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'having',
    prompt: 'Which product **categories** have an **average list_price above 100**? Return category and the average (2 decimals).',
    answer: 'SELECT category, ROUND(AVG(list_price), 2) FROM products GROUP BY category HAVING AVG(list_price) > 100;',
    traps: [{ sql: 'SELECT category, ROUND(AVG(list_price), 2) FROM products WHERE list_price > 100 GROUP BY category;', feedback: 'WHERE drops the cheap products before averaging, so every category looks expensive. Test the average in HAVING.' }],
    explain: 'Four categories qualify: Tents, Footwear, Sleeping Gear and Backpacks. Filtering rows with WHERE would answer a different question.' },
  { id: 'sq2-grp-10', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'group-by',
    prompt: 'Restaurant database: labour cost per **role** for **April to June 2026** (2 decimals). Return role and the total.',
    answer: "SELECT role, ROUND(SUM(labor_cost), 2) FROM labor_daily WHERE work_date BETWEEN '2026-04-01' AND '2026-06-30' GROUP BY role;",
    explain: 'Front of house costs the most in the quarter, just ahead of the kitchen; management is a fixed cost of about 68,800.' },
  { id: 'sq2-grp-11', topic: 'sql-groupby', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'having',
    prompt: 'HR database: which **department_id**s have **more than 50 current employees**? Return department_id and the count.',
    answer: 'SELECT department_id, COUNT(*) FROM employees WHERE termination_date IS NULL GROUP BY department_id HAVING COUNT(*) > 50;',
    traps: [{ sql: 'SELECT department_id, COUNT(*) FROM employees GROUP BY department_id HAVING COUNT(*) > 50;', feedback: 'Without the termination filter, former employees count too, and more departments pass.' }],
    explain: 'Current staff only: departments 1, 2 and 3 have more than 50 people.' },
  { id: 'sq2-grp-12', topic: 'sql-groupby', type: 'number', kind: 'calculation', difficulty: 2, concept: 'group-by',
    prompt: 'Customers belong to 4 regions, and some have no region (NULL). How many rows does `SELECT region, COUNT(*) FROM customers GROUP BY region` return?',
    answer: 5, verify: () => 4 + 1,
    explain: 'GROUP BY puts all the NULLs into one group of their own, so there are 4 region rows plus 1 NULL row.' },
  { id: 'sq2-grp-13', topic: 'sql-groupby', type: 'number', kind: 'calculation', difficulty: 2, concept: 'having',
    prompt: 'Four groups have 90, 150, 101 and 100 rows. How many groups pass `HAVING COUNT(*) > 100`?',
    answer: 2, verify: () => [90, 150, 101, 100].filter((n) => n > 100).length,
    explain: '150 and 101 pass. 100 is not more than 100: check whether the business meant ">=".' },
  { id: 'sq2-grp-14', topic: 'sql-groupby', type: 'number', kind: 'calculation', difficulty: 2, concept: 'group-by',
    prompt: 'There are 4 regions and 2 channels, but the North has no online orders. How many rows does `GROUP BY region, channel` return?',
    answer: 7, verify: () => 4 * 2 - 1,
    explain: 'GROUP BY only creates rows for combinations that exist in the data: 8 possible, 7 present.' },
  { id: 'sq2-grp-15', topic: 'sql-groupby', type: 'number', kind: 'calculation', difficulty: 3, concept: 'group-by',
    prompt: 'Group A has orders of 10 and 20; group B has one order of 30. How much larger is the average of the two group averages than the overall average order?',
    answer: 2.5, tolerance: 0.001, verify: () => (15 + 30) / 2 - (10 + 20 + 30) / 3,
    explain: 'The group averages are 15 and 30, averaging 22.5; the overall average is 20. Averaging averages gives a one-order group the same weight as a bigger one.' },
  { id: 'sq2-grp-16', topic: 'sql-groupby', type: 'tf', kind: 'concept', difficulty: 2, concept: 'having',
    prompt: 'True or false: HAVING can test aggregates such as COUNT(*), but WHERE cannot.',
    answer: true, explain: 'WHERE runs before grouping, when there is nothing to count yet. HAVING runs after.' },
  { id: 'sq2-grp-17', topic: 'sql-groupby', type: 'tf', kind: 'concept', difficulty: 2, concept: 'group-by',
    prompt: 'True or false: GROUP BY always sorts the result, in every database.',
    answer: false, explain: 'Some databases happen to return groups sorted, others do not. Add ORDER BY whenever the order matters.' },
  { id: 'sq2-grp-18', topic: 'sql-groupby', type: 'tf', kind: 'concept', difficulty: 1, concept: 'group-by',
    prompt: 'True or false: in a grouped query, COUNT(*) counts the rows in each group.',
    answer: true, explain: 'Every aggregate works group by group once GROUP BY is present.' },
  { id: 'sq2-grp-19', topic: 'sql-groupby', type: 'fill', kind: 'concept', difficulty: 1, concept: 'having',
    prompt: 'The clause that filters groups after they have been aggregated is ____.',
    answer: ['HAVING', 'having'], explain: 'HAVING COUNT(*) > 100 keeps only the groups with more than 100 rows.' },
  { id: 'sq2-grp-20', topic: 'sql-groupby', type: 'fill', kind: 'concept', difficulty: 1, concept: 'group-by',
    prompt: 'To show the biggest groups first, write ORDER BY COUNT(*) ____.',
    answer: ['DESC', 'desc'], explain: 'DESC sorts from largest to smallest; without it, the smallest groups come first.' },
  { id: 'sq2-grp-21', topic: 'sql-groupby', type: 'order', kind: 'sequence', difficulty: 2, concept: 'group-by',
    prompt: 'Order the steps of building a grouped report.',
    options: ['Decide the grain: one row per what?', 'Filter the rows you need with WHERE', 'Group and aggregate', 'Filter groups with HAVING, then sort'], answer: [0, 1, 2, 3],
    explain: 'Knowing the grain tells you what to GROUP BY; row filters come before grouping and group filters after.' },
  { id: 'sq2-grp-22', topic: 'sql-groupby', type: 'order', kind: 'sequence', difficulty: 3, concept: 'having',
    prompt: 'Put the parts of this query in the order you write them: "regions with more than 100 completed 2025 orders, most first".',
    options: ['FROM orders', 'WHERE status and date conditions', 'GROUP BY region', 'HAVING COUNT(*) > 100', 'ORDER BY COUNT(*) DESC'], answer: [0, 1, 2, 3, 4],
    explain: 'After SELECT, the clauses always come in this order, which is also the order the database applies them in.' },
  { id: 'sq2-grp-23', topic: 'sql-groupby', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'having',
    prompt: '`SELECT region, COUNT(*) FROM orders WHERE COUNT(*) > 100 GROUP BY region` fails. Why?',
    options: ['Conditions on aggregates belong in HAVING', 'COUNT(*) needs a column name', 'GROUP BY must come before WHERE', 'region must be in quotes'], answer: 0,
    explain: 'WHERE is applied row by row, before anything is counted. Move the test to HAVING COUNT(*) > 100.' },
  { id: 'sq2-grp-24', topic: 'sql-groupby', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'null',
    prompt: 'A grouped report shows a row whose region is NULL, with 75 customers. What does it mean?',
    options: ['Customers with no region form their own group', 'The query has an error', '75 customers were deleted', 'NULL is a region called "NULL"'], answer: 0,
    explain: 'Missing regions are grouped together. Keep the row and label it (COALESCE(region, \'Unknown\')) rather than hiding it.' },
  { id: 'sq2-grp-25', topic: 'sql-groupby', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'group-by',
    prompt: 'A manager wants the average order value per region, but each order has several lines. What is the right approach?',
    options: ['Total each order first, then average the order totals per region', 'Average the line values per region', 'Divide total revenue by the number of lines', 'Take the largest line per region'], answer: 0,
    explain: 'Build the order-level result first (a subquery or CTE), then group by region: averaging lines gives a smaller, wrong figure.' },
  { id: 'sq2-grp-26', topic: 'sql-groupby', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'count-distinct',
    prompt: 'Which query counts the **different customers** who ordered, per region?',
    options: ['SELECT region, COUNT(DISTINCT customer_id) … GROUP BY region', 'SELECT region, COUNT(customer_id) … GROUP BY region', 'SELECT DISTINCT region, COUNT(*) … GROUP BY region', 'SELECT region, SUM(customer_id) … GROUP BY region'], answer: 0,
    explain: 'COUNT(customer_id) counts orders that have a customer; DISTINCT inside COUNT counts each customer once.' },
  { id: 'sq2-grp-27', topic: 'sql-groupby', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'group-by',
    prompt: 'In a grouped query, what does `ORDER BY 2 DESC` sort by?',
    options: ['The second column in the SELECT list', 'The second row of the result', 'Every value above 2', 'The second GROUP BY column only'], answer: 0,
    explain: 'A number in ORDER BY refers to a column position. It is quick, but a named column is clearer to read later.' },
  { id: 'sq2-grp-28', topic: 'sql-groupby', type: 'mc', kind: 'concept', difficulty: 2, concept: 'group-by',
    prompt: 'What is the grain of `SELECT region, channel, SUM(revenue) FROM … GROUP BY region, channel`?',
    options: ['One row per region and channel', 'One row per region', 'One row per order', 'One row in total'], answer: 0,
    explain: 'The GROUP BY columns define what one output row stands for.' },

  // ================================================================ sql-case
  { id: 'sq2-cas-01', topic: 'sql-case', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'case',
    prompt: 'Count products by status: "Phased out" when is_active = 0, otherwise "Active". Return the status and the count.',
    answer: "SELECT CASE WHEN is_active = 0 THEN 'Phased out' ELSE 'Active' END AS status, COUNT(*) FROM products GROUP BY status;",
    explain: 'The CASE label becomes the grouping column: 58 active products and 3 being phased out.' },
  { id: 'sq2-cas-02', topic: 'sql-case', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 2, concept: 'case',
    prompt: 'HR database: count **current employees** by salary band: "Under 40k" (below 40,000), "40k to 60k" (below 60,000), otherwise "60k and over". Return band and count.',
    answer: "SELECT CASE WHEN current_salary < 40000 THEN 'Under 40k' WHEN current_salary < 60000 THEN '40k to 60k' ELSE '60k and over' END AS band, COUNT(*) FROM employees WHERE termination_date IS NULL GROUP BY band;",
    traps: [{ sql: "SELECT CASE WHEN current_salary < 60000 THEN '40k to 60k' WHEN current_salary < 40000 THEN 'Under 40k' ELSE '60k and over' END AS band, COUNT(*) FROM employees WHERE termination_date IS NULL GROUP BY band;", feedback: 'The wider test comes first, so nobody ever reaches "Under 40k". Test the lowest band first here.' }],
    explain: 'Half the current staff (243) earn 40k to 60k; 185 earn under 40k and 61 earn 60k or more.' },
  { id: 'sq2-cas-03', topic: 'sql-case', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'case',
    prompt: 'Restaurant database: count menu items by price band: "Under 10" (below 10), "10 to 20" (10 up to and including 20), otherwise "Over 20". Return band and count.',
    answer: "SELECT CASE WHEN current_price < 10 THEN 'Under 10' WHEN current_price <= 20 THEN '10 to 20' ELSE 'Over 20' END AS band, COUNT(*) FROM menu_items GROUP BY band;",
    explain: 'Ten items under 10, ten between 10 and 20, and five above 20. The band edges must match the wording exactly.' },
  { id: 'sq2-cas-04', topic: 'sql-case', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'case',
    prompt: 'Group returns into "Size" (reason Wrong size) and "Other". Return the group, the number of returns and the total refund (2 decimals).',
    answer: "SELECT CASE WHEN reason = 'Wrong size' THEN 'Size' ELSE 'Other' END AS grp, COUNT(*), ROUND(SUM(refund_amount), 2) FROM returns GROUP BY grp;",
    explain: 'Size problems alone account for 528 of 1,466 returns, about a third of the refund money.' },
  { id: 'sq2-cas-05', topic: 'sql-case', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'conditional-agg',
    prompt: 'HR database: per **location**, count **voluntary** and **involuntary** leavers in two separate columns. Return location, voluntary, involuntary.',
    answer: "SELECT location, SUM(CASE WHEN termination_type = 'Voluntary' THEN 1 ELSE 0 END) AS voluntary, SUM(CASE WHEN termination_type = 'Involuntary' THEN 1 ELSE 0 END) AS involuntary FROM employees GROUP BY location;",
    traps: [{ sql: 'SELECT location, termination_type, COUNT(*) FROM employees GROUP BY location, termination_type;', feedback: 'That returns one row per type. The task wants the two counts side by side, one row per location.' }],
    explain: 'CASE inside SUM counts only the matching rows: North Hub lost 388 people voluntarily and 90 involuntarily.' },
  { id: 'sq2-cas-06', topic: 'sql-case', type: 'number', kind: 'calculation', difficulty: 2, concept: 'case',
    prompt: 'Values 30, 75, 100, 49 and 50 go through `CASE WHEN x >= 100 THEN \'A\' WHEN x >= 50 THEN \'B\' ELSE \'C\' END`. How many get \'B\'?',
    answer: 2, verify: () => [30, 75, 100, 49, 50].filter((x) => x < 100 && x >= 50).length,
    explain: '75 and 50 are B; 100 stops at the first test (A); 30 and 49 fall through to C.' },
  { id: 'sq2-cas-07', topic: 'sql-case', type: 'number', kind: 'calculation', difficulty: 2, concept: 'conditional-agg',
    prompt: 'There are 240 orders, 180 of them completed. What does `SUM(CASE WHEN status = \'completed\' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)` return?',
    answer: 75, tolerance: 0.001, verify: () => (180 * 100) / 240,
    explain: '180 × 100 ÷ 240 = 75, the completion rate in percent. The 100.0 keeps the division from dropping decimals.' },
  { id: 'sq2-cas-08', topic: 'sql-case', type: 'tf', kind: 'concept', difficulty: 2, concept: 'conditional-agg',
    prompt: 'True or false: a CASE expression inside SUM can count only the rows that meet a condition.',
    answer: true, explain: 'SUM(CASE WHEN … THEN 1 ELSE 0 END) is the classic way to put several counts side by side.' },
  { id: 'sq2-cas-09', topic: 'sql-case', type: 'tf', kind: 'concept', difficulty: 1, concept: 'null',
    prompt: 'True or false: COALESCE(NULL, NULL, \'x\', \'y\') returns \'y\'.',
    answer: false, explain: 'COALESCE returns the first value that is not NULL, which is \'x\'.' },
  { id: 'sq2-cas-10', topic: 'sql-case', type: 'fill', kind: 'concept', difficulty: 1, concept: 'case',
    prompt: 'Every CASE expression finishes with the keyword ____.',
    answer: ['END', 'end'], explain: 'CASE WHEN … THEN … ELSE … END. Forgetting END is the most common syntax error with CASE.' },
  { id: 'sq2-cas-11', topic: 'sql-case', type: 'order', kind: 'sequence', difficulty: 2, concept: 'case',
    prompt: 'A discount band is "Deep" above 0.3, "Medium" above 0.15, "Light" above 0, otherwise "None". Order the branches.',
    options: ['WHEN discount > 0.3 THEN \'Deep\'', 'WHEN discount > 0.15 THEN \'Medium\'', 'WHEN discount > 0 THEN \'Light\'', 'ELSE \'None\''], answer: [0, 1, 2, 3],
    explain: 'CASE stops at the first true branch, so the strictest test goes first and ELSE catches the rest.' },
  { id: 'sq2-cas-12', topic: 'sql-case', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'conditional-agg',
    prompt: '`AVG(CASE WHEN channel = \'Online\' THEN 1.0 ELSE 0 END)` returns 0.42. What does it mean?',
    options: ['42% of the rows are online orders', 'Online orders are worth 0.42 on average', '0.42 of an order is online', 'The query needs SUM instead'], answer: 0,
    explain: 'The average of 1s and 0s is the share of 1s: a neat way to write a percentage.' },
  { id: 'sq2-cas-13', topic: 'sql-case', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'case',
    prompt: '`SUM(CASE WHEN status = \'Completed\' THEN 1 END)` returns NULL, although there are completed orders. Why?',
    options: ['The data says \'completed\', so no row matched', 'SUM cannot add the number 1', 'CASE needs brackets around it', 'NULL means zero orders'], answer: 0,
    explain: 'Text comparison with = is case-sensitive in SQLite, so nothing matched and every CASE gave NULL; the SUM of only NULLs is NULL. Add ELSE 0 as well.' },
  { id: 'sq2-cas-14', topic: 'sql-case', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'case',
    prompt: 'Marketing wants customers labelled "New" (signed up in the last 90 days) or "Existing". Where should that rule live?',
    options: ['In a CASE column, so the rule is visible and reusable', 'In a spreadsheet after exporting everything', 'In the customer table, typed by hand', 'Nowhere: the dates speak for themselves'], answer: 0,
    explain: 'A CASE on signup_date states the rule once, in the query, where anyone can check and change it.' },
];
