// SQL quiz bank, part C: joins, multiple joins, subqueries and UNION (Intermediate).
const NET = 'oi.quantity * oi.unit_price * (1 - oi.discount_pct)';

export const SQL_QUIZ_C = [
  // ================================================================ sql-joins
  { id: 'sq2-jn-01', topic: 'sql-joins', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'inner-join',
    prompt: 'Count orders dated in **2026** per **store_name** (join orders to stores). Return store_name and the count.',
    answer: "SELECT s.store_name, COUNT(*) FROM orders o JOIN stores s ON s.store_id = o.store_id WHERE o.order_date >= '2026-01-01' GROUP BY s.store_name;",
    traps: [{ sql: 'SELECT s.store_name, COUNT(*) FROM orders o JOIN stores s ON s.store_id = o.store_id GROUP BY s.store_name;', feedback: 'That counts every year since 2024. Keep only orders from 2026.' }],
    explain: 'Online orders have no store, so the inner join leaves them out, which is right for a per-store count. Northgate is the busiest store in 2026.' },
  { id: 'sq2-jn-02', topic: 'sql-joins', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 2, concept: 'inner-join',
    prompt: 'HR database: count **current employees** per **department name**. Return the department name and the count.',
    answer: 'SELECT d.name, COUNT(*) FROM employees e JOIN departments d ON d.department_id = e.department_id WHERE e.termination_date IS NULL GROUP BY d.name;',
    traps: [{ sql: 'SELECT d.name, COUNT(*) FROM employees e JOIN departments d ON d.department_id = e.department_id GROUP BY d.name;', feedback: 'That includes people who have left. Filter termination_date IS NULL.' }],
    explain: 'Joining turns department IDs into names people recognise: Operations (179) and Transport (140) are the largest.' },
  { id: 'sq2-jn-03', topic: 'sql-joins', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'inner-join', ordered: true,
    prompt: 'Restaurant database: total purchases (line_total, 2 decimals) per **supplier name** for deliveries in **2026**, largest first.',
    answer: "SELECT s.name, ROUND(SUM(p.line_total), 2) AS spend FROM purchases p JOIN suppliers s ON s.supplier_id = p.supplier_id WHERE p.delivery_date >= '2026-01-01' GROUP BY s.name ORDER BY spend DESC;",
    traps: [{ sql: 'SELECT s.name, ROUND(SUM(p.line_total), 2) AS spend FROM purchases p JOIN suppliers s ON s.supplier_id = p.supplier_id GROUP BY s.name ORDER BY spend DESC;', feedback: 'That includes 2025. Filter delivery_date from 2026-01-01.' }],
    explain: 'Prime Meats is the biggest supplier by far in 2026 (about 277,868), which is why its price rise hurts.' },
  { id: 'sq2-jn-04', topic: 'sql-joins', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'left-join',
    prompt: 'For **every store**, count its orders dated **2026-08-31**, showing **0** for stores with none. Return store_name and the count.',
    answer: "SELECT s.store_name, COUNT(o.order_id) FROM stores s LEFT JOIN orders o ON o.store_id = s.store_id AND o.order_date = '2026-08-31' GROUP BY s.store_name;",
    traps: [{ sql: "SELECT s.store_name, COUNT(o.order_id) FROM stores s LEFT JOIN orders o ON o.store_id = s.store_id WHERE o.order_date = '2026-08-31' GROUP BY s.store_name;", feedback: 'The date test in WHERE removes the stores with no orders, so Canyon disappears. Put it in the ON clause.' }],
    explain: 'The date condition belongs in ON, so stores without orders stay with a count of 0 (Canyon). COUNT(o.order_id) counts only real matches.' },
  { id: 'sq2-jn-05', topic: 'sql-joins', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'anti-join',
    prompt: 'How many **products have never been returned**? (A return links to an order line, which links to a product.) Return one number.',
    answer: 'SELECT COUNT(*) FROM products p WHERE NOT EXISTS (SELECT 1 FROM order_items oi JOIN returns r ON r.order_item_id = oi.order_item_id WHERE oi.product_id = p.product_id);',
    explain: 'Only 3 products have never come back, and they are the 3 that never sold: a check on sales alone gives the same number here by coincidence, so be sure your query really looks at returns.' },
  { id: 'sq2-jn-06', topic: 'sql-joins', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 3, concept: 'anti-join',
    prompt: 'Restaurant database: how many **ingredients** have **no waste entries at Downtown** (restaurant_id 1) from **2026-01-01** onwards? Return one number.',
    answer: "SELECT COUNT(*) FROM ingredients i LEFT JOIN waste_log w ON w.ingredient_id = i.ingredient_id AND w.restaurant_id = 1 AND w.waste_date >= '2026-01-01' WHERE w.ingredient_id IS NULL;",
    explain: 'The filters on the right-hand table go into ON, and the IS NULL test in WHERE keeps the ingredients with no match: 3.' },
  { id: 'sq2-jn-07', topic: 'sql-joins', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'inner-join',
    prompt: 'HR database: join exit_interviews to employees and return, for each **would_return** answer, the **number of leavers** and their **average current_salary** (0 decimals).',
    answer: 'SELECT x.would_return, COUNT(*), ROUND(AVG(e.current_salary), 0) FROM exit_interviews x JOIN employees e ON e.employee_id = x.employee_id GROUP BY x.would_return;',
    explain: 'Salaries barely differ between the groups (about 40,000 to 43,000), so pay level alone does not explain who would come back.' },
  { id: 'sq2-jn-08', topic: 'sql-joins', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'inner-join',
    prompt: 'HR database: how many **current employees** report to a manager who has **already left** (the manager\'s termination_date is filled)? Return one number.',
    answer: 'SELECT COUNT(*) FROM employees e JOIN employees m ON m.employee_id = e.manager_id WHERE e.termination_date IS NULL AND m.termination_date IS NOT NULL;',
    traps: [{ sql: 'SELECT COUNT(*) FROM employees e JOIN employees m ON m.employee_id = e.manager_id WHERE m.termination_date IS NOT NULL;', feedback: 'That also counts people who have left themselves. Keep only current employees.' }],
    explain: 'A self-join compares each person with their manager: 122 current staff still report to someone who has gone, a gap HR should fix.' },
  { id: 'sq2-jn-09', topic: 'sql-joins', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'left-join',
    prompt: 'HR database: for **current Head Office** employees, how many have **no manager** on record at all? Use a LEFT JOIN to the manager and return one number.',
    answer: "SELECT COUNT(*) FROM employees e LEFT JOIN employees m ON m.employee_id = e.manager_id WHERE e.location = 'Head Office' AND e.termination_date IS NULL AND m.employee_id IS NULL;",
    explain: '28 Head Office people have no manager, mostly account and department managers. Check with HR whether that is the structure or missing data.' },
  { id: 'sq2-jn-10', topic: 'sql-joins', type: 'number', kind: 'calculation', difficulty: 2, concept: 'left-join',
    prompt: 'There are 5 stores. On one day, 4 of them have orders (2, 3, 3 and 1) and one has none. How many rows does `stores LEFT JOIN orders` (for that day) return?',
    answer: 10, verify: () => 2 + 3 + 3 + 1 + 1,
    explain: 'Each order makes a row (9), and the store without orders still appears once with NULLs: 10 rows. COUNT(o.order_id) gives it 0.' },
  { id: 'sq2-jn-11', topic: 'sql-joins', type: 'number', kind: 'calculation', difficulty: 2, concept: 'inner-join',
    prompt: 'Orders on one day: Northgate 3, Riverside 3, Harborview 2, Summit 1, Canyon none. How many rows does an INNER JOIN of the 5 stores to that day\'s orders return?',
    answer: 9, verify: () => 2 + 3 + 3 + 1,
    explain: 'An inner join keeps only matched rows, so the store with no orders vanishes: 9 rows.' },
  { id: 'sq2-jn-12', topic: 'sql-joins', type: 'number', kind: 'calculation', difficulty: 3, concept: 'anti-join',
    prompt: 'A table of 4,571 customers is LEFT JOINed to orders, and 3,380 distinct customers have at least one order. How many customers does `WHERE o.order_id IS NULL` leave?',
    answer: 1191, verify: () => 4571 - 3380,
    explain: '4,571 − 3,380 = 1,191 customers with no order: the anti-join pattern.' },
  { id: 'sq2-jn-13', topic: 'sql-joins', type: 'tf', kind: 'concept', difficulty: 2, concept: 'left-join',
    prompt: 'True or false: after a LEFT JOIN, columns from the right table are NULL for left rows that found no match.',
    answer: true, explain: 'That is how you find the unmatched rows: test a right-table key with IS NULL.' },
  { id: 'sq2-jn-14', topic: 'sql-joins', type: 'tf', kind: 'concept', difficulty: 3, concept: 'join-filter',
    prompt: 'True or false: in a LEFT JOIN, a condition on the right table gives the same result in ON as in WHERE.',
    answer: false, explain: 'In ON it only limits which rows match; in WHERE it removes the unmatched left rows, turning the query into an inner join.' },
  { id: 'sq2-jn-15', topic: 'sql-joins', type: 'fill', kind: 'concept', difficulty: 2, concept: 'inner-join',
    prompt: 'The clause that says which columns link the two tables, as in `JOIN stores s ____ s.store_id = o.store_id`, is ____.',
    answer: ['ON', 'on'], explain: 'ON holds the join condition. Without it every row is paired with every other row.' },
  { id: 'sq2-jn-16', topic: 'sql-joins', type: 'fill', kind: 'concept', difficulty: 2, concept: 'left-join',
    prompt: 'The join that keeps every row of the first table, matched or not, is the ____ JOIN.',
    answer: ['LEFT', 'left', 'LEFT OUTER', 'left outer'], explain: 'LEFT JOIN keeps all rows on the left and fills the right side with NULL where nothing matches.' },
  { id: 'sq2-jn-17', topic: 'sql-joins', type: 'order', kind: 'sequence', difficulty: 3, concept: 'left-join',
    prompt: 'Order the steps to list customers who never ordered.',
    options: ['Start FROM customers', 'LEFT JOIN orders on customer_id', 'Keep rows WHERE the order_id is NULL', 'Select the customer columns you need'], answer: [0, 1, 2, 3],
    explain: 'The table you want everyone from goes first; the LEFT JOIN keeps them; IS NULL keeps only those with nothing to match.' },
  { id: 'sq2-jn-18', topic: 'sql-joins', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'join-filter',
    prompt: 'A "stores with their orders today, including stores with none" query leaves out Canyon, which had no orders. The date test is in WHERE. What is the fix?',
    options: ['Move the date test into the ON clause', 'Use an INNER JOIN instead', 'Add DISTINCT to the SELECT', 'Sort the stores by name'], answer: 0,
    explain: 'In WHERE, the test fails for Canyon\'s NULL row and removes it. In ON, it only decides which orders match.' },
  { id: 'sq2-jn-19', topic: 'sql-joins', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'inner-join',
    prompt: 'An inner join of orders to stores returns fewer rows than the orders table has. What does that tell you?',
    options: ['Some orders have no matching store, such as online orders', 'The stores table has duplicate rows', 'The join condition is always wrong', 'Some orders were deleted'], answer: 0,
    explain: 'Rows without a match drop out of an inner join. Here that is expected: online orders have no store.' },
  { id: 'sq2-jn-20', topic: 'sql-joins', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'left-join',
    prompt: 'A manager wants every product with its 2026 revenue, showing 0 for products that did not sell. What do you write?',
    options: ['Products LEFT JOIN sales (2026 in ON), with COALESCE(SUM(…), 0)', 'Products INNER JOIN sales WHERE the year is 2026', 'Sales LEFT JOIN products WHERE revenue > 0', 'Two separate queries pasted together'], answer: 0,
    explain: 'Start from the list you want complete, keep the year test in ON, and turn the missing totals into 0.' },
  { id: 'sq2-jn-21', topic: 'sql-joins', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'inner-join',
    prompt: 'Each employee has a manager_id pointing at another employee. How do you show each person next to their manager\'s name?',
    options: ['Join the employees table to itself with two aliases', 'Use UNION on the employees table', 'GROUP BY manager_id', 'Use a CASE on manager_id'], answer: 0,
    explain: 'A self-join treats one table as two: e for the employee and m for the manager, linked by m.employee_id = e.manager_id.' },

  // ================================================================ sql-multijoins
  { id: 'sq2-mj-01', topic: 'sql-multijoins', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'inner-join',
    prompt: 'Per product **category**, return the **number of returns** and the **total refund** (2 decimals). (returns → order_items → products)',
    answer: 'SELECT p.category, COUNT(*), ROUND(SUM(r.refund_amount), 2) FROM returns r JOIN order_items oi ON oi.order_item_id = r.order_item_id JOIN products p ON p.product_id = oi.product_id GROUP BY p.category;',
    explain: 'Two joins walk from the return to its product. Footwear has the largest refunds (about 55,645) and Apparel the most returns.' },
  { id: 'sq2-mj-02', topic: 'sql-multijoins', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'inner-join',
    prompt: 'HR database: the **average 2025 rating** (2 decimals) and the **number of reviews** per **department name**.',
    answer: 'SELECT d.name, ROUND(AVG(pr.rating), 2), COUNT(*) FROM performance_reviews pr JOIN employees e ON e.employee_id = pr.employee_id JOIN departments d ON d.department_id = e.department_id WHERE pr.review_year = 2025 GROUP BY d.name;',
    traps: [{ sql: 'SELECT d.name, ROUND(AVG(pr.rating), 2), COUNT(*) FROM performance_reviews pr JOIN employees e ON e.employee_id = pr.employee_id JOIN departments d ON d.department_id = e.department_id GROUP BY d.name;', feedback: 'That mixes 2024 and 2025. Keep review_year = 2025.' }],
    explain: 'Finance rates highest (3.53) but on only 15 reviews; always show the count next to an average.' },
  { id: 'sq2-mj-03', topic: 'sql-multijoins', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 3, concept: 'inner-join',
    prompt: 'Restaurant database: net sales (2 decimals) per **restaurant name** and **menu category** for **July 2026**. Return name, category and net sales.',
    answer: "SELECT r.name, m.category, ROUND(SUM(ds.net_sales), 2) FROM daily_sales ds JOIN restaurants r ON r.restaurant_id = ds.restaurant_id JOIN menu_items m ON m.menu_item_id = ds.menu_item_id WHERE ds.sale_date BETWEEN '2026-07-01' AND '2026-07-31' GROUP BY r.name, m.category;",
    explain: 'The sales table sits in the middle, with one lookup on each side. Mains bring in the most at every site.' },
  { id: 'sq2-mj-04', topic: 'sql-multijoins', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'inner-join',
    prompt: `Net revenue (${NET}, 2 decimals) per **store region** for **completed in-store orders** dated in **2026**. Return region and revenue.`,
    answer: `SELECT s.region, ROUND(SUM(${NET}), 2) FROM order_items oi JOIN orders o ON o.order_id = oi.order_id JOIN stores s ON s.store_id = o.store_id WHERE o.status = 'completed' AND o.order_date >= '2026-01-01' GROUP BY s.region;`,
    traps: [{ sql: `SELECT s.region, ROUND(SUM(${NET}), 2) FROM order_items oi JOIN orders o ON o.order_id = oi.order_id JOIN stores s ON s.store_id = o.store_id WHERE o.order_date >= '2026-01-01' GROUP BY s.region;`, feedback: 'Cancelled orders are included. Keep status = \'completed\'.' }],
    explain: 'Revenue lives on the lines, status and date on the order, region on the store: three tables for one number per region.' },
  { id: 'sq2-mj-05', topic: 'sql-multijoins', type: 'number', kind: 'calculation', difficulty: 2, concept: 'fan-out',
    prompt: '1,000 orders are joined to their order lines, and orders have 1.7 lines on average. About how many rows does the join return?',
    answer: 1700, verify: () => 1000 * 1.7,
    explain: 'Each order repeats once per line: 1,000 × 1.7 = 1,700 rows. Anything stored once per order is now repeated.' },
  { id: 'sq2-mj-06', topic: 'sql-multijoins', type: 'number', kind: 'calculation', difficulty: 3, concept: 'fan-out',
    prompt: 'An order with 3 lines has a shipping fee of 4.95. After joining orders to order lines, what does SUM(shipping_fee) give for that order?',
    answer: 14.85, tolerance: 0.001, verify: () => Math.round(4.95 * 3 * 100) / 100,
    explain: 'The fee is repeated on all 3 rows: 4.95 × 3 = 14.85, three times too much. Sum order-level amounts before joining to lines.' },
  { id: 'sq2-mj-07', topic: 'sql-multijoins', type: 'tf', kind: 'concept', difficulty: 2, concept: 'fan-out',
    prompt: 'True or false: joining to a lookup table on its primary key never adds rows.',
    answer: true, explain: 'A primary key is unique, so each row matches at most once. Duplicates appear when the key on the other side is not unique.' },
  { id: 'sq2-mj-08', topic: 'sql-multijoins', type: 'order', kind: 'sequence', difficulty: 3, concept: 'fan-out',
    prompt: 'Order the steps to add product category and store region to order lines safely.',
    options: ['Start from the table at the grain you want (order_items)', 'Join orders on order_id', 'Join products and stores on their keys', 'Check the row count still equals the number of lines'], answer: [0, 1, 2, 3],
    explain: 'Each join goes from many to one, so the grain stays one row per line; the final count proves it.' },
  { id: 'sq2-mj-09', topic: 'sql-multijoins', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'fan-out',
    prompt: 'Joining 19,510 order lines to a product_prices table returns 19,980 rows. What does that tell you?',
    options: ['Some products have more than one price row', 'Some order lines were duplicated in the source', 'The join dropped 470 lines', 'Nothing: joins often add rows'], answer: 0,
    explain: 'The lookup is not unique per product, so those lines appear twice. Pick one price per product (for example the current one) before joining.' },
  { id: 'sq2-mj-10', topic: 'sql-multijoins', type: 'mc', kind: 'scenario', difficulty: 4, concept: 'left-join',
    prompt: 'Revenue per region: in-store orders use the store\'s region, online orders the customer\'s region. How do you build it?',
    options: ['LEFT JOIN both stores and customers, and pick the region by channel', 'INNER JOIN stores only, since every order has a store', 'INNER JOIN customers only, using their home region', 'Join stores to customers directly on the region column'], answer: 0,
    explain: 'Both joins must be LEFT, or one channel disappears. Then CASE WHEN channel = \'Online\' THEN c.region ELSE s.region END chooses the right one.' },

  // ================================================================ sql-subqueries
  { id: 'sq2-sub-01', topic: 'sql-subqueries', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'subquery',
    prompt: 'How many products are priced **above the average list_price of their own category**? Return one number.',
    answer: 'SELECT COUNT(*) FROM products p WHERE p.list_price > (SELECT AVG(q.list_price) FROM products q WHERE q.category = p.category);',
    traps: [{ sql: 'SELECT COUNT(*) FROM products p WHERE p.list_price > (SELECT AVG(list_price) FROM products);', feedback: 'That compares with the average of all products, not of the product\'s own category.' }],
    explain: 'A correlated subquery recalculates the average for each product\'s category: 25 products sit above their category average.' },
  { id: 'sq2-sub-02', topic: 'sql-subqueries', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 3, concept: 'subquery',
    prompt: 'Restaurant database: in **July 2026**, how many menu items sold **more portions than the average item** did that month (all restaurants together)? Return one number.',
    answer: "WITH t AS (SELECT menu_item_id, SUM(qty_sold) AS q FROM daily_sales WHERE sale_date BETWEEN '2026-07-01' AND '2026-07-31' GROUP BY menu_item_id) SELECT COUNT(*) FROM t WHERE q > (SELECT AVG(q) FROM t);",
    traps: [{ sql: "SELECT COUNT(DISTINCT menu_item_id) FROM daily_sales WHERE sale_date BETWEEN '2026-07-01' AND '2026-07-31' AND qty_sold > (SELECT AVG(qty_sold) FROM daily_sales WHERE sale_date BETWEEN '2026-07-01' AND '2026-07-31');", feedback: 'That compares single daily rows with the average daily row. Total each item for the month first, then compare the totals.' }],
    explain: 'Two steps: total per item, then compare with the average of those totals. 9 of the 25 items beat the average.' },
  { id: 'sq2-sub-03', topic: 'sql-subqueries', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'subquery',
    prompt: 'HR database: how many **current employees** earn more than the **average current salary of their own department**? Return one number.',
    answer: 'SELECT COUNT(*) FROM employees e WHERE e.termination_date IS NULL AND e.current_salary > (SELECT AVG(x.current_salary) FROM employees x WHERE x.termination_date IS NULL AND x.department_id = e.department_id);',
    explain: '202 of 489 current employees earn above their department average: fewer than half, because a few high salaries pull the averages up.' },
  { id: 'sq2-sub-04', topic: 'sql-subqueries', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 3, concept: 'subquery',
    prompt: 'How many customers placed their **first order** (of any status) in **2026 or later**? Ignore orders without a customer. Return one number.',
    answer: "SELECT COUNT(*) FROM (SELECT customer_id, MIN(order_date) AS first_order FROM orders WHERE customer_id IS NOT NULL GROUP BY customer_id) WHERE first_order >= '2026-01-01';",
    traps: [{ sql: "SELECT COUNT(DISTINCT customer_id) FROM orders WHERE order_date >= '2026-01-01';", feedback: 'That counts every customer who ordered in 2026, including long-standing ones. Find each customer\'s first order date first.' }],
    explain: 'The subquery finds each customer\'s first order; the outer query keeps those from 2026: 1,086 new buyers.' },
  { id: 'sq2-sub-05', topic: 'sql-subqueries', type: 'number', kind: 'calculation', difficulty: 2, concept: 'subquery',
    prompt: 'A subquery returns an average customer spend of 312. Five customers spent 250, 300, 320, 400 and 290. How many are above the average?',
    answer: 2, verify: () => [250, 300, 320, 400, 290].filter((v) => v > 312).length,
    explain: '320 and 400 are above 312. The subquery produces one number, which the outer query compares with every row.' },
  { id: 'sq2-sub-06', topic: 'sql-subqueries', type: 'tf', kind: 'concept', difficulty: 2, concept: 'subquery',
    prompt: 'True or false: EXISTS stops searching as soon as it finds one matching row.',
    answer: true, explain: 'EXISTS only needs to know whether any row exists, which makes it efficient for "has at least one" questions.' },
  { id: 'sq2-sub-07', topic: 'sql-subqueries', type: 'fill', kind: 'concept', difficulty: 2, concept: 'subquery',
    prompt: 'The keyword that tests whether a subquery returns at least one row is ____.',
    answer: ['EXISTS', 'exists'], explain: 'WHERE EXISTS (SELECT 1 FROM …) is true when the subquery finds anything; NOT EXISTS when it finds nothing.' },
  { id: 'sq2-sub-08', topic: 'sql-subqueries', type: 'order', kind: 'sequence', difficulty: 3, concept: 'cte',
    prompt: 'Order the steps to find customers who spend more than the average customer.',
    options: ['Total the spend per customer', 'Average those customer totals', 'Compare each customer total with that average', 'Return the customers above it'], answer: [0, 1, 2, 3],
    explain: 'The average must be of customer totals, not of order lines, so the per-customer step comes first.' },
  { id: 'sq2-sub-09', topic: 'sql-subqueries', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'subquery',
    prompt: 'In `WHERE price > (SELECT AVG(price) FROM products)`, how often is the subquery worked out?',
    options: ['Once, since it does not depend on the outer row', 'Once for every product', 'Twice, before and after filtering', 'Never: it is replaced by a join'], answer: 0,
    explain: 'An uncorrelated subquery has no link to the outer row, so its single result is reused for every comparison.' },

  // ================================================================ sql-union
  { id: 'sq2-uni-01', topic: 'sql-union', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 3, concept: 'union',
    prompt: 'Restaurant database: return two rows for **July 2026**: ("Labour", total labor_cost) and ("Purchases", total line_total), each rounded to 2 decimals.',
    answer: "SELECT 'Labour' AS source, ROUND(SUM(labor_cost), 2) AS amount FROM labor_daily WHERE work_date BETWEEN '2026-07-01' AND '2026-07-31' UNION ALL SELECT 'Purchases', ROUND(SUM(line_total), 2) FROM purchases WHERE delivery_date BETWEEN '2026-07-01' AND '2026-07-31';",
    explain: 'Each SELECT makes one labelled row, and UNION ALL stacks them: purchases (about 131,158) were a little higher than labour (about 120,225).' },
  { id: 'sq2-uni-02', topic: 'sql-union', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 3, concept: 'union',
    prompt: 'HR database: how many **different employees** either left **voluntarily in 2025** or gave an **exit interview dated 2025**? Return one number.',
    answer: "SELECT COUNT(*) FROM (SELECT employee_id FROM employees WHERE termination_type = 'Voluntary' AND termination_date LIKE '2025%' UNION SELECT employee_id FROM exit_interviews WHERE exit_date LIKE '2025%');",
    traps: [{ sql: "SELECT COUNT(*) FROM (SELECT employee_id FROM employees WHERE termination_type = 'Voluntary' AND termination_date LIKE '2025%' UNION ALL SELECT employee_id FROM exit_interviews WHERE exit_date LIKE '2025%');", feedback: 'UNION ALL keeps people who appear in both lists twice. UNION removes the duplicates.' }],
    explain: 'The two lists hold the same 131 people, so UNION ALL would double them to 262. UNION counts each person once.' },
  { id: 'sq2-uni-03', topic: 'sql-union', type: 'number', kind: 'calculation', difficulty: 2, concept: 'union',
    prompt: 'One SELECT returns 120 distinct rows, another 80 distinct rows, and 15 rows appear in both. How many rows does UNION return?',
    answer: 185, verify: () => 120 + 80 - 15,
    explain: 'UNION removes the 15 repeats: 120 + 80 − 15 = 185. UNION ALL would return all 200.' },
  { id: 'sq2-uni-04', topic: 'sql-union', type: 'order', kind: 'sequence', difficulty: 2, concept: 'union',
    prompt: 'Order the steps to stack two monthly tables with a label showing where each row came from.',
    options: ['Select the same columns, in the same order, from each table', 'Add a constant label column to each SELECT', 'Join the SELECTs with UNION ALL', 'Sort the combined result once, at the end'], answer: [0, 1, 2, 3],
    explain: 'Matching columns, a source label, UNION ALL (the rows cannot overlap), and a single ORDER BY for the whole result.' },
  { id: 'sq2-uni-05', topic: 'sql-union', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'union',
    prompt: 'After a UNION, a column named "amount" contains dates for some rows. What went wrong?',
    options: ['The columns were listed in a different order in each SELECT', 'UNION changes dates into amounts', 'UNION needs brackets around each SELECT', 'The second table has no amount column'], answer: 0,
    explain: 'UNION pairs columns by position, not by name. List the columns in the same order in every SELECT.' },
  { id: 'sq2-uni-06', topic: 'sql-union', type: 'tf', kind: 'concept', difficulty: 2, concept: 'union',
    prompt: 'True or false: UNION also removes duplicate rows that come from the same SELECT.',
    answer: true, explain: 'UNION removes every duplicate in the combined result, wherever it came from. Use UNION ALL to keep them.' },
];
