// SQL quiz bank, part A: SELECT, WHERE and aggregates (Beginner). SQL questions are graded by
// running the learner's query on the practice database and comparing results.
export const SQL_QUIZ_A = [
  // ================================================================ sql-select
  { id: 'sq2-sel-01', topic: 'sql-select', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 1, concept: 'select-basics', ordered: true,
    prompt: 'Restaurant database: return the **3 cheapest** menu items, with **name** and **current_price**, cheapest first.',
    answer: 'SELECT name, current_price FROM menu_items ORDER BY current_price LIMIT 3;',
    traps: [{ sql: 'SELECT name, current_price FROM menu_items ORDER BY current_price DESC LIMIT 3;', feedback: 'DESC gives the most expensive items. Cheapest first is the default (ascending) order.' }],
    explain: 'ORDER BY sorts ascending unless you add DESC, and LIMIT keeps the first rows after sorting: Espresso, Cappuccino and Side Salad.' },
  { id: 'sq2-sel-02', topic: 'sql-select', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 1, concept: 'select-basics', ordered: true,
    prompt: 'HR database: list every department\'s **name** and **cost_center**, sorted by name A to Z.',
    answer: 'SELECT name, cost_center FROM departments ORDER BY name;',
    explain: 'Choose the columns, then sort. Seven departments, from Customer Service to Transport.' },
  { id: 'sq2-sel-03', topic: 'sql-select', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'select-basics', ordered: true,
    prompt: 'Return the **5 most expensive products** with **sku**, **product_name** and **price_with_vat** = list_price × 1.2, rounded to 2 decimals. Most expensive first.',
    answer: 'SELECT sku, product_name, ROUND(list_price * 1.2, 2) AS price_with_vat FROM products ORDER BY list_price DESC LIMIT 5;',
    traps: [{ sql: 'SELECT sku, product_name, ROUND(list_price * 1.2, 2) FROM products ORDER BY list_price LIMIT 5;', feedback: 'Without DESC you get the cheapest five.' }],
    explain: 'A calculated column needs an alias to read well. The Four-Season Summit Tent tops the list at 718.8 with VAT.' },
  { id: 'sq2-sel-04', topic: 'sql-select', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 1, concept: 'select-basics',
    prompt: 'Restaurant database: which **different cost types** appear in operating_costs? Return each cost_type once.',
    answer: 'SELECT DISTINCT cost_type FROM operating_costs;',
    traps: [{ sql: 'SELECT cost_type FROM operating_costs;', feedback: 'Without DISTINCT every one of the 240 rows comes back. DISTINCT keeps each value once.' }],
    explain: 'DISTINCT removes repeats: four cost types (Rent, Utilities, Marketing, Maintenance) hidden in 240 rows.' },
  { id: 'sq2-sel-05', topic: 'sql-select', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'select-basics', ordered: true,
    prompt: 'Return the **5 most recent orders**: order_id, order_date and channel. Newest first; for orders on the same date, show the **highest order_id first**.',
    answer: 'SELECT order_id, order_date, channel FROM orders ORDER BY order_date DESC, order_id DESC LIMIT 5;',
    traps: [{ sql: 'SELECT order_id, order_date, channel FROM orders ORDER BY order_date, order_id LIMIT 5;', feedback: 'Ascending order starts with the oldest orders from 2024.' }],
    explain: 'Many orders share the last date, so the second sort column decides which five you get. Without it the result is not guaranteed to be the same each time.' },
  { id: 'sq2-sel-06', topic: 'sql-select', type: 'number', kind: 'calculation', difficulty: 2, concept: 'select-basics',
    prompt: '`SELECT * FROM products ORDER BY product_id LIMIT 5 OFFSET 10` returns five rows. Which row number (in that order) is the first one returned?',
    answer: 11, verify: () => 10 + 1,
    explain: 'OFFSET 10 skips the first ten rows, so the result starts at row 11 and ends at row 15. This is how reports page through results.' },
  { id: 'sq2-sel-07', topic: 'sql-select', type: 'number', kind: 'calculation', difficulty: 2, concept: 'select-basics',
    prompt: 'Orders come from 4 regions and 2 channels, and every region uses both channels. How many rows does `SELECT DISTINCT region, channel FROM orders` return?',
    answer: 8, verify: () => 4 * 2,
    explain: 'DISTINCT works on the whole row: each region-channel combination appears once, 4 × 2 = 8.' },
  { id: 'sq2-sel-08', topic: 'sql-select', type: 'tf', kind: 'concept', difficulty: 1, concept: 'select-basics',
    prompt: 'True or false: ORDER BY can sort by a column that is not in the SELECT list.',
    answer: true, explain: 'You can list product names sorted by price without showing the price, although showing it usually helps the reader.' },
  { id: 'sq2-sel-09', topic: 'sql-select', type: 'tf', kind: 'concept', difficulty: 2, concept: 'select-basics',
    prompt: 'True or false: LIMIT without ORDER BY always returns the same rows, in the order they were inserted.',
    answer: false, explain: 'Without ORDER BY the database may return rows in any order. Always sort before LIMIT if the result matters.' },
  { id: 'sq2-sel-10', topic: 'sql-select', type: 'fill', kind: 'concept', difficulty: 1, concept: 'select-basics',
    prompt: 'Fill the gap with the keyword that names a calculated column in the result: `list_price * 1.2 ____ price_with_vat`',
    answer: ['AS', 'as'], explain: 'AS names the output column. The name exists only in the result, not in the table.' },
  { id: 'sq2-sel-11', topic: 'sql-select', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'select-basics',
    prompt: '`... ORDER BY current_price DESC LIMIT 3` returns a different third dish from your colleague\'s identical query. The 3rd and 4th dishes cost the same. Why?',
    options: ['A tie at the cut-off; add a second sort column', 'LIMIT counts from zero', 'DESC sorts text before numbers', 'The prices changed between the runs'], answer: 0,
    explain: 'With a tie, either dish can come third. A second column (for example the name) makes the order, and the result, repeatable.' },
  { id: 'sq2-sel-12', topic: 'sql-select', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'select-basics',
    prompt: 'What does `SELECT DISTINCT city, region FROM customers` return?',
    options: ['Each different city and region combination once', 'Each city once, whatever its region', 'Each region once, with one city', 'Every customer with their city and region'], answer: 0,
    explain: 'DISTINCT applies to the whole selected row, so a city recorded with two different regions appears twice.' },
  { id: 'sq2-sel-13', topic: 'sql-select', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'select-basics',
    prompt: 'Sorting a price column gives 100, 25, 9 instead of 9, 25, 100. What is the likely cause?',
    options: ['The prices are stored as text, so they sort alphabetically', 'ORDER BY sorts from largest by default', 'The column needs DISTINCT', 'LIMIT was applied before sorting'], answer: 0,
    explain: 'Text sorts character by character, so "100" comes before "25". Store numbers as numbers, or sort by CAST(price AS REAL).' },

  // ================================================================ sql-where
  { id: 'sq2-whr-01', topic: 'sql-where', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'where-logic',
    prompt: 'Restaurant database: how many waste_log entries with reason **Expired** did the Airport (restaurant_id **3**) record in **July 2026**? Return one number.',
    answer: "SELECT COUNT(*) FROM waste_log WHERE restaurant_id = 3 AND reason = 'Expired' AND waste_date BETWEEN '2026-07-01' AND '2026-07-31';",
    traps: [{ sql: "SELECT COUNT(*) FROM waste_log WHERE reason = 'Expired' AND waste_date BETWEEN '2026-07-01' AND '2026-07-31';", feedback: 'That counts all three restaurants. Add restaurant_id = 3.' }],
    explain: 'Three conditions joined with AND: the Airport logged 55 expired items that month.' },
  { id: 'sq2-whr-02', topic: 'sql-where', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 2, concept: 'like-in-between',
    prompt: 'HR database: how many employees were hired in **2024** at the **North Hub or South Hub**? Return one number (use IN).',
    answer: "SELECT COUNT(*) FROM employees WHERE location IN ('North Hub', 'South Hub') AND hire_date BETWEEN '2024-01-01' AND '2024-12-31';",
    traps: [{ sql: "SELECT COUNT(*) FROM employees WHERE hire_date BETWEEN '2024-01-01' AND '2024-12-31';", feedback: 'That includes Head Office hires as well. Keep only the two hubs.' }],
    explain: 'IN lists the allowed values, which is shorter and safer than two ORs next to an AND: 138 hires.' },
  { id: 'sq2-whr-03', topic: 'sql-where', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'where-logic',
    prompt: 'List returns with reason **Defective** and a refund **above 400**: return_id, return_date and refund_amount.',
    answer: "SELECT return_id, return_date, refund_amount FROM returns WHERE reason = 'Defective' AND refund_amount > 400;",
    traps: [{ sql: "SELECT return_id, return_date, refund_amount FROM returns WHERE reason = 'Defective' AND refund_amount >= 300;", feedback: 'The threshold is above 400.' }],
    explain: 'Ten expensive defective returns: a short list the buying team can check product by product.' },
  { id: 'sq2-whr-04', topic: 'sql-where', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'null',
    prompt: 'Find customers with **no acquisition_channel** recorded who **signed up in 2026 or later**: customer_id, full_name and signup_date.',
    answer: "SELECT customer_id, full_name, signup_date FROM customers WHERE acquisition_channel IS NULL AND signup_date >= '2026-01-01';",
    traps: [{ sql: "SELECT customer_id, full_name, signup_date FROM customers WHERE acquisition_channel = NULL AND signup_date >= '2026-01-01';", feedback: '= NULL is never true, so nothing comes back. Use IS NULL.' }],
    explain: 'IS NULL finds the missing values: 70 recent customers whose source marketing cannot credit.' },
  { id: 'sq2-whr-05', topic: 'sql-where', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'like-in-between',
    prompt: 'Restaurant database: list menu items in the **Mains** or **Pizza** categories priced **under 19**: name, category and current_price.',
    answer: "SELECT name, category, current_price FROM menu_items WHERE category IN ('Mains', 'Pizza') AND current_price < 19;",
    traps: [{ sql: "SELECT name, category, current_price FROM menu_items WHERE category = 'Mains' OR category = 'Pizza' AND current_price < 19;", feedback: 'AND binds before OR, so every Main comes back whatever its price. Use IN, or brackets around the OR.' }],
    explain: 'Five dishes: two Mains (Ember Burger and Sausage & Mash) and three pizzas.' },
  { id: 'sq2-whr-06', topic: 'sql-where', type: 'number', kind: 'calculation', difficulty: 1, concept: 'like-in-between',
    prompt: 'A column holds 4, 5, 7, 10 and 11. How many values match `WHERE qty BETWEEN 5 AND 10`?',
    answer: 3, verify: () => [4, 5, 7, 10, 11].filter((v) => v >= 5 && v <= 10).length,
    explain: 'BETWEEN includes both ends, so 5, 7 and 10 match.' },
  { id: 'sq2-whr-07', topic: 'sql-where', type: 'number', kind: 'calculation', difficulty: 2, concept: 'null',
    prompt: 'A table has 40 rows with region West, 50 with North and 10 with a NULL region. How many rows does `WHERE region <> \'West\'` return?',
    answer: 50, verify: () => 50,
    explain: 'A comparison with NULL is unknown, not true, so the 10 NULL rows are dropped. Add OR region IS NULL to keep them.' },
  { id: 'sq2-whr-08', topic: 'sql-where', type: 'tf', kind: 'concept', difficulty: 2, concept: 'like-in-between',
    prompt: 'True or false: in SQLite, `LIKE \'tent%\'` matches "Tent Footprint".',
    answer: true, explain: 'SQLite\'s LIKE ignores capitals for plain letters. Other databases differ, so do not rely on it everywhere.' },
  { id: 'sq2-whr-09', topic: 'sql-where', type: 'tf', kind: 'debugging', difficulty: 3, concept: 'null',
    prompt: 'True or false: `WHERE status IN (\'completed\', NULL)` also returns rows whose status is NULL.',
    answer: false, explain: 'IN compares with =, and = NULL is never true. Write status = \'completed\' OR status IS NULL.' },
  { id: 'sq2-whr-10', topic: 'sql-where', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'where-logic',
    prompt: '`WHERE order_date = \'2026-08-01\'` finds nothing, but the values look like "2026-08-01 14:32:00". What is the fix?',
    options: ['Compare the date part only, e.g. date(order_date) = \'2026-08-01\'', 'Write the date the UK way instead: \'01/08/2026\'', 'Use LIKE with no wildcard: LIKE \'2026-08-01\'', 'Sort the table by order_date before filtering'], answer: 0,
    explain: 'The stored text includes a time, so it never equals the bare date. Compare the date part, or use a range up to the next day.' },
  { id: 'sq2-whr-11', topic: 'sql-where', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'where-logic',
    prompt: 'Which rows does `WHERE NOT (channel = \'Online\' AND status = \'completed\')` keep?',
    options: ['Every row except completed online orders', 'Only in-store orders that were not completed', 'Only online orders that were not completed', 'No rows at all'], answer: 0,
    explain: 'NOT flips the whole bracket: in-store orders of any status and online orders that are not completed all stay.' },
  { id: 'sq2-whr-12', topic: 'sql-where', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'where-logic',
    prompt: 'Marketing asks for customers in the North or South who signed up in 2026. Which WHERE clause is right?',
    options: ['region IN (\'North\', \'South\') AND signup_date >= \'2026-01-01\'', 'region = \'North\' OR region = \'South\' AND signup_date >= \'2026-01-01\'', 'region = \'North\' AND region = \'South\' AND signup_date >= \'2026-01-01\'', 'region IN (\'North\', \'South\') OR signup_date >= \'2026-01-01\''], answer: 0,
    explain: 'The second option applies the date only to the South, the third can never be true, and the fourth keeps anyone who signed up in 2026.' },

  // ================================================================ sql-aggregate
  { id: 'sq2-agg-01', topic: 'sql-aggregate', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'aggregates',
    prompt: 'Restaurant database: for **July 2026**, return the **total labor_cost** and the **total hours** across all restaurants (both rounded to 2 decimals).',
    answer: "SELECT ROUND(SUM(labor_cost), 2), ROUND(SUM(hours), 2) FROM labor_daily WHERE work_date BETWEEN '2026-07-01' AND '2026-07-31';",
    traps: [{ sql: 'SELECT ROUND(SUM(labor_cost), 2), ROUND(SUM(hours), 2) FROM labor_daily;', feedback: 'That adds up every month. Filter work_date to July 2026.' }],
    explain: 'Two aggregates in one row: about 120,225 of labour for 6,587 hours in July.' },
  { id: 'sq2-agg-02', topic: 'sql-aggregate', type: 'sql', kind: 'sql-writing', db: 'hr', difficulty: 1, concept: 'aggregates',
    prompt: 'HR database: return the **lowest** and **highest** current_salary of **current** employees (termination_date IS NULL).',
    answer: 'SELECT MIN(current_salary), MAX(current_salary) FROM employees WHERE termination_date IS NULL;',
    explain: 'MIN and MAX give the range: from 30,000 to 122,300 among current staff.' },
  { id: 'sq2-agg-03', topic: 'sql-aggregate', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'count-distinct',
    prompt: 'How many **different products** have ever appeared on an order line? Return one number.',
    answer: 'SELECT COUNT(DISTINCT product_id) FROM order_items;',
    traps: [{ sql: 'SELECT COUNT(product_id) FROM order_items;', feedback: 'That counts order lines (19,510), not different products. Add DISTINCT.' }],
    explain: '58 of the 61 products have been sold at least once, so three have never sold: worth asking why.' },
  { id: 'sq2-agg-04', topic: 'sql-aggregate', type: 'sql', kind: 'sql-writing', db: 'restaurant', difficulty: 2, concept: 'aggregates',
    prompt: 'Restaurant database: for waste entries with reason **Over-prepared**, return the **average qty** per entry (2 decimals) and the **number of entries**.',
    answer: "SELECT ROUND(AVG(qty), 2), COUNT(*) FROM waste_log WHERE reason = 'Over-prepared';",
    explain: 'About 1.14 units per entry over 1,564 entries. Units differ between ingredients, so treat this average as a rough guide only.' },
  { id: 'sq2-agg-05', topic: 'sql-aggregate', type: 'sql', kind: 'sql-writing', db: 'cedarline', difficulty: 2, concept: 'aggregates',
    prompt: 'For returns with reason **Wrong size**, return the **number of returns** and the **total refund_amount** (2 decimals).',
    answer: "SELECT COUNT(*), ROUND(SUM(refund_amount), 2) FROM returns WHERE reason = 'Wrong size';",
    traps: [{ sql: "SELECT COUNT(*), ROUND(SUM(refund_amount), 2) FROM returns WHERE reason = 'Defective';", feedback: 'That is the Defective reason. The question asks about Wrong size.' }],
    explain: 'Wrong size is the most common reason: 528 returns and about 53,423 refunded, a case for better size guides.' },
  { id: 'sq2-agg-06', topic: 'sql-aggregate', type: 'number', kind: 'calculation', difficulty: 1, concept: 'null',
    prompt: 'A column holds 10, 20, NULL and 30. What does AVG(column) return?',
    answer: 20, verify: () => (10 + 20 + 30) / 3,
    explain: 'AVG ignores NULL: (10 + 20 + 30) ÷ 3 = 20. Treating NULL as zero would give 15.' },
  { id: 'sq2-agg-07', topic: 'sql-aggregate', type: 'number', kind: 'calculation', difficulty: 1, concept: 'null',
    prompt: 'A table has 500 rows, and 120 of them have NULL in column c. What does COUNT(c) return?',
    answer: 380, verify: () => 500 - 120,
    explain: 'COUNT(column) skips NULLs; COUNT(*) counts every row (500).' },
  { id: 'sq2-agg-08', topic: 'sql-aggregate', type: 'number', kind: 'calculation', difficulty: 2, concept: 'aggregates',
    prompt: 'Two order lines: 2 units at 50 and 3 units at 20. What does SUM(quantity * unit_price) return?',
    answer: 160, verify: () => 2 * 50 + 3 * 20,
    explain: 'The multiplication happens per row first (100 and 60), then SUM adds them: 160.' },
  { id: 'sq2-agg-09', topic: 'sql-aggregate', type: 'tf', kind: 'concept', difficulty: 2, concept: 'aggregates',
    prompt: 'True or false: MAX also works on text, returning the value that comes last alphabetically.',
    answer: true, explain: 'MIN and MAX compare text alphabetically, and ISO dates (YYYY-MM-DD) too, which is why they work on date text.' },
  { id: 'sq2-agg-10', topic: 'sql-aggregate', type: 'tf', kind: 'concept', difficulty: 2, concept: 'count-distinct',
    prompt: 'True or false: COUNT(DISTINCT column) counts NULL as one extra value.',
    answer: false, explain: 'COUNT ignores NULL, with or without DISTINCT. Missing values need their own check (WHERE column IS NULL).' },
  { id: 'sq2-agg-11', topic: 'sql-aggregate', type: 'fill', kind: 'concept', difficulty: 1, concept: 'aggregates',
    prompt: 'To show an average with 2 decimals in SQLite, wrap it in ____(AVG(x), 2).',
    answer: ['ROUND', 'round'], explain: 'ROUND(value, 2) keeps two decimals. Round at the end, not before adding things up.' },
  { id: 'sq2-agg-12', topic: 'sql-aggregate', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'aggregates',
    prompt: '`SELECT AVG(discount_pct) FROM order_items` returns 0.06. What does that tell you?',
    options: ['Lines got 6% off on average, each line counted equally', 'Customers saved 6% of total revenue', 'Six lines had a discount', 'Revenue was reduced by 0.06 in total'], answer: 0,
    explain: 'A simple average treats a 5-euro line like a 500-euro line. For money saved, divide total discount by total gross value.' },
  { id: 'sq2-agg-13', topic: 'sql-aggregate', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'count-distinct',
    prompt: 'Finance asks for the "average order value". Each order can have several lines. What do you calculate?',
    options: ['Total revenue ÷ number of distinct orders', 'The average of the line values', 'Total revenue ÷ number of lines', 'The largest order ÷ 2'], answer: 0,
    explain: 'An order is the unit that matters here. Averaging lines gives a smaller number that describes lines, not orders.' },
];
