// Analyst thinking quiz bank, part A: can you trust this number, and data quality.
export const THINK_QUIZ_A = [
  // ================================================================ think-trust
  { id: 'th2-trust-01', topic: 'think-trust', type: 'mc', kind: 'scenario', difficulty: 1, concept: 'data-trust',
    prompt: 'A new report says customer complaints fell 60% last month. What do you check before sharing it?',
    options: ['Whether the way complaints are recorded changed', 'Whether the chart uses the brand colours', 'Whether the report has a title page', 'Whether last month had 31 days'], answer: 0,
    explain: 'Big changes often come from a new form, a new category or a system change rather than from the business. Check the process before celebrating.' },
  { id: 'th2-trust-02', topic: 'think-trust', type: 'tf', kind: 'concept', difficulty: 1, concept: 'data-trust',
    prompt: 'True or false: a number that matches your expectation does not need checking.',
    answer: false, explain: 'Numbers that confirm what we expected get less scrutiny, which is exactly how errors survive. Check them the same way.' },
  { id: 'th2-trust-03', topic: 'think-trust', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'data-trust',
    prompt: 'The sales file ends on 24 August, and your report is labelled "August". What is the risk?',
    options: ['August looks lower than it really was', 'August looks higher than it really was', 'Nothing, one week makes no difference', 'Sales after the 24th are counted twice'], answer: 0,
    explain: 'A partial month compared with full months looks like a drop. Check the latest date in the data and label the period correctly.' },
  { id: 'th2-trust-04', topic: 'think-trust', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'data-trust',
    prompt: 'Total revenue in your analysis is exactly twice the finance figure. What is the most likely cause?',
    options: ['The data was loaded or joined twice', 'Finance forgot half the sales', 'Prices doubled during the year', 'Revenue includes a new currency'], answer: 0,
    explain: 'An exact factor of two points to duplication: a file appended twice or a join that doubled every row.' },
  { id: 'th2-trust-05', topic: 'think-trust', type: 'order', kind: 'sequence', difficulty: 2, concept: 'data-trust',
    prompt: 'Order these checks on a new dataset, from first to last.',
    options: ['Where did it come from and what period does it cover?', 'How many rows and columns are there?', 'Do the totals match a known figure?', 'What story do the numbers tell?'], answer: [0, 1, 2, 3],
    explain: 'Source and period, then shape, then reconciliation, and only then interpretation.' },
  { id: 'th2-trust-06', topic: 'think-trust', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'data-trust',
    prompt: 'A manager forwards a spreadsheet "from someone in finance" with no date or source. What do you do?',
    options: ['Ask who produced it, when, and from which system', 'Use it as it is: finance is reliable', 'Delete it without looking', 'Copy the numbers into your report'], answer: 0,
    explain: 'A number without a source and date cannot be checked or updated. Find out where it came from first.' },
  { id: 'th2-trust-07', topic: 'think-trust', type: 'number', kind: 'calculation', difficulty: 2, concept: 'data-trust',
    prompt: 'Your total is $1,248,000 and finance reports $1,260,000. What is the difference as a percentage of the finance figure, to one decimal place?',
    answer: 1, tolerance: 0.05, verify: () => Math.round(((1260000 - 1248000) / 1260000) * 1000) / 10,
    explain: '12,000 ÷ 1,260,000 = 0.95%, about 1%. Small, but still worth explaining before anyone uses the number.' },
  { id: 'th2-trust-08', topic: 'think-trust', type: 'tf', kind: 'concept', difficulty: 2, concept: 'data-trust',
    prompt: 'True or false: if two errors cancel each other out, the total is correct and the analysis can be trusted.',
    answer: false, explain: 'The total may match by luck, but any breakdown (by region, by month) will still be wrong.' },
  { id: 'th2-trust-09', topic: 'think-trust', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'data-trust',
    prompt: 'One store shows revenue of $2.4 million on a single day, when a normal day is $4,000. What is the most likely explanation?',
    options: ['A typing error, such as a missing decimal', 'A genuine record sales day', 'A leap-year effect', 'A new product launch'], answer: 0,
    explain: 'A value 600 times the norm is almost always an error. Find the row, then ask the store before deciding what to do.' },
  { id: 'th2-trust-10', topic: 'think-trust', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'data-trust',
    prompt: 'The dashboard and the monthly finance pack disagree by 4% on revenue. The board meets tomorrow. What is the best approach?',
    options: ['Use one figure, and note the difference and why', 'Show the higher figure', 'Remove revenue from the slides', 'Average the two figures'], answer: 0,
    explain: 'Say which definition you used and what explains the gap. Silence invites questions you cannot answer in the meeting.' },
  { id: 'th2-trust-11', topic: 'think-trust', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'data-trust',
    prompt: 'A survey says 92% of customers are satisfied. Only 40 of 5,000 customers replied. What should you say?',
    options: ['The result may not represent all customers', 'Satisfaction is clearly excellent', 'The survey proves nothing at all', '92% of 5,000 customers are satisfied'], answer: 0,
    explain: 'With a 0.8% response rate, the people who replied may differ from those who did not. Report the result with the response count.' },
  { id: 'th2-trust-12', topic: 'think-trust', type: 'tf', kind: 'concept', difficulty: 1, concept: 'data-trust',
    prompt: 'True or false: knowing how a number was calculated is as important as the number itself.',
    answer: true, explain: 'The same word (revenue, customers) can be calculated several ways. The method tells you what the number means.' },
  { id: 'th2-trust-13', topic: 'think-trust', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'data-trust',
    prompt: 'Average delivery time dropped from 3.2 days to 0.4 days after a system upgrade. Most likely?',
    options: ['A date field changed meaning in the new system', 'Couriers became eight times faster', 'Customers ordered smaller items', 'The warehouse moved closer'], answer: 0,
    explain: 'A sudden, implausible jump at the moment a system changed points to the data, for example "dispatched" replacing "delivered".' },
  { id: 'th2-trust-14', topic: 'think-trust', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'data-trust',
    prompt: 'You find a small error in a report you sent last week. It changes one figure by 3%. What do you do?',
    options: ['Tell the readers, with the corrected figure', 'Say nothing: 3% is small', 'Wait to see if anyone notices', 'Delete the old report'], answer: 0,
    explain: 'Correcting your own error quickly builds trust. Someone relying on the wrong figure is the bigger risk.' },
  { id: 'th2-trust-15', topic: 'think-trust', type: 'number', kind: 'calculation', difficulty: 2, concept: 'data-trust',
    prompt: 'A file should contain one row per day for a year (365 days). It has 358 rows. How many days are missing?',
    answer: 7, verify: () => 365 - 358,
    explain: '365 − 358 = 7 days missing. Find which ones before summing: a missing week distorts monthly totals.' },
  { id: 'th2-trust-16', topic: 'think-trust', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'data-trust',
    prompt: 'Online conversion rose from 2.1% to 3.4% in the week the tracking code was updated. What is the most responsible reading?',
    options: ['It may be a measurement change, not a real improvement', 'The website redesign clearly worked', 'Online customers liked the new prices', 'Conversion always rises in that week'], answer: 0,
    explain: 'When measurement changes at the same moment as the metric, suspect the measurement first. Compare with orders, which do not depend on the tracking code.' },
  { id: 'th2-trust-17', topic: 'think-trust', type: 'fill', kind: 'concept', difficulty: 2, concept: 'data-trust',
    prompt: 'Comparing your total with an independent known figure (for example finance\'s revenue) is called a ____ check. (One word.)',
    answer: ['reconciliation', 'reconcile', 'control'], explain: 'A reconciliation (or control total check) confirms that your result starts from the right place.' },
  { id: 'th2-trust-18', topic: 'think-trust', type: 'tf', kind: 'concept', difficulty: 2, concept: 'data-trust',
    prompt: 'True or false: a dashboard built by an automated system cannot contain errors.',
    answer: false, explain: 'Automation repeats mistakes reliably. Definitions, filters and joins built into a dashboard still need checking.' },
  { id: 'th2-trust-19', topic: 'think-trust', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'data-trust',
    prompt: 'Two regions report customer counts. North counts accounts; South counts households. The director wants to compare them. What do you do?',
    options: ['Point out the difference and use one definition', 'Compare them as they are', 'Add them together for a total', 'Use the larger of the two'], answer: 0,
    explain: 'Numbers built on different definitions cannot be compared. Agree one definition and recalculate at least one region.' },
  { id: 'th2-trust-20', topic: 'think-trust', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'data-trust',
    prompt: 'A monthly chart shows zero sales for March at one store. Before reporting, what is the first thing to check?',
    options: ['Whether March data for that store was loaded', 'Whether the store sells in March', 'Whether March has fewer days', 'Whether the chart is a bar chart'], answer: 0,
    explain: 'A missing file is far more likely than a month with no sales at all. Check the data before explaining the business.' },
  { id: 'th2-trust-21', topic: 'think-trust', type: 'number', kind: 'calculation', difficulty: 3, concept: 'data-trust',
    prompt: 'A report claims 12,500 orders and an average order value of $80. Finance says revenue was $850,000. How far apart are the two revenue figures, in dollars?',
    answer: 150000, verify: () => 12500 * 80 - 850000,
    explain: '12,500 × $80 = $1,000,000, which is $150,000 more than finance. A quick multiplication like this catches inconsistent figures before a meeting.' },

  // ================================================================ think-quality
  { id: 'th2-qual-01', topic: 'think-quality', type: 'mc', kind: 'concept', difficulty: 1, concept: 'data-quality',
    prompt: 'Which check asks "is the same record in the data more than once"?',
    options: ['Uniqueness', 'Completeness', 'Timeliness', 'Validity'], answer: 0,
    explain: 'Uniqueness checks for duplicates; completeness for blanks; validity for impossible values; timeliness for how current the data is.' },
  { id: 'th2-qual-02', topic: 'think-quality', type: 'mc', kind: 'concept', difficulty: 1, concept: 'data-quality',
    prompt: 'A column of ages contains the value 212. Which quality dimension does that fail?',
    options: ['Validity', 'Uniqueness', 'Timeliness', 'Consistency'], answer: 0,
    explain: 'An age of 212 cannot be true, so the value is invalid.' },
  { id: 'th2-qual-03', topic: 'think-quality', type: 'tf', kind: 'concept', difficulty: 1, concept: 'missing-data',
    prompt: 'True or false: a blank value and a zero mean the same thing.',
    answer: false, explain: 'Zero is a known amount. Blank means unknown or not recorded. Treating blanks as zero changes averages and totals.' },
  { id: 'th2-qual-04', topic: 'think-quality', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'missing-data',
    prompt: 'Average order value is calculated after replacing blank order values with 0. What happens?',
    options: ['The average is pulled down', 'The average is unchanged', 'The average is pulled up', 'The count of orders drops'], answer: 0,
    explain: 'Zeros add orders with no value to the denominator, so the average falls. Exclude unknown values or find the real ones.' },
  { id: 'th2-qual-05', topic: 'think-quality', type: 'number', kind: 'calculation', difficulty: 2, concept: 'missing-data',
    prompt: 'Five orders: $100, $120, blank, $80, $100. What is the average of the known values?',
    answer: 100, verify: () => (100 + 120 + 80 + 100) / 4,
    explain: '(100 + 120 + 80 + 100) ÷ 4 = $100. Treating the blank as 0 would give $80.' },
  { id: 'th2-qual-06', topic: 'think-quality', type: 'number', kind: 'calculation', difficulty: 2, concept: 'missing-data',
    prompt: 'Same five orders ($100, $120, blank, $80, $100), but the blank is treated as $0. What average do you get?',
    answer: 80, verify: () => (100 + 120 + 0 + 80 + 100) / 5,
    explain: '400 ÷ 5 = $80: a 20% understatement caused only by how the blank was handled.' },
  { id: 'th2-qual-07', topic: 'think-quality', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'duplicates',
    prompt: 'A customer list has 4,571 rows but only 4,500 different email addresses. What is the most likely explanation?',
    options: ['Some people registered more than once', 'Some customers have no email', 'The export is missing rows', 'Emails are not unique by law'], answer: 0,
    explain: 'More rows than emails means some emails appear on several rows: the same person registered twice. (Blank emails would reduce the email count differently.)' },
  { id: 'th2-qual-08', topic: 'think-quality', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'duplicates',
    prompt: 'Which key best identifies the same person across two registrations?',
    options: ['Email, trimmed and in lower case', 'Customer id', 'Signup date', 'City'], answer: 0,
    explain: 'Two registrations get two customer ids. The same email (cleaned of spaces and case) is the better sign of the same person.' },
  { id: 'th2-qual-09', topic: 'think-quality', type: 'tf', kind: 'concept', difficulty: 2, concept: 'duplicates',
    prompt: 'True or false: two rows with the same employee and date in a salary history are always duplicates to delete.',
    answer: false, explain: 'They can be two real events on the same day, such as a raise and a promotion. Look at the rows before deleting.' },
  { id: 'th2-qual-10', topic: 'think-quality', type: 'number', kind: 'calculation', difficulty: 2, concept: 'duplicates',
    prompt: '139 customer rows share 68 email addresses. How many rows would you remove to keep one row per email?',
    answer: 71, verify: () => 139 - 68,
    explain: '139 − 68 = 71 extra rows. Some emails appear three times, so this is more than half of 139.' },
  { id: 'th2-qual-11', topic: 'think-quality', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'data-quality',
    prompt: 'You find 6 orders dated before their customer\'s signup date. What is the best action?',
    options: ['Report them to the data owner and note the rule used', 'Delete the six orders quietly', 'Change the signup dates yourself', 'Ignore them: six is too few'], answer: 0,
    explain: 'Impossible records point to a process problem. Measure, report, and decide with the owner. Never fix data silently.' },
  { id: 'th2-qual-12', topic: 'think-quality', type: 'mc', kind: 'concept', difficulty: 2, concept: 'data-quality',
    prompt: 'Which is a **consistency** problem?',
    options: ['An order dated before the customer signed up', 'A missing phone number', 'A price of −$5', 'A file last updated a month ago'], answer: 0,
    explain: 'Consistency is about records agreeing with each other. A missing value is completeness, −$5 is validity, an old file is timeliness.' },
  { id: 'th2-qual-13', topic: 'think-quality', type: 'order', kind: 'sequence', difficulty: 2, concept: 'data-quality',
    prompt: 'Order what to do when you find a data quality problem.',
    options: ['Measure how many rows and how much value it affects', 'Show examples to the data owner', 'Agree whether to fix, exclude or flag', 'Document the decision next to the result'], answer: [0, 1, 2, 3],
    explain: 'Measure, show, decide, document. Silent fixes are how two analysts end up with different numbers.' },
  { id: 'th2-qual-14', topic: 'think-quality', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'missing-data',
    prompt: '250 of 4,571 customers have no acquisition channel. In a channel report, what should happen to them?',
    options: ['Show them as "Unknown"', 'Leave them out without comment', 'Add them to the biggest channel', 'Spread them across channels'], answer: 0,
    explain: 'An Unknown bar keeps the total honest and shows how much of the analysis is uncertain.' },
  { id: 'th2-qual-15', topic: 'think-quality', type: 'number', kind: 'calculation', difficulty: 2, concept: 'missing-data',
    prompt: '250 of 4,571 customers have no channel. What percentage is that, to one decimal place?',
    answer: 5.5, tolerance: 0.05, verify: () => Math.round((250 / 4571) * 1000) / 10,
    explain: '250 ÷ 4,571 = 5.5%. About one customer in eighteen.' },
  { id: 'th2-qual-16', topic: 'think-quality', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'data-quality',
    prompt: 'A "quantity" column has values like 3, 5, "3 boxes" and "five". What is the problem?',
    options: ['Numbers stored as text in several formats', 'Too many rows', 'A missing header', 'Duplicate customers'], answer: 0,
    explain: 'Mixed text and numbers cannot be summed reliably. Standardise the values before analysing.' },
  { id: 'th2-qual-17', topic: 'think-quality', type: 'tf', kind: 'concept', difficulty: 2, concept: 'data-quality',
    prompt: 'True or false: checking the latest date in a dataset is part of checking data quality.',
    answer: true, explain: 'Timeliness: a feed that stopped last week makes this week look empty.' },
  { id: 'th2-qual-18', topic: 'think-quality', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'duplicates',
    prompt: 'A marketing email list contains the same people twice under different customer ids. What is the business impact?',
    options: ['Double emails and an overstated customer count', 'Nothing happens, because emails cost nothing', 'Revenue from those people is counted twice', 'Product prices are shown twice in the email'], answer: 0,
    explain: 'Duplicate people annoy customers, inflate "customers reached", and distort per-customer measures like lifetime value.' },
  { id: 'th2-qual-19', topic: 'think-quality', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'data-quality',
    prompt: 'Which SQL finds email addresses that appear more than once?',
    options: ['GROUP BY email HAVING COUNT(*) > 1', 'WHERE email > 1', 'ORDER BY email DESC', 'SELECT DISTINCT email'], answer: 0,
    explain: 'GROUP BY with HAVING COUNT(*) > 1 keeps only the repeated values. DISTINCT hides duplicates instead of finding them.' },
  { id: 'th2-qual-20', topic: 'think-quality', type: 'fill', kind: 'concept', difficulty: 2, concept: 'missing-data',
    prompt: 'In SQL, a missing value is written as ____.',
    answer: ['NULL'], explain: 'NULL means no value. Test for it with IS NULL; = NULL never matches.' },
  { id: 'th2-qual-21', topic: 'think-quality', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'missing-data',
    prompt: '`SELECT COUNT(*) FROM customers WHERE region = NULL` returns 0, but you know some regions are blank. Why?',
    options: ['Comparisons with NULL never match; use IS NULL', 'The customers table has no rows at all', 'COUNT(*) ignores rows with blank values', 'NULL must be written in quotes'], answer: 0,
    explain: 'NULL is not equal to anything, not even NULL. `WHERE region IS NULL` finds the blanks.' },
  { id: 'th2-qual-22', topic: 'think-quality', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'outliers',
    prompt: 'A column of unit prices has values between $2 and $60, and one row at $5,990. What is the most sensible first step?',
    options: ['Look at that row and its product', 'Delete the row straight away', 'Replace it with the average', 'Keep it without comment'], answer: 0,
    explain: 'It may be a typing error (59.90) or a genuine expensive item. Look before deciding.' },
  { id: 'th2-qual-23', topic: 'think-quality', type: 'number', kind: 'calculation', difficulty: 3, concept: 'data-quality',
    prompt: 'A file of 8,000 invoices has 120 with a blank supplier and 40 with a negative amount (20 of those are also blank-supplier rows). How many invoices have at least one of the two problems?',
    answer: 140, verify: () => 120 + 40 - 20,
    explain: '120 + 40 − 20 = 140. Rows with both problems are counted once.' },
  { id: 'th2-qual-24', topic: 'think-quality', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'data-quality',
    prompt: 'An HR file has absence days of 40 in a month with 22 working days. What do you do?',
    options: ['Flag it as impossible and ask HR', 'Cap it at 22 without telling anyone', 'Keep it: some people are often absent', 'Divide it by two'], answer: 0,
    explain: 'The value breaks a rule, so it is an error somewhere. Ask HR which value is right; do not silently cap or change it.' },
  { id: 'th2-qual-25', topic: 'think-quality', type: 'tf', kind: 'concept', difficulty: 2, concept: 'data-quality',
    prompt: 'True or false: it is acceptable to exclude bad rows from an analysis as long as you say how many and why.',
    answer: true, explain: 'Transparent exclusions are fine. The problem is excluding rows silently.' },
  { id: 'th2-qual-26', topic: 'think-quality', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'duplicates',
    prompt: 'After "Remove duplicates", 30 obvious duplicate customers remain. They differ only by a trailing space and capital letters in the name. What was missed?',
    options: ['Cleaning the text before comparing', 'Sorting the data first', 'Removing blank rows', 'Using a pivot table'], answer: 0,
    explain: '"Ana Silva " and "ana silva" are different strings. Trim and standardise case before looking for duplicates.' },
  { id: 'th2-qual-27', topic: 'think-quality', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'missing-data',
    prompt: 'Customers without an email are all walk-in shoppers from one store. What does that mean for an analysis of "email customers"?',
    options: ['The missing data is not random, so that store is under-represented', 'Nothing: missing emails are random', 'Email customers are the only real customers', 'That store has no customers'], answer: 0,
    explain: 'When blanks cluster in one group, excluding them biases the result against that group. Say so in the findings.' },
  { id: 'th2-qual-28', topic: 'think-quality', type: 'order', kind: 'sequence', difficulty: 2, concept: 'duplicates',
    prompt: 'Order the steps to remove duplicate customers safely.',
    options: ['Clean the key (trim spaces, same case)', 'Find the keys that repeat', 'Look at the repeated rows', 'Decide which row to keep and record the rule'], answer: [0, 1, 2, 3],
    explain: 'Clean, find, inspect, decide. Skipping the inspection risks deleting real records.' },
  { id: 'th2-qual-29', topic: 'think-quality', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'data-quality',
    prompt: 'A product table has 61 products, but sales mention 64 different product ids. What does that tell you?',
    options: ['Three sold products are missing from the product table', 'Three products were never sold', 'The sales table has duplicated order lines', 'Product ids are not needed'], answer: 0,
    explain: 'Sales for unknown products will appear as "(Blank)" or be dropped by joins. Update the product table.' },
  { id: 'th2-qual-30', topic: 'think-quality', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'data-quality',
    prompt: 'Which Power Query view shows the percentage of empty and error values in each column?',
    options: ['Column quality', 'Advanced Editor', 'Applied Steps', 'Merge Queries'], answer: 0,
    explain: 'View → Column quality shows valid, error and empty percentages. Set profiling to the entire data set for large files.' },
  { id: 'th2-qual-31', topic: 'think-quality', type: 'number', kind: 'calculation', difficulty: 2, concept: 'data-quality',
    prompt: 'A file has 2,400 rows. 36 rows have an invalid date. What percentage of rows is that?',
    answer: 1.5, tolerance: 0.01, verify: () => (36 / 2400) * 100,
    explain: '36 ÷ 2,400 = 1.5%. Report the share so readers know how much of the result is affected.' },
  { id: 'th2-qual-32', topic: 'think-quality', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'data-quality',
    prompt: 'Two systems give a customer different signup dates. Which one should the analysis use?',
    options: ['The one the business agrees is the source of truth', 'Always the earlier of the two dates', 'Always the later of the two dates', 'An average of the two signup dates'], answer: 0,
    explain: 'Choose the system of record with the data owner, then apply the rule consistently and document it.' },
  { id: 'th2-qual-33', topic: 'think-quality', type: 'tf', kind: 'concept', difficulty: 2, concept: 'outliers',
    prompt: 'True or false: every outlier is an error.',
    answer: false, explain: 'Some are real and important (a large corporate order). Check before excluding.' },
  { id: 'th2-qual-34', topic: 'think-quality', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'data-quality',
    prompt: 'Dates in a file read 03/04/2025 and 25/04/2025. After import, the first became 4 March and the second an error. What happened?',
    options: ['The file uses day/month order but was read as month/day', 'The dates are from different years', 'The column has duplicates', 'April has no 25th day'], answer: 0,
    explain: 'In month/day order, 25 is not a valid month. Read the column with the right locale (day/month).' },
  { id: 'th2-qual-35', topic: 'think-quality', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'data-quality',
    prompt: 'A manager asks you to "just remove the weird rows" so the chart looks cleaner. What is the best response?',
    options: ['Explain what the rows are and agree a rule before excluding', 'Remove them without checking what they are', 'Refuse to change anything in the data', 'Hide them with a filter on the chart'], answer: 0,
    explain: 'Weird rows are sometimes the most important ones. Agree a rule, apply it openly and note it on the chart.' },
  { id: 'th2-qual-36', topic: 'think-quality', type: 'fill', kind: 'concept', difficulty: 2, concept: 'data-quality',
    prompt: 'The quality dimension that asks "is the data up to date?" is called ____.',
    answer: ['timeliness', 'freshness', 'currency'], explain: 'Timeliness: check the latest date against what you expect.' },
  { id: 'th2-qual-37', topic: 'think-quality', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'duplicates',
    prompt: 'Customer "lifetime value" is calculated per customer id. 71 people are registered twice. Which way is the average affected?',
    options: ['Understated: each person\'s spend is split in two', 'Overstated: each person is counted twice', 'Not affected: the total spend is the same', 'Doubled: every purchase appears twice'], answer: 0,
    explain: 'Splitting one person\'s purchases across two ids makes both look like smaller customers, so the average per customer falls.' },
  { id: 'th2-qual-38', topic: 'think-quality', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'data-quality',
    prompt: 'Which SQL finds orders placed before the customer signed up?',
    options: ['JOIN customers and filter order_date < signup_date', 'SELECT MIN(order_date) FROM orders', 'WHERE signup_date IS NULL', 'GROUP BY signup_date'], answer: 0,
    explain: 'Join the two tables on customer_id and compare the dates row by row.' },
  { id: 'th2-qual-39', topic: 'think-quality', type: 'tf', kind: 'concept', difficulty: 1, concept: 'data-quality',
    prompt: 'True or false: data quality checks should be done before building charts.',
    answer: true, explain: 'Charts built on unchecked data spread the errors. Check first.' },
  { id: 'th2-qual-40', topic: 'think-quality', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'missing-data',
    prompt: 'A restaurant\'s waste log has no entries for two weeks at one site. The manager says "we had no waste". What do you do?',
    options: ['Treat it as possibly unrecorded and check with the site', 'Record zero waste for those weeks', 'Copy the waste from other weeks', 'Remove the site from the report'], answer: 0,
    explain: 'No waste at all in a working kitchen is implausible. Missing records are more likely than zero waste; confirm before reporting.' },
];
