// Analyst thinking quiz bank, part D: KPIs, charts, choosing the tool.
export const THINK_QUIZ_D = [
  // ================================================================ think-kpis
  { id: 'th2-kpi-01', topic: 'think-kpis', type: 'mc', kind: 'concept', difficulty: 2, concept: 'kpi',
    prompt: 'Which description fits a good KPI best?',
    options: ['Tied to a goal, clearly defined, and someone can act on it', 'The metric with the biggest number on the dashboard', 'Anything the system can calculate automatically', 'A metric that always goes up over time'], answer: 0,
    explain: 'A KPI earns its place by linking to a goal, having one agreed definition and an owner who can move it.' },
  { id: 'th2-kpi-02', topic: 'think-kpis', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'metric-choice',
    prompt: 'A restaurant owner wants to keep ingredient spending under control. Which KPI fits?',
    options: ['Food cost as a % of food sales', 'Total number of dishes on the menu', 'Number of suppliers used', 'Total food sales this month'], answer: 0,
    explain: 'Food cost % compares what the ingredients cost with what they sold for, so it stays fair when sales rise or fall.' },
  { id: 'th2-kpi-03', topic: 'think-kpis', type: 'number', kind: 'calculation', difficulty: 2, concept: 'kpi',
    prompt: 'Food cost this month was $31,500 and food sales were $105,000. What is the food cost %?',
    answer: 30, tolerance: 0.05, verify: () => (31500 / 105000) * 100,
    explain: '31,500 ÷ 105,000 = 30%. Many restaurants aim for roughly 28 to 35%, depending on the concept.' },
  { id: 'th2-kpi-04', topic: 'think-kpis', type: 'mc', kind: 'concept', difficulty: 3, concept: 'kpi',
    prompt: 'Which of these is a leading indicator of next month\'s sales for a B2B company?',
    options: ['The value of open sales opportunities', 'Last month\'s invoiced revenue', 'Last year\'s profit margin', 'The number of invoices already paid'], answer: 0,
    explain: 'The pipeline of open opportunities points to future sales. Invoices and profit describe the past (lagging).' },
  { id: 'th2-kpi-05', topic: 'think-kpis', type: 'fill', kind: 'concept', difficulty: 2, concept: 'kpi',
    prompt: 'A metric that moves before the result you care about, and helps predict it, is a ____ indicator.',
    answer: ['leading'], explain: 'Leading indicators (bookings, pipeline, website visits) warn you early; lagging ones (revenue, profit) confirm what happened.' },
  { id: 'th2-kpi-06', topic: 'think-kpis', type: 'tf', kind: 'concept', difficulty: 2, concept: 'kpi',
    prompt: 'True or false: last quarter\'s revenue is a lagging indicator.',
    answer: true, explain: 'It reports the outcome after the fact. Pair it with leading indicators to act in time.' },
  { id: 'th2-kpi-07', topic: 'think-kpis', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'metric-choice',
    prompt: 'A call centre rewards agents for a short average call length. Customers now call back more often. What should be added?',
    options: ['A counter-metric such as first-call resolution rate', 'A bonus for even shorter calls', 'A limit on how often customers can call', 'Nothing: shorter calls are always better'], answer: 0,
    explain: 'A counter-metric catches gaming: agents can shorten calls by not solving problems, and resolution rate exposes it.' },
  { id: 'th2-kpi-08', topic: 'think-kpis', type: 'fill', kind: 'concept', difficulty: 3, concept: 'kpi',
    prompt: 'Goodhart\'s law warns that once a measure is turned into a ____, people start optimising the number instead of the goal.',
    answer: ['target', 'goal'], explain: 'When a number becomes a target, people find ways to move it that do not help the business. Counter-metrics limit this.' },
  { id: 'th2-kpi-09', topic: 'think-kpis', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'denominator',
    prompt: 'Stores range from 150 m² to 2,000 m². Which measure compares their sales performance fairly?',
    options: ['Sales per square metre', 'Total sales per store', 'Number of products sold', 'Sales of the biggest store'], answer: 0,
    explain: 'Dividing by floor space removes the size advantage. Total sales mostly rank stores by size.' },
  { id: 'th2-kpi-10', topic: 'think-kpis', type: 'number', kind: 'calculation', difficulty: 2, concept: 'kpi',
    prompt: 'A site spent $18,450 on labour and had net sales of $65,000. What is labour cost as a % of sales, to one decimal place?',
    answer: 28.4, tolerance: 0.05, verify: () => Math.round((18450 / 65000) * 1000) / 10,
    explain: '18,450 ÷ 65,000 = 28.4%. It shows how much of each dollar of sales goes on wages.' },
  { id: 'th2-kpi-11', topic: 'think-kpis', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'metric-choice',
    prompt: 'Which of these is most likely a vanity metric for a subscription app?',
    options: ['Total downloads since launch', 'Monthly active paying users', 'Share of users who renew', 'Revenue per paying user'], answer: 0,
    explain: 'A running total only goes up and says nothing about use or revenue. Active, paying and renewing users show real health.' },
  { id: 'th2-kpi-12', topic: 'think-kpis', type: 'tf', kind: 'concept', difficulty: 2, concept: 'kpi',
    prompt: 'True or false: a management dashboard with 40 KPIs helps managers focus.',
    answer: false, explain: 'Too many KPIs means none gets attention. Keep a handful tied to the goals, with detail pages behind them.' },
  { id: 'th2-kpi-13', topic: 'think-kpis', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'definitions',
    prompt: 'HR wants a KPI for how fast roles are filled. Which definition is the most useful?',
    options: ['Days from job approval to offer accepted, per role', 'Number of CVs received per month', 'Number of interviews held per week', 'Days from offer accepted to first day'], answer: 0,
    explain: 'Time to fill should cover the whole hiring process, with a clear start and end event, measured per role.' },
  { id: 'th2-kpi-14', topic: 'think-kpis', type: 'mc', kind: 'concept', difficulty: 2, concept: 'denominator',
    prompt: 'What is the usual definition of an online store\'s conversion rate?',
    options: ['Orders ÷ website sessions', 'Orders ÷ registered customers', 'Sessions ÷ orders', 'Revenue ÷ sessions'], answer: 0,
    explain: 'Conversion rate is the share of visits that end in an order. Revenue per session is a different metric.' },
  { id: 'th2-kpi-15', topic: 'think-kpis', type: 'number', kind: 'calculation', difficulty: 2, concept: 'denominator',
    prompt: 'An online store had 52,000 sessions and 1,240 orders last month. What is the conversion rate in %, to two decimal places?',
    answer: 2.38, tolerance: 0.01, verify: () => Math.round((1240 / 52000) * 10000) / 100,
    explain: '1,240 ÷ 52,000 = 2.38%. Always state the denominator: per session, per visitor or per customer give different rates.' },
  { id: 'th2-kpi-16', topic: 'think-kpis', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'metric-choice',
    prompt: 'Finance asks how much revenue is lost to returns. The unit return rate is 10.7%; the value-based rate is 4.7%. Which answers the question?',
    options: ['The value-based rate', 'The unit return rate', 'The average of the two', 'Neither rate is relevant'], answer: 0,
    explain: 'Finance cares about money, so the share of revenue returned is the right one. Unit rates suit questions about product quality or handling.' },
  { id: 'th2-kpi-17', topic: 'think-kpis', type: 'order', kind: 'sequence', difficulty: 3, concept: 'kpi',
    prompt: 'Order the steps for designing a new KPI.',
    options: ['Start from the business goal', 'Write the exact calculation and data source', 'Set a target and a comparison', 'Add a counter-metric against gaming'], answer: [0, 1, 2, 3],
    explain: 'Goal first, then a precise definition, then what "good" looks like, then a guard against gaming.' },
  { id: 'th2-kpi-18', topic: 'think-kpis', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'metric-choice',
    prompt: 'A school-meals charity reports "meals served". The trustees ask whether children are better off. Which KPI answers that?',
    options: ['Share of enrolled children with improved attendance or health', 'Number of meals served across all schools this year', 'Number of new school kitchens opened', 'Total money spent on ingredients and staff'], answer: 0,
    explain: 'Meals served measures activity (output). The trustees are asking about outcomes, so measure a change in the children.' },
  { id: 'th2-kpi-19', topic: 'think-kpis', type: 'tf', kind: 'concept', difficulty: 2, concept: 'kpi',
    prompt: 'True or false: a KPI shown without a target or previous period is hard to judge.',
    answer: true, explain: '"93% on time" means little until you know the target was 95% or last month was 88%.' },
  { id: 'th2-kpi-20', topic: 'think-kpis', type: 'mc', kind: 'concept', difficulty: 2, concept: 'definitions',
    prompt: 'A delivery company tracks on-time delivery. Which definition is the clearest?',
    options: ['Deliveries made by the promised date ÷ all deliveries', 'Deliveries made before noon ÷ all deliveries', 'Number of drivers who arrived on time', 'Average delivery time in hours'], answer: 0,
    explain: 'On time only makes sense against a promise. Counting every delivery in the denominator keeps failures visible.' },
  { id: 'th2-kpi-21', topic: 'think-kpis', type: 'number', kind: 'calculation', difficulty: 2, concept: 'kpi',
    prompt: '4,480 of 4,800 deliveries arrived by the promised date. What is the on-time rate in %, to two decimal places?',
    answer: 93.33, tolerance: 0.01, verify: () => Math.round((4480 / 4800) * 10000) / 100,
    explain: '4,480 ÷ 4,800 = 93.33%, so about 1 delivery in 15 missed its promised date.' },
  { id: 'th2-kpi-22', topic: 'think-kpis', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'definitions',
    prompt: 'On-time delivery jumped from 91% to 96% after the team stopped counting "customer not at home" as a failure. What should the report do?',
    options: ['Restate earlier months on the new rule, or show both', 'Celebrate the improvement', 'Go back to the old rule without telling anyone', 'Remove the KPI from the dashboard'], answer: 0,
    explain: 'The jump comes from a definition change, not better service. Recalculate history so the trend compares like with like.' },
  { id: 'th2-kpi-23', topic: 'think-kpis', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'metric-choice',
    prompt: 'Marketing wants to know whether paid ads pay for themselves. Which KPI answers it most directly?',
    options: ['Revenue from ads ÷ ad spend', 'Number of ad clicks', 'Number of ad impressions', 'Cost per click'], answer: 0,
    explain: 'Return on ad spend (ROAS) compares what the ads brought in with what they cost. Clicks and impressions are activity.' },
  { id: 'th2-kpi-24', topic: 'think-kpis', type: 'number', kind: 'calculation', difficulty: 2, concept: 'kpi',
    prompt: 'A campaign cost $4,000 in ads and brought in $18,000 of revenue. What is the return on ad spend (revenue ÷ spend)?',
    answer: 4.5, tolerance: 0.01, verify: () => 18000 / 4000,
    explain: '18,000 ÷ 4,000 = 4.5, so each $1 of ads brought $4.50 of revenue, before product costs.' },
  { id: 'th2-kpi-25', topic: 'think-kpis', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'metric-choice',
    prompt: 'A store trained staff to suggest add-on products. Which KPI shows whether it worked?',
    options: ['Items per transaction, before and after', 'Number of customers per day', 'Total staff hours worked', 'Number of products in stock'], answer: 0,
    explain: 'Add-on selling should raise items per basket. Customer numbers depend on footfall, not on the training.' },

  // ================================================================ think-charts
  { id: 'th2-chart-01', topic: 'think-charts', type: 'mc', kind: 'tool-selection', difficulty: 1, concept: 'chart-choice',
    prompt: 'Which chart shows monthly revenue over the last three years best?',
    options: ['Line chart', 'Pie chart', 'Scatter plot', 'Donut chart'], answer: 0,
    explain: 'Lines show change over time clearly, and a line per year makes seasons easy to compare.' },
  { id: 'th2-chart-02', topic: 'think-charts', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'chart-choice',
    prompt: 'You want to show how this year\'s revenue splits between three channels. Which chart works?',
    options: ['A single 100% bar, or a simple pie', 'A line chart with three lines', 'A scatter plot of the channels', 'A histogram of order values'], answer: 0,
    explain: 'With only a few parts of one whole, a 100% bar (or a pie) shows the shares clearly.' },
  { id: 'th2-chart-03', topic: 'think-charts', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'chart-choice',
    prompt: 'A pie chart has 12 slices of similar size. What is the main problem?',
    options: ['Similar angles are hard to compare', 'Pie charts cannot show 12 values', 'The slices do not add up to 100%', 'Pie charts need a legend'], answer: 0,
    explain: 'People judge angles poorly. A sorted bar chart makes small differences between 12 items easy to see.' },
  { id: 'th2-chart-04', topic: 'think-charts', type: 'number', kind: 'calculation', difficulty: 2, concept: 'chart-honesty',
    prompt: 'A bar chart\'s axis starts at $480k. Store A has $500k and store B $520k. How many times taller does B\'s bar look than A\'s?',
    answer: 2, tolerance: 0.01, verify: () => (520 - 480) / (500 - 480),
    explain: 'The visible bars are 40 and 20 units tall, so B looks twice as big, although it is only 4% higher. Start bars at zero.' },
  { id: 'th2-chart-05', topic: 'think-charts', type: 'tf', kind: 'concept', difficulty: 1, concept: 'chart-honesty',
    prompt: 'True or false: 3D effects make bar and pie charts harder to read accurately.',
    answer: true, explain: 'Perspective changes the apparent size of bars and slices, so 3D adds distortion without adding information.' },
  { id: 'th2-chart-06', topic: 'think-charts', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'chart-choice',
    prompt: 'A café wants to see sales by weekday and by hour of the day at once. Which visual fits?',
    options: ['A heatmap: weekdays by hours', 'A pie chart for each hour', 'A single line for the week', 'A KPI card with the total'], answer: 0,
    explain: 'A heatmap (a matrix with colour) shows two dimensions and one measure, so busy slots stand out.' },
  { id: 'th2-chart-07', topic: 'think-charts', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'chart-honesty',
    prompt: 'A chart puts revenue and ad spend on two different y-axes, and the lines move together. What is the risk?',
    options: ['The axis scales can make any two lines look linked', 'Two axes always hide the data', 'Revenue cannot be shown as a line', 'Ad spend must be shown as a pie'], answer: 0,
    explain: 'Each axis can be stretched independently, so the overlap may be a design choice. Check the numbers, or use two charts.' },
  { id: 'th2-chart-08', topic: 'think-charts', type: 'fill', kind: 'concept', difficulty: 2, concept: 'chart-honesty',
    prompt: 'A chart title that states the main message ("Online drives half of growth") rather than the topic is called an ____ title.',
    answer: ['action', 'headline', 'insight', 'message'], explain: 'An action (headline) title tells the reader what to take away, instead of just "Revenue by channel".' },
  { id: 'th2-chart-09', topic: 'think-charts', type: 'mc', kind: 'scenario', difficulty: 1, concept: 'chart-choice',
    prompt: 'A buyer needs to look up the exact stock value of each of 40 products. What should you give them?',
    options: ['A sorted table', 'A pie chart', 'A line chart', 'A map'], answer: 0,
    explain: 'When exact values matter, a table is the clearest visual. Charts are for patterns.' },
  { id: 'th2-chart-10', topic: 'think-charts', type: 'order', kind: 'sequence', difficulty: 2, concept: 'chart-choice',
    prompt: 'Order the steps for building a chart for a manager.',
    options: ['Write the question the chart must answer', 'Choose the chart type', 'Remove clutter and highlight the key point', 'Add a title that states the message'], answer: [0, 1, 2, 3],
    explain: 'The question decides the chart, then you simplify it, then the title spells out the answer.' },
  { id: 'th2-chart-11', topic: 'think-charts', type: 'tf', kind: 'concept', difficulty: 2, concept: 'chart-choice',
    prompt: 'True or false: a line chart is a good way to compare sales of unrelated products, such as tents, stoves and socks.',
    answer: false, explain: 'Lines suggest a sequence between the points. Separate categories belong in a bar chart.' },
  { id: 'th2-chart-12', topic: 'think-charts', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'chart-honesty',
    prompt: 'Your slide discusses one store out of eight. How should the bars be coloured?',
    options: ['Grey for all, one colour for that store', 'A different colour for every store', 'Red and green in turn', 'All bars in a bright colour'], answer: 0,
    explain: 'Colour should direct attention. Grey context plus one highlight tells the reader where to look.' },
  { id: 'th2-chart-13', topic: 'think-charts', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'chart-honesty',
    prompt: 'A chart of cumulative revenue rises smoothly all year. What can it hide?',
    options: ['A weak month, because a running total never falls', 'Nothing: cumulative charts show everything', 'The total for the year', 'The first month of the year'], answer: 0,
    explain: 'A running total only flattens when sales are weak; drops are easy to miss. Show monthly values alongside.' },
  { id: 'th2-chart-14', topic: 'think-charts', type: 'fill', kind: 'concept', difficulty: 1, concept: 'chart-choice',
    prompt: 'A single headline number with a comparison (for example "Revenue $347k, 98% of target") is shown on a ____ card.',
    answer: ['kpi', 'KPI', 'metric'], explain: 'KPI cards give one number fast. Add a comparison (target or last period) so the reader can judge it.' },
  { id: 'th2-chart-15', topic: 'think-charts', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'chart-choice',
    prompt: 'A manager wants a map to compare sales of five stores in the same city. What do you suggest?',
    options: ['A sorted bar chart compares them better', 'A map, because stores have addresses', 'A pie chart of the five stores', 'A 3D map with tall columns'], answer: 0,
    explain: 'Use a map only when location explains something. Here bars make the comparison easier.' },

  // ================================================================ think-tools
  { id: 'th2-tool-01', topic: 'think-tools', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'tool-choice',
    prompt: 'A colleague sends a 50-row CSV and asks for the total per category, once. What is the quickest good option?',
    options: ['Excel, with a PivotTable or SUMIFS', 'A new Power BI report', 'A scheduled SQL job', 'A Power Query folder import'], answer: 0,
    explain: 'For a small one-off question, the quickest reliable tool wins. Automation pays only when the task repeats.' },
  { id: 'th2-tool-02', topic: 'think-tools', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'tool-choice',
    prompt: 'You need to combine 5 million orders with the customers table in the company database. Where do you start?',
    options: ['SQL, joining inside the database', 'Excel, pasting both tables', 'A pie chart in Power BI', 'Retyping the key figures'], answer: 0,
    explain: 'Large joins belong where the data lives. Bring back only the result you need.' },
  { id: 'th2-tool-03', topic: 'think-tools', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'tool-choice',
    prompt: 'Twelve branches each send a monthly Excel file with the same layout. You need one combined table every month. Best choice?',
    options: ['Power Query, importing from a folder', 'Copy and paste into one sheet', 'A separate PivotTable for each file', 'SQL, typed in by hand'], answer: 0,
    explain: 'A folder import combines every file with the same steps. Next month you drop in the files and refresh.' },
  { id: 'th2-tool-04', topic: 'think-tools', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'tool-choice',
    prompt: 'Thirty managers want to explore sales themselves, refreshed daily, each seeing only their own region. Best fit?',
    options: ['Power BI with row-level security', 'A weekly Excel file by email', 'Thirty separate SQL queries', 'A printed report per manager'], answer: 0,
    explain: 'Power BI gives interactive self-service, scheduled refresh and row-level security for regions.' },
  { id: 'th2-tool-05', topic: 'think-tools', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'tool-choice',
    prompt: 'An auditor wants to see exactly how duplicates were removed from a monthly file. Which approach makes that easy?',
    options: ['Power Query, where each step is recorded', 'Deleting rows by hand in Excel', 'Sorting and hiding rows', 'Copying the clean rows to a new file'], answer: 0,
    explain: 'Power Query lists every applied step, so the cleaning can be checked and repeated exactly.' },
  { id: 'th2-tool-06', topic: 'think-tools', type: 'tf', kind: 'concept', difficulty: 2, concept: 'tool-choice',
    prompt: 'True or false: Power Query can combine all the files in a folder and pick up new files on refresh.',
    answer: true, explain: 'A folder source reads every file with the same steps, including files added later.' },
  { id: 'th2-tool-07', topic: 'think-tools', type: 'tf', kind: 'concept', difficulty: 2, concept: 'tool-choice',
    prompt: 'True or false: one Excel worksheet can hold 3 million rows.',
    answer: false, explain: 'A worksheet stops at 1,048,576 rows. Larger data belongs in a database, the Data Model or Power BI.' },
  { id: 'th2-tool-08', topic: 'think-tools', type: 'number', kind: 'calculation', difficulty: 3, concept: 'tool-choice',
    prompt: 'A worksheet holds 1,048,576 rows. A table has 3,200,000 rows. At least how many worksheets would you need to hold it?',
    answer: 4, verify: () => Math.ceil(3200000 / 1048576),
    explain: '3,200,000 ÷ 1,048,576 ≈ 3.05, so 4 sheets. Splitting data like this is a sign to use SQL or Power BI instead.' },
  { id: 'th2-tool-09', topic: 'think-tools', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'tool-choice',
    prompt: 'You have read-only access to the sales database and need the top 10 customers in each region. Which tool?',
    options: ['SQL with a ranking window function', 'Excel with a manual sort per region', 'A Power BI pie chart', 'A Power Query folder import'], answer: 0,
    explain: 'ROW_NUMBER() or RANK() partitioned by region answers it in one query, inside the database.' },
  { id: 'th2-tool-10', topic: 'think-tools', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'tool-choice',
    prompt: 'Every week an analyst copies and pastes new data into a report, and mistakes keep creeping in. What is the fix?',
    options: ['Automate the import with Power Query', 'Ask the analyst to be more careful', 'Check the report once a year', 'Stop producing the report'], answer: 0,
    explain: 'Manual repetition breeds errors. A recorded, refreshable import removes the copy-paste step.' },
  { id: 'th2-tool-11', topic: 'think-tools', type: 'order', kind: 'sequence', difficulty: 3, concept: 'tool-choice',
    prompt: 'Order a typical reporting pipeline.',
    options: ['SQL pulls the data from the database', 'Power Query cleans and shapes it', 'Power BI models it and adds measures', 'The report is shared with managers'], answer: [0, 1, 2, 3],
    explain: 'Extract in SQL, shape in Power Query, model and calculate in Power BI, then publish.' },
  { id: 'th2-tool-12', topic: 'think-tools', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'tool-choice',
    prompt: 'Managers need year-to-date sales that update when they click a store or category slicer. What do you build?',
    options: ['A DAX measure in Power BI', 'A fixed number typed into a card', 'A calculated column in Excel', 'A new SQL table for each store'], answer: 0,
    explain: 'Measures are recalculated for whatever the slicers select, so one YTD measure works for every store and category.' },
  { id: 'th2-tool-13', topic: 'think-tools', type: 'fill', kind: 'concept', difficulty: 2, concept: 'tool-choice',
    prompt: 'The formula language behind Power Query steps is called ____.',
    answer: ['M', 'M language', 'Power Query M'], explain: 'Every click in Power Query writes M code, which you can view in the Advanced Editor.' },
  { id: 'th2-tool-14', topic: 'think-tools', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'tool-choice',
    prompt: 'The CEO asks one question about a 2,000-row Excel file you already have open. What do you use?',
    options: ['A PivotTable in that workbook', 'A new database and SQL', 'A Power BI data model', 'A Power Query folder import'], answer: 0,
    explain: 'The data is small, already in Excel and the question is one-off. A PivotTable answers it in minutes.' },
  { id: 'th2-tool-15', topic: 'think-tools', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'scoping',
    prompt: 'A manager asks for "a dashboard" but only needs to decide once whether to close a store. What should you do first?',
    options: ['Ask what decision it supports; a short analysis may do', 'Build a full dashboard with every metric', 'Refuse until they explain themselves', 'Send them the raw data to explore'], answer: 0,
    explain: 'The decision defines the deliverable. A one-off decision often needs a focused analysis, not a maintained dashboard.' },
  { id: 'th2-tool-16', topic: 'think-tools', type: 'tf', kind: 'concept', difficulty: 2, concept: 'tool-choice',
    prompt: 'True or false: for every one-off question, a full Power BI model is the best choice.',
    answer: false, explain: 'Building and maintaining a model takes time. For a one-off question, use the quickest reliable tool.' },
  { id: 'th2-tool-17', topic: 'think-tools', type: 'number', kind: 'calculation', difficulty: 3, concept: 'tool-choice',
    prompt: 'A report takes 45 minutes by hand every week. Automating it takes 6 hours once. After how many weeks does the automation pay back?',
    answer: 8, verify: () => (6 * 60) / 45,
    explain: '360 minutes ÷ 45 minutes = 8 weeks. After that, every week saves 45 minutes and removes copy-paste errors.' },
];
