// Analyst thinking quiz bank, part E: validating your own work, communicating results.
export const THINK_QUIZ_E = [
  // ================================================================ think-validation
  { id: 'th2-val-01', topic: 'think-validation', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'validation',
    prompt: 'After joining customers to their addresses, the customer count rose from 4,500 to 5,120. What is the most likely cause?',
    options: ['Some customers have more than one address', 'New customers signed up during the join', 'The addresses table has fewer rows', 'The join removed duplicate customers'], answer: 0,
    explain: 'A one-to-many join repeats the customer for every address. Count distinct customers, or pick one address per customer first.' },
  { id: 'th2-val-02', topic: 'think-validation', type: 'mc', kind: 'concept', difficulty: 2, concept: 'validation',
    prompt: 'What is a sanity check?',
    options: ['Comparing a result with a known figure or a rough estimate', 'Running the same query twice in a row', 'Making the chart look more professional', 'Asking the manager whether they like it'], answer: 0,
    explain: 'If the order of magnitude disagrees with what you know (last year, the ledger, a quick estimate), something is wrong.' },
  { id: 'th2-val-03', topic: 'think-validation', type: 'number', kind: 'calculation', difficulty: 2, concept: 'validation',
    prompt: 'The orders table has 7,645 rows. After a LEFT JOIN to payments the result has 7,812 rows. How many extra rows did the join create?',
    answer: 167, verify: () => 7812 - 7645,
    explain: '7,812 − 7,645 = 167 extra rows: some orders have more than one payment, so their amounts would be counted twice.' },
  { id: 'th2-val-04', topic: 'think-validation', type: 'tf', kind: 'concept', difficulty: 3, concept: 'validation',
    prompt: 'True or false: a LEFT JOIN never returns fewer rows than the left table has.',
    answer: true, explain: 'Every left row is kept at least once. It can return more rows (fan-out), but not fewer, unless a WHERE clause removes them.' },
  { id: 'th2-val-05', topic: 'think-validation', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'validation',
    prompt: 'You suspect an INNER JOIN silently dropped some orders. How do you check?',
    options: ['Compare row counts and list keys with no match', 'Run the same INNER JOIN again', 'Sort the result by order date', 'Add ORDER BY to the query'], answer: 0,
    explain: 'Count before and after, then find the unmatched keys with a LEFT JOIN and WHERE the right side IS NULL.' },
  { id: 'th2-val-06', topic: 'think-validation', type: 'order', kind: 'sequence', difficulty: 3, concept: 'validation',
    prompt: 'Order these checks on a finished analysis.',
    options: ['Check row counts at each step', 'Compare the total with a trusted source', 'Trace a few records back to the source', 'Ask a colleague to review the logic'], answer: [0, 1, 2, 3],
    explain: 'Structure first, then totals, then individual records, then a fresh pair of eyes.' },
  { id: 'th2-val-07', topic: 'think-validation', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'validation',
    prompt: 'Your query says the average warehouse salary is $460,000. What do you do?',
    options: ['Check units and extreme values before reporting', 'Report it: the query ran without errors', 'Round it to $500,000 for the slide', 'Replace it with last year\'s figure'], answer: 0,
    explain: 'A query can run perfectly and still be wrong. Look for monthly vs annual mix-ups, cents, or a typo like an extra zero.' },
  { id: 'th2-val-08', topic: 'think-validation', type: 'fill', kind: 'concept', difficulty: 2, concept: 'reconciliation',
    prompt: 'Comparing your total with an independent figure, such as the finance ledger, and explaining the difference is called ____.',
    answer: ['reconciliation', 'reconciling', 'a reconciliation'], explain: 'Reconciliation shows your number agrees with an independent source, or explains why it does not.' },
  { id: 'th2-val-09', topic: 'think-validation', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'validation',
    prompt: 'A pivot shows a total margin of 486% in the grand total row. What went wrong?',
    options: ['The margin percentages were summed instead of recalculated', 'The company made a very large profit', 'The pivot is missing a filter on region', 'Margins above 100% are normal for pivots'], answer: 0,
    explain: 'Percentages cannot be added. Compute the total as total profit ÷ total revenue.' },
  { id: 'th2-val-10', topic: 'think-validation', type: 'number', kind: 'calculation', difficulty: 2, concept: 'validation',
    prompt: 'Region totals are $120k, $95k, $88k and $101k. The grand total says $412k. How much (in $k) is not explained by the regions?',
    answer: 8, verify: () => 412 - (120 + 95 + 88 + 101),
    explain: '120 + 95 + 88 + 101 = 404, so 8k is missing from the breakdown. Look for rows with a blank or unexpected region.' },
  { id: 'th2-val-11', topic: 'think-validation', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'validation',
    prompt: 'The four regions add up to $8k less than the grand total. What is the most likely explanation?',
    options: ['Some rows have a blank or unknown region', 'The grand total is always rounded up', 'One region was counted twice', 'The regions include tax and the total does not'], answer: 0,
    explain: 'If the parts are smaller than the whole, some rows fall outside the listed groups. Counting twice would make the parts bigger.' },
  { id: 'th2-val-12', topic: 'think-validation', type: 'tf', kind: 'concept', difficulty: 2, concept: 'validation',
    prompt: 'True or false: if a result looks reasonable, it does not need checking.',
    answer: false, explain: 'Reasonable-looking numbers can hide errors that cancel out. Check the structure and a few records anyway.' },
  { id: 'th2-val-13', topic: 'think-validation', type: 'mc', kind: 'concept', difficulty: 2, concept: 'validation',
    prompt: 'What does spot-checking mean?',
    options: ['Tracing a few records by hand back to the source', 'Highlighting cells with a coloured spot', 'Checking only the first row of the result', 'Removing records that look unusual'], answer: 0,
    explain: 'Following a handful of real records through each step proves the logic works on actual data.' },
  { id: 'th2-val-14', topic: 'think-validation', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'validation',
    prompt: 'A query filters order_time <= \'2025-12-31\', but order_time includes the time of day. What happens?',
    options: ['Most orders on 31 December are left out', 'Orders from January 2026 are included', 'The filter is ignored completely', 'Only midnight orders are left out'], answer: 0,
    explain: '\'2025-12-31\' means midnight at the start of that day, so later orders that day fail the test. Use order_time < \'2026-01-01\'.' },
  { id: 'th2-val-15', topic: 'think-validation', type: 'number', kind: 'calculation', difficulty: 2, concept: 'validation',
    prompt: 'Your query says 2025 revenue was $8,610,000. Finance says $861,000. How many times bigger is your figure?',
    answer: 10, verify: () => 8610000 / 861000,
    explain: 'Exactly 10 times: a round multiple like this usually points to a units or decimal error rather than real sales.' },
  { id: 'th2-val-16', topic: 'think-validation', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'validation',
    prompt: 'A result is almost exactly 10 times the figure finance reports. What should you suspect first?',
    options: ['A units, decimal or duplication error', 'A very successful sales year', 'A mistake in the finance team\'s figure', 'Normal differences between systems'], answer: 0,
    explain: 'Round multiples rarely happen by chance. Check units (cents vs dollars), decimals and joins before anything else.' },
  { id: 'th2-val-17', topic: 'think-validation', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'validation',
    prompt: 'How can you check that a new Power BI measure gives the right answer?',
    options: ['Compare it with a total you calculate another way', 'Check that the card shows a number', 'Change the colour of the visual', 'Trust it if there is no error message'], answer: 0,
    explain: 'Recalculate the same figure in SQL, Excel or a simple table for one slice, and confirm the two agree.' },
  { id: 'th2-val-18', topic: 'think-validation', type: 'tf', kind: 'concept', difficulty: 2, concept: 'validation',
    prompt: 'True or false: asking a colleague to review your query is a sign of weak skills.',
    answer: false, explain: 'Review is normal practice. A fresh reader spots assumptions you no longer see.' },
  { id: 'th2-val-19', topic: 'think-validation', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'validation',
    prompt: 'An hour before a deadline, a check shows your total is 3% off the ledger and you cannot explain why. What do you do?',
    options: ['Share it with a clear caveat, or ask for more time', 'Adjust the numbers until they match', 'Send it and say nothing', 'Delete the check from your notes'], answer: 0,
    explain: 'Be open about an unexplained gap. Hiding it or forcing a match damages trust far more than a short delay.' },
  { id: 'th2-val-20', topic: 'think-validation', type: 'fill', kind: 'concept', difficulty: 2, concept: 'validation',
    prompt: 'A basic structural check: the subtotals of a breakdown should ____ to the grand total.',
    answer: ['add up', 'sum', 'add', 'total', 'equal', 'match'], explain: 'If the parts do not add up to the whole, rows are missing, duplicated or in an unexpected group.' },
  { id: 'th2-val-21', topic: 'think-validation', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'duplicates',
    prompt: 'A query on order lines reports 7,446 "customers". The CRM has about 2,000 active buyers. What is the likely mistake?',
    options: ['It used COUNT(*) instead of COUNT(DISTINCT customer_id)', 'The CRM is out of date', 'Some customers have no email address', 'The query used ORDER BY'], answer: 0,
    explain: 'Each order line repeats the customer. Counting distinct IDs counts people, not rows.' },
  { id: 'th2-val-22', topic: 'think-validation', type: 'mc', kind: 'concept', difficulty: 2, concept: 'validation',
    prompt: 'Why write down the steps of an analysis as you go?',
    options: ['So someone can repeat and check the result', 'So the report looks longer', 'So you never have to check again', 'So nobody needs the source data'], answer: 0,
    explain: 'Documented steps make results reproducible and let others find mistakes.' },
  { id: 'th2-val-23', topic: 'think-validation', type: 'number', kind: 'calculation', difficulty: 2, concept: 'validation',
    prompt: 'A chart shows customer shares by segment: 42%, 31%, 19% and 12%. By how many percentage points do they exceed 100%?',
    answer: 4, verify: () => 42 + 31 + 19 + 12 - 100,
    explain: 'They add up to 104%, so either customers sit in more than one segment or the shares use different denominators.' },
  { id: 'th2-val-24', topic: 'think-validation', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'validation',
    prompt: 'Shares for four segments add up to 104%. What is the most likely reason?',
    options: ['Some customers are counted in more than one segment', 'Percentages always add up to more than 100', 'One segment has no customers', 'The chart uses the wrong colours'], answer: 0,
    explain: 'Shares of one whole add up to 100% (give or take rounding). A larger gap means overlap or mixed denominators.' },
  { id: 'th2-val-25', topic: 'think-validation', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'reconciliation',
    prompt: 'Your SQL counts 1,429 returned order lines; a colleague\'s Excel counts 1,466 returns. What is the best next step?',
    options: ['Check whether one counts lines and the other return events', 'Use the higher number to be safe', 'Average the two answers', 'Redo the Excel work in SQL and ignore it'], answer: 0,
    explain: 'A line can be returned more than once. Different units, not a mistake, can explain the gap: agree which one the question needs.' },

  // ================================================================ think-communication
  { id: 'th2-com-01', topic: 'think-communication', type: 'mc', kind: 'concept', difficulty: 2, concept: 'communication',
    prompt: 'What should come first in a briefing for a busy executive?',
    options: ['The conclusion and how big it is', 'How the data was collected', 'The list of tables you used', 'The problems you ran into'], answer: 0,
    explain: 'Lead with the answer. Method and detail follow for those who want them.' },
  { id: 'th2-com-02', topic: 'think-communication', type: 'order', kind: 'sequence', difficulty: 2, concept: 'communication',
    prompt: 'Order the parts of an answer-first briefing.',
    options: ['One-sentence insight with a number', 'Three supporting facts', 'Recommendation', 'Caveats and open questions'], answer: [0, 1, 2, 3],
    explain: 'Insight, evidence, action, then how far to trust it.' },
  { id: 'th2-com-03', topic: 'think-communication', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'scoping',
    prompt: 'A manager asks: "Can you pull all the customer data?" What is the best reply?',
    options: ['"Sure. What question will it help you answer?"', '"Here are all 40 columns for every customer."', '"No, that is too much data to share."', '"Which file format would you like?"'], answer: 0,
    explain: 'Knowing the question lets you deliver the right slice, and often the answer itself.' },
  { id: 'th2-com-04', topic: 'think-communication', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'communication',
    prompt: 'Which sentence explains "the LEFT JOIN returned NULL categories for 57 orders" best for a manager?',
    options: ['57 orders have no matching product, so they are missing from category totals', 'The LEFT JOIN produced NULLs in the category column for 57 rows', 'Some database problems happened with the joins this week', 'There were 57 NULLs, which is normal for a LEFT JOIN'], answer: 0,
    explain: 'Say what it means for the numbers they use, without the technical terms.' },
  { id: 'th2-com-05', topic: 'think-communication', type: 'tf', kind: 'concept', difficulty: 2, concept: 'communication',
    prompt: 'True or false: in a management briefing, each bullet should include a number where possible.',
    answer: true, explain: 'Numbers make points concrete and checkable. "Sales fell" invites the question "by how much?"' },
  { id: 'th2-com-06', topic: 'think-communication', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'communication',
    prompt: 'July returns are not fully processed yet. Which caveat is the most useful?',
    options: ['"July returns are still coming in; the return rate may rise slightly."', '"The data may have some problems we are not sure about."', '"Please do not fully trust any of these numbers yet."', '"Returns are complicated to measure, so treat with care."'], answer: 0,
    explain: 'A good caveat says what is uncertain and which way it could move the result.' },
  { id: 'th2-com-07', topic: 'think-communication', type: 'fill', kind: 'concept', difficulty: 2, concept: 'communication',
    prompt: 'Giving the conclusion before the supporting detail is called the answer-____ structure.',
    answer: ['first'], explain: 'Answer-first (also called the pyramid principle): busy readers get the point even if they stop after one line.' },
  { id: 'th2-com-08', topic: 'think-communication', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'communication',
    prompt: 'Which one-sentence insight is best?',
    options: ['Canyon reached 77% of its summer target because it opens fewer days than the plan assumed', 'Canyon is an interesting store with many things going on', 'We looked at Canyon in detail using several data sources', 'Canyon had some sales in the summer months this year'], answer: 0,
    explain: 'It gives the result, a number and the reason in one sentence.' },
  { id: 'th2-com-09', topic: 'think-communication', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'communication',
    prompt: 'Your estimate of the campaign effect is somewhere between +2% and +6%. How do you present it?',
    options: ['Give the range and say what would narrow it', 'Report +6% because it sounds better', 'Report +4% with no mention of the range', 'Leave the effect out of the report'], answer: 0,
    explain: 'Honest ranges support better decisions. Say what data or test would make the estimate firmer.' },
  { id: 'th2-com-10', topic: 'think-communication', type: 'number', kind: 'calculation', difficulty: 2, concept: 'communication',
    prompt: 'Q2 revenue was $347k against a target of $354k. What percentage of target was reached, to the nearest whole number?',
    answer: 98, verify: () => Math.round((347 / 354) * 100),
    explain: '347 ÷ 354 = 98%. "98% of target (−$7k)" gives both the rate and the size of the gap.' },
  { id: 'th2-com-11', topic: 'think-communication', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'communication',
    prompt: 'You present the same analysis to the data team and then to the board. What should change?',
    options: ['The level of detail and the terms used', 'The numbers in the results', 'The conclusion, to suit each audience', 'Nothing at all'], answer: 0,
    explain: 'Facts and conclusions stay the same; the depth and the vocabulary change with the audience.' },
  { id: 'th2-com-12', topic: 'think-communication', type: 'tf', kind: 'concept', difficulty: 2, concept: 'communication',
    prompt: 'True or false: sending all 20 charts you made helps a manager decide faster.',
    answer: false, explain: 'Choose the two or three charts that support the message. The rest can go in an appendix.' },
  { id: 'th2-com-13', topic: 'think-communication', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'communication',
    prompt: 'An email says only: "Revenue fell 12%." What is missing?',
    options: ['The period and what it is compared with', 'A chart in 3D', 'The SQL query used', 'The analyst\'s job title'], answer: 0,
    explain: 'A change needs a period and a baseline: "July revenue fell 12% compared with July last year".' },
  { id: 'th2-com-14', topic: 'think-communication', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'communication',
    prompt: 'Your analysis contradicts what the sales director believes. How do you handle it?',
    options: ['Show the evidence calmly and offer to check it together', 'Change the result to match their view', 'Leave the finding out of the report', 'Send it to their boss instead'], answer: 0,
    explain: 'Stay factual and open. Checking together builds trust and catches any mistake on either side.' },
  { id: 'th2-com-15', topic: 'think-communication', type: 'fill', kind: 'concept', difficulty: 2, concept: 'communication',
    prompt: 'The short section at the top of a report that sums up the findings for busy readers is the executive ____.',
    answer: ['summary'], explain: 'The executive summary should stand on its own: the main findings, their size and the recommendation.' },
  { id: 'th2-com-16', topic: 'think-communication', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'chart-honesty',
    prompt: 'Your key message is "Online is now half of sales". What title should the chart have?',
    options: ['Online now makes up half of sales', 'Sales by channel', 'Chart 3', 'Channel data 2026'], answer: 0,
    explain: 'A title that states the message tells the reader what to see, so the chart supports the point.' },
  { id: 'th2-com-17', topic: 'think-communication', type: 'number', kind: 'calculation', difficulty: 2, concept: 'communication',
    prompt: 'Revenue was $310k in Q1 and $347k in Q2. What is the growth in %, to one decimal place?',
    answer: 11.9, tolerance: 0.05, verify: () => Math.round(((347 - 310) / 310) * 1000) / 10,
    explain: '(347 − 310) ÷ 310 = 11.9%. Write it as "up 11.9% on Q1 ($347k vs $310k)" so readers can check it.' },
  { id: 'th2-com-18', topic: 'think-communication', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'communication',
    prompt: 'Which way of stating a change is clearest?',
    options: ['Up 12% on last July ($99k vs $88k)', 'Up a lot compared to before', 'Changed by 11,000', 'Better than expected'], answer: 0,
    explain: 'It gives the size, the comparison and the underlying numbers.' },
  { id: 'th2-com-19', topic: 'think-communication', type: 'tf', kind: 'concept', difficulty: 2, concept: 'communication',
    prompt: 'True or false: rounding $347,412 to "$347k" in a headline is fine.',
    answer: true, explain: 'Headlines need readable numbers. Keep the exact figure in the table or appendix.' },
  { id: 'th2-com-20', topic: 'think-communication', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'communication',
    prompt: 'A manager asks how you got the numbers. What is the best reply?',
    options: ['A short plain summary, with detail offered separately', 'The full SQL code read out line by line', 'A refusal: the method is too technical', 'A reminder that the numbers are correct'], answer: 0,
    explain: 'Answer briefly in plain words, and offer the technical appendix for anyone who wants it.' },
  { id: 'th2-com-21', topic: 'think-communication', type: 'mc', kind: 'concept', difficulty: 2, concept: 'communication',
    prompt: 'What is the "so what" of a finding?',
    options: ['Why it matters for a decision', 'The chart used to show it', 'The name of the data source', 'The date of the analysis'], answer: 0,
    explain: 'A finding without a "so what" leaves the reader asking what to do. Link it to a decision or action.' },
  { id: 'th2-com-22', topic: 'think-communication', type: 'order', kind: 'sequence', difficulty: 3, concept: 'scoping',
    prompt: 'Order the steps for scoping a vague request.',
    options: ['Clarify the question and the comparison', 'Agree the metric and the period', 'List the data you need', 'Plan the first analyses'], answer: [0, 1, 2, 3],
    explain: 'Understand the question, pin down how it is measured, then find the data and plan the work.' },
  { id: 'th2-com-23', topic: 'think-communication', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'communication',
    prompt: 'Which bullet in a briefing is the weakest?',
    options: ['Sales were quite a bit lower in some places', 'West reached 87% of target (−$14k)', 'Online grew 21% on last year', 'Returns fell from 11% to 9%'], answer: 0,
    explain: 'It is vague: no number, no place, no comparison. The others can be checked and acted on.' },
];
