// Analyst thinking quiz bank, part B: averages and percentages, distributions and outliers,
// and asking the right business questions.
export const THINK_QUIZ_B = [
  // ================================================================ think-metrics
  { id: 'th2-met-01', topic: 'think-metrics', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pct-points',
    prompt: 'Market share went from 12% to 15%. By how many percentage points did it change?',
    answer: 3, verify: () => 15 - 12,
    explain: '15 − 12 = 3 percentage points. In relative terms that is a 25% increase, which is a different statement.' },
  { id: 'th2-met-02', topic: 'think-metrics', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pct-points',
    prompt: 'Market share went from 12% to 15%. By what percentage did it increase (relative change)?',
    answer: 25, verify: () => ((15 - 12) / 12) * 100,
    explain: '(15 − 12) ÷ 12 = 25%. Always say whether you mean points or percent.' },
  { id: 'th2-met-03', topic: 'think-metrics', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pct-points',
    prompt: 'A report says "margin improved by 50%" when it moved from 4% to 6%. What is a clearer statement?',
    options: ['Margin rose by 2 percentage points, from 4% to 6%', 'Margin rose by 50%, from 4% to 54%', 'Margin rose by 50 percentage points', 'Margin doubled from 4% to 8%'], answer: 0,
    explain: 'A 50% relative rise on a small base sounds dramatic. Stating the points and both values avoids misreading.' },
  { id: 'th2-met-04', topic: 'think-metrics', type: 'number', kind: 'calculation', difficulty: 2, concept: 'mean-median',
    prompt: 'Five delivery times in days: 2, 3, 3, 4, 18. What is the median?',
    answer: 3, verify: () => [2, 3, 3, 4, 18].sort((a, b) => a - b)[2],
    explain: 'Sorted, the middle (third) value is 3. The mean is 6, pulled up by the 18-day delivery.' },
  { id: 'th2-met-05', topic: 'think-metrics', type: 'number', kind: 'calculation', difficulty: 2, concept: 'mean-median',
    prompt: 'Same delivery times (2, 3, 3, 4, 18). What is the mean?',
    answer: 6, verify: () => (2 + 3 + 3 + 4 + 18) / 5,
    explain: '30 ÷ 5 = 6 days: twice the median, because of one slow delivery.' },
  { id: 'th2-met-06', topic: 'think-metrics', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'mean-median',
    prompt: 'A property website wants to describe a "typical" house price in a town with a few mansions. Which figure fits?',
    options: ['The median price', 'The mean price', 'The highest price', 'The total of all prices'], answer: 0,
    explain: 'A few very expensive houses pull the mean up. The median describes the middle of the market.' },
  { id: 'th2-met-07', topic: 'think-metrics', type: 'number', kind: 'calculation', difficulty: 3, concept: 'weighted-avg', crossConcept: true,
    prompt: 'Store A: 800 orders, average $50. Store B: 200 orders, average $100. What is the average order value across both stores?',
    answer: 60, verify: () => (800 * 50 + 200 * 100) / (800 + 200),
    explain: '(40,000 + 20,000) ÷ 1,000 = $60. The simple average of the two averages ($75) ignores that store A has four times the orders.' },
  { id: 'th2-met-08', topic: 'think-metrics', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'simpson',
    prompt: 'Both regions improved their conversion rate, but the company\'s overall rate fell. How is that possible?',
    options: ['The mix shifted towards the region with the lower rate', 'One of the regions must be wrong', 'Overall rates cannot fall in this case', 'Conversion was measured twice'], answer: 0,
    explain: 'If more traffic moves to the region with a lower rate, the overall average can fall even though each region improved. That is a mix effect (Simpson\'s paradox).' },
  { id: 'th2-met-09', topic: 'think-metrics', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pct-points',
    prompt: 'True or false: a fall from 40% to 30% is a 10% decrease.',
    answer: false, explain: 'It is 10 percentage points, which is a 25% relative decrease (10 ÷ 40).' },
  { id: 'th2-met-10', topic: 'think-metrics', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'denominator',
    prompt: 'A manager wants to know which product "sells best". Products have very different prices. Which measure should you ask about?',
    options: ['Whether "best" means units, revenue or margin', 'Always units sold', 'Always the number of orders', 'Always the list price'], answer: 0,
    explain: 'A cheap product can lead on units and trail on revenue. Agree the measure before ranking.' },
  { id: 'th2-met-11', topic: 'think-metrics', type: 'number', kind: 'calculation', difficulty: 3, concept: 'denominator',
    prompt: 'A clinic had 45 complaints from 9,000 visits this year and 30 from 5,000 last year. Complaints per 1,000 visits this year?',
    answer: 5, verify: () => (45 / 9000) * 1000,
    explain: '45 ÷ 9,000 × 1,000 = 5 per 1,000 visits. Last year was 6 per 1,000, so the rate improved even though complaints rose.' },
  { id: 'th2-met-12', topic: 'think-metrics', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'denominator',
    prompt: 'Complaints rose from 30 to 45, while visits rose from 5,000 to 9,000. What is the best summary?',
    options: ['More complaints, but a lower complaint rate', 'Service got 50% worse', 'Nothing changed', 'Visits caused the complaints'], answer: 0,
    explain: 'The count rose by half, but visits nearly doubled, so the rate fell from 6 to 5 per 1,000.' },
  { id: 'th2-met-13', topic: 'think-metrics', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pct-points',
    prompt: 'The difference between two percentages (for example 12% and 15%) is measured in percentage ____.',
    answer: ['points'], explain: 'Percentage points: 15% − 12% = 3 points.' },
  { id: 'th2-met-14', topic: 'think-metrics', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'weighted-avg', crossConcept: true,
    prompt: 'A regional report gives the average margin % as the mean of the stores\' margin percentages. What is the flaw?',
    options: ['Small stores count as much as large ones', 'Margins cannot be averaged at all', 'Percentages must be summed instead', 'Stores must be sorted first'], answer: 0,
    explain: 'The regional margin is total margin ÷ total revenue, which weights stores by their sales.' },
  { id: 'th2-met-15', topic: 'think-metrics', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pct-points',
    prompt: 'Revenue fell 20% one year and rose 20% the next. What is the overall change in %, compared with the start?',
    answer: -4, verify: () => (0.8 * 1.2 - 1) * 100,
    explain: '0.8 × 1.2 = 0.96, a 4% fall overall. A rise of 20% does not undo a fall of 20%.' },
  { id: 'th2-met-16', topic: 'think-metrics', type: 'tf', kind: 'concept', difficulty: 2, concept: 'mean-median',
    prompt: 'True or false: if mean and median are almost equal, the data is roughly symmetric.',
    answer: true, explain: 'A big gap between them signals skew. When they are close, the distribution is roughly balanced (though it can still have two peaks).' },
  { id: 'th2-met-17', topic: 'think-metrics', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'simpson',
    prompt: 'Treatment A has a higher success rate than B in both small and large hospitals, but B looks better overall. What should the report show?',
    options: ['The results split by hospital size', 'Only the overall comparison', 'Only the large hospitals', 'The average of the two overall rates'], answer: 0,
    explain: 'When the mix differs, the split view is the fair comparison. The overall figure is misleading.' },
  { id: 'th2-met-18', topic: 'think-metrics', type: 'number', kind: 'calculation', difficulty: 2, concept: 'denominator',
    prompt: 'An NGO reached 1,200 households with a budget of $54,000. What is the cost per household?',
    answer: 45, verify: () => 54000 / 1200,
    explain: '$54,000 ÷ 1,200 = $45 per household, a figure donors can compare across programmes.' },
  { id: 'th2-met-19', topic: 'think-metrics', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pct-points',
    prompt: 'Prices rose 10% and sales volume fell 10%. What happened to revenue?',
    options: ['It fell by 1%', 'It stayed the same', 'It rose by 1%', 'It fell by 10%'], answer: 0,
    verify: () => 'It fell by 1%',
    explain: '1.1 × 0.9 = 0.99, so revenue is 1% lower. Percentage changes multiply; they do not add.' },
  { id: 'th2-met-20', topic: 'think-metrics', type: 'order', kind: 'sequence', difficulty: 2, concept: 'mean-median',
    prompt: 'Order these values from smallest to largest for the data 1, 2, 2, 3, 22.',
    options: ['Mode (2)', 'Median (2)', 'Mean (6)', 'Maximum (22)'], answer: [0, 1, 2, 3],
    explain: 'Mode and median are both 2 here; the mean (6) is pulled up by the 22; the maximum is 22.' },

  // ================================================================ think-averages
  { id: 'th2-avg-01', topic: 'think-averages', type: 'mc', kind: 'concept', difficulty: 1, concept: 'outliers',
    prompt: 'Which summary is least affected by one extreme value?',
    options: ['Median', 'Mean', 'Total', 'Range'], answer: 0,
    explain: 'The median only depends on the middle value. Mean, total and range all move with an extreme value.' },
  { id: 'th2-avg-02', topic: 'think-averages', type: 'mc', kind: 'concept', difficulty: 2, concept: 'outliers',
    prompt: 'What does the 90th percentile of delivery time tell you?',
    options: ['90% of deliveries take this long or less', 'The average delivery takes this long', '90 deliveries took this long', 'The slowest delivery took this long'], answer: 0,
    explain: 'Percentiles describe the distribution: 90% are at or below that value.' },
  { id: 'th2-avg-03', topic: 'think-averages', type: 'number', kind: 'calculation', difficulty: 2, concept: 'outliers',
    prompt: 'Quartiles of order value: 25th percentile $40, 75th percentile $100. What is the interquartile range (IQR)?',
    answer: 60, verify: () => 100 - 40,
    explain: 'IQR = Q3 − Q1 = 100 − 40 = $60. The middle half of orders sits in that range.' },
  { id: 'th2-avg-04', topic: 'think-averages', type: 'number', kind: 'calculation', difficulty: 3, concept: 'outliers',
    prompt: 'With Q1 = $40, Q3 = $100 and IQR = $60, above what value would an order be flagged by the 1.5 × IQR rule?',
    answer: 190, verify: () => 100 + 1.5 * 60,
    explain: 'Q3 + 1.5 × IQR = 100 + 90 = $190. Orders above that are flagged for a closer look, not automatically removed.' },
  { id: 'th2-avg-05', topic: 'think-averages', type: 'tf', kind: 'concept', difficulty: 2, concept: 'outliers',
    prompt: 'True or false: salaries are usually right-skewed, so the mean salary is above the median.',
    answer: true, explain: 'A minority of high earners pull the mean up. The median is closer to a typical salary.' },
  { id: 'th2-avg-06', topic: 'think-averages', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'outliers',
    prompt: 'Which chart best shows how 5,000 delivery times are spread?',
    options: ['Histogram', 'Pie chart', 'Single card', 'Line chart by customer'], answer: 0,
    explain: 'A histogram shows the shape of a distribution: where values cluster and how long the tail is.' },
  { id: 'th2-avg-07', topic: 'think-averages', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'outliers',
    prompt: 'One corporate order of $48,000 sits among orders that are usually $50 to $300. What is the best treatment in a monthly report?',
    options: ['Keep it, and show it separately from normal orders', 'Delete it as an error', 'Replace it with $300', 'Hide it in the total without comment'], answer: 0,
    explain: 'It is real revenue, but it distorts averages and trends. Report it separately so both stories are visible.' },
  { id: 'th2-avg-08', topic: 'think-averages', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'outliers',
    prompt: 'A product\'s price shows $1,990 in one row and $19.90 everywhere else. What is most likely?',
    options: ['A decimal point was lost when the price was typed', 'A premium version of the product', 'A bulk order of 100 units', 'A currency conversion'], answer: 0,
    explain: 'Exactly 100 times the usual price points to a missing decimal. Check the row and correct it with the data owner.' },
  { id: 'th2-avg-09', topic: 'think-averages', type: 'number', kind: 'calculation', difficulty: 2, concept: 'mean-median',
    prompt: 'Refunds: $20, $30, $40, $50, $60, $700. What is the median?',
    answer: 45, verify: () => (40 + 50) / 2,
    explain: 'With six values the median is the average of the 3rd and 4th: (40 + 50) ÷ 2 = $45.' },
  { id: 'th2-avg-10', topic: 'think-averages', type: 'number', kind: 'calculation', difficulty: 2, concept: 'mean-median',
    prompt: 'Same refunds ($20, $30, $40, $50, $60, $700). What is the mean, to the nearest dollar?',
    answer: 150, tolerance: 0.5, verify: () => (20 + 30 + 40 + 50 + 60 + 700) / 6,
    explain: '900 ÷ 6 = $150, more than three times the median, because of one $700 refund.' },
  { id: 'th2-avg-11', topic: 'think-averages', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'outliers',
    prompt: 'Average call waiting time is 2 minutes, but 10% of callers wait more than 15 minutes. What is the better headline for a service review?',
    options: ['One caller in ten waits over 15 minutes', 'Average wait is just 2 minutes', 'Calls are answered quickly', 'Waiting time is normal'], answer: 0,
    explain: 'The average hides a long tail that matters most to customers. Percentiles describe the experience better.' },
  { id: 'th2-avg-12', topic: 'think-averages', type: 'fill', kind: 'concept', difficulty: 2, concept: 'outliers',
    prompt: 'The range between the 25th and 75th percentiles is called the ____ range.',
    answer: ['interquartile', 'IQR', 'inter-quartile'], explain: 'The interquartile range (IQR) covers the middle half of the data.' },
  { id: 'th2-avg-13', topic: 'think-averages', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'outliers',
    prompt: 'After excluding three outliers, average delivery time drops from 2.9 to 2.3 days. What must the report say?',
    options: ['Which rows were excluded and why', 'Nothing: exclusions are routine', 'Only the original 2.9', 'Only that delivery improved'], answer: 0,
    explain: 'Exclusions change the result, so readers must know about them.' },
  { id: 'th2-avg-14', topic: 'think-averages', type: 'tf', kind: 'concept', difficulty: 2, concept: 'outliers',
    prompt: 'True or false: a value flagged by the 1.5 × IQR rule must be deleted.',
    answer: false, explain: 'The rule flags values to investigate. Real extreme cases are kept.' },
  { id: 'th2-avg-15', topic: 'think-averages', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'mean-median',
    prompt: 'An HR report says "average tenure is 11 years", but most staff joined in the last 3 years. What is the likely issue?',
    options: ['A few very long-serving staff pull the mean up', 'Tenure is measured in months', 'New staff were double counted', 'The report is from a different company'], answer: 0,
    explain: 'Tenure is often right-skewed. The median, and a distribution chart, would describe the workforce better.' },
  { id: 'th2-avg-16', topic: 'think-averages', type: 'number', kind: 'calculation', difficulty: 3, concept: 'weighted-avg', crossConcept: true,
    prompt: 'Site A sells 1,000 dishes at an average $10; site B sells 250 at $14. What is the group average price per dish?',
    answer: 10.8, tolerance: 0.01, verify: () => (1000 * 10 + 250 * 14) / 1250,
    explain: '(10,000 + 3,500) ÷ 1,250 = $10.80. The simple average of the two sites would be $12.00.' },
  { id: 'th2-avg-17', topic: 'think-averages', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'outliers',
    prompt: 'A histogram of basket sizes has two clear peaks: around $15 and around $120. What does that suggest?',
    options: ['Two different kinds of shopping trip', 'An error in the data', 'That the average is the best summary', 'That all baskets are similar'], answer: 0,
    explain: 'Two peaks usually mean two groups (quick top-ups and big shops). Report them separately; a single average would describe neither.' },
  { id: 'th2-avg-18', topic: 'think-averages', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'mean-median',
    prompt: 'Which Excel function returns the middle value of a range?',
    options: ['MEDIAN', 'AVERAGE', 'MODE', 'MIDDLE'], answer: 0,
    explain: 'MEDIAN returns the middle value. There is no MIDDLE function.' },
  { id: 'th2-avg-19', topic: 'think-averages', type: 'order', kind: 'sequence', difficulty: 2, concept: 'outliers',
    prompt: 'Order the steps for handling a suspicious value.',
    options: ['Find it with a chart or a rule', 'Look at the full row and its context', 'Decide: error or real case', 'Correct, exclude or keep, and note it'], answer: [0, 1, 2, 3],
    explain: 'Find, inspect, decide, act and document.' },
  { id: 'th2-avg-20', topic: 'think-averages', type: 'tf', kind: 'concept', difficulty: 2, concept: 'mean-median',
    prompt: 'True or false: the median can be used to describe typical delivery time even if a few deliveries were lost for weeks.',
    answer: true, explain: 'The median ignores how extreme the extreme values are, so a few lost parcels do not distort it.' },
  { id: 'th2-avg-21', topic: 'think-averages', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'outliers',
    prompt: 'A donor asks for the "average donation" to plan a campaign. Donations range from $5 to $50,000. What do you give them?',
    options: ['Median and mean, with the share from the largest gifts', 'Only the mean donation, as requested', 'Only the size of the largest single gift', 'The total number of donors and nothing else'], answer: 0,
    explain: 'The median shows a typical gift, the mean shows income per donor, and the share from big gifts shows how dependent the NGO is on a few donors.' },
  { id: 'th2-avg-22', topic: 'think-averages', type: 'number', kind: 'calculation', difficulty: 3, concept: 'outliers',
    prompt: 'Donations total $200,000. The five largest gifts total $120,000. What share of income comes from those five gifts?',
    answer: 60, verify: () => (120000 / 200000) * 100,
    explain: '120,000 ÷ 200,000 = 60%. Losing one big donor would hurt far more than the average suggests.' },
  { id: 'th2-avg-23', topic: 'think-averages', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'outliers',
    prompt: 'The "average age of customers" is 67, although the brand targets students. The age field contains many 1900 birth years. What happened?',
    options: ['A default birth year was used for unknown ages', 'The brand really serves older people', 'Students lie about their age', 'Ages were stored in months'], answer: 0,
    explain: 'Default values like 1900 are missing data in disguise. Treat them as unknown before averaging.' },
  { id: 'th2-avg-24', topic: 'think-averages', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'mean-median',
    prompt: 'Mean salary $46,000; median $41,800. Which statement is correct?',
    options: ['Half of employees earn less than $41,800', 'Most employees earn $46,000', 'Nobody earns less than $41,800', 'The mean is the typical salary'], answer: 0,
    explain: 'That is the definition of the median. The mean is higher because of a smaller group of high earners.' },
  { id: 'th2-avg-25', topic: 'think-averages', type: 'fill', kind: 'concept', difficulty: 2, concept: 'mean-median',
    prompt: 'When a few large values pull the mean above the median, the data is called right-____.',
    answer: ['skewed', 'skew'], explain: 'Right-skewed (positively skewed): a long tail of high values.' },

  // ================================================================ think-questions
  { id: 'th2-ask-01', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 1, concept: 'business-questions',
    prompt: 'A director asks for "sales by region". Which question changes what you deliver the most?',
    options: ['What decision will this support?', 'Would you like a bar or a column chart?', 'Should the file be named by date?', 'Do you prefer PDF or Excel?'], answer: 0,
    explain: 'The decision tells you the definition, period and comparison that matter.' },
  { id: 'th2-ask-02', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'business-questions',
    prompt: 'You are asked for "revenue last quarter". Which clarifying question matters most?',
    options: ['Before or after discounts, refunds and cancellations?', 'Which font should the report use?', 'How many decimal places?', 'Should the numbers be in a table?'], answer: 0,
    explain: 'Revenue has several legitimate definitions. Agreeing one avoids a later dispute.' },
  { id: 'th2-ask-03', topic: 'think-questions', type: 'tf', kind: 'concept', difficulty: 1, concept: 'business-questions',
    prompt: 'True or false: asking questions before starting an analysis wastes the requester\'s time.',
    answer: false, explain: 'A few minutes of questions saves hours of rework on the wrong analysis.' },
  { id: 'th2-ask-04', topic: 'think-questions', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'business-questions',
    prompt: 'A manager asks "why did sales fall in July?" You check: July sales rose 4% on last July. What is the best reply?',
    options: ['Share the finding and ask what made sales look lower', 'Explain a fall that did not happen', 'Say the data must be wrong', 'Ignore the question'], answer: 0,
    explain: 'Check the premise and discuss it. The manager may have compared July with June, or looked at one store.' },
  { id: 'th2-ask-05', topic: 'think-questions', type: 'order', kind: 'sequence', difficulty: 2, concept: 'business-questions',
    prompt: 'Order a good scoping conversation.',
    options: ['Understand the decision behind the request', 'Agree the definitions and scope', 'Agree the comparison (target, last year)', 'Agree the deadline and format'], answer: [0, 1, 2, 3],
    explain: 'Start with the why, then what exactly, then compared with what, then when and how.' },
  { id: 'th2-ask-06', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'business-questions',
    prompt: 'A restaurant owner wants to know "which dishes to drop". What information is most important to ask about?',
    options: ['Margin per dish, not only sales volume', 'The colour of the menu', 'Dish names in alphabetical order', 'The number of chairs'], answer: 0,
    explain: 'A dish that sells little but has a high margin, or pulls customers in, may be worth keeping. Volume alone is not enough.' },
  { id: 'th2-ask-07', topic: 'think-questions', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'scoping',
    prompt: 'Which document helps avoid misunderstandings about an analysis request?',
    options: ['A short scoping note: question, measure, comparison, data', 'A long list of every table available', 'A copy of last year\'s report', 'A calendar invite'], answer: 0,
    explain: 'A scoping note written back to the requester confirms that you will answer the right question.' },
  { id: 'th2-ask-08', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'business-questions',
    prompt: 'HR asks "which department has the worst absence?". The data has no part-time flags. What do you tell them early?',
    options: ['Part-time staff may distort per-person comparisons', 'Nothing until the report is finished', 'That absence cannot be measured', 'That the question is not allowed'], answer: 0,
    explain: 'Saying early what the data cannot show sets expectations and may get you the missing information.' },
  { id: 'th2-ask-09', topic: 'think-questions', type: 'tf', kind: 'concept', difficulty: 2, concept: 'business-questions',
    prompt: 'True or false: "compared with what?" is one of the most useful questions an analyst can ask.',
    answer: true, explain: 'A number means little without a comparison: a target, last year, another region or a benchmark.' },
  { id: 'th2-ask-10', topic: 'think-questions', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'business-questions',
    prompt: 'A request says "we need more customers". What is missing before you can analyse it?',
    options: ['What counts as a customer and over what period', 'How many employees work in marketing', 'The address of the head office', 'Which colours the report should use'], answer: 0,
    explain: 'Registered accounts, active buyers or households give very different numbers. Define it first.' },
  { id: 'th2-ask-11', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'business-questions',
    prompt: 'The CEO wants an answer "by Friday", but the data needed arrives next Wednesday. What is the best move?',
    options: ['Say so now and offer a partial answer by Friday', 'Wait until Friday to say it is late', 'Guess the missing data', 'Deliver something unrelated'], answer: 0,
    explain: 'Early, honest expectations plus a useful partial answer beat a surprise on the deadline.' },
  { id: 'th2-ask-12', topic: 'think-questions', type: 'fill', kind: 'concept', difficulty: 2, concept: 'scoping',
    prompt: 'Turning a vague request into a clear, measurable question is called ____.',
    answer: ['scoping', 'scope'], explain: 'Scoping: defining the question, measures, comparison, data and limits.' },
  { id: 'th2-ask-13', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'business-questions',
    prompt: 'A marketing manager asks "did the campaign work?". Which question should you ask first?',
    options: ['What was the campaign meant to achieve?', 'What was the campaign\'s slogan?', 'Which agency designed it?', 'How long was the TV advert?'], answer: 0,
    explain: 'The goal (new customers, more orders, higher spend) decides the measure of success.' },
  { id: 'th2-ask-14', topic: 'think-questions', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'business-questions',
    prompt: 'A logistics manager asks for "on-time delivery by driver". Why ask about routes?',
    options: ['Route difficulty affects on-time rates regardless of the driver', 'Routes decide the chart colours', 'Drivers choose their own routes', 'Routes are always exactly the same length'], answer: 0,
    explain: 'Comparing drivers on very different routes is unfair. Route information lets you compare like with like.' },
  { id: 'th2-ask-15', topic: 'think-questions', type: 'tf', kind: 'concept', difficulty: 2, concept: 'business-questions',
    prompt: 'True or false: an analyst should say which questions the data cannot answer.',
    answer: true, explain: 'Stating limits early avoids false confidence and sometimes gets you the missing data.' },
  { id: 'th2-ask-16', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'business-questions',
    prompt: 'Finance asks for "the cost of staff turnover". What is a sensible clarifying question?',
    options: ['Which costs should count: recruitment, training, lost output?', 'How many staff are in finance?', 'Which month is busiest?', 'What is the company\'s founding year?'], answer: 0,
    explain: 'Turnover cost can be narrow or broad. Agree which components to include before calculating.' },
  { id: 'th2-ask-17', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'scoping',
    prompt: 'You are asked to "analyse everything about our customers". What is the best response?',
    options: ['Ask which decisions are coming up and focus on those', 'Build 50 charts to cover everything', 'Refuse: the request is too broad', 'Send the raw customer table'], answer: 0,
    explain: 'Unfocused requests produce unfocused reports. Anchor the work to decisions.' },
  { id: 'th2-ask-18', topic: 'think-questions', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'business-questions',
    prompt: 'A manager wants to "compare our stores". Stores opened in different years. What should you ask?',
    options: ['Whether to compare only stores open for the whole period', 'Whether store names should be shortened', 'Whether to use a pie chart', 'Whether managers should be named'], answer: 0,
    explain: 'New stores distort comparisons. Agree whether to use like-for-like stores.' },
  { id: 'th2-ask-19', topic: 'think-questions', type: 'order', kind: 'sequence', difficulty: 3, concept: 'business-questions',
    prompt: 'Order the parts of a scoping note.',
    options: ['The question, in one sentence', 'The decision it supports', 'The measure and its definition', 'Data available and not available'], answer: [0, 1, 2, 3],
    explain: 'What, why, how measured, and what the data can and cannot cover.' },
  { id: 'th2-ask-20', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'business-questions',
    prompt: 'An NGO director asks "are donors giving less?". What do you need to agree first?',
    options: ['Per donor or in total, and compared with which period', 'The font for the charts', 'Which donors to thank', 'The date of the next board meeting only'], answer: 0,
    explain: 'Total giving can rise while giving per donor falls. Agree the measure and the comparison period.' },
  { id: 'th2-ask-21', topic: 'think-questions', type: 'tf', kind: 'concept', difficulty: 2, concept: 'scoping',
    prompt: 'True or false: a scoping note should be sent back to the requester to confirm.',
    answer: true, explain: 'Confirmation catches misunderstandings before any work is done.' },
  { id: 'th2-ask-22', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'business-questions',
    prompt: 'A request asks you to "prove the new manager is doing a bad job". What is the most professional approach?',
    options: ['Offer a fair assessment of the store\'s results, whatever they show', 'Search only for negative numbers', 'Refuse to look at any data', 'Compare the store with the best store only'], answer: 0,
    explain: 'Analysts test questions; they do not build a case for a fixed conclusion. A fair method protects everyone.' },
  { id: 'th2-ask-23', topic: 'think-questions', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'business-questions',
    prompt: 'A request asks for "weekly sales". The business week runs Monday to Sunday, but the system uses Sunday to Saturday. What should you do?',
    options: ['Ask which week definition to use', 'Use the system week without saying', 'Use calendar months instead', 'Average both weeks'], answer: 0,
    explain: 'Week definitions change totals. Agree one and state it on the report.' },
  { id: 'th2-ask-24', topic: 'think-questions', type: 'fill', kind: 'concept', difficulty: 2, concept: 'business-questions',
    prompt: 'The question "compared with ____?" is the best way to give a single number meaning. (One word.)',
    answer: ['what'], explain: '"Compared with what?" leads to targets, last year, benchmarks or other units.' },
  { id: 'th2-ask-25', topic: 'think-questions', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'business-questions',
    prompt: 'You realise halfway through that the request could mean two different things. What do you do?',
    options: ['Check with the requester before continuing', 'Pick one and hope it is right', 'Do both without saying', 'Stop the work silently'], answer: 0,
    explain: 'A short check saves finishing the wrong analysis.' },
];
