// Analyst thinking quiz bank, part C: cause and correlation, interpreting results, definitions.
export const THINK_QUIZ_C = [
  // ================================================================ think-causation
  { id: 'th2-cause-01', topic: 'think-causation', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'causation',
    prompt: 'Ice-cream sales and sunburn cases rise together. What is the most likely explanation?',
    options: ['Hot, sunny weather drives both', 'Ice cream causes sunburn', 'Sunburn makes people buy ice cream', 'It is a coincidence every year'], answer: 0,
    explain: 'A third factor (sunny weather) causes both. That is a confounder, the most common reason correlation is not causation.' },
  { id: 'th2-cause-02', topic: 'think-causation', type: 'fill', kind: 'concept', difficulty: 2, concept: 'causation',
    prompt: 'A third factor that causes two things to move together is called a ____ (variable).',
    answer: ['confounder', 'confounding', 'confounding variable', 'lurking'], explain: 'A confounder (or lurking variable) creates a correlation between two things that do not cause each other.' },
  { id: 'th2-cause-03', topic: 'think-causation', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'causation',
    prompt: 'Restaurants that discount most have the lowest sales on those days. A consultant says discounts hurt sales. What is the likely flaw?',
    options: ['Discounts are given because the days are already slow', 'Discounts always increase sales', 'The sales data is wrong', 'Discounts are too small to matter'], answer: 0,
    explain: 'That is reverse causation: slow days lead to discounts, not the other way round.' },
  { id: 'th2-cause-04', topic: 'think-causation', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'causation',
    prompt: 'What is the most convincing way to test whether a new checkout design increases orders?',
    options: ['Show the new and old design to random groups at the same time', 'Compare this month with last month', 'Ask customers if they like the new design', 'Launch it and watch the total'], answer: 0,
    explain: 'A randomised test (A/B test) keeps everything else equal, so a difference can be credited to the design.' },
  { id: 'th2-cause-05', topic: 'think-causation', type: 'tf', kind: 'concept', difficulty: 2, concept: 'causation',
    prompt: 'True or false: a strong correlation proves that one thing causes the other.',
    answer: false, explain: 'Correlation can come from coincidence, a confounder or reverse causation. It is a reason to investigate, not proof.' },
  { id: 'th2-cause-06', topic: 'think-causation', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'causation',
    prompt: 'Loyalty members spend 40% more than non-members. Marketing wants to credit the programme. What is the main doubt?',
    options: ['Big spenders were more likely to join in the first place', 'Members forget to use their cards', 'Non-members shop at night', 'The programme is too new'], answer: 0,
    explain: 'Self-selection: people who already spend a lot join loyalty schemes. Compare members\' spending before and after joining, against similar non-members.' },
  { id: 'th2-cause-07', topic: 'think-causation', type: 'mc', kind: 'concept', difficulty: 2, concept: 'causation',
    prompt: 'What does a control group give you?',
    options: ['What would have happened without the change', 'A bigger sample for the report', 'A way to avoid measuring the change', 'Proof that the change was popular'], answer: 0,
    explain: 'A similar group without the change shows the "normal" movement, so the difference can be attributed to the change.' },
  { id: 'th2-cause-08', topic: 'think-causation', type: 'number', kind: 'calculation', difficulty: 3, concept: 'causation',
    prompt: 'Stores with a promotion grew 12%; similar stores without it grew 9% in the same period. How many percentage points can be credited to the promotion?',
    answer: 3, verify: () => 12 - 9,
    explain: '12 − 9 = 3 points. The other 9 points would have happened anyway.' },
  { id: 'th2-cause-09', topic: 'think-causation', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'survivorship',
    prompt: 'A study of "habits of successful restaurants" only looks at restaurants still open after 10 years. What is the problem?',
    options: ['Closed restaurants may have had the same habits', 'Ten years is too long', 'Successful restaurants have no habits', 'The study should use fewer restaurants'], answer: 0,
    explain: 'Survivorship bias: without the failures, you cannot tell whether a habit is linked to success or just common.' },
  { id: 'th2-cause-10', topic: 'think-causation', type: 'order', kind: 'sequence', difficulty: 3, concept: 'causation',
    prompt: 'Order the steps for checking whether a campaign caused a sales rise.',
    options: ['Check the rise is real and not seasonal', 'Find a comparable group without the campaign', 'Compare the change in both groups', 'Look for other changes at the same time'], answer: [0, 1, 2, 3],
    explain: 'Confirm the rise, build a comparison, measure the difference, and rule out other explanations.' },
  { id: 'th2-cause-11', topic: 'think-causation', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'causation',
    prompt: 'Cities with more hospitals have more deaths. What is the best interpretation?',
    options: ['Bigger cities have both more hospitals and more deaths', 'Hospitals cause deaths', 'Deaths cause hospitals to open', 'The data is invented'], answer: 0,
    explain: 'Population size drives both. Compare rates per person, not totals.' },
  { id: 'th2-cause-12', topic: 'think-causation', type: 'tf', kind: 'concept', difficulty: 2, concept: 'causation',
    prompt: 'True or false: a before/after comparison with no control group can be misled by seasonality.',
    answer: true, explain: 'Anything that changes between the two periods (season, prices, competitors) is mixed into the result.' },
  { id: 'th2-cause-13', topic: 'think-causation', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'causation',
    prompt: 'Employees who took a training course got more promotions. HR wants to make the course mandatory "because it causes promotions". What should you point out?',
    options: ['Ambitious people may be the ones choosing the course', 'Promotions cause people to take courses', 'The course is too expensive', 'Promotions are always random'], answer: 0,
    explain: 'Self-selection again. Compare similar employees, or randomise who is offered the course first.' },
  { id: 'th2-cause-14', topic: 'think-causation', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'causation',
    prompt: 'A company cannot run an experiment. What is the next best evidence that a new store layout increased sales?',
    options: ['Compare changed stores with similar unchanged stores over the same period', 'Ask store managers whether sales feel higher than before', 'Compare the best store with the worst', 'Use the layout designer\'s estimate'], answer: 0,
    explain: 'A matched comparison (difference in differences) approximates a control group.' },
  { id: 'th2-cause-15', topic: 'think-causation', type: 'number', kind: 'calculation', difficulty: 3, concept: 'causation',
    prompt: 'Test group conversion rose from 2.0% to 2.6%. Control group rose from 2.0% to 2.2%. What is the estimated effect of the change, in percentage points?',
    answer: 0.4, tolerance: 0.001, verify: () => Math.round(((2.6 - 2.0) - (2.2 - 2.0)) * 10) / 10,
    explain: '(2.6 − 2.0) − (2.2 − 2.0) = 0.6 − 0.2 = 0.4 points. The control group\'s 0.2-point rise would have happened anyway.' },
  { id: 'th2-cause-16', topic: 'think-causation', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'causation',
    prompt: 'Sales rose the month a new manager started. Which statement is fair?',
    options: ['Sales rose after the manager started; the cause is not yet clear', 'The manager increased sales', 'The manager had no effect', 'Sales always rise with new managers'], answer: 0,
    explain: 'Timing alone does not prove cause. Describe what happened and investigate before crediting anyone.' },
  { id: 'th2-cause-17', topic: 'think-causation', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'causation',
    prompt: 'An analysis shows customers who receive more emails buy more. Emails are sent to customers who recently bought. What is wrong with concluding "emails drive purchases"?',
    options: ['Recent buyers are targeted, so buying leads to emails', 'Customers do not read emails', 'Emails are too cheap to matter', 'The correlation is too weak'], answer: 0,
    explain: 'The sending rule creates the correlation. Compare similar customers who did and did not get an email.' },
  { id: 'th2-cause-18', topic: 'think-causation', type: 'tf', kind: 'concept', difficulty: 3, concept: 'survivorship',
    prompt: 'True or false: analysing only current customers to learn why customers stay ignores those who already left.',
    answer: true, explain: 'The customers who left hold the answer to why people leave. Include them.' },
  { id: 'th2-cause-19', topic: 'think-causation', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'causation',
    prompt: 'Which phrase is the most accurate for an observational finding?',
    options: ['"is associated with"', '"causes"', '"proves"', '"guarantees"'], answer: 0,
    explain: 'Use "is associated with" or "is linked to" unless you have evidence of cause.' },
  { id: 'th2-cause-20', topic: 'think-causation', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'causation',
    prompt: 'The Airport restaurant has the highest waste rate and the fewest staff per cover. What should the analysis say?',
    options: ['The two may be linked; look at prep practices there', 'Low staffing definitely causes waste', 'Waste causes low staffing', 'The link is certainly a coincidence'], answer: 0,
    explain: 'A plausible link is worth investigating, but one site cannot prove a cause. Observe and test before concluding.' },
  { id: 'th2-cause-21', topic: 'think-causation', type: 'fill', kind: 'concept', difficulty: 2, concept: 'causation',
    prompt: 'When the effect actually causes what looks like the cause, it is called ____ causation.',
    answer: ['reverse', 'reversed'], explain: 'Reverse causation: for example, slow days cause discounts rather than discounts causing slow days.' },
  { id: 'th2-cause-22', topic: 'think-causation', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'causation',
    prompt: 'An NGO sees higher school attendance in villages with its programme. The programme chose villages with active local leaders. What is the risk?',
    options: ['Active leadership may explain higher attendance', 'The programme cannot work', 'Attendance data is always wrong', 'Villages should not be compared'], answer: 0,
    explain: 'The selection rule is a confounder. Compare with similar villages that also have active leaders.' },

  // ================================================================ think-interpret
  { id: 'th2-int-01', topic: 'think-interpret', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'seasonality',
    prompt: 'Toy sales fell 45% from December to January. What is the most sensible first reading?',
    options: ['A normal post-Christmas drop; compare with last January', 'A collapse in demand that needs urgent action', 'A pricing mistake made in the January sale', 'A data error in the January figures'], answer: 0,
    explain: 'Toys peak before Christmas. Year-on-year comparison removes the season.' },
  { id: 'th2-int-02', topic: 'think-interpret', type: 'mc', kind: 'concept', difficulty: 2, concept: 'sample-size',
    prompt: 'Why is a return rate based on 20 orders less reliable than one based on 2,000?',
    options: ['A few returns move the rate a lot', 'Small numbers are always wrong', 'Large numbers are always right', 'Rates cannot be calculated for 20'], answer: 0,
    explain: 'With 20 orders, each return moves the rate by 5 points. Chance plays a big part.' },
  { id: 'th2-int-03', topic: 'think-interpret', type: 'number', kind: 'calculation', difficulty: 2, concept: 'sample-size',
    prompt: 'A store had 20 orders last week. By how many percentage points does one extra return change the return rate?',
    answer: 5, verify: () => (1 / 20) * 100,
    explain: '1 ÷ 20 = 5 points. With 2,000 orders it would be 0.05 points.' },
  { id: 'th2-int-04', topic: 'think-interpret', type: 'tf', kind: 'concept', difficulty: 2, concept: 'interpretation',
    prompt: 'True or false: the worst-performing store one month tends to look better the next month, even if nothing changes.',
    answer: true, explain: 'That is regression to the mean: extreme results often include bad luck that does not repeat.' },
  { id: 'th2-int-05', topic: 'think-interpret', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'interpretation',
    prompt: 'The five worst stores got coaching and all improved the next quarter. Why is this not proof that coaching works?',
    options: ['The worst stores would likely improve anyway', 'Coaching never works', 'Five stores is too many', 'Quarters are too short'], answer: 0,
    explain: 'Selecting the worst performers guarantees some improvement from regression to the mean. Compare with similar stores that were not coached.' },
  { id: 'th2-int-06', topic: 'think-interpret', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'seasonality',
    prompt: 'A café compares this Saturday with last Tuesday and sees +70%. What is the fair comparison?',
    options: ['This Saturday with previous Saturdays', 'This Saturday with the monthly average', 'This Saturday with last December', 'This Saturday with the best day ever'], answer: 0,
    explain: 'Weekday patterns are strong in hospitality. Compare the same day of the week.' },
  { id: 'th2-int-07', topic: 'think-interpret', type: 'number', kind: 'calculation', difficulty: 2, concept: 'seasonality',
    prompt: 'January sales: $99,000 this year, $88,000 last year. What is the year-on-year change, to one decimal place?',
    answer: 12.5, tolerance: 0.05, verify: () => Math.round(((99000 - 88000) / 88000) * 1000) / 10,
    explain: '(99,000 − 88,000) ÷ 88,000 = 12.5% up on last January, even if January is below December.' },
  { id: 'th2-int-08', topic: 'think-interpret', type: 'mc', kind: 'concept', difficulty: 2, concept: 'seasonality',
    prompt: 'What is the main weakness of month-on-month comparisons?',
    options: ['They mix in seasonal patterns', 'They are always too slow', 'They cannot show growth', 'They need two years of data'], answer: 0,
    explain: 'Many businesses have predictable monthly patterns. Month-on-month changes include them.' },
  { id: 'th2-int-09', topic: 'think-interpret', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'interpretation',
    prompt: 'A dashboard shows March revenue down 8% on last March. March this year had 4 weekends; last March had 5. What should you add?',
    options: ['A note on the calendar difference, or a per-day comparison', 'Nothing, because 8% down is simply 8% down', 'A forecast for April to balance the message', 'A red colour on March to show the problem'], answer: 0,
    explain: 'Calendar effects can explain part of a change. Compare per trading day or like-for-like days.' },
  { id: 'th2-int-10', topic: 'think-interpret', type: 'tf', kind: 'concept', difficulty: 2, concept: 'sample-size',
    prompt: 'True or false: showing the count next to a percentage helps readers judge how reliable it is.',
    answer: true, explain: '"12% (3 of 25)" and "12% (300 of 2,500)" deserve different levels of trust.' },
  { id: 'th2-int-11', topic: 'think-interpret', type: 'number', kind: 'calculation', difficulty: 3, concept: 'interpretation',
    prompt: 'Weekly sales for 8 weeks: 100, 104, 98, 101, 97, 103, 99, 102 (thousands). This week is 105. By how much is it above the 8-week average (in thousands)?',
    answer: 4.5, tolerance: 0.01, verify: () => 105 - (100 + 104 + 98 + 101 + 97 + 103 + 99 + 102) / 8,
    explain: 'The eight weeks add up to 804, so the average is 100.5 and this week is 4.5 above it: just outside the usual 97 to 104 range, not yet a trend.' },
  { id: 'th2-int-12', topic: 'think-interpret', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'interpretation',
    prompt: 'Weekly sales normally move between 97k and 104k. This week is 105k. What is the best comment?',
    options: ['Slightly above the usual range; watch next week', 'A breakthrough week that proves the plan works', 'A clear new upward trend in sales', 'An obvious data error to be removed'], answer: 0,
    explain: 'One value just outside the normal range is not a trend. Wait for more weeks.' },
  { id: 'th2-int-13', topic: 'think-interpret', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'interpretation',
    prompt: 'A chart shows customer satisfaction falling from 4.6 to 4.2 after a survey tool change. What should you check first?',
    options: ['Whether the new tool asks the question differently', 'Whether staff became unfriendly', 'Whether prices went up', 'Whether customers got older'], answer: 0,
    explain: 'A change in wording, scale or who is surveyed can move scores on its own.' },
  { id: 'th2-int-14', topic: 'think-interpret', type: 'order', kind: 'sequence', difficulty: 3, concept: 'interpretation',
    prompt: 'Order the checks before reporting that a metric "changed".',
    options: ['Is the period complete and comparable?', 'Could season or calendar explain it?', 'Is the change bigger than normal variation?', 'What else changed at the same time?'], answer: [0, 1, 2, 3],
    explain: 'Comparable periods, seasonality, normal noise, then other explanations.' },
  { id: 'th2-int-15', topic: 'think-interpret', type: 'fill', kind: 'concept', difficulty: 2, concept: 'interpretation',
    prompt: 'The tendency of extreme results to be followed by less extreme ones is called regression to the ____.',
    answer: ['mean', 'average'], explain: 'Regression to the mean: an extreme month usually contains some luck that does not repeat, so the next one looks more ordinary.' },
  { id: 'th2-int-16', topic: 'think-interpret', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'sample-size',
    prompt: 'A new product got 5 reviews, all 5 stars. Marketing wants to call it "the best-rated product". What do you say?',
    options: ['Five reviews are too few to rank it against others', 'Agree: it has the highest average', 'Remove the reviews', 'Average it with other products'], answer: 0,
    explain: 'A small number of reviews produces extreme averages easily. Show the count or require a minimum.' },
  { id: 'th2-int-17', topic: 'think-interpret', type: 'tf', kind: 'concept', difficulty: 2, concept: 'seasonality',
    prompt: 'True or false: year-on-year comparisons remove the effect of seasons.',
    answer: true, explain: 'Comparing the same period each year compares like with like, season included.' },
  { id: 'th2-int-18', topic: 'think-interpret', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'interpretation',
    prompt: 'Online orders fell 30% in the week a competitor ran a big sale, then recovered. What is the best summary?',
    options: ['A temporary dip linked to the competitor\'s sale', 'A permanent loss of customers', 'A failure of our website', 'No change worth noting'], answer: 0,
    explain: 'The recovery suggests a short-term effect. Mention the likely cause, and keep watching.' },
  { id: 'th2-int-19', topic: 'think-interpret', type: 'number', kind: 'calculation', difficulty: 3, concept: 'seasonality',
    prompt: 'December revenue was $115,000 and January $99,000. What is the month-on-month change, to one decimal place?',
    answer: -13.9, tolerance: 0.05, verify: () => Math.round(((99000 - 115000) / 115000) * 1000) / 10,
    explain: '(99,000 − 115,000) ÷ 115,000 = −13.9%. On its own, this says nothing about whether January was good.' },
  { id: 'th2-int-20', topic: 'think-interpret', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'sample-size',
    prompt: 'Two sales reps: Ana closed 3 of 4 leads (75%), Ben 150 of 250 (60%). Who is the better closer?',
    options: ['Not clear yet: Ana\'s rate rests on only 4 leads', 'Ana, because her closing rate is higher', 'Ben, because he has closed far more deals', 'They are equal once the rates are rounded'], answer: 0,
    explain: 'Ana\'s rate could change a lot with a few more leads. Wait for more data before ranking.' },
  { id: 'th2-int-21', topic: 'think-interpret', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'interpretation',
    prompt: 'This quarter looks weak because the last week of the quarter has not been loaded yet. How should the dashboard show it?',
    options: ['Label the quarter as incomplete, or compare to date', 'Show it as it is, without any comment', 'Hide the quarter until next month', 'Fill the gap with last year\'s last week'], answer: 0,
    explain: 'Partial periods need a clear label or a like-for-like comparison.' },
  { id: 'th2-int-22', topic: 'think-interpret', type: 'tf', kind: 'concept', difficulty: 3, concept: 'interpretation',
    prompt: 'True or false: if a metric moves in the direction you hoped, you can skip checking whether the change is real.',
    answer: false, explain: 'Good news deserves the same checks as bad news. Confirmation bias is how errors survive.' },
  { id: 'th2-int-23', topic: 'think-interpret', type: 'mc', kind: 'concept', difficulty: 2, concept: 'seasonality',
    prompt: 'What does "like-for-like" mean when comparing periods?',
    options: ['Comparing the same things over equivalent periods', 'Comparing only liked products', 'Comparing two random weeks', 'Comparing only the best stores'], answer: 0,
    explain: 'Same stores, same days, same season: only the change you want to measure differs.' },
  { id: 'th2-int-24', topic: 'think-interpret', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'interpretation',
    prompt: 'Complaints doubled from 2 to 4 this month. What is the best way to report it?',
    options: ['"4 complaints (2 last month): too few to call a trend"', '"Complaints up 100%"', '"Customer service is failing"', '"No complaints worth mentioning"'], answer: 0,
    explain: 'With tiny counts, percentages exaggerate. Give the counts and a sensible comment.' },
  { id: 'th2-int-25', topic: 'think-interpret', type: 'fill', kind: 'concept', difficulty: 2, concept: 'seasonality',
    prompt: 'A regular pattern that repeats at the same time every year (like Christmas sales) is called ____.',
    answer: ['seasonality', 'seasonal pattern', 'a seasonal pattern'], explain: 'Seasonality: remove it with year-on-year comparisons or seasonal adjustment.' },

  // ================================================================ think-definitions
  { id: 'th2-def-01', topic: 'think-definitions', type: 'mc', kind: 'concept', difficulty: 2, concept: 'definitions',
    prompt: 'Why can two teams report different "revenue" from the same system?',
    options: ['They include different things, like refunds or cancellations', 'One team must have made an error', 'Revenue changes every time you look', 'Systems give random answers'], answer: 0,
    explain: 'Revenue can be gross or net, with or without cancellations, refunds, shipping or tax. Different definitions, different totals.' },
  { id: 'th2-def-02', topic: 'think-definitions', type: 'number', kind: 'calculation', difficulty: 2, concept: 'reconciliation',
    prompt: 'All orders: $893,000. Cancelled and pending orders: $31,000. Refunds: $66,000. What is revenue after cancellations and refunds?',
    answer: 796000, verify: () => 893000 - 31000 - 66000,
    explain: '893 − 31 − 66 = $796k. Each step of the bridge has a name, so both teams can agree.' },
  { id: 'th2-def-03', topic: 'think-definitions', type: 'order', kind: 'sequence', difficulty: 2, concept: 'reconciliation',
    prompt: 'Order the steps of a revenue bridge from the sales figure to the finance figure.',
    options: ['Revenue from all orders', 'Minus cancelled and pending orders', 'Minus refunds', 'Net revenue after refunds'], answer: [0, 1, 2, 3],
    explain: 'Start from the biggest figure and take away each difference with its name.' },
  { id: 'th2-def-04', topic: 'think-definitions', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'definitions',
    prompt: 'What prevents the same definition argument happening every month?',
    options: ['A shared data dictionary', 'A new dashboard', 'Removing one of the reports', 'Rounding all numbers'], answer: 0,
    explain: 'A written, agreed definition for each metric keeps everyone calculating the same thing.' },
  { id: 'th2-def-05', topic: 'think-definitions', type: 'tf', kind: 'concept', difficulty: 2, concept: 'definitions',
    prompt: 'True or false: "number of customers" has one correct definition.',
    answer: false, explain: 'Registered accounts, unique people and active buyers are all valid; each answers a different question.' },
  { id: 'th2-def-06', topic: 'think-definitions', type: 'number', kind: 'calculation', difficulty: 2, concept: 'denominator',
    prompt: 'An organisation had 131 voluntary leavers and an average headcount of 486 in the year. What is the voluntary turnover rate, to one decimal place?',
    answer: 27, tolerance: 0.05, verify: () => Math.round((131 / 486) * 1000) / 10,
    explain: '131 ÷ 486 = 27.0%. Using average headcount reflects the whole year, not one day.' },
  { id: 'th2-def-07', topic: 'think-definitions', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'definitions',
    prompt: 'Finance counts a sale on the payment date; sales counts it on the order date. December results differ. What is the best response?',
    options: ['Explain the timing difference and agree which date each report uses', 'Report whichever of the two figures is higher', 'Delete December orders from the finance report', 'Publish the average of the two December figures'], answer: 0,
    explain: 'Both are legitimate. Orders placed in December but paid in January explain the gap.' },
  { id: 'th2-def-08', topic: 'think-definitions', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'definitions',
    prompt: 'The CRM has 4,571 customer records, 4,500 unique emails and 2,055 people who bought this year. Which number should a report on "active customers" use?',
    options: ['2,055', '4,571', '4,500', 'The average of the three'], answer: 0,
    verify: () => '2,055',
    explain: 'Active customers are those who bought in the period. The other two count registrations and people.' },
  { id: 'th2-def-09', topic: 'think-definitions', type: 'fill', kind: 'concept', difficulty: 2, concept: 'definitions',
    prompt: 'A shared list of agreed metric definitions is called a data ____.',
    answer: ['dictionary', 'glossary', 'catalogue', 'catalog'], explain: 'A data dictionary (or business glossary).' },
  { id: 'th2-def-10', topic: 'think-definitions', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'definitions',
    prompt: 'Headcount in HR\'s report is 489; the payroll report says 512. Both are "correct". What is the most likely difference?',
    options: ['Payroll includes people paid this month who have left or not yet started', 'HR forgot to count some part-time employees', 'Payroll counts some employees twice by mistake', 'The reports use different currencies'], answer: 0,
    explain: 'Payroll often includes final payments to leavers and contractors. Compare the definitions before assuming an error.' },
  { id: 'th2-def-11', topic: 'think-definitions', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'definitions',
    prompt: 'Marketing reports "churn" as customers who cancelled; finance as customers with no purchase in 90 days. What should a joint report do?',
    options: ['Show both, clearly named, or agree one', 'Pick whichever is lower', 'Use neither', 'Add them together'], answer: 0,
    explain: 'Different definitions measure different things. Label them or agree one.' },
  { id: 'th2-def-12', topic: 'think-definitions', type: 'tf', kind: 'concept', difficulty: 2, concept: 'reconciliation',
    prompt: 'True or false: a reconciliation shows each difference between two figures with a name and an amount.',
    answer: true, explain: 'That is what makes it convincing: nobody needs to trust anybody.' },
  { id: 'th2-def-13', topic: 'think-definitions', type: 'number', kind: 'calculation', difficulty: 3, concept: 'reconciliation',
    prompt: 'Sales report: $500,000. Finance report: $462,000. Known differences: returns $25,000 and shipping income $9,000 (included only in sales). How much is still unexplained?',
    answer: 4000, verify: () => 500000 - 462000 - 25000 - 9000,
    explain: '500 − 462 = 38k difference; 25k + 9k = 34k explained; 4k still to find.' },
  { id: 'th2-def-14', topic: 'think-definitions', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'definitions',
    prompt: 'A region\'s revenue by store location is $122k; by where customers live it is $238k. Which one is "West revenue"?',
    options: ['Both: they answer different questions', 'Only the store figure', 'Only the customer figure', 'Neither'], answer: 0,
    explain: 'Store location measures what West shops sell; customer location measures what West customers buy, online too. Ask which question matters.' },
  { id: 'th2-def-15', topic: 'think-definitions', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'definitions',
    prompt: 'A board slide says "customers up 15%". Which follow-up question matters most?',
    options: ['Which customers: registered, active or paying?', 'Which colour is the chart?', 'Who designed the slide?', 'How many slides are there?'], answer: 0,
    explain: 'The definition decides whether 15% means real growth or just more sign-ups.' },
  { id: 'th2-def-16', topic: 'think-definitions', type: 'tf', kind: 'concept', difficulty: 2, concept: 'denominator',
    prompt: 'True or false: a turnover rate based on headcount on one day can differ from one based on average headcount.',
    answer: true, explain: 'In a growing or shrinking company the two denominators differ, and so do the rates.' },
  { id: 'th2-def-17', topic: 'think-definitions', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'reconciliation',
    prompt: 'Your total of 2025 refunds differs from customer service\'s total. You counted refunds on 2025 orders; they counted refunds issued in 2025. What is the fix?',
    options: ['Agree which date defines the period, then recalculate', 'Use the larger total', 'Delete refunds from December', 'Round both to the nearest thousand'], answer: 0,
    explain: 'Refunds on 2025 orders and refunds issued in 2025 overlap but are not the same. Pick one and label it.' },
  { id: 'th2-def-18', topic: 'think-definitions', type: 'mc', kind: 'concept', difficulty: 2, concept: 'definitions',
    prompt: 'What is the main purpose of writing a definition next to a metric on a dashboard?',
    options: ['So readers know exactly what is counted', 'To make the dashboard longer', 'To show the analyst\'s name', 'To hide the calculation'], answer: 0,
    explain: 'Visible definitions stop misreadings and repeated debates.' },
  { id: 'th2-def-19', topic: 'think-definitions', type: 'number', kind: 'calculation', difficulty: 2, concept: 'definitions',
    prompt: '4,571 customer records contain 71 extra rows from people registered twice. How many unique people are there?',
    answer: 4500, verify: () => 4571 - 71,
    explain: '4,571 − 71 = 4,500 people. Counting rows instead of people overstates the customer base.' },
  { id: 'th2-def-20', topic: 'think-definitions', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'definitions',
    prompt: 'Two restaurants report "covers". One counts guests, the other counts tables. What should happen before comparing them?',
    options: ['Agree one definition and recalculate one site', 'Compare them as they are', 'Divide one by two', 'Use sales instead and ignore covers'], answer: 0,
    explain: 'Guests and tables are different units. Agree on guests (the usual meaning) and recount.' },
  { id: 'th2-def-21', topic: 'think-definitions', type: 'fill', kind: 'concept', difficulty: 2, concept: 'reconciliation',
    prompt: 'A step-by-step explanation of how one total becomes another is often called a ____ (for example a revenue ____).',
    answer: ['bridge', 'walk', 'waterfall', 'reconciliation'], explain: 'A bridge (or walk) lists each difference between two totals.' },
  { id: 'th2-def-22', topic: 'think-definitions', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'definitions',
    prompt: 'Gross margin is 47% in one report and 38% in another. The second deducts shipping and card fees. What is going on?',
    options: ['Different cost definitions: both can be right', 'One report is fraudulent', 'Margins cannot be compared', 'The first report is out of date'], answer: 0,
    explain: 'Which costs are deducted changes margin. Name them in each report.' },
  { id: 'th2-def-23', topic: 'think-definitions', type: 'tf', kind: 'concept', difficulty: 3, concept: 'definitions',
    prompt: 'True or false: when two reports disagree, the right move is to decide which analyst is more experienced.',
    answer: false, explain: 'Compare definitions and data, not people. A bridge settles it objectively.' },
  { id: 'th2-def-24', topic: 'think-definitions', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'definitions',
    prompt: 'An NGO reports "people helped". One programme counts households, another individuals. The trustees want one total. What do you do?',
    options: ['Convert to one unit or report them separately, clearly labelled', 'Add them up as they are', 'Report only the bigger of the two programmes', 'Double the household figure'], answer: 0,
    explain: 'Adding households and individuals mixes units. Convert with a known household size (and say so), or keep them separate.' },
  { id: 'th2-def-25', topic: 'think-definitions', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'definitions',
    prompt: 'This year\'s "active customer" count jumped because the definition changed from 90 to 365 days. What should the report do?',
    options: ['Restate last year with the new definition', 'Report the jump as growth', 'Keep the old definition for last year only', 'Remove the metric'], answer: 0,
    explain: 'A changed definition makes periods incomparable. Recalculate the history with the new rule.' },
];
