// Excel quiz bank, part E: PivotTables (Intermediate), analysis and dashboards (Advanced).
const SALES = [
  ['Date', 'Region', 'Channel', 'Category', 'Revenue'],
  ['2026-01-08', 'West', 'Online', 'Tents', 420],
  ['2026-01-19', 'East', 'Store', 'Footwear', 180],
  ['2026-02-03', 'West', 'Store', 'Tents', 950],
  ['2026-02-14', 'North', 'Online', 'Cooking', 75],
  ['2026-02-27', 'West', 'Online', 'Footwear', 610],
  ['2026-03-05', 'South', 'Store', 'Tents', 300],
  ['2026-03-12', 'West', 'Online', 'Cooking', 1200],
  ['2026-03-22', 'North', 'Store', 'Footwear', 520],
  ['2026-04-02', 'West', 'Online', 'Tents', 88],
  ['2026-04-15', 'East', 'Online', 'Cooking', 450],
  ['2026-04-28', 'West', 'Store', 'Footwear', 230],
  ['2026-05-06', 'South', 'Online', 'Tents', 640],
];

export const XL_QUIZ_E = [
  // ================================================================ xl-pivots
  { id: 'xl2-pvt-01', topic: 'xl-pivots', type: 'order', kind: 'sequence', difficulty: 2, concept: 'pivot',
    prompt: 'Order the steps to build a revenue-by-region PivotTable.',
    options: ['Click inside the data Table', 'Insert → PivotTable', 'Drag Region into Rows', 'Drag Revenue into Values'], answer: [0, 1, 2, 3],
    explain: 'Start from a Table so the pivot can grow with the data; Rows gives one line per region, Values does the adding up.' },
  { id: 'xl2-pvt-02', topic: 'xl-pivots', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pivot',
    prompt: 'The pivot area that gives each distinct value its own line is called ____.',
    answer: ['rows', 'row labels', 'the rows area'], explain: 'Rows lists values down the side, Columns across the top, and Values holds the numbers being summarised.' },
  { id: 'xl2-pvt-03', topic: 'xl-pivots', type: 'fill', kind: 'concept', difficulty: 2, concept: 'pivot',
    prompt: 'To show dates in a pivot as months or quarters, right-click a date and choose ____.',
    answer: ['group', 'grouping'], explain: 'Group → Months (and Years) turns daily dates into a monthly report without touching the source.' },
  { id: 'xl2-pvt-04', topic: 'xl-pivots', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pivot',
    prompt: 'True or false: the same field can go into Values twice, for example once as Sum and once as % of Grand Total.',
    answer: true, explain: 'Adding Revenue twice and changing how the second one is shown gives amount and share side by side.' },
  { id: 'xl2-pvt-05', topic: 'xl-pivots', type: 'tf', kind: 'concept', difficulty: 4, concept: 'pivot',
    prompt: 'True or false: a pivot calculated field such as Profit ÷ Revenue adds up profit and revenue first, then divides.',
    answer: true, explain: 'That is why a calculated field gives a correct overall margin, while averaging row-level margins does not.' },
  { id: 'xl2-pvt-06', topic: 'xl-pivots', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pivot',
    prompt: 'True or false: grouping dates by month in a pivot changes the dates in the source data.',
    answer: false, explain: 'Grouping only changes how the pivot displays the dates. The source keeps every daily date.' },
  { id: 'xl2-pvt-07', topic: 'xl-pivots', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pivot',
    prompt: 'A pivot shows West revenue of 12,000 and a grand total of 48,000. What does "Show Values As → % of Grand Total" display for West?',
    answer: 25, tolerance: 0.01, verify: () => (12000 / 48000) * 100,
    explain: '12,000 ÷ 48,000 = 25%. The shares of all regions add up to 100%.' },
  { id: 'xl2-pvt-08', topic: 'xl-pivots', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pivot',
    prompt: 'For North, a pivot shows Count of Order ID = 1,240 and Sum of Revenue = 186,000. What is North\'s average order value?',
    answer: 150, verify: () => 186000 / 1240,
    explain: '186,000 ÷ 1,240 = 150. Building the average from the two totals is safer than averaging averages.' },
  { id: 'xl2-pvt-09', topic: 'xl-pivots', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pivot',
    prompt: 'A pivot has Region in Rows and Channel in Columns. West shows Online 8,400 and Store 3,600. What does "% of Row Total" show for West Online?',
    answer: 70, tolerance: 0.01, verify: () => (8400 / (8400 + 3600)) * 100,
    explain: '8,400 ÷ 12,000 = 70%: each row adds up to 100%, which shows each region\'s channel mix.' },
  { id: 'xl2-pvt-10', topic: 'xl-pivots', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pivot',
    prompt: 'Monthly revenue is 10,000 in January, 12,500 in February and 9,000 in March. What does "Running Total In → Month" show for March?',
    answer: 31500, verify: () => 10000 + 12500 + 9000,
    explain: 'A running total adds each month to the ones before: 10,000 + 12,500 + 9,000 = 31,500.' },
  { id: 'xl2-pvt-11', topic: 'xl-pivots', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pivot',
    prompt: 'February revenue is 12,500 and January 10,000. What does "% Difference From → (previous)" show for February?',
    answer: 25, tolerance: 0.01, verify: () => (12500 / 10000 - 1) * 100,
    explain: '(12,500 − 10,000) ÷ 10,000 = 25%. January itself shows blank, because it has no previous month.' },
  { id: 'xl2-pvt-12', topic: 'xl-pivots', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'pivot',
    prompt: 'A pivot shows revenue by Category and Channel. To check its **Footwear / Store** cell, write a formula in **H2** that calculates the same number from the data.',
    grid: { rows: SALES }, target: 'H2', answer: '=SUMIFS(E2:E13,D2:D13,"Footwear",C2:C13,"Store")',
    explain: 'A quick SUMIFS check proves the pivot reads the data you think it reads: Footwear in stores is 930.' },
  { id: 'xl2-pvt-13', topic: 'xl-pivots', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'pivot',
    prompt: 'Check a "% of Row Total" pivot: in **H2**, calculate the **Online share of West revenue** (West Online revenue ÷ all West revenue).',
    grid: { rows: SALES }, target: 'H2', answer: '=SUMIFS(E2:E13,B2:B13,"West",C2:C13,"Online")/SUMIFS(E2:E13,B2:B13,"West")',
    explain: 'West Online is 2,318 of West\'s 3,498, a share of about 0.66, which is what the pivot should show as 66%.' },
  { id: 'xl2-pvt-14', topic: 'xl-pivots', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'pivot',
    prompt: 'A pivot shows "Count of Date" for Tents. In **H2**, count the Tents orders with a formula to check it.',
    grid: { rows: SALES }, target: 'H2', answer: '=COUNTIF(D2:D13,"Tents")',
    explain: 'Count of any field counts rows, so it equals the number of Tents orders: 5.' },
  { id: 'xl2-pvt-15', topic: 'xl-pivots', type: 'order', kind: 'sequence', difficulty: 3, concept: 'pivot',
    prompt: 'Order the steps to show monthly revenue with a running total.',
    options: ['Put Date in Rows', 'Group the dates by Months and Years', 'Add Revenue to Values twice', 'Show the second one as Running Total In → Date'], answer: [0, 1, 2, 3],
    explain: 'Group first so the running total builds month by month; the first Values field keeps the monthly amount beside it.' },
  { id: 'xl2-pvt-16', topic: 'xl-pivots', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'pivot',
    prompt: 'A pivot has a row called "(blank)" with revenue of 3,200. What does it mean?',
    options: ['Rows with an empty Region add up to 3,200', 'The pivot has an error of 3,200', '3,200 of revenue was deleted', 'The pivot needs refreshing'], answer: 0,
    explain: 'Blank regions still carry revenue. Find and fix those rows at the source, or the regional figures stay incomplete.' },
  { id: 'xl2-pvt-17', topic: 'xl-pivots', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'pivot',
    prompt: 'One "Jan" row in a pivot shows January 2025 and January 2026 added together. What went wrong?',
    options: ['The dates were grouped by Months only; add Years', 'The source has duplicate rows', 'January is spelled two ways', 'The pivot is filtered to one year'], answer: 0,
    explain: 'Grouping by Months alone merges the same month across years. Group by Years and Months together.' },
  { id: 'xl2-pvt-18', topic: 'xl-pivots', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'pivot',
    prompt: 'Managers want to pick a date range for a pivot by dragging along a bar. What do you add?',
    options: ['A Timeline', 'A calculated field', 'A second PivotTable', 'A Report Filter on Region'], answer: 0,
    explain: 'A Timeline (PivotTable Analyze → Insert Timeline) filters by days, months, quarters or years with a slider.' },
  { id: 'xl2-pvt-19', topic: 'xl-pivots', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'pivot',
    prompt: 'A manager asks for the top 5 products by revenue, straight from the pivot. How?',
    options: ['Value Filters → Top 10, set to 5 by Sum of Revenue', 'Sort the source data and delete the rest', 'Filter the product names alphabetically', 'Copy the pivot and hide rows by hand'], answer: 0,
    explain: 'A Value Filter keeps the top 5 even after a refresh changes which products they are.' },
  { id: 'xl2-pvt-20', topic: 'xl-pivots', type: 'mc', kind: 'concept', difficulty: 3, concept: 'pivot',
    prompt: 'What does GETPIVOTDATA do?',
    options: ['Returns a pivot value by field names, not cell position', 'Refreshes every pivot in the workbook', 'Copies the pivot as plain values', 'Builds a new PivotTable from a formula'], answer: 0,
    explain: 'Because it names the fields and items, the formula still finds the right number when the pivot layout shifts.' },
  { id: 'xl2-pvt-21', topic: 'xl-pivots', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'cleaning',
    prompt: 'A pivot shows two separate rows, "West" and "West ". Why?',
    options: ['One spelling has a trailing space in the source', 'The pivot needs a second refresh', 'Pivots always split long regions', 'The Region field is in Columns'], answer: 0,
    explain: 'To a pivot, "West " is a different value. TRIM the source (or fix it in Power Query) and refresh.' },
  { id: 'xl2-pvt-22', topic: 'xl-pivots', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'pivot',
    prompt: 'A pivot\'s "Count of Customer ID" totals 1,200, but there are only 390 customers. What explains it?',
    options: ['Count counts rows (orders), not distinct customers', 'Some customers were counted in error', 'The pivot is missing a filter', 'Customer IDs are stored as text'], answer: 0,
    explain: 'Each order row is counted. For distinct customers, add the data to the Data Model and use Distinct Count.' },
  { id: 'xl2-pvt-23', topic: 'xl-pivots', type: 'mc', kind: 'concept', difficulty: 2, concept: 'pivot',
    prompt: 'Why is a new worksheet usually the best place for a PivotTable?',
    options: ['It can grow without overwriting other cells', 'Pivots only calculate on new sheets', 'It makes the file smaller', 'Slicers need an empty sheet'], answer: 0,
    explain: 'A pivot changes size when fields or data change, and Excel will not let it overlap other content.' },
  { id: 'xl2-pvt-24', topic: 'xl-pivots', type: 'number', kind: 'calculation', difficulty: 2, concept: 'pivot',
    prompt: 'With "% of Column Total", Tents show 38%, Footwear 29% and Cooking 21%. Accessories is the only other category. What percentage does it show?',
    answer: 12, verify: () => 100 - 38 - 29 - 21,
    explain: 'The shares of a column add up to 100%: 100 − 38 − 29 − 21 = 12%.' },
  { id: 'xl2-pvt-25', topic: 'xl-pivots', type: 'tf', kind: 'concept', difficulty: 2, concept: 'pivot',
    prompt: 'True or false: Data → Refresh All updates every PivotTable and query in the workbook.',
    answer: true, explain: 'Refresh All is the one button to press after new data arrives; a single pivot refresh updates only that pivot and those sharing its cache.' },

  // ================================================================ xl-analysis
  { id: 'xl2-ana-01', topic: 'xl-analysis', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'scenario',
    prompt: 'In **D2**, calculate the **year-on-year growth** (this year ÷ last year − 1). Copy down to D5.',
    grid: { rows: [['Region', 'This year', 'Last year', 'Growth'], ['North', 131000, 120000, null], ['South', 98000, 104000, null], ['East', 76500, 68000, null], ['West', 122000, 122000, null]] },
    target: 'D2', fillTo: 'D5', answer: '=B2/C2-1',
    explain: 'North grew by about 9.2% and South fell by nearly 6%; format the column as a percentage. West at exactly 0 still deserves a comment.' },
  { id: 'xl2-ana-02', topic: 'xl-analysis', type: 'formula', kind: 'formula-writing', difficulty: 4, concept: 'scenario',
    prompt: 'In **F2**, calculate the **price effect**: (new price − old price) × new units. Copy down to F4.',
    grid: { rows: [['Product', 'Old price', 'New price', 'Old units', 'New units', 'Price effect'], ['Tent', 180, 189, 400, 380, null], ['Boots', 125, 129, 610, 640, null], ['Stove', 85, 89, 300, 270, null]] },
    target: 'F2', fillTo: 'F4', answer: '=(C2-B2)*E2',
    explain: 'The price rise on the Tent brought in 9 × 380 = 3,420. The rest of the revenue change comes from volume: (new units − old units) × old price.' },
  { id: 'xl2-ana-03', topic: 'xl-analysis', type: 'number', kind: 'calculation', difficulty: 3, concept: 'pct-points',
    prompt: 'Revenue was 480,000 last year and 516,000 this year. What is the growth in %?',
    answer: 7.5, tolerance: 0.01, verify: () => (516000 / 480000 - 1) * 100,
    explain: '516,000 ÷ 480,000 − 1 = 0.075, a 7.5% increase.' },
  { id: 'xl2-ana-04', topic: 'xl-analysis', type: 'number', kind: 'calculation', difficulty: 4, concept: 'pct-points',
    prompt: 'Revenue grew 7.5% while units fell 2%. By how many % did revenue per unit rise? (two decimals)',
    answer: 9.69, tolerance: 0.02, verify: () => Math.round((1.075 / 0.98 - 1) * 10000) / 100,
    explain: 'Revenue per unit = revenue ÷ units, so it changed by 1.075 ÷ 0.98 − 1 = 9.69%, not 7.5 + 2 = 9.5%: growth rates multiply, they do not add.' },
  { id: 'xl2-ana-05', topic: 'xl-analysis', type: 'order', kind: 'sequence', difficulty: 3, concept: 'business-questions',
    prompt: 'Order the steps of explaining a change in sales.',
    options: ['Agree the question and the comparison period', 'Check the data is complete and comparable', 'Split the change into drivers (price, volume, mix)', 'Write the finding with its caveats'], answer: [0, 1, 2, 3],
    explain: 'A clear question, then trustworthy data, then the drivers, then a finding that says how sure you are.' },
  { id: 'xl2-ana-06', topic: 'xl-analysis', type: 'tf', kind: 'concept', difficulty: 3, concept: 'seasonality',
    prompt: 'True or false: a three-month moving average smooths out one-off spikes, but it also reacts late to a real change.',
    answer: true, explain: 'Averaging calms noise at the cost of delay. Show the raw monthly line too, so a real turn is not hidden.' },

  // ================================================================ xl-dashboards
  { id: 'xl2-dsh-01', topic: 'xl-dashboards', type: 'order', kind: 'sequence', difficulty: 3, concept: 'dashboard',
    prompt: 'Order the steps of building an Excel dashboard.',
    options: ['Agree the questions and KPIs with the users', 'Prepare the data in a Table or a query', 'Build the calculations on their own sheet', 'Lay out the KPI tiles and charts'], answer: [0, 1, 2, 3],
    explain: 'Purpose first, then reliable data, then calculations, and the layout last: the layout is the easy part once the rest is right.' },
  { id: 'xl2-dsh-02', topic: 'xl-dashboards', type: 'number', kind: 'calculation', difficulty: 3, concept: 'kpi',
    prompt: 'A KPI tile shows revenue of 482,000 against a target of 500,000. What percentage of target is that? (one decimal)',
    answer: 96.4, tolerance: 0.05, verify: () => Math.round((482000 / 500000) * 1000) / 10,
    explain: '482,000 ÷ 500,000 = 96.4%. Showing "96.4% of target (−18k)" tells the reader how far off, in both terms.' },
  { id: 'xl2-dsh-03', topic: 'xl-dashboards', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'dashboard',
    prompt: 'In **D2**, calculate each store\'s **variance to target** as a percentage: (actual − target) ÷ target. Copy down to D4.',
    grid: { rows: [['Store', 'Actual', 'Target', 'Variance %'], ['Northgate', 20810, 20000, null], ['Riverside', 17044, 17500, null], ['Canyon', 7826, 8500, null]] },
    target: 'D2', fillTo: 'D4', answer: '=(B2-C2)/C2',
    explain: 'Northgate is about 4% above target and Canyon about 8% below. A variance % lets stores of different sizes be compared fairly.' },
  { id: 'xl2-dsh-04', topic: 'xl-dashboards', type: 'tf', kind: 'debugging', difficulty: 3, concept: 'dashboard',
    prompt: 'True or false: a chart built on the fixed range A1:B13 picks up a new month added in row 14.',
    answer: false, explain: 'A fixed range stays fixed. Build charts on a Table (or a pivot) so new rows appear automatically.' },
  { id: 'xl2-dsh-05', topic: 'xl-dashboards', type: 'fill', kind: 'concept', difficulty: 3, concept: 'dashboard',
    prompt: 'A tiny chart inside a single cell that shows a trend next to a number is called a ____.',
    answer: ['sparkline', 'sparklines'], explain: 'Insert → Sparklines: a line per row that shows the shape of the last 12 months beside the KPI.' },
  { id: 'xl2-dsh-06', topic: 'xl-dashboards', type: 'tf', kind: 'interpretation', difficulty: 3, concept: 'chart-honesty',
    prompt: 'True or false: a traffic-light icon set with no stated thresholds can mislead readers.',
    answer: true, explain: 'Green, amber and red mean nothing until the reader knows the cut-offs. State them next to the tiles.' },
];
