// Excel quiz bank, part A: formulas and references, Tables, IF logic (Beginner).
const PRICES = [['Product', 'Price', 'Cost', 'Margin %'], ['Tent', 120, 78, null], ['Boots', 80, 52, null], ['Stove', 45, 27, null], ['Lamp', 22, 15.4, null], ['Jacket', 150, 84, null]];
const ORDERS = [
  ['Order', 'Region', 'Channel', 'Amount', 'Flag'],
  ['A-101', 'West', 'Online', 420, null],
  ['A-102', 'East', 'Store', 180, null],
  ['A-103', 'West', 'Store', 950, null],
  ['A-104', 'North', 'Online', 75, null],
  ['A-105', 'South', 'Online', 610, null],
  ['A-106', 'South', 'Store', 300, null],
  ['A-107', 'East', 'Online', 1200, null],
  ['A-108', 'North', 'Store', 520, null],
];

export const XL_QUIZ_A = [
  // ================================================================ xl-basics
  { id: 'xl2-bas-01', topic: 'xl-basics', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'cell-refs',
    prompt: 'In **D2**, calculate the **margin %**: (Price − Cost) ÷ Price. Copy it down to D6.',
    grid: { rows: PRICES }, target: 'D2', fillTo: 'D6', answer: '=(B2-C2)/B2',
    explain: 'The brackets make Excel subtract first: =(B2-C2)/B2 gives 0.35 for the Tent. Without them, =B2-C2/B2 divides first and returns nonsense.' },
  { id: 'xl2-bas-02', topic: 'xl-basics', type: 'formula', kind: 'formula-writing', difficulty: 1, concept: 'count-types',
    prompt: 'In **B9**, count how many orders have an amount (some cells are empty).',
    grid: { rows: [['Order', 'Amount'], ['A-1', 420], ['A-2', null], ['A-3', 950], ['A-4', 75], ['A-5', null], ['A-6', 300], ['A-7', 610], ['Orders with an amount', null]] },
    target: 'B9', answer: '=COUNT(B2:B8)',
    explain: 'COUNT counts cells that hold numbers, so the two empty cells are skipped: 5 orders. COUNTA would also count any text.' },
  { id: 'xl2-bas-03', topic: 'xl-basics', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'cell-refs',
    prompt: 'Every store has the same target, in **B8**. In **C2**, show each store\'s sales minus that target. Copy down to C6.',
    grid: { rows: [['Store', 'Sales', 'vs target'], ['Harbour St', 12500, null], ['Mill Lane', 8300, null], ['Station Rd', 15100, null], ['Old Town', 6400, null], ['Riverside', 9700, null], [null, null, null], ['Target', 10000, null]] },
    target: 'C2', fillTo: 'C6', answer: '=B2-$B$8',
    explain: 'B2 moves with each row, and $B$8 stays on the target. Without the $, row 3 would subtract B9, an empty cell.' },
  { id: 'xl2-bas-04', topic: 'xl-basics', type: 'formula', kind: 'formula-writing', difficulty: 1, concept: 'basic-agg',
    prompt: 'In **B9**, return the **largest** order amount.',
    grid: { rows: [['Order', 'Amount'], ['A-1', 420], ['A-2', 180], ['A-3', 950], ['A-4', 75], ['A-5', 610], ['A-6', 300], [null, null], ['Largest', null]] },
    target: 'B9', answer: '=MAX(B2:B7)',
    explain: 'MAX returns the largest number in the range: 950. MIN, AVERAGE and SUM work the same way.' },
  { id: 'xl2-bas-05', topic: 'xl-basics', type: 'number', kind: 'calculation', difficulty: 1, concept: 'cell-refs',
    prompt: 'B2 (price) is 80 and C2 (cost) is 52. What does =(B2-C2)/B2 return? (type a decimal)',
    answer: 0.35, tolerance: 0.0001, verify: () => (80 - 52) / 80,
    explain: '(80 − 52) ÷ 80 = 28 ÷ 80 = 0.35. Format the cell as a percentage to show 35%.' },
  { id: 'xl2-bas-06', topic: 'xl-basics', type: 'number', kind: 'calculation', difficulty: 2, concept: 'basic-agg',
    prompt: 'B2:B6 hold 10, the text "20", 30, an empty cell and 40. What does =SUM(B2:B6) return?',
    answer: 80, verify: () => 10 + 30 + 40,
    explain: 'SUM skips text, even text that looks like a number, and empty cells: 10 + 30 + 40 = 80. A number stored as text silently drops out of totals.' },
  { id: 'xl2-bas-07', topic: 'xl-basics', type: 'tf', kind: 'debugging', difficulty: 1, concept: 'cell-refs',
    prompt: 'True or false: a cell showing ##### means its formula is wrong.',
    answer: false, explain: 'Usually the column is simply too narrow to show the number or date. Widen the column before looking for an error.' },
  { id: 'xl2-bas-08', topic: 'xl-basics', type: 'tf', kind: 'concept', difficulty: 1, concept: 'cell-refs',
    prompt: 'True or false: Excel stores 25% as the number 0.25.',
    answer: true, explain: 'Percentage is only a display format. That is why =B2*25% and =B2*0.25 give the same result.' },
  { id: 'xl2-bas-09', topic: 'xl-basics', type: 'fill', kind: 'debugging', difficulty: 1, concept: 'basic-agg',
    prompt: 'When a formula divides by zero or by an empty cell, Excel shows the error #____!',
    answer: ['DIV/0', 'div/0'], explain: '#DIV/0! means the divisor is zero or empty. Check the data first, then decide how the report should show it.' },
  { id: 'xl2-bas-10', topic: 'xl-basics', type: 'order', kind: 'sequence', difficulty: 2, concept: 'cell-refs',
    prompt: 'Order the steps to build a calculated column that copies correctly.',
    options: ['Write the formula for the first row', 'Check that row\'s result by hand', 'Lock fixed cells such as rates with $', 'Copy down and spot-check a row further down'], answer: [0, 1, 2, 3],
    explain: 'Prove one row is right, make sure fixed inputs will not move, then copy and check again somewhere else.' },
  { id: 'xl2-bas-11', topic: 'xl-basics', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'cell-refs',
    prompt: 'A formula that worked yesterday now shows #REF!. What most likely happened?',
    options: ['A cell or column it used was deleted', 'The workbook was saved as .xlsx', 'A number in the range is negative', 'Someone changed the font'], answer: 0,
    explain: '#REF! means a reference no longer exists. Undo the deletion if you can, or rebuild the formula.' },
  { id: 'xl2-bas-12', topic: 'xl-basics', type: 'mc', kind: 'interpretation', difficulty: 1, concept: 'cell-refs',
    prompt: 'D2 shows 0.35 and your manager wants to see 35%. What do you change?',
    options: ['The number format of D2 to Percentage', 'The formula, by multiplying it by 100', 'The formula, by adding "%" at the end', 'Nothing: 0.35 is already a percentage'], answer: 0,
    explain: 'Change the format, not the value. Multiplying by 100 would break every calculation that uses D2.' },

  // ================================================================ xl-tables
  { id: 'xl2-tab-01', topic: 'xl-tables', type: 'tf', kind: 'concept', difficulty: 1, concept: 'tables',
    prompt: 'True or false: a formula typed in one row of an Excel Table fills the whole column automatically.',
    answer: true, explain: 'Tables use calculated columns: one formula for every row, including rows added later.' },
  { id: 'xl2-tab-02', topic: 'xl-tables', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'structured-refs',
    prompt: 'In a Table named Orders, what does Orders[@Revenue] refer to?',
    options: ['The Revenue value in the same row', 'The whole Revenue column', 'The Revenue total at the bottom', 'The Revenue column header'], answer: 0,
    explain: '@ means "this row". Orders[Revenue] without the @ is the whole column.' },
  { id: 'xl2-tab-03', topic: 'xl-tables', type: 'fill', kind: 'concept', difficulty: 2, concept: 'structured-refs',
    prompt: 'In Orders[@Revenue], the ____ sign means "the value in this row".',
    answer: ['@', 'at'], explain: 'The @ sign limits the reference to the current row, so row-by-row formulas read naturally.' },
  { id: 'xl2-tab-04', topic: 'xl-tables', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'sort-filter',
    prompt: 'After sorting, revenues sit next to the wrong customers. What happened?',
    options: ['Only one column was sorted, so the rows were split apart', 'The sort was largest to smallest', 'The Table has too many rows to sort', 'Excel cannot sort currency values'], answer: 0,
    explain: 'Sorting a single column moves its values without their rows. Undo, then sort the whole Table (a Table always sorts whole rows).' },
  { id: 'xl2-tab-05', topic: 'xl-tables', type: 'order', kind: 'sequence', difficulty: 1, concept: 'sort-filter',
    prompt: 'Order the steps of a sort on several columns.',
    options: ['Click any cell in the data', 'Open Data → Sort', 'Add a level for each column, in priority order', 'Confirm the data has headers and press OK'], answer: [0, 1, 2, 3],
    explain: 'The first level sorts first; later levels only order rows that tie on the earlier ones.' },
  { id: 'xl2-tab-06', topic: 'xl-tables', type: 'number', kind: 'calculation', difficulty: 1, concept: 'sort-filter',
    prompt: 'The status bar says "37 of 1200 records found". How many rows are hidden by the filter?',
    answer: 1163, verify: () => 1200 - 37,
    explain: '1,200 − 37 = 1,163 rows are hidden, not deleted. Clearing the filter brings them all back.' },
  { id: 'xl2-tab-07', topic: 'xl-tables', type: 'tf', kind: 'concept', difficulty: 1, concept: 'sort-filter',
    prompt: 'True or false: filters on two columns show the rows that match either filter.',
    answer: false, explain: 'Filters combine with AND: a row must pass every column\'s filter to stay visible.' },
  { id: 'xl2-tab-08', topic: 'xl-tables', type: 'mc', kind: 'tool-selection', difficulty: 1, concept: 'sort-filter',
    prompt: 'You need the orders from 1 April to 30 June only. Which filter do you use on the date column?',
    options: ['Date Filters → Between', 'Text Filters → Contains', 'Sort Oldest to Newest', 'Number Filters → Top 10'], answer: 0,
    explain: 'Between takes a start and an end date. Other date filters, such as Last Quarter, depend on today\'s date.' },
  { id: 'xl2-tab-09', topic: 'xl-tables', type: 'mc', kind: 'tool-selection', difficulty: 1, concept: 'sort-filter',
    prompt: 'You want to see every product whose name includes "lamp" anywhere. Which filter?',
    options: ['Text Filters → Contains', 'Text Filters → Begins With', 'Text Filters → Equals', 'Number Filters → Greater Than'], answer: 0,
    explain: 'Contains finds "Desk Lamp", "Lamp Shade" and "Floor lamp" alike; the filter ignores capitals.' },
  { id: 'xl2-tab-10', topic: 'xl-tables', type: 'number', kind: 'calculation', difficulty: 2, concept: 'sort-filter',
    prompt: 'With a filter on, SUBTOTAL(9, Revenue) shows 12,400, while the whole column adds up to 58,900. How much revenue is in the hidden rows?',
    answer: 46500, verify: () => 58900 - 12400,
    explain: '58,900 − 12,400 = 46,500. SUBTOTAL and the Total Row count only visible rows; SUM counts everything.' },
  { id: 'xl2-tab-11', topic: 'xl-tables', type: 'tf', kind: 'concept', difficulty: 1, concept: 'tables',
    prompt: 'True or false: a Table\'s Total Row can show an average instead of a sum.',
    answer: true, explain: 'Each Total Row cell has a drop-down: Sum, Average, Count, Max, Min and more.' },
  { id: 'xl2-tab-12', topic: 'xl-tables', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'tables',
    prompt: 'The data has a blank row in the middle. You click a cell near the top and press Ctrl+T. What may happen?',
    options: ['The Table may stop at the blank row', 'Excel fills the blank row with zeros', 'Nothing: blank rows are ignored', 'Excel deletes the blank row'], answer: 0,
    explain: 'Excel guesses the data block from the cell you clicked, and a blank row looks like the end. Remove blank rows first, then check the range in the dialog.' },
  { id: 'xl2-tab-13', topic: 'xl-tables', type: 'number', kind: 'calculation', difficulty: 2, concept: 'sort-filter',
    prompt: 'A Top 10 filter set to "10 Percent" is applied to 1,200 orders. How many rows does it show (with no ties)?',
    answer: 120, verify: () => 1200 * 0.1,
    explain: 'The Top 10 filter can show items or percent. 10% of 1,200 = 120 rows.' },
  { id: 'xl2-tab-14', topic: 'xl-tables', type: 'mc', kind: 'concept', difficulty: 2, concept: 'sort-filter',
    prompt: 'Why add a row-number column before sorting a list you may want to restore?',
    options: ['Sorting by it brings back the original order', 'Excel needs it to sort text', 'It makes the sort run faster', 'Filters only work on numbered rows'], answer: 0,
    explain: 'Once sorted, the original order is gone unless something records it. A numbered column is that record.' },
  { id: 'xl2-tab-15', topic: 'xl-tables', type: 'tf', kind: 'concept', difficulty: 2, concept: 'sort-filter',
    prompt: 'True or false: copying a filtered list and pasting it elsewhere also pastes the hidden rows.',
    answer: false, explain: 'Excel copies only the visible rows of a filtered range, which is handy for sending an extract.' },
  { id: 'xl2-tab-16', topic: 'xl-tables', type: 'mc', kind: 'interpretation', difficulty: 1, concept: 'sort-filter',
    prompt: 'The Region header shows a small funnel icon instead of the usual arrow. What does it mean?',
    options: ['A filter is applied to that column', 'The column is sorted A to Z', 'The column contains errors', 'The column is locked'], answer: 0,
    explain: 'The funnel warns that some rows are hidden by this column\'s filter. Check it before trusting any total.' },
  { id: 'xl2-tab-17', topic: 'xl-tables', type: 'fill', kind: 'concept', difficulty: 1, concept: 'tables',
    prompt: 'View → Freeze ____ keeps the header row visible while you scroll down.',
    answer: ['panes', 'top row'], explain: 'Freeze Panes → Freeze Top Row. Tables do something similar by showing their headers in the column letters.' },
  { id: 'xl2-tab-18', topic: 'xl-tables', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'sort-filter',
    prompt: 'You want to see only the 5 largest orders. Which filter?',
    options: ['Number Filters → Top 10, set to 5 Items', 'Number Filters → Above Average', 'Sort Largest to Smallest only', 'Text Filters → Begins With 5'], answer: 0,
    explain: 'Top 10 is a misleading name: you choose how many items (or what percent) to keep.' },
  { id: 'xl2-tab-19', topic: 'xl-tables', type: 'tf', kind: 'concept', difficulty: 2, concept: 'structured-refs',
    prompt: 'True or false: when you rename a Table, formulas that use its structured references update to the new name.',
    answer: true, explain: 'Excel rewrites Orders[Revenue] as Sales[Revenue] everywhere, which a typed range address would never do.' },
  { id: 'xl2-tab-20', topic: 'xl-tables', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'sort-filter',
    prompt: 'You email a workbook with filters still switched on. What is the risk?',
    options: ['Readers may think the visible rows are all the data', 'The file cannot be opened', 'The filters are removed on sending', 'Formulas stop calculating'], answer: 0,
    explain: 'Clear filters before sharing, or state clearly what is filtered and why.' },

  // ================================================================ xl-logic
  { id: 'xl2-log-01', topic: 'xl-logic', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'if-logic',
    prompt: 'In **E2**, return "Gold" if the Amount is 1000 or more, "Silver" if it is 500 or more, otherwise "Bronze". Copy down to E9.',
    grid: { rows: ORDERS }, target: 'E2', fillTo: 'E9', answer: '=IF(D2>=1000,"Gold",IF(D2>=500,"Silver","Bronze"))',
    explain: 'Test the highest threshold first. IFS(D2>=1000,"Gold",D2>=500,"Silver",TRUE,"Bronze") works too.' },
  { id: 'xl2-log-02', topic: 'xl-logic', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'if-logic',
    prompt: 'In **E2**, return "Review" if the Region is North **or** South, otherwise "OK". Copy down to E9.',
    grid: { rows: ORDERS }, target: 'E2', fillTo: 'E9', answer: '=IF(OR(B2="North",B2="South"),"Review","OK")',
    explain: 'OR is true when either test is true. Text values need quotes: B2="North".' },
  { id: 'xl2-log-03', topic: 'xl-logic', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'if-logic',
    prompt: 'In **C2**, show "Missing" if the price in B2 is empty; otherwise show the price with 10% added. Copy down to C6.',
    grid: { rows: [['Item', 'Price', 'New price'], ['Tent', 120, null], ['Boots', null, null], ['Stove', 45, null], ['Lamp', null, null], ['Jacket', 150, null]] },
    target: 'C2', fillTo: 'C6', answer: '=IF(B2="","Missing",B2*1.1)',
    explain: 'B2="" is true for an empty cell. ISBLANK(B2) also works here, but not for a cell holding a formula that returns "".' },
  { id: 'xl2-log-04', topic: 'xl-logic', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'if-logic',
    prompt: 'In **D2**, pay a bonus of the rate in **F1** times Sales, but only if Sales (B2) reach the Target (C2); otherwise 0. Copy down to D5.',
    grid: { rows: [['Rep', 'Sales', 'Target', 'Bonus', 'Rate', 0.05], ['Ana', 52000, 50000, null], ['Ben', 47000, 50000, null], ['Chloe', 61000, 55000, null], ['Dev', 55000, 55000, null]] },
    target: 'D2', fillTo: 'D5', answer: '=IF(B2>=C2,B2*$F$1,0)',
    explain: 'Dev exactly meets target, so >= pays him. Locking $F$1 keeps the rate in one place for everyone.' },
  { id: 'xl2-log-05', topic: 'xl-logic', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'if-logic',
    prompt: 'In **E2**, return "Priority" if the order is Online **and** over 500, **or** if it comes from the West; otherwise "Normal". Copy down to E9.',
    grid: { rows: ORDERS }, target: 'E2', fillTo: 'E9', answer: '=IF(OR(AND(C2="Online",D2>500),B2="West"),"Priority","Normal")',
    explain: 'Build the rule from its parts: AND for "Online and over 500", then OR with the West test. A West store order of 950 is Priority too.' },
  { id: 'xl2-log-06', topic: 'xl-logic', type: 'number', kind: 'calculation', difficulty: 2, concept: 'if-logic',
    prompt: 'A1 is 12 and B1 is 5. What does =IF(AND(A1>10, B1<5), 100, 0) return?',
    answer: 0, verify: () => ((12 > 10 && 5 < 5) ? 100 : 0),
    explain: 'B1<5 is false (5 is not less than 5), so AND is false and IF returns 0. Watch < versus <=.' },
  { id: 'xl2-log-07', topic: 'xl-logic', type: 'number', kind: 'calculation', difficulty: 1, concept: 'if-logic',
    prompt: 'A1 is 75. What does =IF(A1>=90,4,IF(A1>=75,3,IF(A1>=60,2,1))) return?',
    answer: 3, verify: () => (75 >= 90 ? 4 : 75 >= 75 ? 3 : 75 >= 60 ? 2 : 1),
    explain: 'The first test (>=90) fails, the second (>=75) passes, so the result is 3 and the rest is never checked.' },
  { id: 'xl2-log-08', topic: 'xl-logic', type: 'tf', kind: 'concept', difficulty: 1, concept: 'if-logic',
    prompt: 'True or false: AND(TRUE, FALSE, TRUE) returns FALSE.',
    answer: true, explain: 'AND needs every test to be true. OR(TRUE, FALSE, TRUE) would return TRUE.' },
  { id: 'xl2-log-09', topic: 'xl-logic', type: 'tf', kind: 'debugging', difficulty: 2, concept: 'if-logic',
    prompt: 'True or false: if no condition in IFS is true and there is no TRUE catch-all at the end, IFS returns #N/A.',
    answer: true, explain: 'Add TRUE, "Other" as the last pair so every row gets a result.' },
  { id: 'xl2-log-10', topic: 'xl-logic', type: 'fill', kind: 'concept', difficulty: 1, concept: 'if-logic',
    prompt: 'The function that returns TRUE when at least one of its tests is TRUE is ____.',
    answer: ['OR', 'or'], explain: 'OR(test1, test2, …) is TRUE if any test is TRUE; AND needs all of them.' },
  { id: 'xl2-log-11', topic: 'xl-logic', type: 'order', kind: 'sequence', difficulty: 2, concept: 'if-logic',
    prompt: 'A discount rule gives 15% from 1,000, 10% from 500, 5% from 100, else nothing. Order the tests in a nested IF.',
    options: ['Spend of 1,000 or more', 'Spend of 500 or more', 'Spend of 100 or more', 'Anything else'], answer: [0, 1, 2, 3],
    explain: 'Highest threshold first: a spend of 1,200 also passes ">= 100", so testing that first would give it only 5%.' },
  { id: 'xl2-log-12', topic: 'xl-logic', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'if-logic',
    prompt: 'What does =IF(C2="","",C2*1.2) do?',
    options: ['Leaves the cell blank when C2 is empty, else adds 20%', 'Always adds 20% to C2', 'Shows an error when C2 is empty', 'Returns 1.2 when C2 is empty'], answer: 0,
    explain: 'Returning "" keeps the report clean for rows that have no value yet, instead of showing 0.' },
  { id: 'xl2-log-13', topic: 'xl-logic', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'dates',
    prompt: 'Which formula returns "Weekend" when the date in A2 is a Saturday or Sunday?',
    options: ['=IF(WEEKDAY(A2,2)>5,"Weekend","Weekday")', '=IF(WEEKDAY(A2)>5,"Weekend","Weekday")', '=IF(A2="Saturday","Weekend","Weekday")', '=IF(DAY(A2)>5,"Weekend","Weekday")'], answer: 0,
    explain: 'WEEKDAY(date, 2) numbers Monday as 1 and Sunday as 7, so >5 means Saturday or Sunday. The default numbering starts on Sunday, so >5 catches Friday and Saturday.' },
  { id: 'xl2-log-14', topic: 'xl-logic', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'if-logic',
    prompt: '=IF(B2="Yes","Paid","Unpaid") shows "Unpaid" although B2 shows Yes. What is the most likely cause?',
    options: ['B2 contains "Yes " with a trailing space', 'IF cannot compare text', 'The quotes should be single quotes', 'Yes must be written in capitals'], answer: 0,
    explain: 'A hidden space makes the values different. TRIM the data, or compare TRIM(B2)="Yes". The comparison ignores capitals.' },
  { id: 'xl2-log-15', topic: 'xl-logic', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'lookup-strategy',
    prompt: 'A commission rule has six bands and changes twice a year. What is the best design?',
    options: ['A small band table and an approximate-match lookup', 'A nested IF with six levels', 'A separate formula for each band', 'Typing the commission in by hand'], answer: 0,
    explain: 'When the bands change, you edit the table, not every formula. XLOOKUP with match mode -1 finds the right band.' },
];
