// Excel quiz bank, part C: XLOOKUP and INDEX/MATCH (Intermediate).
/** Put two blocks side by side: the right block starts in column `col` (0 = A). */
const sideBySide = (left, right, col) => Array.from({ length: Math.max(left.length, right.length) }, (_, i) => {
  const l = [...(left[i] || [])];
  while (l.length < col) l.push(null);
  return [...l, ...(right[i] || [])];
});
const PRODUCTS = [
  ['SKU', 'Product', 'Price', 'Category'],
  ['TNT-101', 'Ridgeline 1P Tent', 189, 'Tents'],
  ['TNT-102', 'Ridgeline 2P Tent', 249, 'Tents'],
  ['FTW-201', 'Trail Runner', 129, 'Footwear'],
  ['FTW-202', 'Summit Boot', 179, 'Footwear'],
  ['CKG-301', 'Twin Burner Stove', 89, 'Cooking'],
  ['ACC-401', 'Camp Mug', 12, 'Accessories'],
];
const LINES = [['SKU', 'Qty', 'Result'], ['FTW-201', 2, null], ['CKG-301', 1, null], ['TNT-102', 3, null], ['ACC-401', 6, null], ['FTW-202', 1, null]];
const SALESGRID = [['Product', 'Jan', 'Feb', 'Mar'], ['Tent', 4200, 3900, 5100], ['Boots', 2600, 2750, 3020], ['Stove', 1180, 990, 1340], ['Mug', 310, 280, 420]];

export const XL_QUIZ_C = [
  // ================================================================ xl-xlookup
  { id: 'xl2-xlk-01', topic: 'xl-xlookup', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'xlookup',
    prompt: 'In **C2**, look up the **price** of the SKU in A2 from the product table in H1:K7. Copy down to C6.',
    grid: { rows: sideBySide(LINES, PRODUCTS, 7) }, target: 'C2', fillTo: 'C6', answer: '=XLOOKUP(A2,$H$2:$H$7,$J$2:$J$7)',
    explain: 'XLOOKUP(what, where to look, what to return). Lock both table ranges so they stay put when the formula is copied.' },
  { id: 'xl2-xlk-02', topic: 'xl-xlookup', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'xlookup',
    prompt: 'In **C2**, calculate the **line value**: the quantity in B2 times the price looked up from H1:K7. Copy down to C6.',
    grid: { rows: sideBySide(LINES, PRODUCTS, 7) }, target: 'C2', fillTo: 'C6', answer: '=B2*XLOOKUP(A2,$H$2:$H$7,$J$2:$J$7)',
    explain: 'A lookup can sit inside a calculation: two Trail Runners come to 258. No helper price column is needed, although one can make checking easier.' },
  { id: 'xl2-xlk-03', topic: 'xl-xlookup', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'xlookup',
    prompt: 'In **B2**, return the **product name** for the SKU in A2, or "Not listed" when the SKU is not in H1:K7. Copy down to B5.',
    grid: { rows: sideBySide([['SKU', 'Product'], ['TNT-101', null], ['TNT-199', null], ['CKG-301', null], ['ACC-999', null]], PRODUCTS, 7) },
    target: 'B2', fillTo: 'B5', answer: '=XLOOKUP(A2,$H$2:$H$7,$I$2:$I$7,"Not listed")',
    explain: 'The fourth argument is what to show when nothing matches. Unlike IFERROR, it does not hide other errors such as a broken range.' },
  { id: 'xl2-xlk-04', topic: 'xl-xlookup', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'xlookup',
    prompt: 'The commission rate depends on the sales band in E1:F5 ("From" is the lower limit). In **C2**, return the rate for the sales in B2. Copy down to C5.',
    grid: { rows: sideBySide([['Rep', 'Sales', 'Rate'], ['Ana', 8400, null], ['Ben', 62400, null], ['Chloe', 100000, null], ['Dev', 49999, null]], [['From', 'Rate'], [0, 0.02], [10000, 0.03], [50000, 0.04], [100000, 0.05]], 4) },
    target: 'C2', fillTo: 'C5', answer: '=XLOOKUP(B2,$E$2:$E$5,$F$2:$F$5,,-1)',
    explain: 'Match mode -1 returns the exact value or the next smaller one: 62,400 falls in the 50,000 band (4%), and exactly 100,000 gets 5%.' },
  { id: 'xl2-xlk-05', topic: 'xl-xlookup', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'xlookup',
    prompt: 'In **B2**, return the **SKU** of the product named in A2 (the SKU column sits to the left of the names in H1:K7). Copy down to B4.',
    grid: { rows: sideBySide([['Product', 'SKU'], ['Summit Boot', null], ['Camp Mug', null], ['Ridgeline 2P Tent', null]], PRODUCTS, 7) },
    target: 'B2', fillTo: 'B4', answer: '=XLOOKUP(A2,$I$2:$I$7,$H$2:$H$7)',
    explain: 'XLOOKUP does not care which side the return column is on: search the Product column, return the SKU column.' },
  { id: 'xl2-xlk-06', topic: 'xl-xlookup', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'lookup-strategy',
    prompt: 'A1:C9 is a price history, oldest first. In **F2**, return the **latest** price of the SKU in E2. Copy down to F3.',
    grid: { rows: sideBySide([['Date', 'SKU', 'Price'], ['2026-01-05', 'TNT-101', 179], ['2026-01-05', 'FTW-201', 119], ['2026-02-10', 'TNT-101', 185], ['2026-03-01', 'CKG-301', 85], ['2026-03-15', 'FTW-201', 125], ['2026-04-02', 'TNT-101', 189], ['2026-05-20', 'FTW-201', 129], ['2026-06-01', 'CKG-301', 89]], [['SKU', 'Latest price'], ['TNT-101', null], ['FTW-201', null]], 4) },
    target: 'F2', fillTo: 'F3', answer: '=XLOOKUP(E2,$B$2:$B$9,$C$2:$C$9,,0,-1)',
    explain: 'Search mode -1 searches from the bottom up, so the last (newest) row wins: 189 for TNT-101 and 129 for FTW-201. A normal lookup would return the oldest price.' },
  { id: 'xl2-xlk-07', topic: 'xl-xlookup', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'exact-match',
    prompt: 'The order export has stray spaces around some SKUs. In **B2**, look up the price for A2 from H1:K7 so that the spaces do not matter. Copy down to B4.',
    grid: { rows: sideBySide([['SKU (exported)', 'Price'], [' FTW-201', null], ['CKG-301 ', null], ['TNT-102', null]], PRODUCTS, 7) },
    target: 'B2', fillTo: 'B4', answer: '=XLOOKUP(TRIM(A2),$H$2:$H$7,$J$2:$J$7)',
    explain: 'TRIM inside the lookup cleans the key on the way in. Fixing the source data is still better, but this keeps the report working meanwhile.' },
  { id: 'xl2-xlk-08', topic: 'xl-xlookup', type: 'formula', kind: 'formula-writing', difficulty: 4, concept: 'lookup-strategy',
    prompt: 'A1:C9 holds targets by Region **and** Month. In **H2**, return the target for the region in F2 and the month in G2.',
    grid: { rows: sideBySide([['Region', 'Month', 'Target'], ['West', 'Jun', 8500], ['West', 'Jul', 14000], ['North', 'Jun', 20000], ['North', 'Jul', 20500], ['South', 'Jun', 17500], ['South', 'Jul', 12000], ['East', 'Jun', 13000], ['East', 'Jul', 13500]], [['Region', 'Month', 'Target'], ['North', 'Jul', null]], 5) },
    target: 'H2', answer: '=XLOOKUP(1,($A$2:$A$9=F2)*($B$2:$B$9=G2),$C$2:$C$9)',
    explain: 'Each test gives TRUE or FALSE per row; multiplying them gives 1 only where both are true, and XLOOKUP finds that 1. North in July is 20,500.' },
  { id: 'xl2-xlk-09', topic: 'xl-xlookup', type: 'number', kind: 'calculation', difficulty: 2, concept: 'xlookup',
    prompt: 'Bands start at 0, 10,000, 50,000 and 100,000 with rates 0.02, 0.03, 0.04 and 0.05. What rate does XLOOKUP(62400, bands, rates, , -1) return?',
    answer: 0.04, tolerance: 0.0001, verify: () => [[0, 0.02], [10000, 0.03], [50000, 0.04], [100000, 0.05]].filter(([b]) => b <= 62400).pop()[1],
    explain: '62,400 has no exact match, so match mode -1 takes the next smaller band, 50,000, whose rate is 0.04.' },
  { id: 'xl2-xlk-10', topic: 'xl-xlookup', type: 'number', kind: 'calculation', difficulty: 2, concept: 'exact-match',
    prompt: '36 order lines return #N/A. After wrapping the key in TRIM, 30 of them find a price. How many SKUs are genuinely missing from the price list?',
    answer: 6, verify: () => 36 - 30,
    explain: '30 failures were only spaces; the other 6 need a price added to the list (or a question to the buyer).' },
  { id: 'xl2-xlk-11', topic: 'xl-xlookup', type: 'number', kind: 'calculation', difficulty: 2, concept: 'xlookup',
    prompt: 'An order line has 3 units, XLOOKUP returns a price of 24.50 and the discount in D2 is 10%. What does =B2*XLOOKUP(…)*(1-D2) return?',
    answer: 66.15, tolerance: 0.001, verify: () => Math.round(3 * 24.5 * 0.9 * 100) / 100,
    explain: '3 × 24.50 = 73.50, and keeping 90% of that gives 66.15.' },
  { id: 'xl2-xlk-12', topic: 'xl-xlookup', type: 'tf', kind: 'concept', difficulty: 2, concept: 'xlookup',
    prompt: 'True or false: XLOOKUP can search a list from the bottom up.',
    answer: true, explain: 'Set search mode (the sixth argument) to -1 to get the last match, for example the latest price.' },
  { id: 'xl2-xlk-13', topic: 'xl-xlookup', type: 'tf', kind: 'debugging', difficulty: 2, concept: 'xlookup',
    prompt: 'True or false: if a key appears twice in the lookup column, XLOOKUP returns an error.',
    answer: false, explain: 'It quietly returns the first match. That is why duplicate keys in a lookup table are dangerous: check them with COUNTIF.' },
  { id: 'xl2-xlk-14', topic: 'xl-xlookup', type: 'tf', kind: 'debugging', difficulty: 3, concept: 'xlookup',
    prompt: 'True or false: an XLOOKUP whose lookup range and return range have different numbers of rows returns #VALUE!.',
    answer: true, explain: 'The two ranges must line up row for row. VLOOKUP never checks this, which is one reason XLOOKUP is safer.' },
  { id: 'xl2-xlk-15', topic: 'xl-xlookup', type: 'fill', kind: 'concept', difficulty: 3, concept: 'xlookup',
    prompt: 'Setting XLOOKUP\'s match mode (fifth argument) to ____ returns the next smaller item when there is no exact match.',
    answer: ['-1', 'minus 1', 'minus one'], explain: '-1 is exact or next smaller (tax and commission bands); 1 is exact or next larger; 0 is exact only.' },
  { id: 'xl2-xlk-16', topic: 'xl-xlookup', type: 'fill', kind: 'debugging', difficulty: 2, concept: 'xlookup',
    prompt: 'When a lookup cannot find the key, Excel shows the error #____.',
    answer: ['N/A', 'n/a', 'NA'], explain: '#N/A means "not available": the key was not found. Find out why before replacing it with text.' },
  { id: 'xl2-xlk-17', topic: 'xl-xlookup', type: 'order', kind: 'sequence', difficulty: 3, concept: 'exact-match',
    prompt: 'A lookup shows #N/A for a key you can see in the table. Order your checks.',
    options: ['Compare the two cells directly with =A2=H5', 'Look for spaces with LEN or TRIM', 'Check whether one is text and one a number', 'Only then treat the key as missing'], answer: [0, 1, 2, 3],
    explain: 'Prove the values differ, then test the usual causes (spaces, types) before concluding the key is really missing.' },
  { id: 'xl2-xlk-18', topic: 'xl-xlookup', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'cell-refs',
    prompt: '=XLOOKUP(A2,H2:H7,J2:J7) works in row 2, but copied down some rows show #N/A or the wrong price. Why?',
    options: ['The table ranges were not locked with $', 'XLOOKUP cannot be copied down', 'The SKUs are in the wrong order', 'The prices need to be sorted'], answer: 0,
    explain: 'Unlocked, the ranges slide down with each row and miss the top of the table. Use $H$2:$H$7 and $J$2:$J$7.' },
  { id: 'xl2-xlk-19', topic: 'xl-xlookup', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'xlookup',
    prompt: 'XLOOKUP returns 0 for a product that is in the list. What does the 0 most likely mean?',
    options: ['The product\'s price cell is empty', 'The product is free', 'The product was not found', 'The formula is broken'], answer: 0,
    explain: 'An empty return cell comes back as 0, which looks like a real price. Check blanks in the price list before trusting totals.' },
  { id: 'xl2-xlk-20', topic: 'xl-xlookup', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'iferror',
    prompt: 'You want "Unknown" for customer IDs that are missing, but any other error should still show. Which formula?',
    options: ['=XLOOKUP(A2,IDs,Regions,"Unknown")', '=IFERROR(XLOOKUP(A2,IDs,Regions),"Unknown")', '=IF(A2="","Unknown",XLOOKUP(A2,IDs,Regions))', '=XLOOKUP(A2,IDs,Regions,,-1)'], answer: 0,
    explain: 'The "if not found" argument only handles a missing key. IFERROR would also hide a broken range or a #VALUE! error.' },
  { id: 'xl2-xlk-21', topic: 'xl-xlookup', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'lookup-strategy',
    prompt: 'Each month you bring prices into 50,000 order lines, and new SKUs are added to the price list. What keeps the lookup reliable?',
    options: ['Point it at a Table, so new SKUs are included', 'Retype the range every month', 'Sort the orders before each lookup', 'Copy the prices in as values'], answer: 0,
    explain: 'A Table grows with the list, so the lookup sees new SKUs without anyone editing the formula.' },
  { id: 'xl2-xlk-22', topic: 'xl-xlookup', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'text-numbers',
    prompt: 'Employee IDs look identical in two tables, but the lookup returns #N/A. In one table the IDs are left-aligned. What is going on?',
    options: ['One table stores the IDs as text, the other as numbers', 'The IDs are sorted differently', 'XLOOKUP cannot match numbers', 'One table has more rows'], answer: 0,
    explain: 'Text "1042" and the number 1042 are different values. Convert one side (VALUE, or Text to Columns) so both match.' },
  { id: 'xl2-xlk-23', topic: 'xl-xlookup', type: 'mc', kind: 'concept', difficulty: 3, concept: 'xlookup',
    prompt: 'What does the sixth argument of XLOOKUP (search mode) control?',
    options: ['Whether it searches from the first or the last item', 'Whether the match must be exact', 'Which column is returned', 'What to show when nothing is found'], answer: 0,
    explain: '1 searches from the top, -1 from the bottom; 2 and -2 use a fast binary search on sorted data.' },
  { id: 'xl2-xlk-24', topic: 'xl-xlookup', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'validation',
    prompt: 'You added a Region column to 5,000 sales rows with a lookup. What should you check before using it?',
    options: ['How many rows found no region, and why', 'That the column is formatted in bold', 'That the rows are sorted by region', 'Nothing: lookups are always right'], answer: 0,
    explain: 'Count the "not found" rows (COUNTIF on the result). A few missing regions can change every regional total.' },

  // ================================================================ xl-indexmatch
  { id: 'xl2-idx-01', topic: 'xl-indexmatch', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'index-match',
    prompt: 'In **C2**, look up the **price** of the SKU in A2 using INDEX and MATCH on the table H1:K7. Copy down to C6.',
    grid: { rows: sideBySide(LINES, PRODUCTS, 7) }, target: 'C2', fillTo: 'C6', answer: '=INDEX($J$2:$J$7,MATCH(A2,$H$2:$H$7,0))',
    explain: 'MATCH finds the row of the SKU; INDEX returns the price from that row. The 0 asks for an exact match.' },
  { id: 'xl2-idx-02', topic: 'xl-indexmatch', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'index-match',
    prompt: 'In **G2**, return the **position** of the product in F2 within the list A2:A5.',
    grid: { rows: sideBySide(SALESGRID, [['Product', 'Position'], ['Stove', null]], 5) }, target: 'G2', answer: '=MATCH(F2,A2:A5,0)',
    explain: 'Stove is the third item in A2:A5, so MATCH returns 3. The position is counted inside the range, not from row 1.' },
  { id: 'xl2-idx-03', topic: 'xl-indexmatch', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'index-match',
    prompt: 'In **H2**, return sales for the product in F2 and the month in G2 from the grid A1:D5. Copy down to H4.',
    grid: { rows: sideBySide(SALESGRID, [['Product', 'Month', 'Sales'], ['Boots', 'Feb', null], ['Mug', 'Mar', null], ['Tent', 'Jan', null]], 5) },
    target: 'H2', fillTo: 'H4', answer: '=INDEX($B$2:$D$5,MATCH(F2,$A$2:$A$5,0),MATCH(G2,$B$1:$D$1,0))',
    explain: 'One MATCH finds the row, the other the column. Boots in February is 2,750.' },
  { id: 'xl2-idx-04', topic: 'xl-indexmatch', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'index-match',
    prompt: 'In **F2**, return the **employee ID** (column A) for the name in E2 (names are in column B). Copy down to F3.',
    grid: { rows: sideBySide([['ID', 'Name', 'Dept'], [1001, 'Yusuf Evans', 'Operations'], [1007, 'Grace Ali', 'Operations'], [1011, 'Elena Garcia', 'Customer Service'], [1014, 'Pia Mensah', 'Operations'], [1016, 'Rosa Fischer', 'Customer Service']], [['Name', 'ID'], ['Pia Mensah', null], ['Grace Ali', null]], 4) },
    target: 'F2', fillTo: 'F3', answer: '=INDEX($A$2:$A$6,MATCH(E2,$B$2:$B$6,0))',
    explain: 'INDEX can return a column to the left of the one MATCH searches, which old VLOOKUP could not do.' },
  { id: 'xl2-idx-05', topic: 'xl-indexmatch', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'index-match',
    prompt: 'Scores map to grades in D1:E5 (minimum score, ascending). In **B2**, return the grade for the score in A2 using INDEX and MATCH. Copy down to B5.',
    grid: { rows: sideBySide([['Score', 'Grade'], [48, null], [73, null], [90, null], [59, null]], [['Min score', 'Grade'], [0, 'D'], [50, 'C'], [70, 'B'], [85, 'A']], 3) },
    target: 'B2', fillTo: 'B5', answer: '=INDEX($E$2:$E$5,MATCH(A2,$D$2:$D$5,1))',
    explain: 'Match type 1 finds the largest value that is not above the score, which only works because the minimums are sorted ascending. 73 gets B.' },
  { id: 'xl2-idx-06', topic: 'xl-indexmatch', type: 'number', kind: 'calculation', difficulty: 2, concept: 'index-match',
    prompt: 'What does =MATCH("Stove", {"Tent","Boots","Stove","Lamp"}, 0) return?',
    answer: 3, verify: () => ['Tent', 'Boots', 'Stove', 'Lamp'].indexOf('Stove') + 1,
    explain: 'MATCH returns the position in the list: Stove is third.' },
  { id: 'xl2-idx-07', topic: 'xl-indexmatch', type: 'number', kind: 'calculation', difficulty: 2, concept: 'index-match',
    prompt: 'What does =INDEX({10,20,30;40,50,60}, 2, 3) return? (the semicolon starts a new row)',
    answer: 60, verify: () => [[10, 20, 30], [40, 50, 60]][1][2],
    explain: 'Row 2 is 40, 50, 60, and its third value is 60.' },
  { id: 'xl2-idx-08', topic: 'xl-indexmatch', type: 'tf', kind: 'concept', difficulty: 2, concept: 'index-match',
    prompt: 'True or false: MATCH with match type 1 only works properly when the lookup range is sorted in ascending order.',
    answer: true, explain: 'Type 1 assumes an ascending list and stops early. On an unsorted list it returns believable but wrong positions.' },
  { id: 'xl2-idx-09', topic: 'xl-indexmatch', type: 'fill', kind: 'concept', difficulty: 2, concept: 'index-match',
    prompt: 'In a one-column lookup, INDEX(range, MATCH(…)), MATCH supplies the ____ number.',
    answer: ['row'], explain: 'MATCH says which row; in a two-way lookup, a second MATCH supplies the column number.' },
  { id: 'xl2-idx-10', topic: 'xl-indexmatch', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'index-match',
    prompt: '=INDEX(C1:C100, MATCH(A2, B2:B100, 0)) returns the wrong customer for every row. Why?',
    options: ['INDEX starts at row 1 and MATCH at row 2, so they are one row apart', 'MATCH needs the value 1 as its last argument', 'INDEX cannot return text', 'The ranges must be sorted first'], answer: 0,
    explain: 'MATCH counts from B2, INDEX from C1, so every result is shifted up one row. Both ranges must start on the same row.' },
  { id: 'xl2-idx-11', topic: 'xl-indexmatch', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'index-match',
    prompt: 'What does =INDEX(B2:D10, 3, 2) return?',
    options: ['The value in cell C4', 'The value in cell D3', 'The value in cell B3', 'The value in cell C3'], answer: 0,
    explain: 'Row 3 of the range is sheet row 4; column 2 of the range is column C: cell C4.' },
  { id: 'xl2-idx-12', topic: 'xl-indexmatch', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'index-match',
    prompt: 'You need the column number of the month "Mar" in the header row B1:M1. Which formula?',
    options: ['=MATCH("Mar",B1:M1,0)', '=INDEX(B1:M1,"Mar")', '=XLOOKUP("Mar",B1:M1)', '=COUNTIF(B1:M1,"Mar")'], answer: 0,
    explain: 'MATCH works across a row as well as down a column: it returns 3 for March.' },
];
