// Excel quiz bank, part B: COUNTIF/SUMIF, text and dates, cleaning (Beginner).
const SALES = [
  ['Order', 'Region', 'Channel', 'Amount', 'Product', null, 'Region'],
  ['A-101', 'West', 'Online', 420, 'Ridgeline Tent', null, 'West'],
  ['A-102', 'East', 'Store', 180, 'Trail Boots', null, 'East'],
  ['A-103', 'West', 'Store', 950, 'Basecamp Tent', null, 'North'],
  ['A-104', 'North', 'Online', 75, 'Camp Mug', null, 'South'],
  ['A-105', 'South', 'Online', 610, 'Summit Tent', null, null],
  ['A-106', 'South', 'Store', 300, 'Trail Boots', null, null],
  ['A-107', 'East', 'Online', 1200, 'Tent Footprint', null, null],
  ['A-108', 'North', 'Store', 520, 'Camp Stove', null, null],
  ['A-109', 'West', 'Online', 88, 'Camp Mug', null, null],
  ['A-110', 'South', 'Online', 450, 'Rain Jacket', null, null],
];

export const XL_QUIZ_B = [
  // ================================================================ xl-countif
  { id: 'xl2-cif-01', topic: 'xl-countif', type: 'formula', kind: 'formula-writing', difficulty: 1, concept: 'countif-sumif',
    prompt: 'In **I1**, count the orders for the region typed in **H1**.',
    grid: { rows: SALES.map((r, i) => (i === 0 ? [...r.slice(0, 6), null, 'West', null] : r.slice(0, 5))) }, target: 'I1', answer: '=COUNTIF(B2:B11,H1)',
    explain: 'Pointing at H1 instead of typing "West" lets anyone change the region and see the new count. Here West has 3 orders.' },
  { id: 'xl2-cif-02', topic: 'xl-countif', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'countif-sumif',
    prompt: 'In **H2**, total the Amount of orders **over 500**.',
    grid: { rows: SALES.map((r) => r.slice(0, 5)) }, target: 'H2', answer: '=SUMIF(D2:D11,">500")',
    explain: 'When the test and the numbers are the same column, SUMIF needs only two arguments. The condition goes in quotes: ">500".' },
  { id: 'xl2-cif-03', topic: 'xl-countif', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'countif-sumif',
    prompt: 'In **H2**, calculate the **share of orders** that are Online (Online orders ÷ all orders).',
    grid: { rows: SALES.map((r) => r.slice(0, 5)) }, target: 'H2', answer: '=COUNTIF(C2:C11,"Online")/COUNTA(A2:A11)',
    explain: '6 of the 10 orders are Online, so the share is 0.6. COUNTA on the Order column counts every order, whatever its amount.' },
  { id: 'xl2-cif-04', topic: 'xl-countif', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'countif-sumif',
    prompt: 'The regions are listed in G2:G5. In **H2**, total the Amount for the region in G2, so the formula can be copied down to H5.',
    grid: { rows: SALES.map((r, i) => (i < 5 ? [...r, null] : [...r.slice(0, 5)])) }, target: 'H2', fillTo: 'H5', answer: '=SUMIF($B$2:$B$11,G2,$D$2:$D$11)',
    explain: 'Lock the data ranges with $ and leave G2 relative, so each row picks up its own region. The four totals add up to the grand total.' },
  { id: 'xl2-cif-05', topic: 'xl-countif', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'countif-sumif',
    prompt: 'In **H2**, count the orders whose Product contains the word "Tent" anywhere.',
    grid: { rows: SALES.map((r) => r.slice(0, 5)) }, target: 'H2', answer: '=COUNTIF(E2:E11,"*Tent*")',
    explain: 'The asterisks mean "anything before and after", so "Tent Footprint" counts as well as "Summit Tent": 4 orders.' },
  { id: 'xl2-cif-06', topic: 'xl-countif', type: 'number', kind: 'calculation', difficulty: 1, concept: 'countif-sumif',
    prompt: 'Amounts: 420, 180, 950, 75, 610, 300, 1200, 520. What does COUNTIF(range, ">=500") return?',
    answer: 4, verify: () => [420, 180, 950, 75, 610, 300, 1200, 520].filter((v) => v >= 500).length,
    explain: '950, 610, 1,200 and 520 are 500 or more: 4 orders.' },
  { id: 'xl2-cif-07', topic: 'xl-countif', type: 'number', kind: 'calculation', difficulty: 2, concept: 'countif-sumif',
    prompt: 'The four Store orders are 180, 950, 300 and 520; the Online orders are 420, 75, 610 and 1,200. What does AVERAGEIF(channel, "Store", amount) return?',
    answer: 487.5, tolerance: 0.001, verify: () => (180 + 950 + 300 + 520) / 4,
    explain: 'AVERAGEIF averages only the rows that pass the test: (180 + 950 + 300 + 520) ÷ 4 = 487.5. The Online orders are ignored.' },
  { id: 'xl2-cif-08', topic: 'xl-countif', type: 'tf', kind: 'debugging', difficulty: 2, concept: 'text-numbers',
    prompt: 'True or false: =COUNTIF(A2:A100, ">500") also counts numbers stored as text, such as "750".',
    answer: false, explain: 'A number test only counts real numbers. Text numbers are silently skipped, so convert them first.' },
  { id: 'xl2-cif-09', topic: 'xl-countif', type: 'tf', kind: 'concept', difficulty: 1, concept: 'countif-sumif',
    prompt: 'True or false: SUMIF\'s third argument can be left out when the range you test is also the range to add.',
    answer: true, explain: '=SUMIF(D2:D11,">500") tests and adds the same column.' },
  { id: 'xl2-cif-10', topic: 'xl-countif', type: 'fill', kind: 'concept', difficulty: 1, concept: 'countif-sumif',
    prompt: 'In COUNTIF criteria, the wildcard ____ stands for any number of characters.',
    answer: ['*', 'asterisk'], explain: 'The asterisk matches any run of characters; the question mark matches exactly one.' },
  { id: 'xl2-cif-11', topic: 'xl-countif', type: 'mc', kind: 'debugging', difficulty: 1, concept: 'countif-sumif',
    prompt: '=COUNTIF(B2:B100,West) shows #NAME?. What is wrong?',
    options: ['West needs quotes: "West"', 'COUNTIF needs a third argument', 'The range must start at B1', 'COUNTIF cannot count text'], answer: 0,
    explain: 'Without quotes, Excel looks for something named West, finds nothing and shows #NAME?.' },
  { id: 'xl2-cif-12', topic: 'xl-countif', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'countif-sumif',
    prompt: 'What does =COUNTIF(D2:D100,"<"&AVERAGE(D2:D100)) count?',
    options: ['Orders below the average amount', 'Orders equal to the average', 'The average of the orders', 'Orders above the average'], answer: 0,
    explain: 'The & joins "<" with the calculated average, so the criterion becomes, for example, "<487.5".' },
  { id: 'xl2-cif-13', topic: 'xl-countif', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'countif-sumif',
    prompt: 'A weekly report needs an order count for each of 20 regions. What is the best set-up?',
    options: ['A list of regions with one COUNTIF copied down', 'Twenty filters, counted by hand each week', 'Sorting by region and counting rows', 'One COUNT on the whole column'], answer: 0,
    explain: 'One formula, copied down, updates itself every week and is easy to check.' },
  { id: 'xl2-cif-14', topic: 'xl-countif', type: 'order', kind: 'sequence', difficulty: 1, concept: 'countif-sumif',
    prompt: 'Put the arguments of SUMIF in order.',
    options: ['The range to test', 'The condition', 'The range to add up'], answer: [0, 1, 2],
    explain: 'SUMIF(range, criteria, sum_range). SUMIFS puts the sum range first instead, which catches many people out.' },
  { id: 'xl2-cif-15', topic: 'xl-countif', type: 'mc', kind: 'tool-selection', difficulty: 1, concept: 'count-types',
    prompt: 'Which formula counts the orders that have no amount entered yet in D2:D50?',
    options: ['=COUNTBLANK(D2:D50)', '=COUNT(D2:D50)', '=COUNTA(D2:D50)', '=SUM(D2:D50)'], answer: 0,
    explain: 'COUNTBLANK counts empty cells. COUNT and COUNTA count the filled ones.' },

  // ================================================================ xl-textdates
  { id: 'xl2-txt-01', topic: 'xl-textdates', type: 'formula', kind: 'formula-writing', difficulty: 1, concept: 'text-funcs',
    prompt: 'In **B2**, write the name in A2 with a capital letter at the start of each word. Copy down to B5.',
    grid: { rows: [['Name as typed', 'Name'], ['anna chen', null], ['JAMAL WRIGHT', null], ['irene SATO', null], ['leon lam', null]] },
    target: 'B2', fillTo: 'B5', answer: '=PROPER(A2)',
    explain: 'PROPER capitalises the first letter of every word and lowers the rest: "JAMAL WRIGHT" becomes "Jamal Wright".' },
  { id: 'xl2-txt-02', topic: 'xl-textdates', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'text-funcs',
    prompt: 'Names are written "Last, First". In **B2**, return the **first name**. Copy down to B5.',
    grid: { rows: [['Full name', 'First name'], ['Chen, Anna', null], ['Wright, Jamal', null], ['Sato, Irene', null], ['Lam, Leon', null]] },
    target: 'B2', fillTo: 'B5', answer: '=MID(A2,FIND(",",A2)+2,LEN(A2))',
    explain: 'FIND gives the comma\'s position; the first name starts two characters later (after ", "). TEXTAFTER(A2,", ") does the same in newer Excel.' },
  { id: 'xl2-txt-03', topic: 'xl-textdates', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'text-funcs',
    prompt: 'In **D2**, build a product code: the first three letters of the Category in capitals, a dash, then the number in C2 (for example TEN-104). Copy down to D4.',
    grid: { rows: [['Product', 'Category', 'Number', 'Code'], ['Ridgeline 2P', 'Tents', 104, null], ['Trail Mid', 'Boots', 211, null], ['Twin Burner', 'Stoves', 305, null]] },
    target: 'D2', fillTo: 'D4', answer: '=UPPER(LEFT(B2,3))&"-"&C2',
    explain: 'LEFT takes the letters, UPPER capitalises them and & joins the pieces. The number turns into text automatically when joined.' },
  { id: 'xl2-txt-04', topic: 'xl-textdates', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'dates',
    prompt: 'In **B2**, return the **last day of the month** of the date in A2. Copy down to B5.',
    grid: { rows: [['Invoice date', 'Month end'], ['2026-01-15', null], ['2026-02-03', null], ['2026-02-28', null], ['2026-12-09', null]] },
    target: 'B2', fillTo: 'B5', answer: '=EOMONTH(A2,0)',
    explain: 'EOMONTH(date, 0) is the end of the same month; EOMONTH(date, 1) is the end of next month. Format the result as a date.' },
  { id: 'xl2-txt-05', topic: 'xl-textdates', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'dates',
    prompt: 'Contracts renew **12 months** after they start. In **B2**, return the renewal date. Copy down to B4.',
    grid: { rows: [['Start', 'Renewal'], ['2025-03-31', null], ['2025-08-15', null], ['2026-01-31', null]] },
    target: 'B2', fillTo: 'B4', answer: '=EDATE(A2,12)',
    explain: 'EDATE adds whole months and handles month ends: 31 January plus one month would give 28 February. Adding 365 days breaks in leap years.' },
  { id: 'xl2-txt-06', topic: 'xl-textdates', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'dates',
    prompt: 'In **C2**, count the **working days** (Monday to Friday) from the order date to the delivery date, both included. Copy down to C4.',
    grid: { rows: [['Ordered', 'Delivered', 'Working days'], ['2026-03-02', '2026-03-06', null], ['2026-03-05', '2026-03-10', null], ['2026-03-13', '2026-03-23', null]] },
    target: 'C2', fillTo: 'C4', answer: '=NETWORKDAYS(A2,B2)',
    explain: 'NETWORKDAYS skips weekends and counts both ends: Monday 2 to Friday 6 March is 5 working days. A holiday list can be added as a third argument.' },
  { id: 'xl2-txt-07', topic: 'xl-textdates', type: 'number', kind: 'calculation', difficulty: 1, concept: 'text-funcs',
    prompt: 'What does =LEN("  Tent  ") return? (there are two spaces before and after the word)',
    answer: 8, verify: () => '  Tent  '.length,
    explain: 'LEN counts every character, spaces included: 2 + 4 + 2 = 8. That is how you spot hidden spaces.' },
  { id: 'xl2-txt-08', topic: 'xl-textdates', type: 'number', kind: 'calculation', difficulty: 2, concept: 'dates',
    prompt: 'February 2026 has 28 days. What does =DAY(DATE(2026,2,30)) return?',
    answer: 2, verify: () => new Date(Date.UTC(2026, 1, 30)).getUTCDate(),
    explain: 'DATE rolls extra days into the next month: 30 February becomes 2 March, so DAY returns 2. Handy, but it can also hide typos.' },
  { id: 'xl2-txt-09', topic: 'xl-textdates', type: 'tf', kind: 'concept', difficulty: 2, concept: 'dates',
    prompt: 'True or false: =EOMONTH(A2,-1)+1 returns a real date (the first of the month), while =TEXT(A2,"yyyy-mm") returns text.',
    answer: true, explain: 'Both can group rows by month, but only the real date can be used in date calculations and sorts correctly on its own.' },
  { id: 'xl2-txt-10', topic: 'xl-textdates', type: 'fill', kind: 'concept', difficulty: 2, concept: 'dates',
    prompt: 'The function that counts working days (Monday to Friday) between two dates is ____.',
    answer: ['NETWORKDAYS', 'networkdays', 'NETWORKDAYS.INTL'], explain: 'NETWORKDAYS(start, end, [holidays]); NETWORKDAYS.INTL lets you choose which days are the weekend.' },
  { id: 'xl2-txt-11', topic: 'xl-textdates', type: 'mc', kind: 'debugging', difficulty: 2, concept: 'dates',
    prompt: '=LEFT(A2,4) on a date cell showing 17/05/2026 returns "4615" instead of "17/0". Why?',
    options: ['The date is stored as a number, and LEFT reads its digits', 'LEFT only works on the first four cells', 'The date format is set to text', 'The cell is too narrow to show the result'], answer: 0,
    explain: 'Dates are day counts (46159 here); the display is only a format. Use DAY, MONTH, YEAR or TEXT to work with the parts.' },
  { id: 'xl2-txt-12', topic: 'xl-textdates', type: 'mc', kind: 'interpretation', difficulty: 1, concept: 'dates',
    prompt: 'A2 holds a due date one week from today. What does =A2-TODAY() return?',
    options: ['7, the days left', 'The due date again', 'An error', 'The date one week ago'], answer: 0,
    explain: 'Subtracting dates gives days. TODAY() changes every day, so the result updates on its own.' },
  { id: 'xl2-txt-13', topic: 'xl-textdates', type: 'mc', kind: 'tool-selection', difficulty: 2, concept: 'dates',
    prompt: 'Which formula returns the **first day of the month** for the date in A2?',
    options: ['=EOMONTH(A2,-1)+1', '=EOMONTH(A2,0)', '=A2-1', '=DAY(A2)'], answer: 0,
    explain: 'The end of the previous month plus one day is the first of this month. EOMONTH(A2,0) is the last day instead.' },
  { id: 'xl2-txt-14', topic: 'xl-textdates', type: 'order', kind: 'sequence', difficulty: 2, concept: 'text-numbers',
    prompt: 'Order the steps to turn text dates such as "17/05/2026" into real dates with formulas.',
    options: ['Check that the dates really are text (ISTEXT)', 'Split the day, month and year with LEFT, MID and RIGHT', 'Rebuild the date with DATE(year, month, day)', 'Format as a date and check a few rows by eye'], answer: [0, 1, 2, 3],
    explain: 'Confirm the problem, take the pieces apart, put them together in the right order, then prove it worked.' },
  { id: 'xl2-txt-15', topic: 'xl-textdates', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'text-numbers',
    prompt: 'An export has real dates in some rows and text such as "Mar 5, 2026" in others. What is the safest approach?',
    options: ['Convert the text rows and check them all with ISNUMBER', 'Format the whole column as Date', 'Sort the column so the text goes to the bottom', 'Delete the rows that are text'], answer: 0,
    explain: 'Formatting does not convert text. Convert the text rows (for example with DATEVALUE), then check that every row is a number.' },

  // ================================================================ xl-cleaning
  { id: 'xl2-cln-01', topic: 'xl-cleaning', type: 'formula', kind: 'formula-writing', difficulty: 1, concept: 'cleaning',
    prompt: 'In **B2**, remove the extra spaces from the name in A2 and give each word a capital letter. Copy down to B5.',
    grid: { rows: [['Name as exported', 'Clean name'], ['  YUSUF EVANS', null], ['grace ali  ', null], ['Elena   garcia', null], ['pia mensah', null]] },
    target: 'B2', fillTo: 'B5', answer: '=PROPER(TRIM(A2))',
    explain: 'TRIM removes the spaces at the ends and turns double spaces inside into single ones; PROPER fixes the capitals.' },
  { id: 'xl2-cln-02', topic: 'xl-cleaning', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'text-numbers',
    prompt: 'Weights are written like "12 kg". In **B2**, turn A2 into a number of kilograms. Copy down to B5.',
    grid: { rows: [['Weight', 'Kg'], ['12 kg', null], ['3.5 kg', null], ['0.75 kg', null], ['20 kg', null]] },
    target: 'B2', fillTo: 'B5', answer: '=VALUE(SUBSTITUTE(A2," kg",""))',
    explain: 'SUBSTITUTE removes the unit, and VALUE turns the remaining text into a number you can add up.' },
  { id: 'xl2-cln-03', topic: 'xl-cleaning', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'cleaning',
    prompt: 'In **B2**, return TRUE if the customer ID in A2 appears more than once in A2:A9, otherwise FALSE. Copy down to B9.',
    grid: { rows: [['Customer ID', 'Repeated?'], ['CU-2000', null], ['CU-2001', null], ['CU-2002', null], ['CU-2001', null], ['CU-2003', null], ['CU-2004', null], ['CU-2002', null], ['CU-2001', null]] },
    target: 'B2', fillTo: 'B9', answer: '=COUNTIF($A$2:$A$9,A2)>1',
    explain: 'COUNTIF counts how often each ID appears; more than 1 means it is repeated. Filter on TRUE to review the rows before deleting anything.' },
  { id: 'xl2-cln-04', topic: 'xl-cleaning', type: 'formula', kind: 'formula-writing', difficulty: 1, concept: 'cleaning',
    prompt: 'In **B2**, clean the product code in A2: no spaces at either end, and all capitals. Copy down to B4.',
    grid: { rows: [['Code as typed', 'Clean code'], [' tnt-104', null], ['TNT-105 ', null], ['tnt-106', null]] },
    target: 'B2', fillTo: 'B4', answer: '=UPPER(TRIM(A2))',
    explain: 'Lookups compare codes exactly as stored, so " tnt-104" would never match "TNT-104" until it is trimmed and upper-cased.' },
  { id: 'xl2-cln-05', topic: 'xl-cleaning', type: 'number', kind: 'calculation', difficulty: 2, concept: 'cleaning',
    prompt: 'What does =LEN(TRIM("  Grace   Ali  ")) return?',
    answer: 9, verify: () => 'Grace Ali'.length,
    explain: 'Excel\'s TRIM removes the outer spaces and shrinks the three inner spaces to one: "Grace Ali" has 9 characters.' },
  { id: 'xl2-cln-06', topic: 'xl-cleaning', type: 'number', kind: 'calculation', difficulty: 2, concept: 'data-quality',
    prompt: 'Of 480 phone numbers, 36 contain spaces and 12 start with +44; 5 have both problems. How many numbers need fixing?',
    answer: 43, verify: () => 36 + 12 - 5,
    explain: '36 + 12 counts the 5 numbers with both problems twice: 36 + 12 − 5 = 43.' },
  { id: 'xl2-cln-07', topic: 'xl-cleaning', type: 'tf', kind: 'concept', difficulty: 2, concept: 'cleaning',
    prompt: 'True or false: Excel\'s TRIM also turns double spaces in the middle of text into single spaces.',
    answer: true, explain: 'Unlike Power Query\'s Trim, Excel\'s TRIM also shrinks inner runs of spaces to one.' },
  { id: 'xl2-cln-08', topic: 'xl-cleaning', type: 'tf', kind: 'debugging', difficulty: 3, concept: 'cleaning',
    prompt: 'True or false: CLEAN removes the non-breaking spaces that often come with text copied from web pages.',
    answer: false, explain: 'CLEAN removes control characters such as line breaks. For non-breaking spaces use SUBSTITUTE(A2, CHAR(160), " ") and then TRIM.' },
  { id: 'xl2-cln-09', topic: 'xl-cleaning', type: 'fill', kind: 'concept', difficulty: 1, concept: 'cleaning',
    prompt: 'The function that removes non-printing characters such as line breaks from text is ____.',
    answer: ['CLEAN', 'clean'], explain: 'CLEAN(text) strips control characters; combine it with TRIM for tidy text: TRIM(CLEAN(A2)).' },
  { id: 'xl2-cln-10', topic: 'xl-cleaning', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'cleaning',
    prompt: 'After TRIM, "Riverside" still does not match, and LEN shows 10 instead of 9. What is the likely cause?',
    options: ['A non-breaking space copied from a web page', 'TRIM only works on numbers', 'The text is in capitals', 'The cell is formatted as a date'], answer: 0,
    explain: 'TRIM ignores CHAR(160). Replace it with a normal space first, then trim.' },
  { id: 'xl2-cln-11', topic: 'xl-cleaning', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'duplicates',
    prompt: 'A COUNTIF(…)>1 flag column shows TRUE on 14 rows. What does that mean?',
    options: ['14 rows share their ID with another row, first copies included', 'There are 14 extra copies to delete', 'There are 14 unique customers', '14 rows have an error in the ID'], answer: 0,
    explain: 'The flag marks every copy, including the one you will keep. Seven IDs appearing twice would show 14 TRUE rows but only 7 extras.' },
  { id: 'xl2-cln-12', topic: 'xl-cleaning', type: 'order', kind: 'sequence', difficulty: 2, concept: 'cleaning',
    prompt: 'Order these cleaning steps.',
    options: ['Keep an untouched copy of the raw data', 'Fix text: TRIM, CLEAN, consistent capitals', 'Convert text numbers and text dates', 'Flag and review duplicates before removing them'], answer: [0, 1, 2, 3],
    explain: 'Protect the original, make values comparable, fix types, then deal with duplicates once equal records look equal.' },
  { id: 'xl2-cln-13', topic: 'xl-cleaning', type: 'mc', kind: 'scenario', difficulty: 2, concept: 'cleaning',
    prompt: 'The same customer appears as "ACME Ltd", "Acme Ltd." and "Acme Limited". What is the best approach?',
    options: ['Map the variants to one name with a small lookup table', 'Delete two of the three spellings', 'Leave them: the totals are still right', 'Retype every row by hand'], answer: 0,
    explain: 'A mapping table is visible, reusable and easy to extend when a new spelling turns up. Totals by customer are wrong until the names agree.' },
  { id: 'xl2-cln-14', topic: 'xl-cleaning', type: 'mc', kind: 'concept', difficulty: 1, concept: 'cleaning',
    prompt: 'Why clean data in new columns (or a copy) rather than over the original values?',
    options: ['You can check and redo a step if it was wrong', 'Excel cannot change original cells', 'New columns calculate faster', 'It makes the file smaller'], answer: 0,
    explain: 'Keeping the raw values lets you compare before and after, and fix a cleaning rule without re-exporting the data.' },
  { id: 'xl2-cln-15', topic: 'xl-cleaning', type: 'tf', kind: 'concept', difficulty: 2, concept: 'text-numbers',
    prompt: 'True or false: multiplying a text number by 1 (for example =A2*1) turns it into a real number.',
    answer: true, explain: 'Arithmetic forces Excel to read the text as a number; VALUE(A2) does the same more visibly.' },
];
