// Excel quiz bank, part F: scenario analysis and anomaly detection (Advanced).
const MODEL = [['Input', 'Value'], ['Price', 25], ['Variable cost', 12], ['Units', 9000], ['Fixed costs', 60000], ['Target profit', 50000], [null, null], ['Result', null]];
const ORDERS12 = [412, 398, 405, 1210, 389, 401, 377, 415, 60, 408, 395, 402];
const TWO_WEEKS = [380, 402, 415, 398, 470, 520, 440, 390, 395, 430, 405, 610, 505, 450];

export const XL_QUIZ_F = [
  // ================================================================ xl-scenario
  { id: 'xl2-scn-01', topic: 'xl-scenario', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'scenario',
    prompt: 'In **B8**, calculate **profit**: (price − variable cost) × units − fixed costs, using the inputs above.',
    grid: { rows: MODEL }, target: 'B8', answer: '=(B2-B3)*B4-B5',
    explain: 'Each unit contributes 13 towards fixed costs: 13 × 9,000 − 60,000 = 57,000. Every number comes from an input cell, so the model can be tested.' },
  { id: 'xl2-scn-02', topic: 'xl-scenario', type: 'formula', kind: 'formula-writing', difficulty: 4, concept: 'scenario',
    prompt: 'In **B8**, calculate the **break-even revenue**: fixed costs ÷ contribution margin ratio, where the ratio is (price − variable cost) ÷ price.',
    grid: { rows: MODEL }, target: 'B8', answer: '=B5/((B2-B3)/B2)',
    explain: '52% of each sale is left after variable costs, so revenue must reach 60,000 ÷ 0.52 ≈ 115,385 to cover fixed costs.' },
  { id: 'xl2-scn-03', topic: 'xl-scenario', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'scenario',
    prompt: 'In **B8**, calculate how many **units** are needed to reach the **target profit**: (fixed costs + target profit) ÷ (price − variable cost).',
    grid: { rows: MODEL }, target: 'B8', answer: '=(B5+B6)/(B2-B3)',
    explain: 'The units must cover the fixed costs and the profit: 110,000 ÷ 13 ≈ 8,462 units, a little below the 9,000 expected.' },
  { id: 'xl2-scn-04', topic: 'xl-scenario', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'scenario',
    prompt: 'Prices for scenarios 1 (worst), 2 (expected) and 3 (best) are in B2:D2. In **B6**, use CHOOSE to return the price for the scenario number in A6. Copy down to B8.',
    grid: { rows: [['Scenario', 'Worst', 'Expected', 'Best'], ['Price', 22, 25, 27], [null, null, null, null], [null, null, null, null], ['Scenario no.', 'Price', null, null], [1, null, null, null], [2, null, null, null], [3, null, null, null]] },
    target: 'B6', fillTo: 'B8', answer: '=CHOOSE(A6,$B$2,$C$2,$D$2)',
    explain: 'CHOOSE(n, option1, option2, …) picks the n-th option. Pointing at the input cells keeps the scenario prices editable in one place.' },
  { id: 'xl2-scn-05', topic: 'xl-scenario', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'what-if',
    prompt: 'Revenue is 480,000 today (B1) and is assumed to grow by the rate in B2 each year. In **B5**, project revenue for the year number in A5. Copy down to B8.',
    grid: { rows: [['Revenue today', 480000], ['Growth per year', 0.06], [null, null], ['Year', 'Revenue'], [1, null], [2, null], [3, null], [4, null]] },
    target: 'B5', fillTo: 'B8', answer: '=$B$1*(1+$B$2)^A5',
    explain: 'Growth compounds: each year grows on top of the last. After four years revenue is roughly 606,000, a little more than four years of simple 6% growth (595,200) would give.' },
  { id: 'xl2-scn-06', topic: 'xl-scenario', type: 'formula', kind: 'formula-writing', difficulty: 4, concept: 'scenario',
    prompt: 'In **B8**, calculate the **margin of safety**: (expected units − break-even units) ÷ expected units, where break-even units = fixed costs ÷ (price − variable cost).',
    grid: { rows: MODEL }, target: 'B8', answer: '=(B4-B5/(B2-B3))/B4',
    explain: 'Break-even is about 4,615 units, so sales could fall by roughly 49% before the product loses money: a comfortable cushion.' },
  { id: 'xl2-scn-07', topic: 'xl-scenario', type: 'number', kind: 'calculation', difficulty: 3, concept: 'scenario',
    prompt: 'Fixed costs are 60,000, the price is 25 and the variable cost 12 per unit. How many whole units must be sold to break even?',
    answer: 4616, verify: () => Math.ceil(60000 / (25 - 12)),
    explain: '60,000 ÷ 13 = 4,615.4, and you cannot sell part of a unit, so 4,616 units are needed to stop losing money.' },
  { id: 'xl2-scn-08', topic: 'xl-scenario', type: 'number', kind: 'calculation', difficulty: 4, concept: 'what-if',
    prompt: 'Profit = (price − 12) × 9,000 − 60,000. Goal Seek looks for the price that gives a profit of 50,000. What price does it find? (two decimals)',
    answer: 24.22, tolerance: 0.01, verify: () => Math.round((12 + 110000 / 9000) * 100) / 100,
    explain: 'The price must satisfy (P − 12) × 9,000 = 110,000, so P = 12 + 12.22 = 24.22. Goal Seek finds the same answer by trial and error.' },
  { id: 'xl2-scn-09', topic: 'xl-scenario', type: 'number', kind: 'calculation', difficulty: 4, concept: 'what-if',
    prompt: 'Price rises 5% and volume falls 1.5% for every 1% of price rise. By how many % does revenue change? (two decimals, negative for a fall)',
    answer: -2.88, tolerance: 0.02, verify: () => Math.round((1.05 * (1 - 0.075) - 1) * 10000) / 100,
    explain: 'Volume falls 7.5%, so revenue becomes 1.05 × 0.925 = 0.97125 of before: a 2.88% fall, even though the price went up.' },
  { id: 'xl2-scn-10', topic: 'xl-scenario', type: 'number', kind: 'calculation', difficulty: 3, concept: 'scenario',
    prompt: 'Profit is 3,000 in the worst case (25% likely), 57,000 in the expected case (50%) and 95,500 in the best case (25%). What is the probability-weighted profit?',
    answer: 53125, verify: () => 0.25 * 3000 + 0.5 * 57000 + 0.25 * 95500,
    explain: '750 + 28,500 + 23,875 = 53,125. The weighted figure is below the expected case because the worst case is further away than the best.' },
  { id: 'xl2-scn-11', topic: 'xl-scenario', type: 'number', kind: 'calculation', difficulty: 3, concept: 'what-if',
    prompt: 'Fixed costs rise from 60,000 to 66,000 (price 25, variable cost 12). By how many units does the break-even point rise? (two decimals)',
    answer: 461.54, tolerance: 0.02, verify: () => Math.round((6000 / 13) * 100) / 100,
    explain: 'The extra 6,000 must be covered at 13 per unit: 6,000 ÷ 13 ≈ 461.54 more units.' },
  { id: 'xl2-scn-12', topic: 'xl-scenario', type: 'tf', kind: 'concept', difficulty: 3, concept: 'what-if',
    prompt: 'True or false: Goal Seek can change several input cells at once to reach its target.',
    answer: false, explain: 'Goal Seek changes one input. Solver (an add-in) can change several and respect limits.' },
  { id: 'xl2-scn-13', topic: 'xl-scenario', type: 'tf', kind: 'concept', difficulty: 3, concept: 'scenario',
    prompt: 'True or false: a number typed inside a formula, such as =B4*1.08, is an assumption that readers cannot see.',
    answer: true, explain: 'Move it to a labelled input cell ("Growth 8%") so it can be seen, questioned and changed.' },
  { id: 'xl2-scn-14', topic: 'xl-scenario', type: 'tf', kind: 'concept', difficulty: 4, concept: 'what-if',
    prompt: 'True or false: in a one-variable Data Table, the results update when you change the model\'s other inputs, unless calculation is set to "Automatic except for data tables".',
    answer: true, explain: 'Data Tables recalculate with the model. In big files people switch that off for speed, so check the setting before trusting the grid.' },
  { id: 'xl2-scn-15', topic: 'xl-scenario', type: 'fill', kind: 'concept', difficulty: 3, concept: 'what-if',
    prompt: 'The Excel add-in that changes several inputs to find the best result within limits is called ____.',
    answer: ['Solver', 'solver'], explain: 'Solver handles questions like "which mix of products maximises profit with this much capacity?".' },
  { id: 'xl2-scn-16', topic: 'xl-scenario', type: 'fill', kind: 'concept', difficulty: 3, concept: 'what-if',
    prompt: 'Data → What-If Analysis → ____ Seek finds the input value that makes a formula reach a target.',
    answer: ['Goal', 'goal'], explain: 'Goal Seek: set cell (the result), to value (the target), by changing (one input).' },
  { id: 'xl2-scn-17', topic: 'xl-scenario', type: 'order', kind: 'sequence', difficulty: 3, concept: 'scenario',
    prompt: 'Order the steps of building a scenario model.',
    options: ['List the assumptions in one input block', 'Link every calculation to those inputs', 'Build worst, expected and best cases', 'Test which inputs move the result most'], answer: [0, 1, 2, 3],
    explain: 'Visible inputs first, calculations that use them, then scenarios, then sensitivity to find what matters.' },
  { id: 'xl2-scn-18', topic: 'xl-scenario', type: 'mc', kind: 'concept', difficulty: 3, concept: 'what-if',
    prompt: 'What does a tornado chart show?',
    options: ['Which inputs move the result most, one at a time', 'How profit changes month by month', 'The share of each product in revenue', 'The spread of daily sales'], answer: 0,
    explain: 'Each bar shows the result when one input goes low and high, sorted with the biggest swing on top.' },
  { id: 'xl2-scn-19', topic: 'xl-scenario', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'scenario',
    prompt: 'You change the price input, but the profit in your model does not move. What is the most likely cause?',
    options: ['The profit formula has the price typed in', 'The price cell is formatted as currency', 'Excel only updates models once a day', 'The price must be a whole number'], answer: 0,
    explain: 'A formula that uses a typed number ignores the input cell. Search the model for hard-coded values.' },
  { id: 'xl2-scn-20', topic: 'xl-scenario', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'scenario',
    prompt: 'Break-even is 4,600 units and expected sales are 5,000. The margin of safety is 8%. What does that mean?',
    options: ['Sales can fall 8% before the product loses money', 'The product makes an 8% profit margin', 'Costs can rise 8% without any effect', 'The forecast is 8% too high'], answer: 0,
    explain: '(5,000 − 4,600) ÷ 5,000 = 8%: a thin cushion, worth stating next to the forecast.' },
  { id: 'xl2-scn-21', topic: 'xl-scenario', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'scenario',
    prompt: 'The CFO asks: "What happens if our supplier raises costs by 10%?" What is the most useful answer?',
    options: ['Profit before and after, plus what else could move', 'A new model built from scratch', 'The new cost figure on its own', 'A reminder that forecasts are uncertain'], answer: 0,
    explain: 'Show the effect on the result, and mention the linked assumptions (such as passing some of the rise on to prices).' },
  { id: 'xl2-scn-22', topic: 'xl-scenario', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'what-if',
    prompt: 'You want profit for five prices and four volumes in one grid. Which tool?',
    options: ['A two-variable Data Table', 'Goal Seek', 'A PivotTable', 'Scenario Manager with one scenario'], answer: 0,
    explain: 'A two-variable Data Table fills the grid with the model\'s result for every pair of price and volume.' },
  { id: 'xl2-scn-23', topic: 'xl-scenario', type: 'mc', kind: 'scenario', difficulty: 4, concept: 'scenario',
    prompt: 'The expected case shows a profit of 57,000 and the worst case 3,000. How should you present it?',
    options: ['Show the range and what drives the worst case', 'Show only the expected case', 'Average the two and show 30,000', 'Leave out the worst case to avoid alarm'], answer: 0,
    explain: 'Decision makers need the spread and its cause, for example "if prices fall to 22, profit nearly disappears".' },
  { id: 'xl2-scn-24', topic: 'xl-scenario', type: 'mc', kind: 'concept', difficulty: 3, concept: 'scenario',
    prompt: 'Why keep scenarios in one table instead of separate copies of the workbook?',
    options: ['One model to fix, and cases side by side', 'Copies use more colours', 'Excel limits the number of files', 'Tables calculate faster than copies'], answer: 0,
    explain: 'With copies, a formula fix must be made in every file, and the cases drift apart without anyone noticing.' },
  { id: 'xl2-scn-25', topic: 'xl-scenario', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'what-if',
    prompt: 'Goal Seek reports a price of 24.2222 for a target profit of 50,000, and the model then shows 49,999.80. What is going on?',
    options: ['Goal Seek stops within a small tolerance', 'The model has a hidden error', 'Goal Seek used the wrong target cell', 'The price must be rounded up to 25'], answer: 0,
    explain: 'Goal Seek iterates until it is close enough. Round the input sensibly, and read the result as "about 24.22".' },

  // ================================================================ xl-anomaly
  { id: 'xl2-anm-01', topic: 'xl-anomaly', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'anomaly',
    prompt: 'In **C2**, return "High" if the orders in B2 are more than 1.5 times the **median** of B2:B13, otherwise "OK". Copy down to C13.',
    grid: { rows: [['Day', 'Orders', 'Flag'], ...ORDERS12.map((v, i) => [`Day ${i + 1}`, v, null])] },
    target: 'C2', fillTo: 'C13', answer: '=IF(B2>1.5*MEDIAN($B$2:$B$13),"High","OK")',
    explain: 'The median (401.5) ignores the extreme days, so the rule stays stable: only Day 4 is above 1.5 × 401.5, roughly 602.' },
  { id: 'xl2-anm-02', topic: 'xl-anomaly', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'seasonality',
    prompt: 'B2:B15 hold two weeks of daily orders, starting on a Monday. In **C9**, compare each day with the **same weekday a week earlier** (this day ÷ that day − 1). Copy down to C15.',
    grid: { rows: [['Day', 'Orders', 'vs last week'], ...TWO_WEEKS.map((v, i) => [`Day ${i + 1}`, v, null])] },
    target: 'C9', fillTo: 'C15', answer: '=B9/B2-1',
    explain: 'Friday of week 2 (610) is about 30% above the previous Friday, the biggest jump, while the normal weekday rhythm cancels out.' },
  { id: 'xl2-anm-03', topic: 'xl-anomaly', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'anomaly',
    prompt: 'In **D2**, calculate the **conversion rate** (orders ÷ sessions) for each day. Copy down to D6.',
    grid: { rows: [['Date', 'Sessions', 'Orders', 'Conversion'], ['2026-02-09', 4310, 104, null], ['2026-02-10', 4280, 101, null], ['2026-02-11', 4350, 190, null], ['2026-02-12', 4190, 99, null], ['2026-06-15', 13600, 102, null]] },
    target: 'D2', fillTo: 'D6', answer: '=C2/B2',
    explain: '11 February converts at roughly twice the usual rate (190 orders on normal traffic), while 15 June converts at under 1% (normal orders on triple traffic). The ratio exposes both problems; the order totals alone would not.' },
  { id: 'xl2-anm-04', topic: 'xl-anomaly', type: 'formula', kind: 'formula-writing', difficulty: 4, concept: 'anomaly',
    prompt: 'In **C2**, return "Check" if the z-score of B2 against B2:B13 is beyond ±2 (use ABS), otherwise "OK". Copy down to C13.',
    grid: { rows: [['Day', 'Orders', 'Flag'], ...ORDERS12.map((v, i) => [`Day ${i + 1}`, v, null])] },
    target: 'C2', fillTo: 'C13', answer: '=IF(ABS((B2-AVERAGE($B$2:$B$13))/STDEV.S($B$2:$B$13))>2,"Check","OK")',
    explain: 'Only Day 4 is flagged. Day 9 (60 orders) is clearly wrong too, but the huge Day 4 inflates the standard deviation and hides it.' },
  { id: 'xl2-anm-05', topic: 'xl-anomaly', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'anomaly',
    prompt: 'In **C4**, calculate the **3-day moving average** of orders (this day and the two before). Copy down to C15.',
    grid: { rows: [['Day', 'Orders', '3-day average'], ...TWO_WEEKS.map((v, i) => [`Day ${i + 1}`, v, null])] },
    target: 'C4', fillTo: 'C15', answer: '=AVERAGE(B2:B4)',
    explain: 'A relative range slides down with the formula: row 5 averages B3:B5. The smoothed line makes a jump stand out against the trend.' },
  { id: 'xl2-anm-06', topic: 'xl-anomaly', type: 'formula', kind: 'formula-writing', difficulty: 4, concept: 'anomaly',
    prompt: 'In **C5**, compare each day with the average of the **three days before it** (this day ÷ that average − 1). Copy down to C15.',
    grid: { rows: [['Day', 'Orders', 'vs previous 3 days'], ...TWO_WEEKS.map((v, i) => [`Day ${i + 1}`, v, null])] },
    target: 'C5', fillTo: 'C15', answer: '=B5/AVERAGE(B2:B4)-1',
    explain: 'The window ends the day before, so a spike cannot dampen its own comparison. Day 12 (610) stands about 50% above the three days before it.' },
  { id: 'xl2-anm-07', topic: 'xl-anomaly', type: 'number', kind: 'calculation', difficulty: 3, concept: 'outliers',
    prompt: 'A day has 180 orders. The mean is 100 and the standard deviation 25. What is its z-score?',
    answer: 3.2, tolerance: 0.001, verify: () => (180 - 100) / 25,
    explain: '(180 − 100) ÷ 25 = 3.2: more than three standard deviations above the mean, which is rare enough to check.' },
  { id: 'xl2-anm-08', topic: 'xl-anomaly', type: 'number', kind: 'calculation', difficulty: 3, concept: 'outliers',
    prompt: 'Q1 is 80 and Q3 is 120. Where is the upper IQR fence (Q3 + 1.5 × IQR)?',
    answer: 180, verify: () => 120 + 1.5 * (120 - 80),
    explain: 'IQR = 120 − 80 = 40, so the fence is 120 + 60 = 180. Values above it deserve a look.' },
  { id: 'xl2-anm-09', topic: 'xl-anomaly', type: 'number', kind: 'calculation', difficulty: 3, concept: 'mean-median',
    prompt: 'Five values: 10, 12, 11, 13 and 90. By how much does the mean exceed the median?',
    answer: 15.2, tolerance: 0.001, verify: () => (10 + 12 + 11 + 13 + 90) / 5 - 12,
    explain: 'The mean is 27.2 and the median 12: one extreme value pulls the mean up by 15.2, while the median barely notices it.' },
  { id: 'xl2-anm-10', topic: 'xl-anomaly', type: 'number', kind: 'calculation', difficulty: 3, concept: 'anomaly',
    prompt: 'A day shows 4,750 sessions and 190 orders, while a normal day converts at 2%. What is that day\'s conversion rate in %?',
    answer: 4, tolerance: 0.01, verify: () => (190 / 4750) * 100,
    explain: '190 ÷ 4,750 = 4%, twice the norm with ordinary traffic: a strong hint that orders were loaded twice.' },
  { id: 'xl2-anm-11', topic: 'xl-anomaly', type: 'number', kind: 'calculation', difficulty: 3, concept: 'anomaly',
    prompt: 'One day has 42 refunds on 120 orders; the usual refund rate is about 3.5%. What is that day\'s refund rate in %?',
    answer: 35, tolerance: 0.01, verify: () => (42 / 120) * 100,
    explain: '42 ÷ 120 = 35%, ten times the usual rate: look for fraud, a faulty batch or a system error.' },
  { id: 'xl2-anm-12', topic: 'xl-anomaly', type: 'tf', kind: 'concept', difficulty: 3, concept: 'outliers',
    prompt: 'True or false: a value outside the IQR fences is always a data error.',
    answer: false, explain: 'It is unusual, not necessarily wrong. A big sale or a holiday produces real outliers that belong in the data.' },
  { id: 'xl2-anm-13', topic: 'xl-anomaly', type: 'tf', kind: 'concept', difficulty: 3, concept: 'outliers',
    prompt: 'True or false: the mean and standard deviation are pulled by the very outliers you are trying to find.',
    answer: true, explain: 'That is why a robust rule (median, quartiles) often catches values the z-score misses.' },
  { id: 'xl2-anm-14', topic: 'xl-anomaly', type: 'tf', kind: 'concept', difficulty: 3, concept: 'seasonality',
    prompt: 'True or false: comparing a Monday with the previous Monday removes the weekday pattern from the comparison.',
    answer: true, explain: 'Like-for-like comparisons (same weekday, same month last year) leave only the change you care about.' },
  { id: 'xl2-anm-15', topic: 'xl-anomaly', type: 'fill', kind: 'concept', difficulty: 3, concept: 'outliers',
    prompt: 'A value\'s distance from the mean, measured in standard deviations, is called its ____.',
    answer: ['z-score', 'z score', 'zscore', 'standard score'], explain: 'z = (value − mean) ÷ standard deviation. STANDARDIZE calculates it in Excel.' },
  { id: 'xl2-anm-16', topic: 'xl-anomaly', type: 'fill', kind: 'concept', difficulty: 3, concept: 'outliers',
    prompt: 'The spread between the first and third quartile is called the ____ range.',
    answer: ['interquartile', 'inter-quartile', 'iqr'], explain: 'The interquartile range (IQR) covers the middle half of the values, which is why extremes barely affect it.' },
  { id: 'xl2-anm-17', topic: 'xl-anomaly', type: 'order', kind: 'sequence', difficulty: 3, concept: 'anomaly',
    prompt: 'Order the steps for investigating a flagged day.',
    options: ['Confirm the value in the raw data', 'Check the calendar for a known event', 'Check the related measures, such as sessions and refunds', 'Decide: fix it, exclude it with a note, or keep it'], answer: [0, 1, 2, 3],
    explain: 'Make sure the number is really there, look for an innocent explanation, test it against related data, then act and record why.' },
  { id: 'xl2-anm-18', topic: 'xl-anomaly', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'anomaly',
    prompt: 'Sessions tripled on one day while orders stayed at their usual level. What is the most likely explanation?',
    options: ['Bot or crawler traffic', 'A very successful sale', 'A duplicated order import', 'A payment outage'], answer: 0,
    explain: 'Real shoppers would place some orders. Visits without any extra orders usually come from automated traffic.' },
  { id: 'xl2-anm-19', topic: 'xl-anomaly', type: 'mc', kind: 'debugging', difficulty: 4, concept: 'outliers',
    prompt: 'A z-score rule flags nothing on a series with one obviously wrong day. Why?',
    options: ['The extreme value inflated the standard deviation', 'z-scores only work on dates', 'The threshold should be 0', 'The data must be sorted first'], answer: 0,
    explain: 'A huge value widens the standard deviation, so even it looks less extreme. Use the median or IQR fences as well.' },
  { id: 'xl2-anm-20', topic: 'xl-anomaly', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'conditional-format',
    prompt: 'You want flagged rows to turn orange in the sheet as soon as the data changes. Which tool?',
    options: ['Conditional formatting with a formula rule', 'Colouring the rows by hand', 'A PivotTable filter', 'Sorting by the flag column'], answer: 0,
    explain: 'A rule such as =$C2="Check" applied to the table recolours rows automatically whenever values change.' },
  { id: 'xl2-anm-21', topic: 'xl-anomaly', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'anomaly',
    prompt: 'A spike lines up with a planned sale in the marketing calendar. What do you do with it?',
    options: ['Keep it and label it as an event', 'Delete it as an outlier', 'Replace it with the average day', 'Ignore the calendar'], answer: 0,
    explain: 'A real event is part of the story. Label it so readers do not mistake it for growth or for an error.' },
  { id: 'xl2-anm-22', topic: 'xl-anomaly', type: 'mc', kind: 'concept', difficulty: 3, concept: 'anomaly',
    prompt: 'Why are ratios, such as conversion or refund rate, useful for spotting anomalies?',
    options: ['They stay steady when traffic changes, so problems stand out', 'They are easier to type than totals', 'Excel calculates them faster', 'They never contain errors'], answer: 0,
    explain: 'Totals rise and fall with the number of visitors; a ratio that suddenly moves points to something else going on.' },
  { id: 'xl2-anm-23', topic: 'xl-anomaly', type: 'mc', kind: 'interpretation', difficulty: 3, concept: 'anomaly',
    prompt: 'On one day card payments fall to 10% of orders while PayPal orders rise. What does that suggest?',
    options: ['Card payments were failing', 'Customers suddenly preferred PayPal', 'The orders were imported twice', 'A sale was running'], answer: 0,
    explain: 'Customers who could not pay by card switched or gave up. Check the payment provider\'s status for that day.' },
  { id: 'xl2-anm-24', topic: 'xl-anomaly', type: 'mc', kind: 'scenario', difficulty: 4, concept: 'validation',
    prompt: 'Finance wants the "bad day" removed from half-year revenue. Orders on that day were imported twice. What do you do?',
    options: ['Remove only the duplicated half, and note the correction', 'Remove the whole day\'s revenue', 'Replace the day with the median day', 'Leave it, since revenue is revenue'], answer: 0,
    explain: 'Only the duplicated orders are wrong; the real ones happened. Correct exactly what is proven wrong and say so.' },
  { id: 'xl2-anm-25', topic: 'xl-anomaly', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'seasonality',
    prompt: 'A retail business flags every December as an anomaly. What should change?',
    options: ['Compare each month with the same month last year', 'Remove December from the data', 'Lower the flag threshold', 'Use a longer yearly average'], answer: 0,
    explain: 'December is always big in retail. A seasonal comparison flags only a December that is unusual for a December.' },
];
