// Excel quiz bank, part D: SUMIFS / COUNTIFS / IFERROR and dynamic arrays (Intermediate).
const SALES = [
  ['Date', 'Region', 'Channel', 'Category', 'Revenue'],
  ['2026-01-08', 'West', 'Online', 'Tents', 420],
  ['2026-01-19', 'East', 'Store', 'Footwear', 180],
  ['2026-02-03', 'West', 'Store', 'Tents', 950],
  ['2026-02-14', 'North', 'Online', 'Cooking', 75],
  ['2026-02-27', 'West', 'Online', 'Footwear', 610],
  ['2026-03-05', 'South', 'Store', 'Tents', 300],
  ['2026-03-12', 'West', 'Online', 'Cooking', 1200],
  ['2026-03-22', 'North', 'Store', 'Footwear', 520],
  ['2026-04-02', 'West', 'Online', 'Tents', 88],
  ['2026-04-15', 'East', 'Online', 'Cooking', 450],
  ['2026-04-28', 'West', 'Store', 'Footwear', 230],
  ['2026-05-06', 'South', 'Online', 'Tents', 640],
];
/** SALES with extra cells written into columns G and H (row index → [G, H]). */
const withInputs = (inputs) => SALES.map((r, i) => (inputs[i] ? [...r, null, ...inputs[i]] : r));
const ORDERS = [
  ['Order', 'Region', 'Channel', 'Revenue'],
  ['A-101', 'West', 'Online', 420],
  ['A-102', 'East', 'Store', 180],
  ['A-103', 'West', 'Store', 950],
  ['A-104', 'North', 'Online', 75],
  ['A-105', 'South', 'Online', 610],
  ['A-106', 'South', 'Store', 300],
  ['A-107', 'East', 'Online', 1200],
  ['A-108', 'North', 'Store', 520],
  ['A-109', 'West', 'Online', 88],
  ['A-110', 'East', 'Online', 450],
];

export const XL_QUIZ_D = [
  // ================================================================ xl-sumifs
  { id: 'xl2-sfs-01', topic: 'xl-sumifs', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'sumifs',
    prompt: 'In **H2**, total the Revenue of **West** orders sold **Online**.',
    grid: { rows: SALES }, target: 'H2', answer: '=SUMIFS(E2:E13,B2:B13,"West",C2:C13,"Online")',
    explain: 'SUMIFS(sum range, then pairs of range and condition). Both conditions must hold: 420 + 610 + 1,200 + 88 = 2,318.' },
  { id: 'xl2-sfs-02', topic: 'xl-sumifs', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'sumifs',
    prompt: 'In **H3**, total the Revenue for the region in **H1** and the category in **H2**.',
    grid: { rows: withInputs({ 0: ['Region', 'West'], 1: ['Category', 'Tents'], 2: ['Revenue', null] }) }, target: 'H3', answer: '=SUMIFS(E2:E13,B2:B13,H1,D2:D13,H2)',
    explain: 'Criteria cells turn the formula into a small report: change H1 or H2 and the total follows. West Tents come to 1,458.' },
  { id: 'xl2-sfs-03', topic: 'xl-sumifs', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'date-criteria',
    prompt: 'In **H3**, total the Revenue between the start date in **H1** and the end date in **H2**, both included.',
    grid: { rows: withInputs({ 0: ['Start', '2026-03-01'], 1: ['End', '2026-03-31'], 2: ['Revenue', null] }) }, target: 'H3', answer: '=SUMIFS(E2:E13,A2:A13,">="&H1,A2:A13,"<="&H2)',
    explain: 'The same date column is tested twice, and & joins each operator to its date cell. March comes to 2,020.' },
  { id: 'xl2-sfs-04', topic: 'xl-sumifs', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'sumifs',
    prompt: 'In **H2**, count the **West** orders worth **more than 500**.',
    grid: { rows: SALES }, target: 'H2', answer: '=COUNTIFS(B2:B13,"West",E2:E13,">500")',
    explain: 'COUNTIFS takes range and condition pairs, with no sum range: three West orders are over 500.' },
  { id: 'xl2-sfs-05', topic: 'xl-sumifs', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'sumifs',
    prompt: 'H1 holds a channel. In **H3**, total the Revenue for the region in G3 **and** the channel in H1, so the formula can be copied down to H6.',
    grid: { rows: withInputs({ 0: ['Channel', 'Online'], 1: ['Region', 'Revenue'], 2: ['West', null], 3: ['East', null], 4: ['North', null], 5: ['South', null] }) },
    target: 'H3', fillTo: 'H6', answer: '=SUMIFS($E$2:$E$13,$B$2:$B$13,G3,$C$2:$C$13,$H$1)',
    explain: 'G3 moves down to pick up each region, while the data ranges and the channel cell stay locked.' },
  { id: 'xl2-sfs-06', topic: 'xl-sumifs', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'sumifs',
    prompt: 'In **H2**, calculate the **average** Revenue of **Online** orders in the **Tents** category.',
    grid: { rows: SALES }, target: 'H2', answer: '=AVERAGEIFS(E2:E13,C2:C13,"Online",D2:D13,"Tents")',
    explain: 'AVERAGEIFS uses the same pattern as SUMIFS. Three orders qualify (420, 88 and 640), so the average is about 382.67.' },
  { id: 'xl2-sfs-07', topic: 'xl-sumifs', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'iferror',
    prompt: 'In **D2**, calculate the margin (Profit ÷ Revenue). Where the revenue is 0, show "n/a" instead of an error. Copy down to D5.',
    grid: { rows: [['Product', 'Revenue', 'Profit', 'Margin'], ['Tent', 6000, 1800, null], ['Stove', 0, 0, null], ['Boots', 4200, 1050, null], ['Mug', 0, -30, null]] },
    target: 'D2', fillTo: 'D5', answer: '=IFERROR(C2/B2,"n/a")',
    explain: '"n/a" is honest: a 0% margin would claim something that did not happen. Mug\'s -30 profit on no revenue deserves a closer look too.' },
  { id: 'xl2-sfs-08', topic: 'xl-sumifs', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'sumifs',
    prompt: 'In **H2**, return the **largest** single order in the **West**.',
    grid: { rows: SALES }, target: 'H2', answer: '=MAXIFS(E2:E13,B2:B13,"West")',
    explain: 'MAXIFS and MINIFS follow the SUMIFS pattern. The largest West order is 1,200.' },
  { id: 'xl2-sfs-09', topic: 'xl-sumifs', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'sumifs',
    prompt: 'In **H2**, total the **West** Revenue for every category **except Tents**.',
    grid: { rows: SALES }, target: 'H2', answer: '=SUMIFS(E2:E13,B2:B13,"West",D2:D13,"<>Tents")',
    explain: '"<>Tents" means "not Tents": 610 + 1,200 + 230 = 2,040.' },
  { id: 'xl2-sfs-10', topic: 'xl-sumifs', type: 'number', kind: 'calculation', difficulty: 2, concept: 'reconciliation',
    prompt: 'Total revenue is 48,000. SUMIFS totals for the four regions are 12,000, 9,500, 15,200 and 10,100. How much revenue has no matching region?',
    answer: 1200, verify: () => 48000 - (12000 + 9500 + 15200 + 10100),
    explain: 'The regions add up to 46,800, so 1,200 sits on rows whose region is blank or spelled differently. Always check the parts add up to the whole.' },
  { id: 'xl2-sfs-11', topic: 'xl-sumifs', type: 'number', kind: 'calculation', difficulty: 2, concept: 'sumifs',
    prompt: 'AVERAGEIFS returns 250 for the West, which has 8 orders. What is total West revenue?',
    answer: 2000, verify: () => 250 * 8,
    explain: 'An average times the count gives the total: 250 × 8 = 2,000.' },
  { id: 'xl2-sfs-12', topic: 'xl-sumifs', type: 'number', kind: 'calculation', difficulty: 2, concept: 'date-criteria',
    prompt: 'COUNTIFS(dates, ">="&D1, dates, "<"&D2) uses D1 = 1 March 2026 and D2 = 1 April 2026. How many calendar days does it cover?',
    answer: 31, verify: () => (Date.UTC(2026, 3, 1) - Date.UTC(2026, 2, 1)) / 86400000,
    explain: 'From 1 March up to, but not including, 1 April: all 31 days of March, including orders stamped late on 31 March.' },
  { id: 'xl2-sfs-13', topic: 'xl-sumifs', type: 'number', kind: 'calculation', difficulty: 2, concept: 'sumifs',
    prompt: 'West orders: 420, 950, 610, 1200, 88, 230. What does COUNTIFS(region, "West", revenue, ">=500") return?',
    answer: 3, verify: () => [420, 950, 610, 1200, 88, 230].filter((v) => v >= 500).length,
    explain: '950, 610 and 1,200 pass both tests. ">=500" includes 500 itself; ">500" would not.' },
  { id: 'xl2-sfs-14', topic: 'xl-sumifs', type: 'tf', kind: 'concept', difficulty: 2, concept: 'sumifs',
    prompt: 'True or false: SUMIFS conditions are not case-sensitive, so "west" matches "West".',
    answer: true, explain: 'Capitals do not matter, but spaces do: "West " still fails.' },
  { id: 'xl2-sfs-15', topic: 'xl-sumifs', type: 'tf', kind: 'concept', difficulty: 3, concept: 'sumifs',
    prompt: 'True or false: one range and condition pair in SUMIFS can mean "West OR East".',
    answer: false, explain: 'SUMIFS combines its conditions with AND. For OR, add two SUMIFS, or use =SUM(SUMIFS(…, region, {"West","East"})).' },
  { id: 'xl2-sfs-16', topic: 'xl-sumifs', type: 'fill', kind: 'concept', difficulty: 2, concept: 'date-criteria',
    prompt: 'In the condition ">="&H1, the symbol that joins the operator to the cell is called the ____.',
    answer: ['ampersand', '&', 'and sign'], explain: 'The ampersand joins text: ">=" and the date in H1 become one condition.' },
  { id: 'xl2-sfs-17', topic: 'xl-sumifs', type: 'fill', kind: 'concept', difficulty: 2, concept: 'iferror',
    prompt: 'The function that returns a value of your choice when a formula produces any error is ____.',
    answer: ['IFERROR', 'iferror'], explain: 'IFERROR(formula, value_if_error). IFNA only catches #N/A, which is safer for lookups.' },
  { id: 'xl2-sfs-18', topic: 'xl-sumifs', type: 'order', kind: 'sequence', difficulty: 2, concept: 'sumifs',
    prompt: 'Put the arguments of SUMIFS in order.',
    options: ['The range to add up', 'The first range to test', 'The first condition', 'Any further range and condition pairs'], answer: [0, 1, 2, 3],
    explain: 'Unlike SUMIF, SUMIFS puts the sum range first, so any number of condition pairs can follow.' },
  { id: 'xl2-sfs-19', topic: 'xl-sumifs', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'date-criteria',
    prompt: 'A SUMIFS with the condition ">=01/03/2026" gives a different total on a colleague\'s US-settings computer. Why?',
    options: ['The typed date is read month-first there; use DATE(2026,3,1)', 'SUMIFS works differently in the US version of Excel', 'The colleague has an older Excel', 'Dates cannot be used in conditions'], answer: 0,
    explain: 'On a US computer 01/03/2026 means 3 January. Build dates with DATE or point at a date cell, and the condition works everywhere.' },
  { id: 'xl2-sfs-20', topic: 'xl-sumifs', type: 'mc', kind: 'tool-selection', difficulty: 3, concept: 'date-criteria',
    prompt: 'Which formula counts West orders placed in Q1 2026 (dates in column A)?',
    options: ['=COUNTIFS(B:B,"West",A:A,">="&DATE(2026,1,1),A:A,"<"&DATE(2026,4,1))', '=COUNTIFS(B:B,"West",A:A,"Q1")', '=COUNTIF(B:B,"West")/4', '=COUNTIFS(B:B,"West",A:A,"<"&DATE(2026,4,1))'], answer: 0,
    explain: 'Q1 needs a start and an end. Without the start, every West order before April, from any year, is counted.' },
  { id: 'xl2-sfs-21', topic: 'xl-sumifs', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'sumifs',
    prompt: 'What does =SUMIFS(E:E,B:B,"West")/COUNTIFS(B:B,"West") return?',
    options: ['The average West order value', 'West\'s share of all revenue', 'The number of West orders', 'The largest West order'], answer: 0,
    explain: 'Total West revenue divided by the number of West orders is the average West order, the same as AVERAGEIFS.' },
  { id: 'xl2-sfs-22', topic: 'xl-sumifs', type: 'mc', kind: 'scenario', difficulty: 3, concept: 'sumifs',
    prompt: 'A manager wants monthly revenue by region that updates itself as new orders arrive. What do you build?',
    options: ['A region-by-month grid of SUMIFS pointing at a Table', 'A new filter and a note of each total every month', 'A copy of last month\'s numbers, edited by hand', 'One SUMIF for the whole year'], answer: 0,
    explain: 'One SUMIFS pattern, copied across the grid, recalculates as the Table grows. A PivotTable is the other good option.' },
  { id: 'xl2-sfs-23', topic: 'xl-sumifs', type: 'mc', kind: 'debugging', difficulty: 3, concept: 'sumifs',
    prompt: '=COUNTIFS(B2:B100,"West",E2:E90,">500") returns #VALUE!. Why?',
    options: ['The two ranges have different sizes', 'COUNTIFS cannot mix text and numbers', 'The condition needs a cell reference', 'West must be in capitals'], answer: 0,
    explain: 'Every range in COUNTIFS and SUMIFS must have the same number of rows, so the conditions line up row by row.' },

  // ================================================================ xl-dynamic
  { id: 'xl2-dyn-01', topic: 'xl-dynamic', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'dynamic-arrays',
    prompt: 'In **G2**, list the Order IDs of all **West** orders with one formula.',
    grid: { rows: ORDERS }, target: 'G2', answer: '=FILTER(A2:A11,B2:B11="West")',
    explain: 'FILTER spills the matching IDs (A-101, A-103, A-109) down from G2, and updates when the data changes.' },
  { id: 'xl2-dyn-02', topic: 'xl-dynamic', type: 'formula', kind: 'formula-writing', difficulty: 2, concept: 'dynamic-arrays',
    prompt: 'In **G2**, list the **distinct regions**, sorted A to Z.',
    grid: { rows: ORDERS }, target: 'G2', answer: '=SORT(UNIQUE(B2:B11))',
    explain: 'UNIQUE removes repeats and SORT orders the result: East, North, South, West.' },
  { id: 'xl2-dyn-03', topic: 'xl-dynamic', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'dynamic-arrays',
    prompt: 'In **G2**, list the Revenue of the **West** orders, **largest first**.',
    grid: { rows: ORDERS }, target: 'G2', answer: '=SORT(FILTER(D2:D11,B2:B11="West"),1,-1)',
    explain: 'FILTER picks the West values; SORT with -1 orders them from largest: 950, 420, 88.' },
  { id: 'xl2-dyn-04', topic: 'xl-dynamic', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'dynamic-arrays',
    prompt: 'In **G2**, count the **Online** orders worth **more than 500** (any method).',
    grid: { rows: ORDERS }, target: 'G2', answer: '=ROWS(FILTER(A2:A11,(C2:C11="Online")*(D2:D11>500)))',
    explain: 'Multiplying the two tests means AND. ROWS counts what FILTER returns: 2. COUNTIFS gives the same answer more simply.' },
  { id: 'xl2-dyn-05', topic: 'xl-dynamic', type: 'formula', kind: 'formula-writing', difficulty: 3, concept: 'dynamic-arrays',
    prompt: 'In **G2**, list the Order IDs from the **East or North** regions.',
    grid: { rows: ORDERS }, target: 'G2', answer: '=FILTER(A2:A11,(B2:B11="East")+(B2:B11="North"))',
    explain: 'Adding the tests means OR: a row passes if either is true. Multiplying would mean AND, which no row could meet here.' },
  { id: 'xl2-dyn-06', topic: 'xl-dynamic', type: 'number', kind: 'calculation', difficulty: 2, concept: 'dynamic-arrays',
    prompt: 'D2:D11 holds 420, 180, 950, 75, 610, 300, 1200, 520, 88, 450. How many values does =FILTER(D2:D11, D2:D11>500) spill?',
    answer: 4, verify: () => [420, 180, 950, 75, 610, 300, 1200, 520, 88, 450].filter((v) => v > 500).length,
    explain: '950, 610, 1,200 and 520: four cells, and the spill grows or shrinks as the data changes.' },
  { id: 'xl2-dyn-07', topic: 'xl-dynamic', type: 'number', kind: 'calculation', difficulty: 2, concept: 'dynamic-arrays',
    prompt: 'West orders are 420, 950 and 88. What does =SUM(FILTER(D2:D11, B2:B11="West")) return?',
    answer: 1458, verify: () => 420 + 950 + 88,
    explain: 'Functions can work on a spilled result directly: 420 + 950 + 88 = 1,458.' },
  { id: 'xl2-dyn-08', topic: 'xl-dynamic', type: 'tf', kind: 'concept', difficulty: 2, concept: 'dynamic-arrays',
    prompt: 'True or false: UNIQUE treats "West" and "west" as the same value.',
    answer: true, explain: 'UNIQUE ignores capitals, but not spaces: "West " would still show up as a separate value.' },
  { id: 'xl2-dyn-09', topic: 'xl-dynamic', type: 'fill', kind: 'concept', difficulty: 3, concept: 'dynamic-arrays',
    prompt: 'The # in =SUM(D2#) is called the ____ range operator.',
    answer: ['spill', 'spilled', 'spilled range'], explain: 'D2# means "everything the formula in D2 spills", however many cells that is today.' },
  { id: 'xl2-dyn-10', topic: 'xl-dynamic', type: 'order', kind: 'sequence', difficulty: 3, concept: 'dynamic-arrays',
    prompt: 'In a "top 5 West orders" formula, order the steps from the inside out.',
    options: ['FILTER keeps the West rows', 'SORT puts them largest first', 'TAKE keeps the first five'], answer: [0, 1, 2],
    explain: 'The innermost function runs first: filter, then sort, then take the top rows.' },
  { id: 'xl2-dyn-11', topic: 'xl-dynamic', type: 'mc', kind: 'interpretation', difficulty: 2, concept: 'dynamic-arrays',
    prompt: '=FILTER(A2:A11, B2:B11="Central", "None") shows "None". What does that tell you?',
    options: ['No row has the region Central', 'The formula is blocked by another cell', 'Central is spelled wrongly in the formula', 'FILTER only returns text'], answer: 0,
    explain: 'The third argument is shown when nothing passes the test. If Central should exist, check the data for spellings.' },
];
